### ISSUE TITLE
Better ESCPOS Image Support

### ISSUE THREAD

**Issue by tresf** [qzind/tray#10]
Better image support for the following ESCP printers:
- Epson TMU220
- Star (model unknown, see below)

**Epson TMU220**

We use appendEpsonSlices via [`ImageWrapper.java#L467`](https://github.com/qzindustries/qz-print/blob/1.8/qz-print/src/qz/ImageWrapper.java#L467) but pass in an `m` value of `33`, but the TMU220 only supports values of `m=1, m=2` via: (screenshot attached)

![image](https://cloud.githubusercontent.com/assets/6345473/6607042/493f2f3c-c812-11e4-9d13-d8e8b81687d8.png)

[1] This image is Copyright (C) 2002 Seiko Epson Corporation and depicted here as an educational example, reproduced under [US Fair Use, §107.1](http://www.copyright.gov/fls/fl102.html)

---

**Star (model unknown)**

It appears Star's ESCP standard differs slightly from Epson's preventing images from appending properly... 

The format seems to use 
http://www.starmicronics.com/support/mannualfolder/escpos_cm_en.pdf#page=158

![image](https://cloud.githubusercontent.com/assets/6345473/8021765/7a2e6204-0c7b-11e5-8068-1e6e575b0d29.png)

Migrated from https://github.com/qzind/qz-print/issues/42

**Comment by tresf** [comment]
Update, @lite1979's obtained the legacy Star printer hardware, awaiting advisement with raw commands so that we can patch the raw image logic.

**Comment by lite1979** [comment]
I'm thinking the way to work with this will involve changing the commands that get sent to match various printer models, as the syntax has remained the same, but the actual commands that get passed have changed. i.e.: https://github.com/qzind/tray/blob/280152b58049abf07ef4a987772e8bd5dbc21d21/src/qz/printer/ImageWrapper.java#L461

Looks like this pull request has a lot of the logic figured out (python example):  https://github.com/python-escpos/python-escpos/pull/128/files

**Comment by lite1979** [comment]
Yes. Mike42 gave me replied to me on his python-pos project. I'll be testing some variations of the code today. :)

**Comment by lite1979** [comment]
While the Star printer produced similar odd character results to the TM-U220, the odd characters are part of two separate problems.

The problem for my Star TSP650II Tear Bar was that the printer was in Star Line Mode, a different markup language mode. Once I changed the dipswitch on the bottom of the printer to ESC/POS mode, the image printed fine.

Using the ImageWrapper in ESCP works for Star printer as long as it is set to ESC/POS emulation mode via the dipswitch. 

Creating a Star Line Mode code block for the ImageWrapper is on my agenda, but probably as an enhancement rather than a bug, since it is not a problem with the current ESCP code.

The ESCP ImageWrapper code still has a problem on the Epson TM-U220. I do not currently have hardware to test this on.

**Comment by tresf** [comment]
On top of ordering a TM-U220 for image testing, we also need to fix our documentation and code to distinguish the difference between [ESC/P and ESC/POS](https://en.wikipedia.org/wiki/ESC/P) as the manuals are actually quite different.

This will have upgrade problems because we've used the two rather synonymously (incorrectly) in our code.

The ImageWrapper should have separate logic for ESC/P which complies with the ESC/P or ESC/P2 guidelines.

**Comment by tresf** [comment]
> The ESCP ImageWrapper code still has a problem on the Epson TM-U220. I do not currently have hardware to test this on.

@lite1979 can you please provide an update on this?

**Comment by tresf** [comment]
Providing an update on @lite1979's behalf... the TM-U220 printer prints gibberish even after adjusting for the lower-resolution print head.  More R&D is needed.  Re-milestoning for the 2.2. branch.

**Comment by lite1979** [comment]
After reviewing [mike42's code snippets](https://github.com/mike42/escpos-snippets/blob/master/image-ports/columnFormat.php) we found that `dotDensity: 0` and `dotDensity: 1` need special consideration for stripe width and stripe height.

It's our belief that `dotDensity` values of 0 and 1 would previously break image support on all ESC/POS printers and our new logic fixes it for the U220 as well as newer TM-series, etc.

This fix will be available in 2.1.1 and available to white-label customers immediately.
A subsequent patch will be back-ported to 2.0.12.
