### ISSUE TITLE
MacOS Ventura: Won't start after installing over an existing version

### ISSUE THREAD

**Issue by tresf** [qzind/tray#1005]
When installing QZ Tray 2.2.1 over the top of itself on MacOS Ventura, it breaks the installation and QZ Tray will not start.

A temporary workaround is to delete QZ Tray from the applications folder and then try again.

**Comment by Vzor-** [comment]
This issue does not occur on 12.5.1 Monterey

**Comment by Vzor-** [comment]
I was unable to reproduce this on M1 Ventura 13.0. I tried master and tresf/222-libs. Is the installer failing in an obvious way?

**Comment by tresf** [comment]
> Is the installer failing in an obvious way?

In my case, the installer succeeds, but QZ fails to launch.  I have a feeling that.the OS is caching the digital signature and that removing the directory is refreshing this.

I'm glad to hear it's not yet reproducible.  Are you on the latest beta from Apple (have you run all the updates?)

**Comment by tresf** [comment]
> I was unable to reproduce this on M1 Ventura 13.0. I tried master and tresf/222-libs. Is the installer failing in an obvious way?

With my latest changes to #1000 PR and a reboot this issue has gone away on my machine as well.  I'll close it out for now.  Thanks for testing.
