### ISSUE TITLE
MacOS: Block & Remember this decision leave hanging Window

### ISSUE THREAD

**Issue by tresf** [qzind/tray#1007]
On MacOS, if you visit https://demo.qz.io and click "Block" and "Remember this decision", the "Are you sure" dialog appears below the "Allow".  Then, once you click "Yes", the "Allow" hangs forever and there's no way to close it.

The bug occurs on MacOS Ventura with QZ Tray 2.2.1.  I'm not sure if this bug exists on other MacOS and QZ Tray versions.

**Comment by Vzor-** [comment]
This issue did not present on 12.5.1 Monterey

**Comment by Vzor-** [comment]
This issue did present on M1 ventura 13.0

**Comment by tresf** [comment]
Minimal code to reproduce: https://gist.github.com/Vzor-/e23c5faa79218d12644d7fe664e3831e

Bug filed (private) with vendor `#QZ-8`.

**Comment by tresf** [comment]
Workaround merged to master via https://github.com/qzind/tray/pull/1012.  This will be part of QZ Tray 2.2.2 and higher.

**Comment by tresf** [comment]
Workaround is being reverted.  The latest macOS Ventura beta fixes this upstream, so we don't need the workaround.

**Comment by tresf** [comment]
Workaround reverted via f24f80b.  Closing.
