### ISSUE TITLE
Manually sending JSON breaks UI

### ISSUE THREAD

**Issue by tresf** [qzind/tray#1013]
~~Two~~ issues:

~~1. On Windows 11, certain JSON payloads, when sent to QZ Tray out of order will cause UI anomalies, such as a blank window.~~ (CANNOT REPRODUCE, POSSIBLE DUPLICATE OF #823)
 

2. By modifying the dialog's `x` and `y` positions, you can place the dialog non-centered, which can make it harder to find (e.g. upper right corner, etc).
   ```js
   var obj =  {"call":"printers.find","timestamp":1661263106002,"uid":"5w9ad2","position":{"x":-1,"y":-1}}
   _qz.websocket.connection.send(JSON.stringify(obj));
   ```

**Comment by Vzor-** [comment]
Important note, this only occurs on windows.

**Comment by tresf** [comment]
> Important note, this only occurs on Windows(OS).

Sorry, original description updated.
