### ISSUE TITLE
Bad Dropdown Menu Location on Ubuntu

### ISSUE THREAD

**Issue by Vzor-** [qzind/tray#1014]
The location of the drop-down menu seems to be determined by the last location of the 'about' dialog. Running ubuntu 22.04.1 LTS with openjdk18.

<img width="1440" alt="Screenshot 2022-08-25 at 6 15 30 PM" src="https://user-images.githubusercontent.com/10621658/186779163-908a9066-9bfe-4823-825f-fadbd6135d20.png">
<img width="1396" alt="Screenshot 2022-08-25 at 6 19 58 PM" src="https://user-images.githubusercontent.com/10621658/186779166-74940d3d-2f03-4e9e-96e7-0efd3481eb7b.png">

**Comment by tresf** [comment]
I think this is worse in a Parallels VM due to the mouse integration.  @lite1979 can you confirm that it's not this bad on a physical machine?  @Vzor- ideas welcome.

**Comment by Vzor-** [comment]
It looks like the cursor coordinates coming from https://github.com/qzind/tray/blob/master/src/qz/ui/tray/TaskbarTrayIcon.java#L114 are what is changing when about is relocated.

**Comment by Vzor-** [comment]
You may be right about it being strangeness with the mouse itself via parallels. I ran `xdotool getmouselocation` from terminal, the location doesn't change as I move my mouse. If I relaunch QZ though and move the about window, then run the command again, the reported location has changed.

**Comment by tresf** [comment]
Right, I'd recommend disabling mouse integration in Parallels and see if it goes away.

**Comment by tresf** [comment]
This is planned to be superceded by features in #1044.  In short, for systems that don't have a System Tray available, a QZ Tray dialog will be shown instead.  Closing as superseded by a new feature in #1043.
