### ISSUE TITLE
Page Header / Footer & Paper Size name

### ISSUE THREAD

**Issue by samratsm** [qzind/tray#1015]
How can I set page header and footer? Also how can set paper size name like "Letter" etc.?

**Comment by tresf** [comment]
Can you please be more specific?  For example, is this printing PDFs?  HTML? Other?

Note HTML does not support headers or footers at this time.

**Comment by samratsm** [comment]
I'm currently trying HTML. Is there any such option for PDF?

**Comment by tresf** [comment]
Not currently, no, they would need to be part of the original PDF being printed.

**Comment by samratsm** [comment]
Can we expect these properties in the future release?

**Comment by tresf** [comment]
PDF may be doable but it's not on the radar currently.  If you're a premium subscriber, please email support@qz.io to file an enhancement request .

HTML is encumbered upstream, so is unlikely to happen soon if at all.

**Comment by samratsm** [comment]
Thanks

**Comment by tresf** [comment]
For future onlookers, this is a duplicate of https://github.com/qzind/tray/issues/268.
