### ISSUE TITLE
Windows ARM64 - JavaFX failure prevents "Allow" dialog from appearing

### ISSUE THREAD

**Issue by tresf** [qzind/tray#1018]
Steps to reproduce:

1. Start QZ Tray using a Windows aarch64 native Java runtime
2. Wait for the idle tasks to start, specifically JavaFX
3. JavaFX tasks fails (as we'd expect, it doesn't exist for Windows ARM64)
4. The "Allow" dialog stops working

@Vzor- assigning to you, seems right up your alley.

**Comment by Vzor-** [comment]
Using windows 11 ARM I was not able to reproduce this.

<html><head></head><body>


java | 16.0.2 (aarch64)
-- | --
java (location) | C:\Program Files (Arm)\Microsoft\jdk-16.0.2.7-hotspot
java (vendor) | Microsoft


</body>
</html>

**Comment by tresf** [comment]
@Vzor- thanks, I can't reproduce either using Microsoft's JDK11 for ARM64.  Perhaps my tests were flawed and I forgot the [`add-opens`](https://github.com/qzind/tray/commit/dbd6ca2b370673d925838d0c47ab00d237982c36) to my command line flags.  I think we're OK closing this out unless we can concretely reproduce.
