### ISSUE TITLE
Serial n-th byte contains packet length

### ISSUE THREAD

**Issue by tresf** [qzind/tray#102]
When a serial configuration is first created, it can be configured to use:
1. Fixed packet length
2. Dynamic packet length based on `STX` and `ETX`

We have a request to allow serial to use the `n-th` byte to determine packet size.

**Comment by tresf** [comment]
Albeit inefficient, I believe just returning 1-byte at a time will suffice these use-cases, however the following example doesn't work... 

```js
var p = document.createElement('p');
document.getElementById('body').appendChild(p);

var callback = function(evt) {
	if (evt.type !== 'ERROR') return (p.innerHTML = p.innerHTML + '<br>' + evt.output);
	console.error(evt.exception);
};

qz.serial.setSerialCallbacks(callback);

var props = { baudRate: 9600, dataBits: 7, stopBits: 1, parity: 'EVEN', flowControl: 'NONE' };
var delims = { begin: '', end: '', width: 1 };

qz.websocket.connect().then(function() {
	console.log("Opening port...");
	return qz.serial.openPort('COM4', delims);
}).then(function() {
	console.log("Port openened.  Sending data...");
	return qz.serial.sendData('COM4', "W\n", props);
}).then(function() {
	console.log("Data sent 1.");
	return qz.serial.sendData('COM4', "", props);
}).then(function() {
	console.log("Data sent 2.");
	return qz.serial.sendData('COM4', "", props);
}).then(function() {
	console.log("Data sent 3.");
	return qz.serial.sendData('COM4', "", props);
}).then(function() {
	console.log("Data sent 4.");
	return qz.serial.sendData('COM4', "", props);
}).then(function() {
	console.log("Data sent 5.");
	return qz.serial.sendData('COM4', "", props);
}).catch(function(err) { console.error(err); });
```

According to @bberenz 

>  it might be a single response because it's returning everything at once (so sends if >=1byte)
We'd need to change to split it out if the response is greater than specified length

**Comment by bberenz** [comment]
I tested this out with a virtual serial port, and that comment I made was wrong. It _does_ currently split out any data received into the specified width, and will wait to send more if there is any remainder.

We may need to revisit testing this on a physical device then.

**Comment by tresf** [comment]
@bberenz is there a chance that some serial properties such as flow control can influence this?  I noticed our sample.html and documentation was incorrect: had the word `begin` instead of `start` and that's been fixed now but tests last night seemed to be similar as before.

Is the above usage correct?

**Comment by bberenz** [comment]
`width` takes precedence so if it is present, `begin` and `end` will just be ignored.
I'm not sure what effect flow control would have on our output though, since we just append to an array until the magic number is hit, then split and send what's there.

The above example is correct, though you shouldn't need any of the empty send commands to continue receiving any data from the device.

**Comment by tresf** [comment]
I'm not sure why the scale would behave differently but our client has actually been live with reading 2-bytes at a time for a few months, so I'll close this out as invalid, working.
