### ISSUE TITLE
Can this work remotely?

### ISSUE THREAD

**Issue by UVLabs** [qzind/tray#1034]
I've been checking out the docs and videos but it's not immediately apparent (i think) whether or not this would work from a remote website?

As in a website on the internet firing a print action in a local store. Think an e-commerce website sending a print action when an order is placed online by a customer

**Comment by lite1979** [comment]
QZ-Tray facilitates the ability to print from a browser on a PC. That means that with some human interaction, the printable content goes from the website (server) to the printer. This doesn't happen without a browser and a PC in between the printer and the server.

If you want to trigger the print after an order is placed, you need a way to get the PC on the printer side to read that from the web server and act accordingly. This may prove to be difficult, as we tend to inhibit web servers from being able to manipulate any action that would normally be the user's (think Java applets and getting rickrolled).

If you can get the browser to refresh a page on a regular basis and print all of the data that has been populated by orders, I could see this working, but there's still a user interaction that needs to be automated.

Still another method would be to have the printers connected to a print-server. This would likely only be possible if the server were running on the same LAN, with the appropriate port forwarding allowing an outside user to interact with it.

https://qz.io/wiki/print-server

**Comment by tresf** [comment]
> I've been checking out the docs and videos but it's not immediately apparent (i think) whether or not this would work from a remote website?
> 
> As in a website on the internet firing a print action in a local store. Think an e-commerce website sending a print action when an order is placed online by a customer

As Lite has explained, in nearly all cases, QZ Tray must be running on the local network of the client.  It's a solution which prints from a PC, invoked by the browser.
