### ISSUE TITLE
setPromiseType bluebird

### ISSUE THREAD

**Issue by jstans** [qzind/tray#104]
I am using: qz.api.setPromiseType([Promise.fromCallback](http://bluebirdjs.com/docs/api/promise.fromcallback.html)) at the start of my code with the latest version of bluebird but my qz promises are rejecting rather than resolving (with the data as the argument), is Promise.fromCallback expecting arguments in the order qz sends them in?

bluebird: 3.4.6
qz: 2.0.1 current commit

**Comment by tresf** [comment]
@jstans our documentation was missing a line... 

```diff
+ var Promise = require('bluebird');
  qz.api.setPromiseType(Promise.fromCallback);
```

I would even go as far as to recommend explicitly using a variable such as `BlueBird` as to hide the built-in global `Promise` object.

```js
var Bluebird = require('bluebird');
qz.api.setPromiseType(Bluebird.fromCallback);
```

If this extra step is not taken, Node will attempt to use the built-in `Promise` type which does not have a `fromCallback` function.

We've added this into our tutorial:

https://qz.io/wiki/2.0-API-Overrides

If this works, please close out.

P.S.  I found a bug on the `onclose` function which affects Node.js, patched here https://github.com/qzind/tray/commit/91b4ae146e72d2e702a2a32b4c9b46f4e64f1278

This mostly causes a problem when QZ Tray is not running and was found while Bluebird testing.

**Comment by jstans** [comment]
Apologies, I should have been a bit more clear. I'm using bluebird in the browser, which I believe overrides window.Promise, so won't use a commonjs syntax.

**Comment by tresf** [comment]
@jstans I can attempt to reproduce later.. 
1. What version of Bluebird?
1. Any other special things to consider (browser version, etc)?
2. What if you use the basic logic instead, does that fix it?

```js
qz.api.setPromiseType(function promise(resolver) { return new Promise(resolver); });
```

**Comment by jstans** [comment]
Bluebird is 3.4.6 installed via bower.

The basic logic seems to work fine!

I now unfortunately have non-qz problems with a module which I suspect is extending the Promise object which is causing unintended behaviour but I've checked that it's not what caused fromCallback to not work.

**Comment by tresf** [comment]
> The basic logic seems to work fine!

Ok, updated per via https://qz.io/wiki/2.0-API-Overrides.

Closing, but feel free to continue using this bug to report your findings as others are likely to encounter them as well.
