### ISSUE TITLE
Partial Cut/Full cut support from HTML printing

### ISSUE THREAD

**Issue by mlscherer** [qzind/tray#1048]
Hi!

We're having an issue with prints cutting when sending an HTML print.

On most of the printers we've used and tested, partial cut is done by default after each print. However, we tested it on a specific model (Bematech MP-4200) and it is only doing the full cut.

The printer supports partial cut. Before using the QZ Tray, we used another solution that was working that way (from RAW printing).

Any ideas or suggestions on what can be done? We need to use the HTML format for this, but also needed the partial cut functionality. Is there any parameter to solve this situation?

Thanks in advance.

**Comment by lite1979** [comment]
The spec sheet for the MP-4200 states 

> "total or partial cut configurable, panel or software application control"

This may be adjusted on the firmware using an advanced configuration program. "Panel" _may_ refer to Control Panel > Devices and Printers > Print Properties > Device Settings, or it may refer to using the Feed button to change settings, described later in my comment.

The application for your printer appears to be "Logic Controls Printers User Software". It may also be called "Bematech User Software"

If using the buttons on the printer, generally you must press and hold the Feed button, turn the printer ON, and wait for the self-test to print. From here you can access the configuration menu using the button(s) based on long- and short-presses for navigation.

If you prefer to use the raw markup language to print your HTML, this is also possible; you will simply have to send the cut command after the rawHTML (assuming ESC/POS) data is sent. Results will vary based on printer density and HTML content.

https://qz.io/wiki/raw#escpos-2

**Comment by mlscherer** [comment]
Hello @lite1979 , thanks for the reply.

Just to share what we identified here that helped us, and maybe it will help others with the same question.

The printer has a default cut setting (set in printer properties in Windows).

When printing via HTML, qz tray always respects this default setting, whereas before, when printing raw, we sent the desired cut setting for each print.
