### ISSUE TITLE
QZ Tray doesn’t refresh its printer list when a USB printer is deleted

### ISSUE THREAD

**Issue by tresf** [qzind/tray#1049]
Quoting the cutomer:

> QZ Tray doesn’t refresh its printer list when we delete an USB Printer from “Windows Printer” and add a new one.
>
> When we call `qz.details` methods , it returns the printer list that include printer that has been removed and doesn’t include then new one.
> Qz tray return the status of the removed printer  : it is `“pending deletion”`.
> 
> Below what QZ Tray sample page returns when calling details methods :
> 
> 6 printers found whereas there are 5 printers. And the name is incorrect.
>
> <img width="669" alt="Screenshot 2022-12-06 at 10 39 43 PM" src="https://user-images.githubusercontent.com/6345473/206082793-70c92bf0-db44-4e50-8636-1bd7e507047f.png">

**Comment by Vzor-** [comment]
I was unable to reproduce this on Windows 10 with a USB Boca BIDI ticket printer. Could we get some more setup/environment info? Could we also get the output of `wmic printer list brief` in powershell after the printer has been deleted?

**Comment by myriamk** [comment]
Hi, the main issue that I noticed is that Qz Tray doesn't  refresh its printer list unless I restart it when I add or remove Windows printer.
What I tested today :
- I have a Windows  printer list with a Boca Printer not connected : (no Boca printer is  plugged to the PC) : **Boca BIDI FGL 26/46 300 DPI (Copie 2)**
 - I plug another Boca Printer to USB port (but not same usb port that previously) : **Boca BIDI FGL 26/46 300 DPI**
![image](https://user-images.githubusercontent.com/7124667/207372081-a4b6a97c-8631-4070-b28d-d394f74c293e.png)
- The result of _wmic printer list brief_command :
![image](https://user-images.githubusercontent.com/7124667/207372129-725f72d5-bca1-4a67-b0b6-715e9a05c5b5.png)
- The result of QZ printer details :
Return from QZ Tray Printer details:(https://demo.qz.io/)
	• [\\sgesrps.fnac.group\Point](file://sgesrps.fnac.group/Point) Copie Flavia
		○ Driver: Canon Generic Plus PCL6
		○ Density: 600dpi
		○ Connection: localhost:Relais_Copie_Flavialocalhost:Relais3_Copie_Flavialocalhost:Relais2_Copie_Flavia
		○ Trays: Automatic-Feeder,manual,top,Type de papier priorit.
	• Envoyer à OneNote 2013
		○ Driver: Send to Microsoft OneNote 15 Driver
		○ Density: 600dpi
		○ Connection: nul:
	• Samsung M2020 Series (192.168.1.160)
		○ Driver: Samsung M2020 Series
		○ Density: 600dpi
		○ Connection: SEC30CDA7FB653E
		○ Trays: Automatic-Feeder,manual
	• **Boca BIDI FGL 26/46 300 DPI (Copie 2)**
		○ Driver: Boca BIDI FGL 26/46 300 DPI
		○ Density: 300dpi
		○ Connection: USB003

		○ Trays: Form-Source,Default Path,Alternate Path,P1 - Rotate 180,P2 - Rotate 180,Path 3,Path 4
	• OneNote (Desktop)
		○ Driver: Send to Microsoft OneNote 16 Driver
		○ Density: 600dpi
		○ Connection: nul:

QZ Printer doesn't return the new plugged printer Boca BIDI FGL 26/46 300 DPI  , but only  **Boca BIDI FGL 26/46 300 DPI (Copie 2)**

**Comment by myriamk** [comment]
I did a second test and removed  Boca BIDI FGL 26/46 300 DPI (Copie 2) printer from Windows printer List.
![image](https://user-images.githubusercontent.com/7124667/207374120-e9c18fe5-f4e4-484b-91b0-fb89dc62c80a.png)
QZ Tray still return the removed printer.

**Comment by tresf** [comment]
@Vzor- pinging you.

**Comment by Vzor-** [comment]
https://github.com/Vzor-/tray/releases/tag/v2.2.3-beta

This release contains a custom JRE with some logging.

**Comment by tresf** [comment]
@myriamk note, the logging won't make it to the log files so please test using `qz-tray-console.exe` from C:\Program Files\QZ Tray.

**Comment by tresf** [comment]
@myriamk hi, just checking in on the above.

**Comment by tresf** [comment]
User reports issue is no longer present with QZ Tray 2.2.2.
