### ISSUE TITLE
authcert.override in properties is not working

### ISSUE THREAD

**Issue by atvvarna** [qzind/tray#105]
Hello,
I tried to add in qz-tray.properties
authcert.override=C:\\Program Files\\QZ Tray\\auth\\override.crt
or 
authcert.override=override.crt
(override.crt is in both locations) but it seems it skip my settings.

Command java -Xms512M -DtrustedRootCert=override.crt -jar qz-tray.jar  works fine.

Regards,
Alex

**Comment by tresf** [comment]
@atvvarna can you please try to escape your backslashes?

e.g.
```properties
authcert.override=C:\\Program Files\\QZ Tray\\auth\\override.crt
```

This is what our chained NSIS technique does and this is what was tested for the `2.0.1` release.

https://qz.io/wiki/compiling#ant-command-line

**Comment by atvvarna** [comment]
Ok, I will test tomorrow but I do it that way as the upper properties where in that format.
I tried with only =override.crt but same.

**Comment by tresf** [comment]
@atvvarna as long as you're on 2.0.1 or higher, the `authcert.override` should be picked up automatically via https://github.com/qzind/tray/blob/2.0/src/qz/auth/Certificate.java#L86.

**Comment by atvvarna** [comment]
I'm with latest version I will post some screenshots tomorrow.

**Comment by tresf** [comment]
@atvvarna apologies for the confusion, this feature is [only available in 2.0.2 (unreleased and higher)](https://github.com/qzind/tray/pull/64#issuecomment-237578951).  This means you will need to compile from source  to try this feature out before the official 2.0.2 release.

Please reopen this issue if the feature is broken with the latest build from the 2.0 branch.

**Comment by kerbymart** [comment]
This should be re-opened, I did a compile and build and it did not solved the issue.

**Comment by atvvarna** [comment]
As a temporary solution you can use:
start.bat file
`cd "C:\Program Files\QZ Tray"
java -Xms512M -DtrustedRootCert=override.crt -jar qz-tray.jar`

**Comment by kerbymart** [comment]
@atvvarna Even running with that option, running the web app from Webstorm (with Server Certificate setup), when launched in the browser like Chrome or Firefox, the "Allow" notification still shows up.

**Comment by atvvarna** [comment]
override.crt should be your certificate. located in QZ Tray folder.
I'm doing the same and it works, also you should modify the demo with your cert.

**Comment by kerbymart** [comment]
Here, http://imgur.com/a/0QVFW I did add the certificate text into the HTML

**Comment by atvvarna** [comment]
Follow these steps: https://qz.io/wiki/2.0-signing-messages
and check your certificate.

**Comment by tresf** [comment]
> This should be re-opened, I did a compile and build and it did not solved the issue.
> Here, http://imgur.com/a/0QVFW I did add the certificate text into the HTML

No, you should follow the instructions we've provided 1. On our mailing list 2. On stackoverflow. 3. On our wiki which has been linked 3 times to you now.

If you have urgency needs, contact our paid support, that's what it's for.

**Comment by tresf** [comment]
@atvvarna I assume this is working for you.  Please feel free to reopen if that's not the case.
