### ISSUE TITLE
MacOS: "find-certificate" must have "-a" option

### ISSUE THREAD

**Issue by tresf** [qzind/tray#1060]
Does NOT work reliably:

```bash
security find-certificate -e support@qz.io /Library/Keychains/System.keychain
```

DOES work reliably:

```bash
security find-certificate -a -e support@qz.io /Library/Keychains/System.keychain
```

Quoting:

> `-a`  Find all matching certificates, not just the first one

🤦

**Comment by tresf** [comment]
@Vzor- can you double check that this `-a` option has been around for a while?

**Comment by Vzor-** [comment]
I can confirm this happens on my machine too. I'll look into it

**Comment by Vzor-** [comment]
-a has been part of security find-certificate since atleast 2013 https://web.archive.org/web/20130209234041/https://ss64.com/osx/security-find-cert.html

**Comment by Vzor-** [comment]
Interestingly, if we give an invalid email we get a different error.

```
>security find-certificate -e support@qz.io /Library/Keychains/System.keychain
security: SecKeychainItemCopyKeychain: The specified keychain could not be found.
>security find-certificate -e acquisitions@qz.io /Library/Keychains/System.keychain   
security: SecCertificateFindByEmail: The specified item could not be found in the keychain.
```
Also requesting the email with -m results in a response before the error. This does not occur with a bad email.
```
>security find-certificate -m -e support@qz.io /Library/Keychains/System.keychain
email addresses: support@qz.io
security: SecKeychainItemCopyKeychain: The specified keychain could not be found.
```
