### ISSUE TITLE
Printing plain HTML to Zebra GK420t isn't working well because... printing too fast?

### ISSUE THREAD

**Issue by sergiocasero** [qzind/tray#1064]
Hello,

I'm working with QZ-Tray and a Zebra GK420t printer, trying to print plain HTML.

The current status is that I can print the HTML but... it's not working as expected. Let me show a pic:

<img width="637" alt="imagen" src="https://user-images.githubusercontent.com/10833202/209795325-989478dd-353d-4113-a159-3994b1665afd.png">

If I print with the official tool, I see everything ok:

<img width="637" alt="imagen" src="https://user-images.githubusercontent.com/10833202/209795283-45cd31d8-be74-4fc5-a777-d2a2ebfdda19.png">

The only difference I see from the printer is the speed, the "QZ-tray labels" are so fast printed, even if have changed the printer speed to the slowest one in the printer hardware settings.

Is this an issue, or maybe I'm loosing something. I've checked the `Advance printing` section on the website but I can't see nothing related to the speed, I've also tried to change the density. Maybe there is a problem with the... font??

**Comment by lite1979** [comment]
@sergiocasero Sorry for the trouble. We will need more information to proceed:

1. Can you zip logs and send them to support@qz.io ?

QZ-Tray > Advanced > Diagnostic > Zip logs to Desktop, attach in email

2. Can you tell us what the "official tool" is that you're using? 

3. A self-test of the GK420t will help: Hold the feed button until it blinks once, then release. Take a picture of the resulting printout and share it here or send it to support@qz.io

I suspect that the printer is feeding the labels too fast, and this is causing the printed content to be too light to read. The self-test should confirm this.

The speed at which the printer feeds during a print job is best changed in a program called "Zebra Setup Utility" using a Windows PC.

**Comment by sergiocasero** [comment]
Hello @lite1979, sure! As soon as I can, I'll send all the data to you.

1. Yes, sure
2. Zebra Designer tool I mean
3. I'll do, we're on holidays until next monday, but I'll try to send it ASAP

jmmmm Yes, if I remember well, there is a Zebra Setup Utility app, I'll check it because I've changed the speed inside the Windows Printers section

**Comment by sergiocasero** [comment]
Ok, so this is the config printed by the printer

![imagen](https://user-images.githubusercontent.com/10833202/209932383-6984fbaa-3de0-48e9-966e-6f0ce65b4f7e.png)

**Comment by tresf** [comment]
@sergiocasero  It looks like it's defaulting to a different font as well.  Note, our HTML API has very limited support for 3rd party fonts, so I would recommend getting the fonts correct using a few test prints.

Furthemore, can you advise what the email subject is?  I cannot seem to locate the logs, which would contain the HTML in question so that we can reproduce.

**Comment by sergiocasero** [comment]
Hello @tresf, I didn't send the logs because of we were on holidays. 

The issue is solved because of the printer settings (as you said).

For incoming people with this printer, in my case the correct values are:

Speed: 50.8
Darkness: 25

Don't use font-size < 8px.
If font-size < 10px -> bold style.

Thanks you all!

**Comment by tresf** [comment]
@sergiocasero thanks for the update!
