### ISSUE TITLE
Make qz.websocket.connect() still using localhost certificate

### ISSUE THREAD

**Issue by alu0100990539** [qzind/tray#1067]
Hi, I use 2.2.1 self-compile with me own-create certificate like this:

<details>
<summary>Link hidden (outdated)</summary>
https://ijustlearnedsomethingnewtoday.blogspot.com/2017/04/using-self-signed-certificates-with-qz.html
</details>

All ok, but when I try to conect (previous follow and do all this steps: [https://qz.io/docs/signing-examples#javascript](https://qz.io/docs/signing-examples#javascript)) the conection still make with the localhost certificate:

![image](https://user-images.githubusercontent.com/50412651/211173817-75742de8-b85e-410a-984a-cc79f43417df.png)

When I click to check the details about this certificate:

![image](https://user-images.githubusercontent.com/50412651/211173856-5cedb6dc-5979-4bdc-89dc-1ebebdad09e5.png)
![image](https://user-images.githubusercontent.com/50412651/211173903-55b41aa0-6d6b-4a92-81c1-8c31d57e7c7b.png)

I see this, thats not the certificate that I create and use to sing the message.

I think I'm not understanding something...

Thanks.

**Comment by alu0100990539** [comment]
Thats the certificate that I use to self-compilling and to sing the messages:

![image](https://user-images.githubusercontent.com/50412651/211174005-7828e8f3-adcb-418e-bba3-289cb6625409.png)

Thanks.

**Comment by tresf** [comment]
That tutorial linked is 5 years old and is outdated.  The link has been hidden to avoid more people visiting this outdated article.  If you have questions about an article someone else wrote, please ask them.

That said... 

There are two certificates you should be worried about when using QZ Tray:
1. The licensing certificate
2. The SSL certificate

These are NOT related although you may -- if you choose -- to use the same certificate for both.

To update the licensing (signing) certificate:
1. Provide your own as `override.crt`<br>-- OR --
2. Generate and install a new certificate using Advanced, Site Manager, +, Create New
3. Update `setSignaturePromise(...)` and `setCertificatePromise(...)` accordingly

To update the SSL certificate:
1. Re-run the `certgen` step of the installer providing `--key` and `--cert` parameters of your own certificate.<br>-- OR --
2. Re-run the `certgen` using the `--host` parameter where you may provide a custom hostname or IP address

**Comment by tresf** [comment]
Furthemore, if you are receiving error messages related to security software, you will have to escalate with them.  We do not support QZ Tray running with advanced security software, as it can block `localhost` certificates as well as completely sandbox the QZ Tray application, both of which will prevent QZ Tray from working at all.  You would have to take any Kaspersky related issues directly to Kaspersky support, not here.
