### ISSUE TITLE
Mistery error (maybe certificates???)

### ISSUE THREAD

**Issue by alu0100990539** [qzind/tray#1069]
I dont understand this error, sorry too much:

![image](https://user-images.githubusercontent.com/50412651/211540986-9667b040-e0df-4e62-9899-78c8ae402480.png)

I check the PFD file and is ok.

The error only happen when try to print in this pc only, print in other pc no problem...

Thanks.

**Comment by tresf** [comment]
Hi, this issue is documented here: https://qz.io/docs/faq#pkix-build-path-failed

**Comment by tresf** [comment]
> Sorry and thanks

Oh, no need to apologize!  Were you able to fix it?  The web developer may be happy using base64 which will avoid the need for Java to reach out to the web in this fashion.  I only closed this issue because it's documented, feel free to use this area to tell us or others how you fixed it!

**Comment by alu0100990539** [comment]
Hi @tresf , I try but I can´t fix it yet, still the same.

I do all the solutions that apear in the docs: check certificates in sslshopper.com, install the certificates in java, add exception in firewall (in and out), add exception in java for the web site, even reinstall java, but no fix it...

How can I get more details about this bug? in chrome developer console I didn't see more details...

Thanks @tresf

**Comment by tresf** [comment]
This MUST be done on the problematic workstation.  Using SSLShopper won't expose this issue if it's related to locally installed software.
