### ISSUE TITLE
unable to use it in flipkart seller panel

### ISSUE THREAD

**Issue by kuldeepbala198** [qzind/tray#1083]
when i try to use it in flipkart seller portal it says qz tray is not detected please go to settings kindly help me out with this
![Screenshot (15)](https://user-images.githubusercontent.com/99167287/213910217-7371c3d5-86ea-4287-95eb-e6013668c98b.png)

**Comment by tresf** [comment]
Hi,

Please reach out to Flipkart support first.

**Comment by tresf** [comment]
Closing due to lack of response.  Please let us know what the fix was, or ask Flipkart to escalate this issue to us if you feel it's a defect with QZ Tray.
