### ISSUE TITLE
Typo in the release date for version 2.2.2 on GitHub

### ISSUE THREAD

**Issue by jacobshilitz** [qzind/tray#1086]
A minor issue but worth noting.

There is a mistake on the release page for version 2.2.2 on GitHub. The date listed is `2022-01-18` but it should be `2023-01-18`. This may cause confusion and should be corrected.
Thanks
https://github.com/qzind/tray/releases/tag/v2.2.2

**Comment by tresf** [comment]
Kudos!  Fixed!
