### ISSUE TITLE
React Native support!

### ISSUE THREAD

**Issue by PhamChuongBD** [qzind/tray#1101]
Hello there
If I use web socket, can I send a print command from React Native? Thank you.

**Comment by tresf** [comment]
Hi, yes.  To override the websocket you may use this syntax:. https://qz.io/docs/api-overrides#websocket

**Comment by PhamChuongBD** [comment]
Hi @tresf 
Do you have any sample code using React Native? If you do, please share it with me for reference. Thank you.
