### ISSUE TITLE
Xprinter XP-350BM not prining

### ISSUE THREAD

**Issue by itsyosefali** [qzind/tray#1103]
hello as you can see from the title
i tried to connect qz-tray-demo with my Xprinter XP-350BM
and i used ESC/POS Language but when i try print from qz-tray it dont print 
note : the printer is working and print with anything ive tried it

**Comment by lite1979** [comment]
I'm afraid this is not a problem with QZ-Tray, but a problem with the printer and its capabilities.

The XPrinter XP-350BM is advertised as a label printer, not a receipt printer, so I would not normally expect it to process ESC/POS commands, which are typically used with receipt printers.

All the same, the product specification _does imply that it supports ESC/POS_

> Q:What are your product command?

A:Thermal printer compatible with ESC\POS.
Label printer compatible with TSPL\ EPL\ DPL\ ZPL emulation.

source: https://www.xprintertech.com/xp-350b/xp-350bm

I have seen other complaints stating that the printer does not support ESC/POS as well:

https://github.com/mike42/escpos-php/issues/711

https://github.com/mike42/escpos-php/issues/127

I recommend you consult the manufacturer to see why this printer does not print the ESC/POS commands as advertised.

I have a feeling that the printer will work with ZPL commands.
