### ISSUE TITLE
I'm facing trouble with installation on Ubuntu server 22.04.2 LTS

### ISSUE THREAD

**Issue by naderelabed** [qzind/tray#1109]
I'm using the command "wget -qO - qz.sh | bash" for the installation.

the linux server is a VPS with a web application we use it to serve some android POS devices to print directly with raw printing command (ESC/POS).

the installation return this warning:
```
Running spawn task...
      [warning] Task spawn skipped.  You'll have to start QZ Tray manually.
```
I try to start QZ manually by running "sudo ./qz-tray"  from the directory "/opt/qz-tray/"

and this returned the error below:
Idle runner failed to preemptively start JavaFX service

with https://demo.qz.io/ testing connections this error returned:
Error: Unable to establish connection with QZ

from console this is the error details:
```
Error: Unable to establish connection with QZ
    at deeper (qz-tray.js:99:40)
    at _qz.websocket.connection.onerror (qz-tray.js:168:29)
```

I'm using this java:
```
-bash: /usr/lib/jvm/java-11-openjdk-amd64/
```

I appreciate your help in this regards, if any further information needed I will provide.

Thanks in advance for your time, your help and support are appreciated.

**Comment by tresf** [comment]
Java is bundled since 2.2.x and you shouldn't ever run as root.

That said, is the server on-prem?  QZ Tray requires a valid CA issued SSL certificate to run in print-server mode.  I'd recommend testing from HTTP, not HTTPS.  For Android you may also add an exception: https://qz.io/docs/print-server#android-using-chrome-browser-pixel-moto-samsung-et-cetera-smart-devices

**Comment by tresf** [comment]
In most cases, trying to get QZ Tray to run in a VPS won't work.  QZ Tray isn't magic, it can't talk to local printers from the cloud without a bunch of ports getting opened and/or forwarded.

**Comment by naderelabed** [comment]
Thanks for your support and the clarification you provide.

for my case, the android pos are mobile devices for the field sales team as pic below.

![1](https://user-images.githubusercontent.com/97305974/229768284-e3cd07cb-6ae6-4849-bfb9-abe890c8945a.png)

I understand the limitation for QZ Tray as to be on the same network (which I was not aware of before), 

in my case as the field sales team are on the street, what are my options for a print server (as there are no option for android install or if there are a way to use qz tray on android as an application).

Thanks for your time, I really get informed with your help and clarifications.

**Comment by tresf** [comment]
If the printer is built into the handheld, you should look for native android solutions.  If the printer has a bluetooth connection, Google Chrome does direcly support Bluetooth, however I have not found any ready examples of it for printing yet.
