### ISSUE TITLE
Build Failed  jsign: The file D:\project couldn't be found

### ISSUE THREAD

**Issue by rizky-saraan** [qzind/tray#1122]
please help me when i build i got errror this

$ ant nsis -Dauthcert.use="cert.pem"
Buildfile: D:\project hokky cargo\qz_tray_new\tray\build.xml

get-host-arch:

get-target-arch:

target-os-windows:

init:
     [echo] Building qz-tray using JDK 13

quick-clean:

get-host-os:

get-target-os:

get-libext:

platform-detect:

echo-platform:
     [echo]
     [echo]         Host platform:
     [echo]             host.os: "windows"
     [echo]             host.arch: "x86_64"
     [echo]             host.libext: "dll"
     [echo]             host.os.windows: true
     [echo]             host.arch.x86_64: true
     [echo]

echo-platform:
     [echo]
     [echo]         Target platform:
     [echo]             target.os: "windows"
     [echo]             target.arch: "x86_64"
     [echo]             target.libext: "dll"
     [echo]             target.os.windows: true
     [echo]             target.arch.x86_64: true
     [echo]

get-javafx-versions:
     [echo]
     [echo]         JavaFX host platform:
     [echo]             Version: 15.ea+3_monocle (windows, x86_64)
     [echo]             Major Version: 15
     [echo]             URLs: "15-ea+3_monocle"
     [echo]
     [echo]         JavaFX target platform:
     [echo]             Version: 15.ea+3_monocle (windows, x86_64)
     [echo]             Major Version: 15
     [echo]             URLs: ""15-ea+3_monocle"
     [echo]

host-fx-exists:
     [echo] JavaFX host platform file glass.dll found, skipping download.
     [echo] Location: D:\project hokky cargo\qz_tray_new\tray\lib\javafx-windows-x86_64-15-ea+3_monocle\javafx-sdk-15\bin\glass.dll

download-javafx-host:

target-fx-exists:
     [echo] JavaFX target platform file glass.dll found, skipping download.
     [echo] Location: D:\project hokky cargo\qz_tray_new\tray\out\javafx-windows-x86_64-15-ea+3_monocle\javafx-sdk-15\bin\glass.dll

download-javafx-target:

download-javafx:

compile-socket:
    [mkdir] Created dir: D:\project hokky cargo\qz_tray_new\tray\out\build\qz-tray
    [javac] Compiling 171 source files to D:\project hokky cargo\qz_tray_new\tray\out\build\qz-tray
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
     [copy] Copying 50 files to D:\project hokky cargo\qz_tray_new\tray\out\build\qz-tray
     [copy] Copying 1 file to D:\project hokky cargo\qz_tray_new\tray\out\dist

copy-libs:
    [mkdir] Created dir: D:\project hokky cargo\qz_tray_new\tray\out\dist\libs
     [copy] Copying 56 files to D:\project hokky cargo\qz_tray_new\tray\out\dist\libs
    [mkdir] Created dir: D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\charsets\TCVN-3.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\charsets\icu4j-charset-slim.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\charsets\icu4j-slim.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\commons-codec-1.15.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\commons-io-2.11.0.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\commons-lang3-3.12.0.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\commons-pool2-2.11.1.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\communication\hid4java-0.7.1-SNAPSHOT.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\communication\jna-5.12.1.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\communication\jna-platform-5.12.1.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\communication\jssc-2.9.5-SNAPSHOT.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\communication\libusb4java-1.3.0-darwin-x86-64.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\communication\libusb4java-1.3.0-linux-aarch64.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\communication\libusb4java-1.3.0-linux-arm.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\communication\libusb4java-1.3.0-linux-x86-64.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\communication\libusb4java-1.3.0-linux-x86.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\communication\libusb4java-1.3.0-win32-x86-64.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\communication\libusb4java-1.3.0-win32-x86.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\communication\purejavahidapi-0.0.10-SNAPSHOT.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\communication\usb-api-1.0.2.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\communication\usb4java-1.3.0.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\communication\usb4java-javax-1.3.0.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\darcula-bobbylight.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\imaging\common-image-3.8.3.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\imaging\common-io-3.8.3.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\imaging\common-lang-3.8.3.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\imaging\imageio-core-3.8.3.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\imaging\imageio-jpeg-3.8.3.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\imaging\imageio-metadata-3.8.3.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\java-semver-0.10.0.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\logging\log4j-api-2.19.0.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\logging\log4j-core-2.19.0.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\mslinks-1.1.0.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\printing\pdfbox-app-2.0.27.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\websocket\javax.websocket-api-1.0.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\websocket\jettison-1.3.3-SNAPSHOT.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\websocket\jetty-client-9.4.50.v20221201.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\websocket\jetty-http-9.4.50.v20221201.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\websocket\jetty-io-9.4.50.v20221201.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\websocket\jetty-security-9.4.50.v20221201.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\websocket\jetty-server-9.4.50.v20221201.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\websocket\jetty-servlet-9.4.50.v20221201.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\websocket\jetty-util-9.4.50.v20221201.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\websocket\not-going-to-be-commons-ssl-0.3.20.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\websocket\servlet-api-3.1.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\websocket\websocket-api-9.4.50.v20221201.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\websocket\websocket-client-9.4.50.v20221201.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\websocket\websocket-common-9.4.50.v20221201.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\websocket\websocket-server-9.4.50.v20221201.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\lib\websocket\websocket-servlet-9.4.50.v20221201.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
     [echo] Copying D:\project hokky cargo\qz_tray_new\tray/out/javafx-windows-x86_64-15-ea+3_monocle
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\out\javafx-windows-x86_64-15-ea+3_monocle\javafx-sdk-15\lib\javafx-swt.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\out\javafx-windows-x86_64-15-ea+3_monocle\javafx-sdk-15\lib\javafx.base.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\out\javafx-windows-x86_64-15-ea+3_monocle\javafx-sdk-15\lib\javafx.controls.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\out\javafx-windows-x86_64-15-ea+3_monocle\javafx-sdk-15\lib\javafx.fxml.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\out\javafx-windows-x86_64-15-ea+3_monocle\javafx-sdk-15\lib\javafx.graphics.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\out\javafx-windows-x86_64-15-ea+3_monocle\javafx-sdk-15\lib\javafx.media.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\out\javafx-windows-x86_64-15-ea+3_monocle\javafx-sdk-15\lib\javafx.swing.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp
    [unzip] Expanding: D:\project hokky cargo\qz_tray_new\tray\out\javafx-windows-x86_64-15-ea+3_monocle\javafx-sdk-15\lib\javafx.web.jar into D:\project hokky cargo\qz_tray_new\tray\out\libs-temp

copy-dylibs:

copy-dlls:
     [echo] Copying native library files to libs
     [copy] Copying 4 files to D:\project hokky cargo\qz_tray_new\tray\out\dist\libs
     [copy] Copying D:\project hokky cargo\qz_tray_new\tray\out\libs-temp\com\sun\jna\win32-x86-64\jnidispatch.dll to D:\project hokky cargo\qz_tray_new\tray\out\dist\libs\jnidispatch.dll
     [copy] Copying D:\project hokky cargo\qz_tray_new\tray\out\libs-temp\natives\windows_64\jssc.dll to D:\project hokky cargo\qz_tray_new\tray\out\dist\libs\jssc.dll
     [copy] Copying D:\project hokky cargo\qz_tray_new\tray\out\libs-temp\org\usb4java\win32-x86-64\libusb4java.dll to D:\project hokky cargo\qz_tray_new\tray\out\dist\libs\libusb4java.dll
     [copy] Copying D:\project hokky cargo\qz_tray_new\tray\out\libs-temp\win32-x86-64\hidapi.dll to D:\project hokky cargo\qz_tray_new\tray\out\dist\libs\hidapi.dll

copy-solibs:

externalize-libs:

build-jar:
     [echo] Building jar
     [echo] Stripping jlink-incompatible files
      [jar] Building jar: D:\project hokky cargo\qz_tray_new\tray\out\dist\qz-tray.jar

override-authcert:
     [echo] Bundling with manual cert for signing auth: cert.pem
     [copy] Copying 1 file to D:\project hokky cargo\qz_tray_new\tray\out\dist

build-demo:
     [echo] Copying demo resource files to D:\project hokky cargo\qz_tray_new\tray/out/dist/demo
     [copy] Copying 48 files to D:\project hokky cargo\qz_tray_new\tray\out\dist\demo
     [move] Moving 1 file to D:\project hokky cargo\qz_tray_new\tray\out\dist\demo

whitelist-certs:

distribute:
     [echo] Process complete

download-jre:
     [echo] Downloading and bundling the jre for windows
     [java] [WARN] 2023-04-28T06:51:56,133 @ qz.build.JLink:53
     [java]     Java versions are incompatible, locating a suitable runtime for Java 11...
     [java] [INFO] 2023-04-28T06:51:56,145 @ qz.build.JLink:120
     [java]     No platform specified, assuming 'windows'
     [java] [INFO] 2023-04-28T06:51:56,146 @ qz.build.VendorArch:39
     [java]     Arch provided: amd64 matches: amd64
     [java] [INFO] 2023-04-28T06:51:56,147 @ qz.build.JLink:129
     [java]     No garbage collector specified, assuming 'hotspot'
     [java] [INFO] 2023-04-28T06:51:56,150 @ qz.build.Fetcher:80
     [java]     Resource 'jlink/jdk-bellsoft-amd64-windows-11.0.17_7' from [https://download.bell-sw.com/java/11.0.17+7/bellsoft-jdk11.0.17+7-windows-amd64.zip] has already been downloaded and extracted.  Using: [D:\project hokky cargo\qz_tray_new\tray\out\jlink\jdk-bellsoft-amd64-windows-11.0.17_7]
     [java] [INFO] 2023-04-28T06:51:56,152 @ qz.build.JLink:155
     [java]     Selecting JDK home: D:\project hokky cargo\qz_tray_new\tray\out\jlink\jdk-bellsoft-amd64-windows-11.0.17_7\jdk-11.0.17
     [java] [INFO] 2023-04-28T06:51:56,153 @ qz.build.JLink:189
     [java]     Using JAVA_HOME: D:\project hokky cargo\qz_tray_new\tray\out\jlink\jdk-bellsoft-amd64-windows-11.0.17_7\jdk-11.0.17
     [java] [INFO] 2023-04-28T06:51:56,154 @ qz.build.JLink:192
     [java]     Assuming jdeps path: D:\project hokky cargo\qz_tray_new\tray\out\jlink\jdk-bellsoft-amd64-windows-11.0.17_7\jdk-11.0.17\bin\jdeps.exe
     [java] [INFO] 2023-04-28T06:51:56,154 @ qz.build.JLink:193
     [java]     Assuming jlink path: D:\project hokky cargo\qz_tray_new\tray\out\jlink\jdk-bellsoft-amd64-windows-11.0.17_7\jdk-11.0.17\bin\jlink.exe
     [java] [DEBUG] 2023-04-28T06:51:56,156 @ qz.utils.ShellUtilities:182
     [java]     Executing: [D:\project hokky cargo\qz_tray_new\tray\out\jlink\jdk-bellsoft-amd64-windows-11.0.17_7\jdk-11.0.17\bin\jdeps.exe, --version]
     [java] [INFO] 2023-04-28T06:51:56,658 @ qz.build.VendorArch:39
     [java]     Arch provided: x86_64 matches: x86_64
     [java] [INFO] 2023-04-28T06:51:56,659 @ qz.build.JLink:129
     [java]     No garbage collector specified, assuming 'hotspot'
     [java] [INFO] 2023-04-28T06:51:56,660 @ qz.build.Fetcher:80
     [java]     Resource 'jlink/jdk-bellsoft-amd64-windows-11.0.17_7' from [https://download.bell-sw.com/java/11.0.17+7/bellsoft-jdk11.0.17+7-windows-amd64.zip] has already been downloaded and extracted.  Using: [D:\project hokky cargo\qz_tray_new\tray\out\jlink\jdk-bellsoft-amd64-windows-11.0.17_7]
     [java] [INFO] 2023-04-28T06:51:56,661 @ qz.build.JLink:155
     [java]     Selecting JDK home: D:\project hokky cargo\qz_tray_new\tray\out\jlink\jdk-bellsoft-amd64-windows-11.0.17_7\jdk-11.0.17
     [java] [INFO] 2023-04-28T06:51:56,662 @ qz.build.JLink:63
     [java]     Selecting jmods folder: D:\project hokky cargo\qz_tray_new\tray\out\jlink\jdk-bellsoft-amd64-windows-11.0.17_7\jdk-11.0.17\jmods
     [java] [INFO] 2023-04-28T06:51:56,662 @ qz.build.JLink:171
     [java]     Assuming jar path: D:\project hokky cargo\qz_tray_new\tray\out\dist\qz-tray.jar
     [java] [INFO] 2023-04-28T06:51:56,663 @ qz.build.JLink:181
     [java]     Assuming output path: D:\project hokky cargo\qz_tray_new\tray\out\dist\runtime
     [java] [INFO] 2023-04-28T06:51:56,663 @ qz.build.JLink:201
     [java]     Calling jdeps to determine runtime dependencies
     [java] [DEBUG] 2023-04-28T06:51:56,664 @ qz.utils.ShellUtilities:182
     [java]     Executing: [D:\project hokky cargo\qz_tray_new\tray\out\jlink\jdk-bellsoft-amd64-windows-11.0.17_7\jdk-11.0.17\bin\jdeps.exe, --multi-release, 9, --list-deps, --ignore-missing-deps, D:\project hokky cargo\qz_tray_new\tray\out\dist\qz-tray.jar]
     [java] [TRACE] 2023-04-28T06:52:31,004 @ qz.build.JLink:216
     [java]     Removing dependency: 'JDK removed internal API/sun.reflect'
     [java] [DEBUG] 2023-04-28T06:52:31,014 @ qz.utils.ShellUtilities:90
     [java]     Executing: [D:\project hokky cargo\qz_tray_new\tray\out\jlink\jdk-bellsoft-amd64-windows-11.0.17_7\jdk-11.0.17\bin\jlink.exe, --strip-debug, --compress=2, --no-header-files, --no-man-pages, --exclude-files=glob:**/legal/**, --module-path, D:\project hokky cargo\qz_tray_new\tray\out\jlink\jdk-bellsoft-amd64-windows-11.0.17_7\jdk-11.0.17\jmods, --add-modules, java.base,java.compiler,java.datatransfer,java.desktop,java.logging,java.management,java.naming,java.net.http,java.prefs,java.rmi,java.scripting,java.security.jgss,java.sql,java.xml,jdk.jfr,jdk.jsobject,jdk.unsupported,jdk.unsupported.desktop,jdk.xml.dom,jdk.zipfs,jdk.crypto.ec, --output, D:\project hokky cargo\qz_tray_new\tray\out\dist\runtime]
     [java] [INFO] 2023-04-28T06:52:49,031 @ qz.build.JLink:268
     [java]     Successfully deployed a jre to D:\project hokky cargo\qz_tray_new\tray\out\dist\runtime
     [java] [INFO] 2023-04-28T06:52:49,035 @ qz.build.JLink:284
     [java]     Keeping D:\project hokky cargo\qz_tray_new\tray\out\dist\runtime\bin\awt.dll
     [java] [INFO] 2023-04-28T06:52:49,036 @ qz.build.JLink:284
     [java]     Keeping D:\project hokky cargo\qz_tray_new\tray\out\dist\runtime\bin\client
     [java] [INFO] 2023-04-28T06:52:49,037 @ qz.build.JLink:284
     [java]     Keeping D:\project hokky cargo\qz_tray_new\tray\out\dist\runtime\bin\fontmanager.dll
     [java] [INFO] 2023-04-28T06:52:49,037 @ qz.build.JLink:284
     [java]     Keeping D:\project hokky cargo\qz_tray_new\tray\out\dist\runtime\bin\freetype.dll
     [java] [INFO] 2023-04-28T06:52:49,038 @ qz.build.JLink:284
     [java]     Keeping D:\project hokky cargo\qz_tray_new\tray\out\dist\runtime\bin\j2gss.dll
     [java] [INFO] 2023-04-28T06:52:49,038 @ qz.build.JLink:284
     [java]     Keeping D:\project hokky cargo\qz_tray_new\tray\out\dist\runtime\bin\java.dll
     [java] [INFO] 2023-04-28T06:52:49,039 @ qz.build.JLink:289
     [java]     Keeping D:\project hokky cargo\qz_tray_new\tray\out\dist\runtime\bin\java.exe
     [java] [INFO] 2023-04-28T06:52:49,039 @ qz.build.JLink:284
     [java]     Keeping D:\project hokky cargo\qz_tray_new\tray\out\dist\runtime\bin\javajpeg.dll
     [java] [INFO] 2023-04-28T06:52:49,040 @ qz.build.JLink:289
     [java]     Keeping D:\project hokky cargo\qz_tray_new\tray\out\dist\runtime\bin\javaw.exe
     [java] [INFO] 2023-04-28T06:52:49,040 @ qz.build.JLink:284
     [java]     Keeping D:\project hokky cargo\qz_tray_new\tray\out\dist\runtime\bin\jawt.dll
     [java] [INFO] 2023-04-28T06:52:49,041 @ qz.build.JLink:293
     [java]     Deleting D:\project hokky cargo\qz_tray_new\tray\out\dist\runtime\bin\jfr.exe
     [java] [INFO] 2023-04-28T06:52:49,042 @ qz.build.JLink:284
     [java]     Keeping D:\project hokky cargo\qz_tray_new\tray\out\dist\runtime\bin\jimage.dll
     [java] [INFO] 2023-04-28T06:52:49,042 @ qz.build.JLink:284
     [java]     Keeping D:\project hokky cargo\qz_tray_new\tray\out\dist\runtime\bin\jli.dll
     [java] [INFO] 2023-04-28T06:52:49,043 @ qz.build.JLink:293
     [java]     Deleting D:\project hokky cargo\qz_tray_new\tray\out\dist\runtime\bin\jrunscript.exe
     [java] [INFO] 2023-04-28T06:52:49,044 @ qz.build.JLink:284
     [java]     Keeping D:\project hokky cargo\qz_tray_new\tray\out\dist\runtime\bin\jsound.dll
     [java] [INFO] 2023-04-28T06:52:49,045 @ qz.build.JLink:293
     [java]     Deleting D:\project hokky cargo\qz_tray_new\tray\out\dist\runtime\bin\keytool.exe
     [java] [INFO] 2023-04-28T06:52:49,047 @ qz.build.JLink:293
     [java]     Deleting D:\project hokky cargo\qz_tray_new\tray\out\dist\runtime\bin\kinit.exe
     [java] [INFO] 2023-04-28T06:52:49,048 @ qz.build.JLink:293
     [java]     Deleting D:\project hokky cargo\qz_tray_new\tray\out\dist\runtime\bin\klist.exe
     [java] [INFO] 2023-04-28T06:52:49,050 @ qz.build.JLink:293
     [java]     Deleting D:\project hokky cargo\qz_tray_new\tray\out\dist\runtime\bin\ktab.exe
     [java] [INFO] 2023-04-28T06:52:49,051 @ qz.build.JLink:284
     [java]     Keeping D:\project hokky cargo\qz_tray_new\tray\out\dist\runtime\bin\lcms.dll
     [java] [INFO] 2023-04-28T06:52:49,052 @ qz.build.JLink:284
     [java]     Keeping D:\project hokky cargo\qz_tray_new\tray\out\dist\runtime\bin\management.dll
     [java] [INFO] 2023-04-28T06:52:49,052 @ qz.build.JLink:284
     [java]     Keeping D:\project hokky cargo\qz_tray_new\tray\out\dist\runtime\bin\mlib_image.dll
     [java] [INFO] 2023-04-28T06:52:49,053 @ qz.build.JLink:284
     [java]     Keeping D:\project hokky cargo\qz_tray_new\tray\out\dist\runtime\bin\msvcp140.dll
     [java] [INFO] 2023-04-28T06:52:49,053 @ qz.build.JLink:284
     [java]     Keeping D:\project hokky cargo\qz_tray_new\tray\out\dist\runtime\bin\net.dll
     [java] [INFO] 2023-04-28T06:52:49,054 @ qz.build.JLink:284
     [java]     Keeping D:\project hokky cargo\qz_tray_new\tray\out\dist\runtime\bin\nio.dll
     [java] [INFO] 2023-04-28T06:52:49,054 @ qz.build.JLink:284
     [java]     Keeping D:\project hokky cargo\qz_tray_new\tray\out\dist\runtime\bin\prefs.dll
     [java] [INFO] 2023-04-28T06:52:49,054 @ qz.build.JLink:284
     [java]     Keeping D:\project hokky cargo\qz_tray_new\tray\out\dist\runtime\bin\rmi.dll
     [java] [INFO] 2023-04-28T06:52:49,055 @ qz.build.JLink:293
     [java]     Deleting D:\project hokky cargo\qz_tray_new\tray\out\dist\runtime\bin\rmid.exe
     [java] [INFO] 2023-04-28T06:52:49,057 @ qz.build.JLink:293
     [java]     Deleting D:\project hokky cargo\qz_tray_new\tray\out\dist\runtime\bin\rmiregistry.exe
     [java] [INFO] 2023-04-28T06:52:49,058 @ qz.build.JLink:284
     [java]     Keeping D:\project hokky cargo\qz_tray_new\tray\out\dist\runtime\bin\server
     [java] [INFO] 2023-04-28T06:52:49,085 @ qz.build.JLink:284
     [java]     Keeping D:\project hokky cargo\qz_tray_new\tray\out\dist\runtime\bin\splashscreen.dll
     [java] [INFO] 2023-04-28T06:52:49,086 @ qz.build.JLink:284
     [java]     Keeping D:\project hokky cargo\qz_tray_new\tray\out\dist\runtime\bin\sspi_bridge.dll
     [java] [INFO] 2023-04-28T06:52:49,086 @ qz.build.JLink:284
     [java]     Keeping D:\project hokky cargo\qz_tray_new\tray\out\dist\runtime\bin\sunec.dll
     [java] [INFO] 2023-04-28T06:52:49,087 @ qz.build.JLink:284
     [java]     Keeping D:\project hokky cargo\qz_tray_new\tray\out\dist\runtime\bin\vcruntime140.dll
     [java] [INFO] 2023-04-28T06:52:49,087 @ qz.build.JLink:284
     [java]     Keeping D:\project hokky cargo\qz_tray_new\tray\out\dist\runtime\bin\verify.dll
     [java] [INFO] 2023-04-28T06:52:49,088 @ qz.build.JLink:284
     [java]     Keeping D:\project hokky cargo\qz_tray_new\tray\out\dist\runtime\bin\w2k_lsa_auth.dll
     [java] [INFO] 2023-04-28T06:52:49,089 @ qz.build.JLink:284
     [java]     Keeping D:\project hokky cargo\qz_tray_new\tray\out\dist\runtime\bin\zip.dll

get-version:
     [echo]
     [echo]             Version   : 2.2.2
     [echo]             Bundle Id : io.qz.qz-tray
     [echo]

build-exe:

sign-win:

find-jsign:

sign-win-tsa:

find-jsign:

sign-win-self:
     [echo] Signing without timestamp:
     [echo]
     [echo]                 No tsaurl was provided so the file was not timestamped. Users will not be able to validate
     [echo]                 this file after the signer certificate's expiration date or after any future revocation date.
     [echo]
     [java] jsign: The file D:\project couldn't be found
     [java] Try `java -jar jsign.jar --help' for more information.

BUILD FAILED
D:\project hokky cargo\qz_tray_new\tray\ant\windows\installer.xml:20: The following error occurred while executing this line:
D:\project hokky cargo\qz_tray_new\tray\ant\windows\installer.xml:111: The following error occurred while executing this line:
D:\project hokky cargo\qz_tray_new\tray\ant\windows\installer.xml:160: Java returned: 1

**Comment by tresf** [comment]
@rizky-saraan hi, thanks for the bug report.  Please git cherry-pick https://github.com/qzind/tray/commit/c26b7db4ee9503d92d1e0fb96e5329674b92d241 and your issue will be solved.  Alternately, you may remove the spaces from your folder name.

**Comment by rizky-saraan** [comment]
oke thanks for your reply
