### ISSUE TITLE
Help printing image and ticket in one job

### ISSUE THREAD

**Issue by yaredga** [qzind/tray#1126]
Hola buen dia queria ver si de casualidad me podrian apoyar , estoy imprimiendo tickets y ahora estoy batallando ya que imprimo uno pero necesito ponerla la imagen , osea un logo al principio , actualmente ya lo hago pero lo hago como si fueran 2 impresiones y la necesito hacer en una , este es un ejemplo 

> Translate: 
> Hi, good morning, I wanted to see if you could help me by chance. I'm printing tickets and now I'm struggling since I print one but I need to put the image, that is, a logo at the beginning. Currently I already do it, but I do it as if there were 2 prints and I need it do in a , this is an example

```js
function printTextPlanpos(imagen, ticket) {
    var config = {...getUpdatedConfig()}
    cfg = null
    ticket = ticket.replace("corta", '\x1D' + '\x56' + '\x00');

    var printData1 = [{
        type: 'pixel', format: 'image',flavor: 'file',data:"https://placekitten.com/400/450"
    // type: 'pixel', format: 'image',flavor: 'file',data:imagen
    }];

    var printData2 = [
        { type: 'raw', format: 'plain',data:ticket, options: {language: "ESCPOS"}}
    ];
    // qz.print(config, [prinLogo, printData]).catch(displayError);

    config.config.margins = {
        top: 0.15,
        width:50,
        // right: 0.25,
        bottom: 0.15,
        // left: 0.25
    }
    config.config.scaleContent = "false"

    qz.print(config,printData1).then(function () {
        // alert("Sent data to printer");
        let config2 = getUpdatedConfig()
        config2.printer = config.printer
        return qz.print(config2,printData2)
    }).then(function() {
        qzDonePrinting();
    }).catch(function (e) {
        console.error(e);
        qzDonePrintingCancel();
        // displayError
    });
}

/**
 * le agregue varias cosas para la configuracion de la imagen ,,
 * pero luego intento poner este cosigo y me falla
 * 
 *  (Translation)
 *  I added several things to the image configuration
 *  but then I try to put this thing and it fails me
 * 
 */

function printTextPlanpos(ticket) {
    var config = getUpdatedConfig;
    ticket = ticket.replace ("corta", '\x1D' + '\x56' + '\x00');

    var printData1 = [{
            type:'pixel' , format: 'image', flavor:'file', data:'https://placekitten.com/200/230'
    }];

    var printData2 = [{
        type:'raw' , format: 'plain', data:ticket, options: {language: "ESCPOS"}
    }];
    // qz.print(config, [printData1, printData2]).catch(displayError);
    qz.print(config, [printData1,printData2]).then(function () {

        // alert("Sent data to printer");
        qzDonePrinting();
    }).catch(function (e) {
        qzDonePrintingCancel();
        // displayError
    });
}

/**
 * y me arroja este error
 *
 * caught TypeError: config.getPrinter is not a function
 * ( lo estoy ejecutando en la consola de chrome , tengo entendido que no me falla por una funcion del qzmod , pero no se a que moverle )::)
 *
 * (Translation)
 *  and it throws me this error
 *
 *  caught TypeError: config.getPrinter is not a function
 *  (I'm running it in the chrome console, I understand that it doesn't fail me because of a qzmod function, but I don't know what to move it to)::)
 */
```

**Comment by tresf** [comment]
Hi,

Please see the first line of our ESC/POS example here:
https://qz.io/docs/raw#escpos

```js
[{ type: 'raw', format: 'image', flavor: 'file', data: 'https://placekitten.com/400/450', options: { language: "ESCPOS", dotDensity: 'double' } }],
   ```

**Comment by yaredga** [comment]
hello tresf I was checking the line but it does not print it sends me an error



function printTextPlanpos(imagen,ticket) {
var config = getUpdatedConfig();
 ticket = ticket.replace("_corta_", '\x1D' + '\x56'  + '\x00');



var printData1 = [
    { type: 'raw', format: 'image', flavor: 'file', data: 'https://placekitten.com/400/450', options: { language: "ESCPOS", dotDensity: 'double' }},
    { type: 'raw', format: 'plain',data:ticket, options: {language: "ESCPOS"}}
    ];
    


    


 qz.print(config, printData1).then(function () {
       
        qzDonePrinting();
    }).catch(function (e) {
        console.log(e);
        qzDonePrintingCancel();
        // displayError
    });
}

**Comment by tresf** [comment]
Can you try `dotDensity: 0`, `1`, `32`, `33` and report your findings?  Possibly related: #10

**Comment by tresf** [comment]
... also, please share your error.

**Comment by tresf** [comment]
> ```js
> data = [{
>    type: 'raw',
>    format: 'plain',
>    data: ticket
> }];
> ```

Hmm... can you try:

```js
data = [{
     type: 'raw',
     format: 'command',
     flavor: 'plain',
     data: ticket
}];
```

**Comment by yaredga** [comment]
It worked for me thank you very much friend , But one question, is there a possibility to give size to an image,
 type: 'raw',
    format: 'image',
    flavor: 'file',
    data: 'https://www.sangabriel.mx/images/logo-sangabriel-2.png',
    options: {
        language: "ESCPOS",}
already poor with
dotDensity but it still comes out too big

**Comment by tresf** [comment]
> It worked for me thank you very much friend

Great, thanks for the update.

> But one question, is there a possibility to give size to an image

No, sorry, currently, the raw image support does not allow resizing.
