### ISSUE TITLE
Installation failed during preinstall step

### ISSUE THREAD

**Issue by mlscherer** [qzind/tray#1127]
I've had some similar situations, where I tried to install qz and had failures. In one case I even opened an Issue, but I was toldthat it seemed to be an error because Windows was 32 bits. It wasnt, but I was unable to collect extra infos.

I just had a similar failure, but in this case I was able to gather more info.

Windows is not 32-bit and this computer had version 2.2.1 installed before. I uninstalled it, tried to install version 2.2.2 and got this error...

After that I installed version 2.2.1 again and it worked. I tried to install version 2.2.2 over it, without uninstalling the previous one and it also gave the same error.

Attached is an image with the entire error log

Any ideas why this error happened?

Thanks

![3](https://user-images.githubusercontent.com/41930365/236554544-15534dc7-07ff-43c6-9968-a3fe4cf69a86.png)
![4](https://user-images.githubusercontent.com/41930365/236554548-8b297b91-5a06-478f-af33-febd6f1f58fb.png)
![2](https://user-images.githubusercontent.com/41930365/236554540-d5f0a52e-5b13-4002-b064-a836f1841344.png)![1](https://user-images.githubusercontent.com/41930365/236554530-670a2b21-57ec-43cd-921e-8e7334deb21d.png)

**Comment by tresf** [comment]
Weird, it's using the wrong Java.  Can you screenshot the Windows information as well as the exact installer name?

**Comment by tresf** [comment]
A temporary workaround is probably to uninstall Java 8, but this still shouldn't happen.

**Comment by mlscherer** [comment]
What exactly Windows info you need? I will try to get this infos for you...

**Comment by tresf** [comment]
The "about this computer" would be helpful.

Our installer is supposed to search for its own Java version first.  I'm not sure how Java 8 is being picked up, so I suspect something we haven't accounted for.

**Comment by mlscherer** [comment]
And I just connected at this computer again... I tried to uninstall the installed Java 8 (update 241). After that, tried to install qz, version 2.2.2. During the install, it asked to download the Java with that popup. I tried to download, install, but it appears to not recognize, so it keeps asking to download Java and stays into that loop.

Here are the info you asked for...
<img width="549" alt="infos" src="https://user-images.githubusercontent.com/41930365/236588066-5a6be816-3719-4b12-952a-797da50a04e0.png">

**Comment by tresf** [comment]
How about the installer?  Can you share the name of the installer that you are using?

**Comment by tresf** [comment]
Furthermore if you'd be so kind as to email me, my address is tres@qz.io, I'm very interested in debugging this.

**Comment by mlscherer** [comment]
Hi @tresf . I just sent you the email you asked.

And I just tested again at this same computer. I tried to install the original qz .exe from the homepage (2.2.2+1) and it worked... So its probably something related to our compilation.

**Comment by tresf** [comment]
> So its probably something related to our compilation.

Please share your compilation steps so that we can determine if this is a defect or not.

**Comment by tresf** [comment]
Closing due to lack of response.  If you can provide the compilation steps, I'd be happy to check our installer logic for bugs.
