### ISSUE TITLE
Multi-page PDF only prints first page, only on Zebra, only on Windows

### ISSUE THREAD

**Issue by lite1979** [qzind/tray#1128]
Using the same source PDF, the issue is also evident using PDFBox (tested both 2.0.27 and 3.0.x).

To further complicate things, when printing to another printer, such as a laser printer or a virtual printer, not only do both page print, but the _second page appears to be rasterized_

The PDF in question was created using Qt 4.8.7 via wkhtmltopdf 0.12.6 (which is unfortunately archived as of January of this year).

TODO: Open issue with PDFBox once a publicly shareable PDF is available to reproduce the problem.

**Comment by lite1979** [comment]
[sample_file-1.pdf](https://github.com/qzind/tray/files/11432463/sample_file-1.pdf)

**Comment by tresf** [comment]
Emailed PDFBOX user's list.  https://lists.apache.org/list.html?users@pdfbox.apache.org (please manually update this link once it shows in the archive)

**Comment by tresf** [comment]
> To further complicate things, when printing to another printer, such as a laser printer or a virtual printer, not only do both page print, but the second page appears to be rasterized

@lite1979 can you retest this build with  "☑️  Ignore Transparency:" checked?

https://github.com/tresf/tray/releases/download/v2.2.3/qz-tray-2.2.2-PDFFONT5-x86_64.exe

**Comment by lite1979** [comment]
> can you retest this build with "ballot_box_with_check Ignore Transparency:" checked?

It works! Both pages printed just fine to the Zebra GK420d printer, and I can also confirm that the zoomed in results when printing to a virtual printer indicate that no rasterization is happening on the second page of our problematic PDF. :)

**Comment by tresf** [comment]
Thanks!  This will be resolved once #1108 is merged.
