### ISSUE TITLE
Barcode from PDF becomes altered when printed using QZ-Tray

### ISSUE THREAD

**Issue by lite1979** [qzind/tray#1129]
A recent inquiry stated that the printed barcode from QZ-Tray could not be scanned, while it was perfectly scan-able using the original PDF on a computer monitor. 

The barcode that is printed via QZ-Tray looks nothing like the original, explaining why it's not scannable, but printing with a native application such as Adobe Acrobat Viewer yields a scan-able barcode that looks exactly like the orignal.

The original PDF was created with pdftk-java

Waiting for the potential client to either provide a PDF without sensitive data to reproduce, or give permission to use the current PDF.

**Comment by lite1979** [comment]
[234457694-edit.pdf](https://github.com/qzind/tray/files/11454337/234457694-edit.pdf)

**Comment by lite1979** [comment]
[QZ_Tray_PDF_Print-job_2741.pdf](https://github.com/qzind/tray/files/11454349/QZ_Tray_PDF_Print-job_2741.pdf)

**Comment by tresf** [comment]
Upstream bug report filed: https://issues.apache.org/jira/browse/PDFBOX-5601

**Comment by tresf** [comment]
Initial upstream patch (WARNING: this produces blank images on MacOS)

[pdfbox-app-2.0.29-SNAPSHOT.jar.zip](https://github.com/qzind/tray/files/11483976/pdfbox-app-2.0.29-SNAPSHOT.jar.zip)

**Comment by tresf** [comment]
This fix will be available starting with QZ Tray 2.2.3.

Thanks to PDFBOX, a workaround for this issue has been created.  At time of writing this, the issue is still open, so there's a chance that the code will change slightly prior to the release of QZ Tray 2.2.3. https://issues.apache.org/jira/browse/PDFBOX-5601
