### ISSUE TITLE
Find Printers

### ISSUE THREAD

**Issue by yaredga** [qzind/tray#1134]
Hello good morning. I wanted to see if you could help me find printers. Currently I have this code but it brings me all this
![image](https://github.com/qzind/tray/assets/131406025/3793cb7b-d536-4536-bc8c-f7c2bc3134f5)
(I want it to bring me only the printers that I have connected with usb or so)

_**Codigo**_
qz.printers.find().then(function(data) {
   console.log()
   $("#dummy").html("")
   data.forEach(printer => {
      option = `<option> ${printer} </option>` 
      $("#dummy").append(option)
   })
  }).catch(function(e) { console.error(e); });

**Comment by tresf** [comment]
Sure:

```js
qz.printers.details().then(details => {
    var usbOnly = details.filter(detail => detail.connection.toLowerCase().startsWith("usb"));
    console.log(usbOnly);
}).catch(e => { console.error(e) });
```

**Comment by yaredga** [comment]
**ERROR**

Uncaught TypeError: qz.printers.details is not a function




I understand that I get this error because I don't have the 2.1 library onwards, I am using 2.0 in a project and it is very difficult for me to change the library since the project is very advanced

**Comment by tresf** [comment]
2.1 is needed

**Comment by yaredga** [comment]
I made a few small changes and I'm already using version 2.2.2 and I get this error TypeError: Cannot read properties of undefined (reading 'toLowerCase')

Previously, when I was not using 2.2.2, it did not send me the qz alert to connect, and now it does, but I got the error above, what could I do?

**Comment by yaredga** [comment]
How to keep 2 or more printers connected at the same time with qz ?

**Comment by tresf** [comment]
> How to keep 2 or more printers connected at the same time with qz ?

Will you please open a second ticket for this?

**Comment by tresf** [comment]
> I made a few small changes and I'm already using version 2.2.2 and I get this error `TypeError: Cannot read properties of undefined (reading 'toLowerCase')`


Sorry, I have a feeling that this is an upgrade bug.
- Did you also upgrade the `qz-tray.js` file to 2.2.2?
- Can you share your qz-tray.js version and a snippet of code/logs?

**Comment by yaredga** [comment]
> > ¿Cómo mantener 2 o más impresoras conectadas al mismo tiempo con qz?
> 
> ¿Puedes abrir un segundo ticket para esto?
 Currently I have 2 processes to print on 2 different printers, one is with ESC/POS language and the other with ZPL
 **ESC/POS**

function printTextPlanpos(serverPath) {
    var config = getUpdatedConfig();
    serverPath = serverPath.replace("_corta_", '\x1D' + '\x56' + '\x00');
    var textoPequeño = ('\x1B' + '\x4D' + '\x31');
//    console.log(serverPath);
//    var printData = [{
//            type: 'raw', format: 'plain', data: serverPath, options: {language: "ESCPOS"}
//        }
//    ];
    
    var data = [{
    type: 'raw',
    format: 'image',
    flavor: 'file',
    data: 'https://www.sangabriel.mx/images/home/logo-sangabriel-2.png',
    options: {
        language: "ESCPOS"
//        dotDensity: '32'
//pageHeight: 2 
    }
}, {
    type: 'raw',
    format: 'command',
    flavor: 'plain',
    data:  textoPequeño + serverPath, options: {language: "ESCPOS"}
}];

    // qz.print(config, printData).catch(displayError);
    qz.print(config, data).then(function () {
        // alert("Sent data to printer");
        qzDonePrinting();
    }).catch(function (e) {
        console.log(e);
        qzDonePrintingCancel();
        // displayError
    });
}




**ZPL**

function zebraImpresion(filename) {
    var config = getUpdatedConfig();
    var data1 = [
        "CT~~CD,~CC^~CT~",
        "^XA~TA000~JSN^LT0^MNW^MTT^PON^PMN^LH0,0^JMA^PR4,4~SD10^JUS^LRN^CI0^XZ",
        "^XA",
        "^MMT",
        "^PW812",
        "^LL0812",
        "^LS0",
        "^FT794,307^A0I,25,24^FH\^FDL0REBANAR A 3/4 , EMPLAYADO^FS",
        "^FT796,174^A0I,25,24^FH\^FDL4345678901234567890123456789012345678901234567890123456789012345^FS", //cada texto debe iniciar con "FD/FDL"
        "^FT795,208^A0I,25,24^FH\^FDL3345678901234567890123456789012345678901234567890123456789012345^FS",
        "^FT794,242^A0I,25,24^FH\^FDL2345678901234567890123456789012345678901234567890123456789012345^FS",
        "^FT794,374^A0I,25,24^FH\^FDL3345678901234567890123456789012345678901234567890123456789012345^FS",
        "^FT795,406^A0I,25,24^FH\^FDL2345678901234567890123456789012345678901234567890123456789012345^FS",
        "^FT794,440^A0I,25,24^FH\^FDL1345678901234567890123456789012345678901234567890123456789012345^FS",
        "^FT793,274^A0I,25,24^FH\^FDL1345678901234567890123456789012345678901234567890123456789012345^FS",
        "^FT486,764^A0I,28,28^FH\^FD^FS", //aqui va el nombre o el numero que le puedes  asignar al codigo de barras
        "^FT792,341^A0I,28,28^FH\^FDINDICACIONES:^FS",
        "^FT794,513^A0I,28,28^FH\^FDPROCESOS:^FS",
        "^FT142,561^A0I,51,50^FH\^FDKG^FS",
        //"",
        `^FT340,558^A0I,56,55^FH\^FD${filename.listaDetalles[0].cantA}^FS`, //Le concatene de ejemplo la cantidad de productos que se estan enviando , en teoria el original seria en kg (pero esta es una prueba )
        "^FT794,474^A0I,25,24^FH\^FDL0REBANADO, EMPLAYADO^FS",
        `^FT215,18^A0I,17,16^FH\^FD${filename.fecha}^FS`,
        `^FT796,18^A0I,17,16^FH\^FD${filename.nombreTienda}^FS`,
        `^FT797,637^A0I,28,28^FH\^FD${filename.listaDetalles[0].producto}^FS`,
        "^FT482,720^A0I,28,28^FH\^FDPIEZA 1 DE 3^FS",
        `^FT797,677^A0I,28,28^FH\^FD${filename.vendedor} ^FS`,
        "^BY3,3,82^FT566,73^BCI,,Y,N",
        //"",
        `^FD>;${filename.folio}^FS`,
        "^FO18,370^GB774,0,1^FS",
        "^FO23,543^GB774,0,1^FS",
        "^BY3,3,82^FT796,711^BCI,,N,N",
        //"^FD>;000000000234^FS",//aqui es donde va la variable para poner el codigo de barras 
        `^FD>;${filename.listaDetalles[0].barra}^FS`,
        "^FO21,38^GB774,0,1^FS",
        //{type:"raw", format:"plain", data:filename},
        "^PQ1,0,1,Y^XZ"

    ];
    qz.print(config, data1).then(function () {
        //validar lista detalle
        //si contiene, llamar a esta funcion
        filename.listaDetalles.shift();
        if (filename.listaDetalles.length > 0) {
            zebraImpresion(filename);
        } else {
            qzDonePrinting();
        }

    }).catch(function (e) {
//        console.log(e);
        qzDonePrintingCancel();
        // displayError
    });
}

**Comment by tresf** [comment]
> I already managed to make a button that brings me the printers I needed, only when I connect one it is connected correctly, but when I want to connect the other one, the first one I connect is disconnected and only one remains active, do you explain?

Please open a separate bug report for this problem: https://github.com/qzind/tray/issues/new

**Comment by tresf** [comment]
> only when I connect one it is connected correctly, but when I want to connect the other one, the first one I connect is disconnected and only one remains active, do you explain?

Can you please try:

```js
var escpos = [{
    type: 'raw',
    format: 'image',
    flavor: 'file',
    data: 'https://www.sangabriel.mx/images/home/logo-sangabriel-2.png',
    options: {
        language: "ESCPOS"
    }
}, {
    type: 'raw',
    format: 'command',
    flavor: 'plain',
    data:  textoPequeño + serverPath, options: {language: "ESCPOS"}
}];

var zpl = [
    "^XA\n" +
    "^CFA,60\n" +
    "^FO50,100^FDZPL CONTENT^FS\n" +
    "^XZ"
];

var printer1 = qz.configs.create("TM");
var printer2 = qz.configs.create("ZDesigner");

qz.print([printer1, printer2], [escpos, zpl]);
```

If instead you need to search for the printer first, you may be happy using two drop-downs.  You will have to author this code yourself.

**Comment by tresf** [comment]
Closing due to lack of response.
