### ISSUE TITLE
authcert.override it's bypassed on the qz-tray.properties

### ISSUE THREAD

**Issue by dariusve** [qzind/tray#114]
I put the:
`authcert.override=C:\\Program files\\QZ Tray\\auth\\override.crt`
on the qz-tray.properties and it's not loaded, but when I run the qz-tray manually:
`java -Xms512M -DtrustedRootCert=override.crt -jar qz-tray.jar`
the digital certificate it's loaded with no problem.

**Comment by tresf** [comment]
@dariusve if you're using 2.0.1, this is by design.  This feature won't be available from our downloads page until 2.0.2 is released.  Per https://github.com/qzind/tray/issues/105#issuecomment-247741364.

If you've compiled from source and still having this problem, please reopen.

**Comment by kerbymart** [comment]
@tresf when will the version 2.0.2 be available for build or download?

**Comment by tresf** [comment]
> @tresf when will the version 2.0.2 be available for build or download?

Probably a month.  We do full regression testing on each build.  Premium clients needing expedited features like this one receive RC builds directly from support leading up to stable.
