### ISSUE TITLE
How to remember this decision? 

### ISSUE THREAD

**Issue by yhyunKim** [qzind/tray#1144]
I am using this product for the first time
I wrote the code to proceed as follows when connecting to the printer.
But still, when I check '_remember this decision_', the allow button is disabled.
How can i click allow button with remeber this decision?
Additionally, I have already purchased the Premium Support product. :)
```
    qz.security.setCertificatePromise(function (resolve, reject) {
      fetch("./demo/digital-certificate.txt", {
        cache: "no-store",
        headers: { "Content-Type": "text/plain" },
      }).then(function (data) {
        console.log(data);
        data.ok ? resolve(data.text()) : reject(data.text());
      });
    });

    qz.security.setSignatureAlgorithm("SHA512"); // Since 2.1
    qz.security.setSignaturePromise(function (toSign) {
      return function (resolve, reject) {
        fetch("./demo/assets/signing/sign-message.php?request=" + toSign, {
          cache: "no-store",
          headers: { "Content-Type": "text/plain" },
        }).then(function (data) {
          console.log(data);
          data.ok ? resolve(data.text()) : reject(data.text());
        });
      };
    });`

**Comment by yhyunKim** [comment]
<img width="660" alt="스크린샷 2023-06-15 오후 3 48 31" src="https://github.com/qzind/tray/assets/130429827/b6575831-4d8d-470c-9217-b0364429e9d3">

log is as follows.
I modified the php file according to the guidelines, and it is the same situation even if I work using the js file. 
For example, the php file was written as follows:

`$KEY = '../../demo/private-key.pem'`

**Comment by tresf** [comment]
The logs show that the signature is blank.  I would check that PHP file.

**Comment by tresf** [comment]
Furthermore, we offer interactive help for Premium Support customers if you decide to go down that route (support@qz.io)

**Comment by yhyunKim** [comment]
For php files

```
<?php

$KEY = '../../demo/private-key.pem'
//$PASS = 'S3cur3P@ssw0rd';

$req = $_GET['request'];
$privateKey = openssl_get_privatekey(file_get_contents($KEY) /*, $PASS */);

$signature = null;
openssl_sign($req, $signature, $privateKey, "sha512"); // Use "sha1" for QZ Tray 2.0 and older

if ($signature) {
	header("Content-type: text/plain");
	echo base64_encode($signature);
	exit(0);
}

echo '<h1>Error signing message</h1>';
http_response_code(500);
exit(1);

?>

```

For JS files 

```
var privateKey =
  "-----BEGIN PRIVATE KEY-----\n" +
  ~~~~~~~~~~~~
  "-----END PRIVATE KEY-----";

qz.security.setSignatureAlgorithm("SHA512"); // Since 2.1
qz.security.setSignaturePromise(function (toSign) {
  return function (resolve, reject) {
    try {
      var pk = KEYUTIL.getKey(privateKey);
      var sig = new KJUR.crypto.Signature({ alg: "SHA512withRSA" }); // Use "SHA1withRSA" for QZ Tray 2.0 and older
      sig.init(pk);
      sig.updateString(toSign);
      var hex = sig.sign();
      console.log("DEBUG: \n\n" + stob64(hextorstr(hex)));
      resolve(stob64(hextorstr(hex)));
    } catch (err) {
      console.error(err);
      reject(err);
    }
  };
});
```
written as above

**Comment by tresf** [comment]
It looks OK at a glance.  Is there a chance you have a lingering `qz.security.setSignaturePromise` somewhere else in your code?

Note, since you're a premium subscriber, we'd be happy to help interactively with this problem if you'd like to email support@qz.io.

**Comment by yhyunKim** [comment]
```
import React, { useEffect } from "react";
import qz from "../js/qz-tray";

export const SilentPrint = () => {
  useEffect(() => {
    qz.websocket
      .connect()
      .then(function () {
        alert("Connected!");
        return qz.printers.find("musinsa");
      })
      .then((found) => {
        alert(found);
        var config = qz.configs.create(found);
        var data = [
          {
            type: "pixel",
            format: "html",
            flavor: "plain",
            data: "<h1>Hello World!</h1>",
          },
        ];
        qz.print(config, data);
      });

    var privateKey =
      "~~~~";

    qz.security.setCertificatePromise(function (resolve, reject) {
      resolve(
        "-----~~~"
      );
    });

    qz.security.setSignatureAlgorithm("SHA512"); 
    qz.security.setSignaturePromise(function (toSign) {
      console.log(toSign);
      return function (resolve, reject) {
        console.log(resolve, reject);
        try {
          var pk = KEYUTIL.getKey(privateKey);
          var sig = new KJUR.crypto.Signature({ alg: "SHA1withRSA" });
          sig.init(pk);
          sig.updateString(toSign);
          var hex = sig.sign();
          console.log("DEBUG: \n\n" + stob64(hextorstr(hex)));
          resolve(stob64(hextorstr(hex)));
        } catch (err) {
          console.error(err);
          reject(err);
        }
      };
    });

  }, []);

  return <div>SilentPrint</div>;
};

```
When the code is written as follows, remember this decision is checked and the allow button is not activated.
What part needs to be modified to activate the allow button?

**Comment by tresf** [comment]
Hi,

You need to call `qz.security.*` BEFORE `qz.websocket.connect(...)`.

**Comment by tresf** [comment]
Hi, @yhyunKim checking in on the above. 🍻

**Comment by yhyunKim** [comment]
Thanks, it looks like the above problem has been solved😄
But another problem arose.
I am trying to print a label template in html file using zpl label printer.
If you directly input the data converted to zpl, the output is normal, but if you input and load a separate Html file path, it does not print.
I'm still looking for a way What should I do in such a case?

**Comment by tresf** [comment]
> If you directly input the data converted to zpl, the output is normal, but if you input and load a separate Html file path, it does not print.

I would suspect that Java is having a problem accessing the page.  Does it require a login session or proxy or something special?

**Comment by yhyunKim** [comment]
Thank you for answer ;)
```
 var data = [
      "^XA\n",
      {
        type: "raw",
        format: "html",
        flavor: "file",
        data: "./template/label.html",
        options: { language: "ZPL" }, //, "pageWidth":..., "pageHeight":... },
      },
      "^XZ\n",
    ];
```
No login session or proxy is required.
When written as follows, the content of the html file is output in an empty state without inputting anything. Do I need to do anything else to output the html file to zpl?

**Comment by tresf** [comment]
We've recently added support for `Uint8Array`, which can allow you to fetch this page using the browser (rather than trusting Java to do it for you).

Here's a code snippet you may adapt to work with your HTML example:

https://github.com/qzind/tray/pull/1098#issuecomment-1624016656

Note, for this to work properly, you will need to be on the beta qz-tray.js:

https://github.com/qzind/tray/blob/master/js/qz-tray.js

**Comment by tresf** [comment]
@yhyunKim Hi, checking in on the above workaround.

**Comment by tresf** [comment]
> @yhyunKim Hi, checking in on the above workaround.

I just realized this is a separate issue, so we should probably track is as such.  Do you mind opening a new issue if the problem persists?
