### ISSUE TITLE
Raw printing (ZPL) not abiding print options

### ISSUE THREAD

**Issue by xewl** [qzind/tray#115]
I'm having another issue with the current version of QZ Tray (2.0.1)

HTML, Images and PDF seem to listen fine to my request with custom print-options/configs.
However, when I do a RAW print with ZPL-code, it seems to ignore at least these 2 options, entirely:
- `orientation`
- `rotation`

Whatever I change about these, end up in the exact same print-job.

- I can not verify options like `color`.
- `copies` however works fine.

When I send in my request, the debug-log (`qz.api.showDebug(true)`) shows me the correct settings entirely.

I'm not sure how to force it to take these settings correctly, but I'd think this is the server applet not overwriting driver options at this point. Assistance would be great!

**Comment by tresf** [comment]
@xewl thanks for submitting a bug on this.

Raw printing bypasses the driver settings.  This is true for all raw printing and is not specific to Zebra printers.

We haven't and have no plans to write rotation and orientation for each raw language.  Instead, reference [the programming manuals and adjust your raw commands accordingly](https://km.zebra.com/kb/index?page=content&id=SO8075).

If you feel our documentation doesn't explain this properly, please help use improve our documentation by making recommendations for how we can make this more clear.
