### ISSUE TITLE
Unable to recognize HPRT SL42 label printer in qz tray

### ISSUE THREAD

**Issue by hitz-crafty** [qzind/tray#1153]
Need help in setting up QZ tray in my system. Unable to recognize HPRT SL42 label printer in QZ tray.
Unable to follow the QZ tray help links as they are too technical for me.

**Comment by tresf** [comment]
If you visit https://demo.qz.io and list all printers, does it show up?

**Comment by hitz-crafty** [comment]
Hi,

Yes the printer shows up in the list. However, there is an error always
saying - unable to recognize the printer.

**Comment by tresf** [comment]
> unable to recognize the printer.

I'm not familiar with this message.  Can you provide some more context... 

1. Logs from QZ
   * QZ Menu
   * Advanced
   * Diagnostics
   * Zip Logs to Desktop
2. Any browser errors (Inspect element, console)

**Comment by tresf** [comment]
> Unable to follow the QZ tray help links as they are too technical for me.

Sorry, I missed this part.  If you're not a technical user, please reach out to the website that asked you to install QZ Tray.

**Comment by tresf** [comment]
Closing due to lack of response.
