### ISSUE TITLE
Printers disconnecting between prints

### ISSUE THREAD

**Issue by mlscherer** [qzind/tray#1161]
Hello, we are experiencing a situation with a client, where some impressions are not being carried out (when sent with a small time interval)

Before sending each print, to ensure that the printer exists, we make a `qz.printers.find` call and apparently, the return indicates that the printer is disconnected.

We have a `startListening` running on the printers, and with that, we noticed that right after disconnecting, it is connected again.

The problem happens when there are several prints in sequence and when trying to print in that short time that it shows as "disconnected", it does not print...

We would like to understand if it is normal for the printer to change status right after printing, or if this could be caused by something specific. And if this is normal, do you have any recommendations on how to avoid this problem?

Thanks!

**Comment by tresf** [comment]
What OS?  Do you mind sending the logs to `support@qz.io` with subject of "Issue #1161" ?

**Comment by tresf** [comment]
We took this conversation offline as a premium support plan.  We'll continue any support issues there.
