### ISSUE TITLE
Allow certificate rejection to prevent further calls

### ISSUE THREAD

**Issue by tresf** [qzind/tray#1166]
Currently the default behavior when a certificate cannot be retrieved is to send a `null` certificate.  This is good default behavior as it allows printing to succeed in cases where a certificate is unavailable or misconfigured.

However, this may not always be desired, there may be scenarios where a customer would rather queue up this print request until the certificate promise succeeds.   In this case, we should allow a configuration option to `reject()` WITHOUT calling `sendCert(null)`.

https://github.com/qzind/tray/blob/95db68d7e9b883380d4a949de780dd32c31a239f/js/qz-tray.js#L364-L367

**Comment by tresf** [comment]
@akberenz initial implementation in #1172.  It's not working though, I can't seem to catch the rejection, but I may be using it wrong.

**Comment by akberenz** [comment]
the code at that point is not in a promise but rather has it passed in, so a slight change to what gets the reject called on it and its looking fine
