### ISSUE TITLE
Add ability to clear a printer's queue

### ISSUE THREAD

**Issue by tresf** [qzind/tray#1185]
Request to add the ability to clear a print queue.  It should be assumed that a person can only clear their own jobs.

> We [...] had an issue related to the OS spooler caused by sending a bad ESC command to Star printers. Despite immediately correcting the change, we had no way to clear the queue and had to manually clear it on every device which had a huge impact on customers and our support team. Our primary objective is to avoid this havoc in the future.

**Windows:**

* Perhaps using `JOB_CONTROL_DELETE` on [`SetJob`](https://learn.microsoft.com/en-us/windows/win32/printdocs/setjob).

**MacOS/Linux:**

* TBD... Perhaps an API that calls [`CANCEL`](https://www.cups.org/doc/man-cancel.html) on the print job?

**Comment by Vzor-** [comment]
IPP has Cancel-Job operation that will probably work. There is also a Purge-Jobs operation, but that also clears out the completed jobs, not just pending.

**Comment by Vzor-** [comment]
I was able to implement this for cups https://github.com/Vzor-/tray/tree/cancel-jobs. Implementing it for windows will likely be a little bit harder. We need the [setJob](https://learn.microsoft.com/en-us/windows/win32/printdocs/setjob) method, but it is not part of JNA's Winspooler class, so we will likely have to add it ourself.

**Comment by Vzor-** [comment]
>We need the [setJob](https://learn.microsoft.com/en-us/windows/win32/printdocs/setjob) method, but it is not part of JNA's Winspooler class, so we will likely have to add it ourself.

This is now working, also it will be included in the next version of JNA's Winspooler https://github.com/java-native-access/jna/pull/1556
