### ISSUE TITLE
PDFBox Assumes Orientation

### ISSUE THREAD

**Issue by tresf** [qzind/tray#12]
Quoting @bberenz:

> It looks like PDFBox is internally forcing a swap of dimensions when width > height to avoid the exception thrown by the `MediaSize` class when this condition is met. 
We manage to skirt around this issue with image printing by using the `MediaPrintableArea` class, but as we have no control over the pdf printing logic I'm not sure there is anything we can do here. 
The XPS printer is a bit .. loose anyways. Have you seen any of the results when using an actual label printer with PDFs?

Quoting @tresf
> @bberenz using `PDFCreator`, this auto-rotates as documented.  We have some options... 
 * Echo a warning and ignore this
 * Try to tackle this via PDFBOX-recommended method

> To [quote the relevant portions from the developer](https://issues.apache.org/jira/browse/PDFBOX-2922)... 

> > If you want to customise the orientation, then you don't want to use `PDFPageable`. The purpose of a `Pageable` interface is to let the source document determine its own layout. If you want to do something custom, then skip the `Pageable` and use a `Printable` directly.

> I do much prefer the standard behavior, but how much work is the `Printable` portions he speaks of?  Can we use `Printable` if orientation is provided and fallback onto `Pageable` if not?
 
***

**Original bug report:**

Placeholder for testing, configuration and output for [`99010`](http://www.amazon.co.uk/Sieko-99010-Compatible-Address-Label/dp/B0057NLF90) (1.1in x 3.3in, 28mm x 89mm) Dymo label format.

Related: #177

Sample label: (landscape)
[3.3in x 1.1in.pdf](https://github.com/qzind/qz-print/files/157116/3.3in.x.1.1in.pdf)
![image](https://cloud.githubusercontent.com/assets/6345473/13500089/ea433cbc-e12e-11e5-99ad-0bb16fe5fcac.png)

Sample label: (portrait)
[1.1in x 3.3in.pdf](https://github.com/qzind/qz-print/files/157132/1.1in.x.3.3in.pdf)
![image](https://cloud.githubusercontent.com/assets/6345473/13500164/5ac2570c-e12f-11e5-9545-bd60757204b5.png)

Migrated from https://github.com/qzind/qz-print/issues/183

**Comment by bberenz** [comment]
After discussing with @tresf, it looks like the root cause of this problem was PDF printing did not respect orientation, rather than it changing any page sizes. a27a5c63f4f3b93ddef309e5eb5ae8208b7a03a1 forces pdfs to obey the orientation at the data level (rotating the actual document).

**Comment by klabarge** [comment]
Works on Windows, OS X, and Ubuntu :+1:
