### ISSUE TITLE
How to check if printer support ZPL commands 

### ISSUE THREAD

**Issue by akhare22sandeep** [qzind/tray#120]
Hi Team, 
Till now i was using Default printer to find and print ZPL commands. Now i need to find a way if in the list of printers is there any printer which supports ZPL commands ? please advice . 

Regards
Sandeep Akhare

**Comment by tresf** [comment]
ZPL?  No. 
Raw, yes.

Starting with 2.1 per https://github.com/qzind/tray/issues/71#issuecomment-250618777 we have a method for fetching whether or not a printer supports raw printing.  This library is only as good as the [data we provide to it](https://github.com/qzind/sift/blob/master/sift.js#L94), so please help add driver information as it's discovered.
