### ISSUE TITLE
Baud rate of 2400 not supported

### ISSUE THREAD

**Issue by myzonjkee** [qzind/tray#1211]
Cannot open serial port with baud rate 2400 using last version of qzTray (v2.2.3)

<img width="910" alt="Sergej_Brjuchanov__DHL_IT_Services____Microsoft_Teams_classic" src="https://github.com/qzind/tray/assets/18481498/831df3d3-451e-4524-861f-6c13a47d265a">

**Comment by tresf** [comment]
Thanks for the bug report.  Sorry about that, we missed it when working on #476.  Here's a new build with 2400 patched in:
https://github.com/tresf/tray/releases/download/v2.2.4/qz-tray-2.2.3+7-x86_64.exe

This will be fixed permanently when QZ Tray 2.2.4 is released.

**Comment by myzonjkee** [comment]
Thanks for the quick response!
Already tried the new build and now it works as expected. 
Good job 👍
