### ISSUE TITLE
Update signing examples to produce signatures that can be verified with QZ Tray

### ISSUE THREAD

**Issue by mtoo020** [qzind/tray#1224]
Signing using the example code in `sign-message.java` causes an Invalid Signature error when verifying with QZ Tray.

**The cause is:**
`Certificate.isSignatureVerified()` hashes the data: `DigestUtils.sha256Hex(data)`
`sign-message.java` doesn't: `sig.update(data.getBytes())`

So for `sign-message.java`, please can you change:
`sig.update(data.getBytes());`
to
`sig.update(StringUtils.getBytesUtf8(DigestUtils.sha256Hex(data)));`

**Comment by tresf** [comment]
> `Certificate.isSignatureVerified()` hashes the data: `DigestUtils.sha256Hex(data)`
> `sign-message.java` doesn't: `sig.update(data.getBytes())`

Correct, none of our signing examples hash the data because `setSignaturePromise(...)` does this automatically.

https://github.com/qzind/tray/blob/3b1d953d5397e62db66e40264dbc108acf59fefb/js/qz-tray.js#L246-L255

**Comment by tresf** [comment]
Thanks for the update. :)
