### ISSUE TITLE
open cashdrawer using qzind

### ISSUE THREAD

**Issue by hendranata** [qzind/tray#123]
helo

want to ask how to open cashdrawer using this script? any example?

and last time i use jzebra.. and it required java applet and now browser chrome is not supporting java applet..
so does qzind also using java applet?

**Comment by tresf** [comment]
We have the ESC/P "pulse" cash drawer code at the bottom of our ESC/P examples.  Does this work?

https://qz.io/wiki/2.0-Raw-Printing#escp

If not, this command can vary between printers, cash drawers and cables.

**Comment by tresf** [comment]
No response in 10 days; closing.  Please feel free to reply to this bug report with any further questions.
