### ISSUE TITLE
React example

### ISSUE THREAD

**Issue by mkromann** [qzind/tray#1231]
Hi,

I am playing with qz and got printing working but I am having trouble getting my head around signing to allow for silent printing (just trying with dev certificate for now).

I'd like to do it client side, as the use-case is for an internal secured environment. Do you by any chance know or have an example of how to set it up in a React fashion?

Thanks for this library. 🙏

Magnus

**Comment by tresf** [comment]
Not uet.  We do have an angular/ TS example here... Perhaps this has some pointers? https://github.com/qzind/tray/blob/f2761f83177bc6ac1db7a318dd059c7a4b03b2ee/assets/signing/sign-message.ts

**Comment by tomashlavac** [comment]
@mkromann Hi, here is example of signing certificate on client side.

```
export const initQzCerts = () => {
  qz.security.setCertificatePromise((resolve) =>
    fetch("/cert.pem", {
      cache: "no-store",
      headers: { "Content-Type": "text/plain" },
    })
      .then((data) => data.text())
      .then((text) => resolve(text)),
  );
  qz.security.setSignatureAlgorithm("SHA512");
  qz.security.setSignaturePromise(
    (dataToSign) => (resolve, reject) =>
      fetch("/key.pem", {
        cache: "no-store",
        headers: { "Content-Type": "text/plain" },
      })
        .then((wrapped) => wrapped.text())
        .then((data) => {
          const pk = KEYUTIL.getKey(data);
          const sig = new KJUR.crypto.Signature({ alg: "SHA512withRSA" });
          sig.init(pk);
          sig.updateString(dataToSign);
          const hex = sig.sign();
          console.log("DEBUG: \n\n" + stob64(hextorstr(hex)));
          resolve(stob64(hextorstr(hex)));
        })
        .catch((error) => reject(error)),
  );
}; 
```

You can use it in `App.tsx` with `useEffect` like this:

```
useEffect(() => {
    initQzCerts();
}, []);
```

**Comment by tresf** [comment]
Thanks @mkromann!

**Comment by Productivix** [comment]
hi, jsrsasign is not supported in Reactjs now, please @mkromann & @tomashlavac , how did you import the lib to be able to run the code : 
`  const pk = KEYUTIL.getKey(data);
          const sig = new KJUR.crypto.Signature({ alg: "SHA512withRSA" });
          sig.init(pk);
          sig.updateString(dataToSign);`
?
nomally I have to import jsrsasign-all-min.js but I do not how !
thanks  !
regards

**Comment by tresf** [comment]
Per https://github.com/qzind/tray/blob/master/assets/signing/sign-message.ts

```js
import { KJUR, KEYUTIL, stob64, hextorstr } from 'jsrsasign';
```

Just tested it in an online sandbox environment and it works.   Can you be more specific in regards to what you believe is "not supported"?

**Comment by Productivix** [comment]
hi, thanks , I did not know that we can use Angular code in ReactJs ! I will try, it is also JS after all.

"not supported" is because:
- in your examples of JS you use V11 of  jsrsasign-all-min.js 
- please read for the next V11of jsrsasign : https://github.com/kjur/jsrsasign?tab=readme-ov-file#notice-for-comming-1100-release  
- import { KJUR, KEYUTIL, stob64, hextorstr } from 'jsrsasign', so with > npm install jsrsasign jsrsasign-util  if for V10 .

**Comment by tresf** [comment]
> hi, thanks , I did not know that we can use Angular code in ReactJs ! I will try, it is also JS after all.
> 
> "not supported" is because:
> 
> * in your examples of JS you use V11 of  jsrsasign-all-min.js

"Not supported in React" is not the same as "version x is not supported in React". Your statement reads like React broke something.

> * please read for the next V11of jsrsasign : https://github.com/kjur/jsrsasign?tab=readme-ov-file#notice-for-comming-1100-release

I read that the first time you linked me to it and I don't understand which part of it is React breaking.  Is it the WebCrypto stuff?

> * import { KJUR, KEYUTIL, stob64, hextorstr } from 'jsrsasign', so with > npm install jsrsasign jsrsasign-util  if for V10 .

Did you try this before making this statement?

I don't know much about React, we just offer help on here as a courtesy, but it seems to work just fine as I stated earlier when you challenged this.

https://playcode.io/2274692
