### ISSUE TITLE
Troubleshooting Qz Tray Connectivity Issues with Zebra Printer

### ISSUE THREAD

**Issue by Qatarmagazine** [qzind/tray#1232]
I already had Qz Tray installed on my computer, but I needed to reinstall it. However, after the reinstallation, it stopped working correctly. The printer icon no longer turns green; it's now only in gray, and I can't connect to my Zebra printer anymore. For manual printing, the Zebra ZD220 printer works perfectly. The issue seems to be with Qz Tray, as I've tried several versions and none seem to work.
![Capturar](https://github.com/qzind/tray/assets/159482620/ea4b1374-eac0-42dc-85cf-54bf94d281b5)

**Comment by tresf** [comment]
Hi,

Sorry for the trouble you're having.  The green icon is now white, that's a change we made in version 2.1, so any newer versions will be a white or black icon.

Can you test out printing from our demo page?  https://demo.qz.io.  Please let us know if you have any success from our demo page, this will help us offer assistance.

**Comment by Qatarmagazine** [comment]
Thank you very much for the feedback. I'm still trying to connect the printer to Qz Tray. After installation, this message appears attached.
![Capturar](https://github.com/qzind/tray/assets/159482620/95076edb-ca78-49c1-aeed-1f636f2627fd)

**Comment by tresf** [comment]
> Thank you very much for the feedback. I'm still trying to connect the printer to Qz Tray. After installation, this message appears attached. ![Capturar](https://private-user-images.githubusercontent.com/159482620/304807830-95076edb-ca78-49c1-aeed-1f636f2627fd.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MzQ0NTQsIm5iZiI6MTcwNzkzNDE1NCwicGF0aCI6Ii8xNTk0ODI2MjAvMzA0ODA3ODMwLTk1MDc2ZWRiLWNhNzgtNDljMS1hZWVkLTFmNjM2ZjI2MjdmZC5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNFQxODA5MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYjM2OWYyZTQ3YWM5ZjM3ZThmYmZmMWQ1ODIxOGMwYzA4NzZkMzljOWZkNmRkM2IxNjRiZTQzZTY0OWVjMDI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RvrVyZyoFbOVfuFHy5c0usy0aLHU54ubCmTa_If_qkE)

Thanks.  Can you delete `%appdata%\qz` and see if it goes away?

**Comment by Qatarmagazine** [comment]
I found out that the issue was my internet service provider blocking the
connection with Qz Tray. After switching providers, the problem was
resolved. Once again, I appreciate your dedication and attention. Wishing
you much success!

**Comment by tresf** [comment]
Thanks for the update!
