### ISSUE TITLE
cannot verify trust - Invalid Signature

### ISSUE THREAD

**Issue by sartyx** [qzind/tray#1242]
This pops up every time, no matter if I "Remember this decision", 
once you set the check it "Allow" stays grayed out:

![grafik](https://github.com/qzind/tray/assets/12257583/10416b55-7453-4a4b-83a0-ff1ec2f0a346)

Windows 11 Pro

As I understand 2.2.3 doesn't ask for JAVA anymore ?

**Comment by tresf** [comment]
> As I understand 2.2.3 doesn't ask for JAVA anymore ?

Correct, but this is unrelated to your issue.

> This pops up every time

What website?  What shows when you click "View request details"?

**Comment by sartyx** [comment]
![grafik](https://github.com/qzind/tray/assets/12257583/3de86439-6ffb-4e93-932e-46f225510bbd)

website, your demo: https://demo.qz.io/

**Comment by tresf** [comment]
That is correct.  Our demo page does not have a valid signature yet.
