### ISSUE TITLE
How to handle Confirmation Popup Yes/No using power shell command

### ISSUE THREAD

**Issue by veerupvbsails** [qzind/tray#1243]
While downloading and installing the Qz tray using powershell  command "irm pwsh.sh | iex" ,after installation asking the Confirmation popup like Yes/No , how to handle this popup using powershell command

**Comment by tresf** [comment]
@veerupvbsails thanks for the question.  This has been answered in fully detail in your StackOverflow question here: https://stackoverflow.com/a/78096866/3196753.  If you have any questions about this answer, please feel free to ask them in either location. 🍻
