### ISSUE TITLE
Connection Abruptly Closes for openStream API Method

### ISSUE THREAD

**Issue by krahulrd** [qzind/tray#1265]
Hello Team,

We are integrating QZTray with a weight scale on our website. Currently, we are utilizing the `openStream()` method from [hid](https://qz.io/api/qz.hid) to fetch the stream of weight data. As per our application requirements, we need to open and close this connection multiple times. However, when we open a new connection, it sometimes emits the close event with code 1006 and throws the error:

`Error: Connection closed before response received`

<img width="705" alt="Screenshot 2024-05-14 at 12 13 38 AM" src="https://github.com/qzind/tray/assets/115509358/db4d205c-a9b1-4fcc-b015-70c376a2d9ef">

As customers, we do not have control over this close event. We would like to understand why the connection is closing abruptly only when using the `openStream()` method.

Note: The same connection works fine for the `readData()` method.

Thank you.

**Comment by tresf** [comment]
@krahulrd code [`1006`](https://github.com/Luka967/websocket-close-codes) is abnormal and usually the sign of a bug.
* This bug may be our own code or code that we leverage from an HID project.
* To reproduce locally, we'd love to know more about how you can trigger this bug.
* If it's not too much to ask, I'd love to know if this can be reproduced using https://demo.qz.io/#hidContent

What we'd expect as a bare minimum:
* OS
* QZ Tray version
* If it can be reproduced on another machine

What might be insightful:
* Close QZ Tray
* Launch QZ Tray from console and see if there's anything usable that happens with the crash occurs: https://qz.io/docs/faq#console-logs

If it can, great.  If it cannot, it will be harder to track down.

**Comment by krahulrd** [comment]
@tresf Thanks for the quick turnaround!

Yes, this issue is reproducible here: https://demo.qz.io/#hidContent

Steps to reproduce in the above URL:

1. Click on the QZ Tray `Connect` button > `List Devices` > `Use This` > `Claim Device` > `Open Stream`.
2. Reload the page. The Open Stream output is lost, but the QZ Tray connection remains active.
3. Repeat the same process to connect to Open Stream: `List Devices` > `Use Device` > `Claim Device` > `Open Stream`.
Right after the first click of List Devices, QZ Tray crashes and I see the below error:

`(index):2988 Error: Connection closed before response received
    at _qz.websocket.connection.onclose (qz-tray.js:203:72)`

After a few seconds, QZ Tray is coming back.

Our application also faces the same issue whenever a user reloads or closes the browser tab and then tries to connect again. As a backup, we have implemented retry mechanisms, but sometimes this is problematic. If QZ Tray completely crashes, the retry mechanism won't work.

Please let me know if any further information is needed.

Our QZ Tray version is 2.2.2 on a Mac device, but this issue occurs regardless of the OS and QZ Tray version.

**Comment by tresf** [comment]
> Our QZ Tray version is 2.2.2 on a Mac device, but this issue occurs regardless of the OS and QZ Tray version.

Hmm... if it's a HARD crash, I would expect the symptoms to vary between OSs, since they use different libraries.

For Mac, we use one called `hid4java`, but for Windows, we use one called `purejavahidapi`.

If it's a SOFT crash, I would expect it to be rather consistent.  I remember in the past we had some listeners to cleanup, maybe we missed one.  I'll take a look.

**Comment by krahulrd** [comment]
Oh yeah, you're right. Symptoms are varying between OSs. On Windows, I have observed a different issue with the openStream API. When I connected to the scale, the output response was not consistent, as it was always blinking with the hexadecimal data once a weight had been changed, and I was unable to parse the response. Do you think it's a problem with my Windows machine or with the QZTray?

**Comment by tresf** [comment]
Just a status update, we're still actively investigating the crash on the MacOS side.  We'll provide an update here once we're able to narrow it down.

**Comment by tresf** [comment]
Turns out macOS was a resurfacing of #137, a regression caused by #1177.  We should have that patched soon.

**Comment by tresf** [comment]
Patch ready for testing here: https://github.com/tresf/tray/releases/download/v2.2.4/qz-tray-2.2.3+35-arm64.pkg

**Comment by krahulrd** [comment]
Wow! Thanks for the update and great turnaround.

**Comment by tresf** [comment]
> Wow! Thanks for the update and great turnaround.

Did it fix it for you?  We haven't merged #1267 yet.
