### ISSUE TITLE
Can't open 2.2.4

### ISSUE THREAD

**Issue by santcosta** [qzind/tray#1282]
[DEBUG] 2024-07-22T17:41:42,152 @ qz.utils.GtkUtilities:38
        Finding preferred Gtk version...
[DEBUG] 2024-07-22T17:41:42,152 @ qz.utils.GtkUtilities:62
        Found Gtk0
[WARN] 2024-07-22T17:41:42,153 @ qz.utils.GtkUtilities:45
        Not a compatible Gtk version
[WARN] 2024-07-22T17:41:42,153 @ qz.utils.GtkUtilities:29
        An error occurred initializing the Gtk library
[ERROR] 2024-07-22T17:41:42,184 @ qz.App:89
        Could not start tray manager

![imagen](https://github.com/user-attachments/assets/5c6f6c95-9e5d-47ad-b279-d29304444d7c)

Java version
![imagen](https://github.com/user-attachments/assets/052e2c37-c020-496b-a2f6-9df13a67f047)

Ubuntu version
![imagen](https://github.com/user-attachments/assets/631cc9c8-50f5-4be4-848e-e962b67b1d74)

any ideas ?

**Comment by tresf** [comment]
Thanks, we introduced a bug in #1266.  Here's a download link until we get it updated on our Downloads page. 

Intel:
https://github.com/tresf/tray/releases/download/v2.2.4/qz-tray-2.2.4+1-x86_64.run

ARM64:
https://github.com/tresf/tray/releases/download/v2.2.4/qz-tray-2.2.4+1-arm64.run

**Comment by tresf** [comment]
Downloads have been updated.  https://qz.io/download
