### ISSUE TITLE
Wiki: Homebrew Download URL 404

### ISSUE THREAD

**Issue by Vzor-** [qzind/tray#1285]
Under https://github.com/qzind/tray/wiki/install-dependencies#mac

The command `ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"` fails due to a 404.

https://brew.sh/ suggests the command `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`

**Comment by tresf** [comment]
Closed via https://github.com/qzind/tray/wiki/Install-Dependencies/_compare/9f806023ed3c373efa752201d8267351a06f6edc...dbd9390048e69d97788eda42e6d08ea0343fd315.
