### ISSUE TITLE
Cannot verify trust - Invalid Signature -  Support

### ISSUE THREAD

**Issue by PhamChuongBD** [qzind/tray#1287]
# Cannot verify trust - Invalid Signature

### Frontend 

-     qz-tray: "^2.2.4",
-     react: "^18.2.0",

<img width="252" alt="Screenshot 2024-08-15 at 10 03 18" src="https://github.com/user-attachments/assets/11d0f6ee-d04b-4c71-aa96-76aacf168930">

I followed the https://qz.io/docs/signing-examples#javascript instructions

<img width="1141" alt="Screenshot 2024-08-15 at 10 05 42" src="https://github.com/user-attachments/assets/c455b201-641d-4ba1-bd1d-7d6ec9580e35">
but it's not working. 

If you have an example integrated using React.js, please provide me with instructions.

**Comment by tresf** [comment]
What's the value of the signature from the logs?

**Comment by tresf** [comment]
> If you have an example integrated using React.js, please provide me with instructions.

We generally recommend following the vanilla JavaScript tutorial and start from there as a baseline,

**Comment by tresf** [comment]
@PhamChuongBD do you mind sharing your fix?
