### ISSUE TITLE
Print html not correct with print stamp and barcode device (label).

### ISSUE THREAD

**Issue by DiepHoang2711** [qzind/tray#1297]
* **Device:** X-printer 420B, Window, 
* **Driver:** Xprinter_2022.1
* **Description:** I print stamp and barcode by html + pixel. I try to use all qz-tray version (2.2.2, 2.2.3, 2.2.4) but not any version work correctly.
   * **Expected result:** 1 stamp
   * **Actual result:** 4 stamp ( 1 stamp was deviated, 3 stamp blank)

**Note:** Three months ago, with this code my printer was still done correctly
Could you help me? Many thanks!

```js
  const void printStamp(deviceName) {
      let printData = [{
          type: 'pixel',
          format: 'html',
          flavor: 'plain',
          data: `<!DOCTYPE html><html><head></head><div style="font-family: Arial">` +
              '<div>HELLO</div>' +
              `</div></html>`,
      }];
      const config = {
          jobName: 'MyJob',
          scaleContent: false,
          units: 'mm',
      };
  }

  void sendDataToPrinter(deviceName, printData, config);
  }

  async function sendDataToPrinter(printerName, data, dataConfig) {
      var config = qz.configs.create(printerName, dataConfig);
      if (!qz.websocket.isActive()) {
          qz.websocket
              .connect()
              .then(() => {
                  return qz.print(config, data);
              })
              .catch((e) => {
                  console.log(e);
              });
      } else {
          return qz.print(config, data).catch((e) => {
              console.log(e);
          });
      }
  }
```

**Comment by builam66** [comment]
same issue

**Comment by lehunghxt** [comment]
same issue

**Comment by tresf** [comment]
> Note: Three months ago, with this code my printer was still done correctly

@DiepHoang2711 can you please rephrase this sentence?

**Comment by tresf** [comment]
```
const config = ...
```

Since the problem involves improper page sizing, your example MUST include a paper/label/stamp size that you're printing to.  Please update your example to provide the paper size in the config.  As a courtesy,  I have edited your question to make it more readable.

**Comment by tresf** [comment]
> <img width="84" alt="image" src="https://github.com/user-attachments/assets/0fdedf92-24f3-4867-b8ac-0424bdd014eb">

Please do not ask your friends and colleagues to spam our bug tracker. 🍻

**Comment by DiepHoang2711** [comment]
Can you help close the topic!
I have found a solution for myself. I missed the step of configuring the page size for my printer. Sorry for the confusion.
Thanks @tresf support me.
![image](https://github.com/user-attachments/assets/fa3b32ee-eeaf-4695-86a2-26afa879157e)

**Comment by tresf** [comment]
> I missed the step of configuring the page size for my printer.

This would normally be provided by the config object (not the driver) per:

```js
var config = qz.configs.create("Xprinter XP-D4603B", { size: { width: 1.97, height: 1.18 } });
var data = [ ... etc ... ];
qz.print(config, data);
```

> Can you help close the topic!

You may close it at any time using the "Close" button at the bottom of the window, however I would like others that read thsi bug report to have the optimal solution. :)
