### ISSUE TITLE
Intelij Ant Plugin Missing

### ISSUE THREAD

**Issue by Vzor-** [qzind/tray#1298]
As of Intelij 2023.3, the Ant plugin is no longer bundled and needs to be downloaded through the marketplace. https://blog.jetbrains.com/idea/2023/12/intellij-idea-2023-3/#other This should be reflected in the wiki, or maybe we can somehow include it as a project dependency so intelij will automatically download it.

**Comment by Vzor-** [comment]
It should also be noted, this does not cause issues with the launching of QZ. Currently it only breaks the `download-jfx` task

**Comment by tresf** [comment]
Considering how many Maven projects use `antrun` tasks, this is a bit surprising.

**Comment by tresf** [comment]
> Considering how many Maven projects use `antrun` tasks, this is a bit surprising.

The community is surprised by this as well: https://youtrack.jetbrains.com/issue/IDEA-340088/IDEA-2023.3-moves-Ant-support-to-a-plugin-but-that-plugin-is-not-installed-by-an-upgrade

#1299 fixes this, thanks.

If you dismissed this popup and it won't come back, try to repair the IDE, it seems to fix it.

Also, it's mentioned in the PR, but restarting the IDE afterwards is required for the startup job to work.

We can probably remove this once #1216 is merged.
