### ISSUE TITLE
I can not use the Insecure (ws) connection

### ISSUE THREAD

**Issue by asciiblues** [qzind/tray#1307]
I can not use the Insecure (ws) connection for other qz tray site's example [ seller.flipkart.com , mdirect.myntrainfo.com ] i can use in demo.qz.io using enter this { ` qz.websocket.connect({ host: 'localhost', usingSecure: false });`  } , but i enter this in seller.flipkart.com or mdirect.myntrainfo.com to this  | Error [ `Uncaught ReferenceError: qz is not defined at <anonymous>:1:2``]  | error image :- 
![2Capture](https://github.com/user-attachments/assets/e87b4039-cec7-4da8-9b93-bdd4934c3ca5)

**Comment by tresf** [comment]
> I can not use the Insecure (ws) connection for other qz tray site's example

The browser prohibits a secure website from interacting with secure origin.  https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content

Some browsers allow exceptions to this rule which you may set explicitely.

> `Uncaught ReferenceError: qz is not defined`

Our JavaScript must be loaded in the browser to obtain access to the global `qz` object. This is covered in our getting started material https://qz.io/docs/getting-started.  If you are trying to invoke qz from a website you did not author, you would need to ask them.
