### ISSUE TITLE
Self-signed certificate getting "Cannot verify trust - Expired Signature" 

### ISSUE THREAD

**Issue by JonathanCabezas** [qzind/tray#1308]
Hello,

I'm investigating the use of QZTray for a customer, but I cannot set-up a self-signed certificate for local dev.
I'm on version 2.2.4. I generated a demo key pair inside QZTray, and installed it as mentioned in the documentation.

I then call `setCertificatePromise` and `setCertificatePromise` using the `digital-certificate.txt` and `private-key.pem` content.

The call to `connect` doesn't trigger a pop-up anymore, but the calls to `getDefaultPrinter` and `print` cannot verify trust:

![image](https://github.com/user-attachments/assets/e4ede16c-2435-41a8-a96d-85addef671c4)

**Comment by tresf** [comment]
"Expired Signature" usually means something terribly wrong has occured between the date that Java is using and the date that the browser is using.  Have you recently changed the date of this machine?

**Comment by JonathanCabezas** [comment]
Thank you for the quick answer !
I did not realize this could be caused by the way I hacked the date in my browser to have the same day as my data set.
This is indeed terribly wrong, and I should find something less hacky.
I'll try again tomorrow and close the thread if it works.

**Comment by tresf** [comment]
> Thank you for the quick answer ! I did not realize this could be caused by the way I hacked the date in my browser to have the same day as my data set. This is indeed terribly wrong, and I should find something less hacky. I'll try again tomorrow and close the thread if it works.

We do this so that people can't stash a signed and trusted message and payload it later to an unsuspecting PC.

If -- for testing -- you don't care how long it's valid for, you can change this line and recompile:  

https://github.com/qzind/tray/blob/6fa6ce623d235d0ed97973da4dba69cedc7b4a24/src/qz/common/Constants.java#L82

**Comment by tresf** [comment]
Closing as invalid.  Please feel free to continue discussion here even though the thread is closed.

**Comment by JonathanCabezas** [comment]
After setting the clock back to normal, I can confirm I had no issue with qz-tray signing.

Thanks for helping out !
