### ISSUE TITLE
macOS hard crash when releasing HID device

### ISSUE THREAD

**Issue by tresf** [qzind/tray#137]
Steps to reproduce:

**Prerequisites:**

 * Using `garry-rowe/hid4java` (uses `signal11` under the covers)
   * **Edit:** This bug is also reproducible using `purejavahidapi` (uses `jna` under the covers)
   * **Edit:** This bug is also reproducible using `codeminders/javahidapi` (uses `signal11` under the covers)
 * HID USB Scale
 * Mac 

**Steps:**

1. Java 8u11, macOS Sierra
2. Install QZ Tray 2.0.2
3. Load QZ Tray 2.0.2 from terminal (so a crash can be collected)
  ```bash
/Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java -Xms512m -jar /Application/QZ\ Tray.app/qz-tray.jar
```
4. Load sample.html
5. Claim the HID device and start streaming data
  * If you're unsure how to claim the device, try "List devices" and click "Use this" for the HID USB Scale, then "Claim Device"

6. After 20 minutes, release the device and attempt to claim it again.
7. If the crash does not occur, wait 5 minutes and repeat (release the device and attempt to claim it again)

Crash log: [hs_err_pid2398.zip](https://github.com/qzind/tray/files/593728/hs_err_pid2398.zip) | [mirror](https://gist.github.com/tresf/7fa2c32ecead94a8ddb8f0a33dfc427c)

**Comment by tresf** [comment]
Possible downstream bug: https://github.com/signal11/hidapi/issues/205

**Comment by tresf** [comment]
Experimental branch created for testing against an alternate library which does not use the signal11 library:  https://github.com/tresf/tray/tree/hid

**Comment by klabarge** [comment]
This crash continues to happen using @tresf [patch](https://github.com/tresf/tray/commit/4c05cd75a895aecbd79cf0514dd30295c1be349b)

Here's the [JVM crash log](https://gist.github.com/klabarge/25210f395cdce4357a68a0afb6c3b423)

**Console Stacktrace**

```
[INFO] 2016-11-22 19:28:08,018 @ qz.common.TrayManager:?
	Allowed localhost to claim a USB device
2016-11-22 19:28:08.019 java[1082:17292] -[__NSCFTimer member:]: unrecognized selector sent to instance 0x7ff8c008f3a0
2016-11-22 19:28:08.020 java[1082:17292] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFTimer member:]: unrecognized selector sent to instance 0x7ff8c008f3a0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fffaa65852b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fffbed30cad objc_exception_throw + 48
	2   CoreFoundation                      0x00007fffaa6d9d34 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fffaa5cabf5 ___forwarding___ + 1061
	4   CoreFoundation                      0x00007fffaa5ca748 _CF_forwarding_prep_0 + 120
	5   CoreFoundation                      0x00007fffaa59c155 __CFRunLoopFindMode + 197
	6   CoreFoundation                      0x00007fffaa59c929 CFRunLoopAddSource + 201
	7   IOKit                               0x00007fffac53c58f IOHIDDeviceScheduleWithRunLoop + 102
	8   IOKit                               0x00007fffac53eb5a __IOHIDManagerDeviceApplier + 488
	9   IOKit                               0x00007fffac53fb02 __IOHIDManagerDeviceAdded + 339
	10  IOKit                               0x00007fffac53f010 __IOHIDManagerSetDeviceMatching + 255
	11  jna2494885493229802864.tmp          0x000000014ef51134 ffi_call_unix64 + 76
	12  ???                                 0x000070000da80b38 0x0 + 123145531427640
)
libc++abi.dylib: terminating with uncaught exception of type NSException
/Applications/QZ Tray.app/Contents/MacOS/QZ Tray: line 28:  1082 Abort trap: 6           /usr/libexec/java_home -v 1.7+ --exec java -Xms512m -Xdock:name="QZ Tray" -Xdock:icon="$iconpath" -jar "$jarpath"
```

**Comment by tresf** [comment]
Ok, here's the `signal11` upstream report: https://github.com/signal11/hidapi/issues/114

Take special note of https://github.com/signal11/hidapi/issues/114#issuecomment-195676194 which specifically mentions `purejavahidapi` by name.

**Comment by Vzor-** [comment]
I have prepared a test based on some suggestions we received from mrpippy. I have the test ready at https://github.com/vzor-/tray/ on the 2.0 branch but don't have a way to test it.

**Comment by klabarge** [comment]
I've been unable reproduce the crash using @Vzor-'s branch.

Been running for almost 2 hours on macOS Sierra and I can release and claim the HID device with 100% success so far 👍

**Comment by tresf** [comment]
The fix is  in the signal11 `C` library:

* Remove this line: [`hid.c#L1025`](https://github.com/mrpippy/hidapi/blob/75b8627432c5a1aac1b15f9364b6094d5ea98a70/mac/hid.c#L1025)

Once completed, the `signal11` library needs to be recompiled on a suitable Mac build environment and the `hid4java` must be re-bundled with the updated library.

Note:  additional work has been done to improve the threading which was not included in @Vzor-'s jar.  https://github.com/mrpippy/hidapi/commit/75b8627432c5a1aac1b15f9364b6094d5ea98a70

**Comment by tresf** [comment]
Further testing shows this crash still exists following the steps in the original bug report.

Currently, we're testing a new approach -- executing all events on the Event Dispatch Thread as to force Java to run the HID calls in sync with Cocoa.  Build available for download here [qz-tray-2.0.2-hidsplit2.pkg](https://github.com/tresf/tray/releases/download/v2.0.2-hidsplit/qz-tray-2.0.2-hidsplit2.pkg)

**Comment by Vzor-** [comment]
I have prepared a second test based on the threading code suggested by mrpippy. The test is ready at https://github.com/vzor-/tray/ on the 2.0 branch.

**Comment by tresf** [comment]
@Vzor- this patch seems to be running stable for @klabarge and myself for about 3 hours without any crashes repeating the steps in the original bug report many times.

**Comment by tresf** [comment]
Reopening.  This issue has resurfaced since #1177.
