### ISSUE TITLE
Bematech Printer Support

### ISSUE THREAD

**Issue by tresf** [qzind/tray#138]
From client:

> These are commands by Bematech, the company of the fiscal printer. Venezuela, Argentina, Brazil, and Panama all require very specific Fiscal Printers by the government. These are Bematech and Hassar brands. These are commands in the ESC/BEMA , not in the ESC/POS.

Bematech offers a printer emulator software which I was unsuccessful in getting working.

What "working" means:

* https://qz.io/wiki/2.0-raw-printing updated with ESC/BEMA examples
* Add BEMA image support: https://github.com/qzind/tray/blob/2.0/src/qz/printer/ImageWrapper.java#L306

Screenshot of the emulator:
![unnamed](https://cloud.githubusercontent.com/assets/6345473/20418878/92664c10-ad1f-11e6-9ca3-0b058cf8f692.png)

@taupter is going to start this feature.

**Comment by tresf** [comment]
@taupter can you help us with some basics?  We just need to get the emulator setup and send what's needed for a basic receipt.  If not, can you recommend someone that can read Portuguese to assist us moving forward?

**Comment by taupter** [comment]
Yes, tres, I can help you. I'll contact you later today (18th) to help you
recreate what I've done here.


Em qui, 17 de ago de 2017 às 00:24, Tres Finocchiaro <
notifications@github.com> escreveu:

**Comment by tresf** [comment]
No word from @taupter for weeks at a time.  Bumping to 2.2 milestone, but may close as `wontfix` if we can't find some translation help on this.

**Comment by tresf** [comment]
We hired some R&D on this and it's simply not a product worth supporting at this time.  The API makes it possible in Java, but it introduces some licensing issues.  Raw serial data just has too many combinations of printer to support and the regulatory restrictions make it too hard to support this in the project's current state.

I'll quote the contractor we hired:

> There is 4 types of response, 3 with fixed length, one with length inside message [and worse other] models of this brand have different protocols [...].  [To impliment this] I think that you need to have a new type of serial `RAW SERIAL` and then the utility just do a open async channel between port data and JavaScript.  This is because the serial impl needs RX byte to read return, of stream is not ok, just proxy read(byte[]) method.

(he's right, we [do rely on RX byte](https://github.com/qzind/tray/blob/1f0b1c172c9c833fb02f2a2eb5b75556d4418263/src/qz/communication/SerialIO.java#L96), it's part of the JSSC api)

> Normally the commands have length [but the] problem is [with] the another 3 types which are `error`, `wait` and `sync`.  [The Bematech] protocol don’t use RX byte to mark the start.
> 
> [Serial support for] tax printers on Brazil = Hell

Closing, marking as `wontfix`, at least for now.
