### ISSUE TITLE
Tray closed mid-print doesn't throw reject

### ISSUE THREAD

**Issue by tresf** [qzind/tray#14]
Per client:

> To reproduce it you can:
>  1. Have the log open in qz tray (This slows the sending down, this also only works with base 64 encoded sending since that is outputed to the log).
>  2. Then you start a print job from the client, and exit qz tray while the data is being sent.
>  3. The console log will show that the connection was closed but the print promise does not resolve nor reject.

**Comment by bberenz** [comment]
Likely fix:
Run through all promises stored in `_qz.websocket.pendingCalls` and call the `reject` method for each when a disconnect is detected. Otherwise they sit there waiting for a response from the tray software.

**Comment by tresf** [comment]
@bberenz I'm on it, thanks.

**Comment by tresf** [comment]
@bberenz no luck with this one.  I've tried placing the following in various locations including `disconnect`, `sendData`, `callClose`.  I'll defer to you on this one.

```javascript
if (Array.isArray(_qz.websocket.pendingCalls)) {
   for (var i = 0; i < i < _qz.websocket.pendingCalls.length; i++) {
      _qz.websocket.pendingCalls[i].reject(evt);
   }
}
```

**Comment by bberenz** [comment]
I should have mentioned here that it's used as a dictionary, not an array.
Taken care of via 99dffe530fecf1b4e5c72095ae0ec20f46ef3e0b
