### ISSUE TITLE
HID streaming with Stamps.com 70lb scale

### ISSUE THREAD

**Issue by klabarge** [qzind/tray#152]
**Edit:** Tested against `tresf/hid` branch

**Scale:** Stamps.com Stainless Steel 70 lb. Digital Postal Scale
 * **VendorID:** 0x1446
 *  **ProductID:** 0x6a73

**OS:** Windows 10 
**Browser:** Chrome 32-bit
**Java:** 8u111
**QZ Tray:** 2.0.2-ALT

### Issue
When `hid.openStream` is called to read weight off the scale:
* Sometimes the value is stuck at "0.000" and weight is not registered
* Sometimes the value is stuck at "1.000" and weight is not registered
* Sometimes reading from the scale works fine

Currently only reproducible at the client's website ONLY using this type of scale.  I have also tested with a Stamps.com 5lb scale (same VendorID and ProductID) with 100% success (no issues).

Sometimes when I move off the page, the logs show:
 ```
[ERROR] 2017-01-12 20:21:54,631 @ qz.ws.PrintSocketClient:?
	Could not send message
org.eclipse.jetty.websocket.api.WebSocketException: RemoteEndpoint unavailable, outgoing connection not open
	at org.eclipse.jetty.websocket.common.WebSocketSession.getRemote(WebSocketSession.java:251)
	at qz.ws.PrintSocketClient.send(Unknown Source)
	at qz.ws.PrintSocketClient.sendStream(Unknown Source)
	at qz.utils.UsbUtilities$1.run(Unknown Source)
 ```

Other times, this is the disconnect message
 ```
[INFO] 2017-01-12 20:23:48,250 @ qz.ws.PrintSocketClient:?
	Connection closed: 1006 - Disconnected
[INFO] 2017-01-12 20:23:48,251 @ qz.ws.SocketConnection:?
	Closing all communication channels for Support
 ```

* I have not been able to find a correlation between the two different disconnects.

### Reproducing
1. Login to the web application and go to "Settings" to choose HID scale to be used
1. Go to area in application to read weight.
1. If streaming is working, navigate to different area of application and then return to the area to read weight on scale
1. Repeat until the Weight field does not show the weight on the scale 
   * Again, sometimes this value is stuck on"1.000" Lb, other times it is "0.000"

* Typically when this happens, I am unable to get this field to update appropriately until a power cycle of the scale

**Comment by klabarge** [comment]
We believe this may be a page navigation problem.  I am attempting to create a sample page for reproducing this error.

**Comment by klabarge** [comment]
There was a `NullPointerException` being thrown when streaming occurred before data was being sent.

After handling the NPE, we could not reproduce the issue in the clients environment.

This bug report should be closed out when the changes make it to this repo

**Comment by tresf** [comment]
Closed via https://github.com/qzind/tray/commit/b6da1a8fc3d96946c6a0e642c176c4dd99768100.
