### ISSUE TITLE
Sigma symbol from sha256 getting stripped/interpreted wrong, causing illegal token

### ISSUE THREAD

**Issue by aarmora** [qzind/tray#16]
When I run the demo file it works fine.  When I run it on any other page, including a fresh HTML page with only the javascript files included it throws this error.

This symbol "Σ" is what trips it.

This section of the sha-256.min.js, `var T=y+Sha256.Σ1(d)`, for example.

Am I missing a required file?

`Unexpected token ILLEGAL`

	<script type="text/javascript" src="/WhsePalmIPad/JS/qz-print/rsvp-3.1.0.min.js" ></script>  
	<script type="text/javascript" src="/WhsePalmIPad/JS/qz-print/sha-256.min.js" ></script>  
	<script type="text/javascript" src="/WhsePalmIPad/JS/qz-print/qz-tray.js" ></script>

**Comment by tresf** [comment]
@aarmora this is usually a sign the page isn not UTF-8 encoded.  There are several ways to set encoding, but what seems to work best for is plain old:

```html
<head>
<meta charset="UTF-8">
<!--- ... -->
</head>
```

**Comment by aarmora** [comment]
@tresf Man, you nailed it!  Thanks so much for the help, this was really not your issue.
