### ISSUE TITLE
nodejs qz-tray.js v2.03. has issue

### ISSUE THREAD

**Issue by waitingsong** [qzind/tray#165]
Hi, 
 I found a bug in qz-tray.js under node.js npm ,but i do not know how to commit issue on npm, so i post here.
file: node_modules\.2.0.3@qz-tray\qz-tray.js
line 18:  z
cause " ReferenceError: z is not defined"

i delete this line, it works ok.
pls fix it

**Comment by tresf** [comment]
Thanks!

Closed via https://www.npmjs.com/package/qz-tray.

`npm install qz-tray` or `npm install -g qz-tray` depending on your environment.

```bash
npm view qz-tray versions
```
```js
[ 
  '2.0.1-1',
  '2.0.1-2',
  '2.0.1-1B',
  '2.0.1-1C',
  '2.0.1-1D',
  '2.0.1-1E',
  '2.0.3-1',  // <--------- 2017/02/12
  '2.0.3' 
]
```

**Comment by tresf** [comment]
> i do not know how to commit issue on npm

I appreciate you offering.  NPM has it's own security and this bug wasn't present in the source, it was made at publishing time, so opening a bug report is the best way for now, thanks!

**Comment by waitingsong** [comment]
qz-tray npm package has updated.
thanks.
