### ISSUE TITLE
Landscape Orientation for PDF's

### ISSUE THREAD

**Issue by klabarge** [qzind/tray#173]
**QZ Tray Version:** 2.0.3-RC4
**OS:** Windows 10

When I try to use `orientation: landscape` with PDF's, the PDF prints portrait.

This feature worked in the official 2.0.2 release.

**Comment by klabarge** [comment]
This is also not working on Ubuntu.

This feature works on macOS.

**Comment by tresf** [comment]
Since macOS uses a different technique for rotation (due to https://github.com/qzind/tray/issues/174) That make sense Mac isn't affected.

@klabarge can you please roll back to 3c9361d (`git reset --hard 3c9361d`) and see if it fixes it?  That's just before [`BookBundle.java`](https://github.com/qzind/tray/blob/2.0/src/qz/printer/BookBundle.java) was introduced.

**Comment by tresf** [comment]
Confirmed, reverting to 3c9361d reverses the bug.  Now to find out why.... 😕

**Comment by bberenz** [comment]
So even though we set the orientation under the attributes, the Book/Pageable does not seem to see it unless it is also set on the page format object as well.
Should be fixed under 667a6b12d0baeb3ac0a4701c714b4c20bc59d6cb

**Comment by tresf** [comment]
@klabarge can you please confirm?  Updated RC installer available [here](https://github.com/tresf/tray/releases/tag/v2.0.3-RC5).

**Comment by klabarge** [comment]
1. The PDF rotates now, but does not scale correctly, the bottom of the page is cut off. This happens on both Windows and Ubuntu
1. On Mac, setting `landscape` now only prints the right-half of the PDF, and does not change the orientation

⛔️ **Windows 2.0.3-RC5 using `landscape`**

![image](https://cloud.githubusercontent.com/assets/12505463/23384155/9b7372a4-fd17-11e6-9390-93d11c0be880.png)

⛔️ **macOS 2.0.3-RC5 using `landscape`**
![image](https://cloud.githubusercontent.com/assets/12505463/23383500/aecbcfca-fd14-11e6-886e-c9625e09a7b7.png)


✅ **macOS 2.0.3-RC4 using `landscape`**
![image](https://cloud.githubusercontent.com/assets/12505463/23383965/c8807b9e-fd16-11e6-9c9a-f6f24f9fd075.png)

**Note:** Disregard the way the text is displayed, that is due to the zoom size I have set to the PDF.

**Comment by bberenz** [comment]
Going back to what we did on 2.0.1 (when using just `Book` object) seems to present expected behavior.
Ready to test again under cc089f467842181891f0ea45061becd73eea1306

**Comment by tresf** [comment]
@klabarge can you please confirm? Updated RC6 installer available [here](https://github.com/tresf/tray/releases/tag/v2.0.3-RC6).

**Comment by klabarge** [comment]
This patch passed on all OS's 👍

**Comment by edsonpa** [comment]
Hello Guys, I encounter the same problem, how can I come up with this solution.

**Comment by tresf** [comment]
This issue was closed as fixed.  If you are compiling from source I would recommend doing a tag checkout of `v2.0.3` until we've completed the release of 2.0.4.

**Comment by edsonpa** [comment]
Actually I'm using the executable available for download, in version 2.0.3

We have the whole program developed and in the homologation part we are faced with this problem.

I need to sort this out to buy your support and generate the necessary certificates.

But this deadlock is delaying everything, please is there not something like the one that was done in the above solution?

**Comment by tresf** [comment]
@edsonpa you can try our latest release-candidate here: https://github.com/klabarge/tray/releases/tag/v2.0.4-RC.1

**Comment by edsonpa** [comment]
Unfortunately it did not work.
We notice that the printing area has 270 mm already discounting 0.5 mm in the initial edge.
The cut occurs 20 mm from the end edge.
So I came to the conclusion that there is a size limit for the 300mm x 216mm landscape format, if that exists where I can change this in the source code to create a version that suits us for this dimension.

**Comment by bberenz** [comment]
@edsonpa, this issue is about landscape oriented documents printing with a portrait orientation. What you describe sounds like an issue with content being cut off. You may be better off opening a new issue and thoroughly describing the issue you are seeing. (configurations, expected/actual results, etc)

Also, we don't limit sizing anywhere in our code. so it sounds like you may need to make use of the `pageWidth` and `pageHeight` data options. (See https://github.com/qzind/tray/issues/193 for a discussion on this setup with landscape documents)

**Comment by edsonpa** [comment]
Thanks for the answer but that's not it, we did the tests on more than one operating system on more than one physical printer is the error is the same, we created documents on other platforms in both guidelines.
The printout is cut about 20 mm at the bottom of the page.
As I mentioned the error that occurs is the same as described here (Landscape Orientation for PDF's # 173

The situation is the same as mentioned above.

**Comment by klabarge** [comment]
@edsonpa 

I still believe your issue is different. This issue is stating that a document printed `portrait` and `landscape` result in the same print.

You are using a custom page size of `300mm x 216mm`. You would need to specify (in your code) to use `orientation: landscape` as opposed to flipping the dimensions of your PDF.

I am going to reply to your google groups post with more information.

**Comment by edsonpa** [comment]
thank you
