### ISSUE TITLE
QZ not working over WSS using IP machine

### ISSUE THREAD

**Issue by giolazzareschi** [qzind/tray#183]
Hi!

I'm facing a strange issue and any help will be apreciated.

I've been using qz (the paid one) to work with my clients using one pc as "server" and other pc's on network just pont to its IP to make print happens. Ok this always worked fine with ws protocol but in last days I just implemented https on my website and the prints just stopped. Well, searching for an answer I've found this:

[Remove static localhost bindings in code #91](https://github.com/qzind/qz-print/issues/91)

But trying to work with the solutions the thing just don't happen.

I tried to create the certs for the wss but I receive an failure message when qz tryies to print.

My scenario is: I use the host machine IP to connect with QZ but receive this message:

![image](https://cloud.githubusercontent.com/assets/4623190/24277804/5d1c0100-101e-11e7-84e0-a5f9e1a93048.png)

This ip is the host machine. Neither this or guests machines works.

I dont know if i was clear enough but any help will be helpful. Regards :)

**Comment by tresf** [comment]
HTTPS is very picky as the SSL cert must match the IP or domain it's being accessed on, which forces cert distribution, which generally frowned upon.

We have a dedicated tutorial for this here:

https://qz.io/wiki/print-server#remove-localhost-bindings

If you own an SSL cert that's already trusted, you can fire up QZ Tray with that instead.  We don't have a formal tutorial for this, but we've documented it for the free "lets encrypt" service, which some of our clients use.

https://github.com/qzind/tray/issues/73#issuecomment-237165577

**Comment by giolazzareschi** [comment]
Hi Thanks!

Well, i tryied both ways, no one finished working.

Here the results:

1. Generating certificate from qz -- (C:\Program Files\QZ Tray>cscript auth\windows-keygen.js . install "192.168.0.11")

![image](https://cloud.githubusercontent.com/assets/4623190/24279242/63fd2568-1027-11e7-995c-607225bf7cfd.png)

Although I installed the generated certificates the qz stills not connects properly.

2. Genererate from fullchain.pem and privkey.pem - fails too

I ran this (with my correct paths): 

C:\Program Files\QZ Tray>cscript auth\windows-keygen.js . install 192.168.0.11 "C:\Ciao\centos7\igo_api\cert\fullchain.pem" "C:\Ciao\centos7\igo_api\cert\privkey.pem"

![image](https://cloud.githubusercontent.com/assets/4623190/24279319/e48a9b7a-1027-11e7-8cbd-721141eadd63.png)

Says: ....window-keygen(363, 5) Path not found

Well what else i can do? Are there something that I'm doing incorrencly?

**Comment by giolazzareschi** [comment]
Well I managed to install the certificate but qz strll not permit connection via wss

![image](https://cloud.githubusercontent.com/assets/4623190/24280729/abba309e-1031-11e7-9862-905f3dacfab3.png)

Well, if someone could help it will be apreciated.

**Comment by tresf** [comment]
Closed via f8d74d7.  This fix will be available in the next patch release: 2.0.4
