### ISSUE TITLE
allowedFromDialog Slow/Not Thread-safe

### ISSUE THREAD

**Issue by dsanders11** [qzind/tray#185]
The current implementation of thread-safety in `allowedFromDialog` is not a good one. When using QZ Tray for webcam control on my own branches I found responses were very slow when sending several requests in a rapid fire manner. I determined this was due to the 1 second sleep time in `allowedFromDialog` if the dialog is already "open" (quotes because with a trusted cert there is no visible dialog that's open).

Upon further inspection it became clear that while attempting to provide thread-safety, there's a race condition in the current code. There's no check that once the `AtomicBoolean` becomes false that the thread actually acquires it when it sets it to true. An implementation continuing to use `AtomicBoolean` would want to use something like [`compareAndSet`](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/atomic/AtomicBoolean.html#compareAndSet\(boolean,%20boolean\)) to ensure only one thread grabs the boolean. The current implementation means two threads looking at the same time will both go ahead and attempt the dialog.

A better implementation would be to use a semaphore like I've done in b44a1321d771980c63dd24818d03ee67cc0b5beb, which lets the thread block on the `acquire` call instead of doing a loop with sleep. It also ensures only a single thread acquires it at a time, and also adds "fairness" by providing FIFO to ensure no thread gets starved. I don't love silently ignoring the `InterruptedException` in that commit, but I needed something quick.

BTW, despite using a trusted certificate, a few times a week we see a dialog pop up on the computer we use for hosting QZ Tray which then blocks print jobs until it is allowed, and then it goes back to being silent. I wonder if that may be due to the race condition I described above - it's very random and sporadic.

**Comment by tresf** [comment]
@dsanders11 thanks!  Closed via https://github.com/qzind/tray/commit/75054c6a4d2345b63dfbd05f916d9865f072f08d.

**Comment by dsanders11** [comment]
@tresf, I still think the silently ignoring `InterruptedException` is a bad idea, as it means the thread will continue to the dialog even if the thread is supposed to be being interrupted. However, I don't think this is a change from the previous behavior which swallowed any exception while it was sleeping.

There's also likely several other places in the code that should be reviewed for thread-safety, like `PrintRaw.java`.

**Comment by tresf** [comment]
@dsanders11, thanks.  @bberenz actually said the same thing.  We're going to return false in that case.

In regards to other unsafe areas, we should track them in a new issue.
