### ISSUE TITLE
QZ-Tray is failing to render PDF documents on Windows 10.

### ISSUE THREAD

**Issue by sbs-callum** [qzind/tray#188]
Edit: Whoops this was meant for our internal issue tracker, sorry about that.

As of QZ-Tray 2.0.3 there appears to be an issue with rendering and printing PDF documents on Windows 10 machines. It may or may not be related to passing the PDF as a base64 encoded string.

**Comment by tresf** [comment]
Can you please provide a reproducible code snippet?  Also, you state Windows 10 and QZ Tray 2.0.3.  Does reverting to QZ Tray 2.0.2 remedy this problem?

**Comment by sbs-callum** [comment]
The issue was indeed present within 2.0.2. I am working on getting you a code snippet now. I will come back to you when my test order has been through the necessary stages to produce this. 

I will also verify that the print code output by our windows 10 machines matches that which is output by our windows 7 machines.

**Comment by tresf** [comment]
@sbs-callum friendly bump to get the unit test for us to reproduce.

**Comment by tresf** [comment]
@sbs-callum without steps to reproduce, we cannot work on this issue.  Please kindly post a steps to reproduce when you have then and we'll confirm and reopen.
