### ISSUE TITLE
 #165 still exist

### ISSUE THREAD

**Issue by Jetxiaoli** [qzind/tray#194]
after run npm install qz-tray. the below issue still exist.
file: node_modules.2.0.3@qz-tray\qz-tray.js
line 18: z
cause " ReferenceError: z is not defined"

**Comment by tresf** [comment]
@Jetxiaoli no, it's not.  Perhaps you have an outdated package or you installed something globally `-g` so it's failing to update locally, but `2.0.3-1` has this issue fixed.
