### ISSUE TITLE
Unsigned Request

### ISSUE THREAD

**Issue by Jetxiaoli** [qzind/tray#195]
Hi,
when I use the key in the demo in localhost, it shows I can connect with qz, when connect with printers, it shows untrusted website: UNSIGNED REQUEST

**Comment by klabarge** [comment]
All messages need to be signed to suppress the warning dialogues. The demo page (sample.html) ships with a trusted Intermediate Certificate for connection, but no private key to sign messages with.

The below wiki outlines this in detail:

https://qz.io/wiki/2.0-signing-messages

If you require assistance with this setup, please reach out through the official support channel.
