### ISSUE TITLE
QzTray for synaptics package manager - Ubuntu easy installation 

### ISSUE THREAD

**Issue by alexandrox92** [qzind/tray#199]
Is it possible to load QZtray to synaptics package manager ? It would be great to be able to do it official so it would be very fast to install and we would not worry about dependencies, we also have the problem of companies that do not want to use more windows but do not know about linux and try to install qz this terminal can be traumatic.

is this possible ?

**Comment by alexandrox92** [comment]
Another option would be the official ubuntu store, normal users do not know how to handle the terminal and this creates traumas when convincing the client to use free software.

**Comment by tresf** [comment]
>  this creates traumas when convincing the client to use free software.

I don't agree.  Many Linux application still require terminal installation.

> Is it possible to load QZtray tosynaptics package manager

Yes it is 100% possible, but we have no plans on offering this feature, no do we plan to put it in Ubuntu Software Center, Yast, Homebrew, DNF or the Windows Store as the maintenance associated with publishing, updating and upgrading is far more of a setback than the benefit our clients would receive by such a service.  Our time is better spent improving the software.

We may eventually opt for an AppImage installer, but we will first need a method to do a runonce on any root tasks, such as setting up the SSL certificate.

**Comment by alexandrox92** [comment]
It's okay, thanks for replying.

CLOSED
