### ISSUE TITLE
PDF Rasterize Option

### ISSUE THREAD

**Issue by tresf** [qzind/tray#2]
@bberenz the PDF crash bug is causing clients to use DPI work-arounds.

Although this works great, they don't always know the DPI of the printer they're printing to.

I think we need a new param `rasterize: true` for Pixel printing which -- in the case of a PDF -- will auto-sense the DPI of the printer and use that when the `rasterize: true` parameter is provided.  Setting a dpi would naturally force this parameter to true as well.

This will have the benefit of auto-scaling to the desired paper using the rendering of the PDF without knowing the DPI, thus completely circumventing the PDF printing bug for the 2.0 release.

Should be safe to always default to `true` for other Pixel jobs, since HTML and Images are already rasterized anyway.

Then for those non-Mac shops that want PDF vector printing (or HTML if JavaFX ever adds it down the road), they can set `rasterize: false` and allow the data to be sent in a more native/preferable flavor.

Migrated from https://github.com/qzind/qz-print/issues/187

**Comment by bberenz** [comment]
Completed via a133715cd3019a663de54568bbe34780cc45f9e1

**Comment by tresf** [comment]
Supplemental documentation for this feature is available here: https://github.com/qzind/tray/wiki/2.0-Pixel-Printing#rasterize

**Comment by tresf** [comment]
Hmm... `PrintService.getDefaultAttributeValue(PrinterResolution.class)` returns null on Mac... might need to write a hack for this one.... :confused: Investigating...

**Comment by tresf** [comment]
Ok... found an ugly hack... Yuck... 

```java
if (density == 0 && pxlOpts.isRasterize()) {
            PrinterResolution resolution = (PrinterResolution)output.getPrintService().getDefaultAttributeValue(PrinterResolution.class);
            if (resolution != null) {
                density = resolution.getFeedResolution(ResolutionSyntax.DPI);
            } else {
               if (SystemUtilities.isMac()) {
                   String stdout = ShellUtilities.execute(
/// FIXME - REPLACE PDFwriter.ppd with actual printer name... 
                           new String[]{"grep", "*DefaultResolution",  "/etc/cups/ppd/PDFwriter.ppd"},
                           new String[] {
                             "*DefaultResolution"
                           }
                   );
                   if (!stdout.isEmpty()) {
                       String[] parts = stdout.split("\\s+");
                       String end = parts[parts.length -1];
                       density = Integer.parseInt(toString().replaceAll("\\D+", ""));
                   }
               }
            }
        }
```

**Comment by tresf** [comment]
@bberenz ok, I've edited the above post with some native commands that can retrieve the default DPI.

The code clearly needs to be cleaned up, but it works.

I'm not sure if we should:
 * Run a task which sets the default DPI attribute directly on the print services
 * Run this series of bash commands on every print
 * Cache the values on startup and try to retrieve them later

There's a project called `cups4j` that claims to be able to help with these things too, but it's quite dated and there aren't a lot of people using it... 

http://www.cups4j.org/

**Comment by bberenz** [comment]
If this is CUPS related, is Linux also being affected?

I think we should try to set the DPI directly on the print services, as that should make it possible to use the `getDefaultAttributeValue` call for the next print, right? Failing that, we could store the results on the first run for a printer in a map, and use that for future use with the respective printer.

**Comment by tresf** [comment]
> If this is CUPS related, is Linux also being affected?

We haven't tested yet, I'll do so now.

> I think we should try to set the DPI directly on the print services, as that should make it possible to use the getDefaultAttributeValue call for the next print, right? Failing that, we could store the results on the first run for a printer in a map, and use that for future use with the respective printer.

That was my thought as well.  The only downside is that if attributes are changed or printers are added after the application is started, they won't be reflected unless we have some worker thread refreshing these things periodically.

**Comment by tresf** [comment]
> If this is CUPS related, is Linux also being affected?

I can confirm that Linux throws the same `NullPointerException`.

**Comment by tresf** [comment]
I can also confirm an identical technique should work in regards to parsing the console output:

![image](https://cloud.githubusercontent.com/assets/6345473/13964777/d267f066-f041-11e5-803f-8703abadefed.png)

**Comment by tresf** [comment]
>  identical technique should work

Ok, one exception... Linux renames the PPD file when its renamed in control panel, so it doesn't require the reverse-lookup `name/description` hack that Mac needs.
