### ISSUE TITLE
I can't able to print arabic

### ISSUE THREAD

**Issue by riyask** [qzind/tray#204]
When i trying to print arabic it shown as "????????" like this. Please help me how to solve this issue

Regards

Riyas

**Comment by lite1979** [comment]
Can you share your code and tell us which printer you're using?  There are
some printer models which must be ordered with firmware that supports
Arabic characters.

Regards,

Lite

**Comment by tresf** [comment]
@riyask I'm closing this because you've failed to provide what is needed for a basic bug report.  Please request a re-open once you have the necessary information, such as your printer model and some sample code.
