### ISSUE TITLE
Segfault on macOS unclean HID disconnection

### ISSUE THREAD

**Issue by alethea** [qzind/tray#207]
I discovered a hard crash in the HID4Java integration on macOS. This can be reproduced reliably by the following steps:

1. List HID devices: `qz.hid.listDevices()`
2. Select a HID device and claim it: `qz.hid.claimDevice('0d8f', '0200')` 
3. Open the event stream from the device `qz.hid.openStream('0d8f', '0200', 6)`
4. Disconnect and reconnect to QZ Tray: `qz.websocket.disconnect(); qz.websocket.connect()` or reload the host page.
5. Attempt to list devices again: `qz.hid.listDevices()`

I've attached the [JVM stack trace](https://github.com/qzind/tray/files/1125777/hs_err_pid22167.log.txt) and the [macOS problem report log](https://github.com/qzind/tray/files/1125795/macos-problem-report.txt).
 This appears to be specific to macOS or HID4Java, since it does not occur on Windows. Ensuring the device is released and the stream closed prevents the error from occurring, but I can't guarantee that the user doesn't navigate away from the page before that occurs.

**Comment by tresf** [comment]
We should be disconnecting the stream with the lifecycle of the websocket (and we've found this previously in QA, so I'm surprised to see it resurface).  We'll take a look, thanks.

**Comment by tresf** [comment]
Also, a side note, Windows uses [PureJavaHIDAPI](https://github.com/qzind/tray/blob/5116bfe3061cd786657ecfd53d2a69ae8ca5e3a6/src/qz/ws/PrintSocketClient.java#L327-L332), so the libraries are a bit different.

History on this decision is available here: https://github.com/qzind/tray/pull/166

HID4Java uses a `signal11` library which contains quite a few Mac crashes, so any upstream fixes we'd happily take downstream as well. 👍

**Comment by alethea** [comment]
Yeah, I dug through the source, and it looked like everything was getting cleaned up properly, I suspect something gets garbaged collected while the native code is still hanging onto it. Which means that the PureJavaHIDAPI wouldn't be affected.

**Comment by klabarge** [comment]
Thanks for the detailed steps. I tried the above steps at least 10 times and could not reproduce a crash.

I tried to mimic your environment. Is this reproducible on different HID devices? What HID device? I assume you are using the latest version of QZ Tray?

Your environment:
* **OS:** Mac OS X 10.12.5
* **Java:** Java(TM) SE Runtime Environment (8.0_31-b13) (build 1.8.0_31-b13)
* **Hardware Model:** MacBookAir6

My environment:
* **OS:** Mac OS X 10.12.5
* **Java:** Java(TM) SE Runtime Environment (8.0_31-b13) (build 1.8.0_31-b13)
* **QZ Tray:** 2.0.4
* **Hardware Model:** Mac mini (Late 2014)
* **Scale:** Stamps.com Stainless Steel 70lb Digital Scale

**Comment by alethea** [comment]
I'm on QZ Tray 2.0.4 and the HID device I've been trying to access is a Pitney Bowes 5lb scale.

**Comment by tresf** [comment]
@alethea just to rule out the Java version, can you confirm that this bug still exists with Java 8u131?  Worth noting, we prefer the JDK over the JRE, so if you have both you should upgrade both or [launch from JRE manually](https://github.com/qzind/tray/blob/2.0/ant/apple/apple.properties#L20).

**Comment by alethea** [comment]
@tresf Updating the JRE to build 1.8.0_131-b11 appears to have resolved this on my setup. Guess I must have dismissed the update Java update notification at some point. 😆  Thanks for the help, y'all.

**Comment by tresf** [comment]
The MacBook Air versus Mac mini was the reason, similar problem in #35, but different crash logs.
