### ISSUE TITLE
Don't Entirely Replace Properties File When Replacing SSL Cert

### ISSUE THREAD

**Issue by dsanders11** [qzind/tray#208]
Currently if you have to update the SSL certificate on an existing QZ Tray installation, the process will entirely replace the `qz-tray.properties` file. This is not ideal because any custom settings like `authcert.override` will be lost.

Would it be possible for it to reuse the keystore password for the new keystore? I believe this is the only reason it needs to replace that file, to update the keystore password.

We're using LetsEncrypt certificates so they need to be replaced every 3 months, and I always seem to forget to save off the custom settings before they get lost. :-) It's especially painful because we're running a fork that adds a couple extra settings to the properties file as well.

**Comment by dsanders11** [comment]
@tresf, FYI, some time in the next 3 months (before the next LetsEncrypt cert expiration, heh) I'll probably try to fully integrate the renewal process into QZ Tray itself to make it less painful and reduce the [bus factor](https://en.wikipedia.org/wiki/Bus_factor).

I'm thinking an interface where QZ Tray will check the expiration on the certificate, and a few days before expiration it'll try to renew (and log errors if it has problems) and replace the keystore while running (might be a little tricky).

To get the new certificate I'm thinking a web service (since LetsEncrypt needs public access) running on a server, which QZ Tray will contact (with username and password stored in `qz-tray.properties` for an extra layer of security) and ask the server to renew the certificate for it, providing the certificate and a signature to prove it has the private key. The server will renew the certificate (probably shell out to run `certbot` as they don't seem to have a direct API you can use) and hand the new info back to QZ Tray. Only trickiness there is the process might take a little bit, so need a clean API for QZ Tray to check for the result in case it gets disconnected while waiting and won't restart the whole renewal process.

Any thoughts or pre-requisite work towards that end would be appreciated.

**Comment by tresf** [comment]
This seems like an involved process for something that `certbot` could simply farm off to a post-hook, which kills the Java process and relaunches.

The standard use-case is to for qz-tray simply randomize the private key password when it is converted from `pem` to `p12` and then to `jks`.  We could certainly check for existence of the `authcert.override` when rewriting the properties file on a Trusted SSL install, but making Java responsible for rewing the certificate seems like the wrong place and the password logic should cover 80% of use-cases which is what we aim to meet.

**Comment by tresf** [comment]
Perhaps I'm missing something.  What I've read about `certbot` is that it will auto renew when ready and you can call it daily without worry.  I think what's unique about your setup is that IIRC, you're using the same cert for SSL that you are for the trust dialog, which means everything breaks at once (right?).

We run `certbot` on our white-label service server and we are responsible for any post-cert-renewal tasks (such as reloading `nginx`, etc).  It seems that we could be a bit more respectful of the existing properties file of that suits your needs, I just don't think Java is the place to replace the post-hook stuff that certbot needs done.  It seems like the wrong end of the renewal process.

**Comment by dsanders11** [comment]
@tresf, sorry, I shouldn't have combined the two issues, this was mostly just don't throw away other properties in `qz-tray.properties` when updating SSL certificate. My mentioning `authcert.override` was just an example of a property that may get lost as a result.

> Perhaps I'm missing something. What I've read about certbot is that it will auto renew when ready and you can call it daily without worry. I think what's unique about your setup is that IIRC, you're using the same cert for SSL that you are for the trust dialog, which means everything breaks at once (right?).

QZ Tray is running on an internal network with only outbound traffic to the Internet. We use SSL certificates from LetsEncrypt to ensure there's no client setup step and we can run a very mixed environment (Android, Raspberry Pi, Windows, OS X, etc) with no worries about setting up certificate trust on each device since LetsEncrypt is trusted by all of those automatically.

Since LetsEncrypt needs a public hostname that it can verify and create the certificate for, we use our public Internet domain and simply place the internal hosts under a subdomain, e.g. `warehouse.internal.foobar.com`.

As such `certbot` has to run on the server which that domain name routes to. From there the certificate has to be manually moved from the server to any machines running QZ Tray and installed there manually. We can't use `certbot` hooks, it is running on an entirely different machine.

So the solution I was discussing allows the QZ Tray instance running on the internal network to reach out to the server who runs `certbot` on it's behalf. It's proxying `certbot`, basically.

**Comment by tresf** [comment]
The "public cert running on isolated lan" problem is a problem we've encountered as well.  The only recommendation I can make to that is to simply make the print-server publicly accessible, or clone it to a network that is and mirror the settings back to isolated device on change.  Unfortunately some networks have strict controls (HPPA, PCI, etc) so this may require a VPN service account, but should be possible.  This is just a common [limitation of using `certbot` on an isolated network](https://community.letsencrypt.org/t/certificates-for-hosts-on-private-networks/174/7).

The cost effective (anti-bus) way of doing this may eventually be to [just go back to the old way of rolling HTTPS](https://blog.filippo.io/how-plex-is-doing-https-for-all-its-users/) as you can get that 3-month renewal window 12x longer to 3-years, but none of this is news. :)

Anyway, back to the `qz-tray.properties` file.  We currently write the following values:
```properties
wss.alias=qz-tray                       # always "qz-tray", unless a custom build or white-label install
wss.keystore=/path/to/private-key.jks   # always generated by *-keygen.sh
wss.keypass=<random>                    # always generated by *-keygen.sh
wss.storepass=<random>                  # always generated by *-keygen.sh
wss.host=0.0.0.0                        # **wiped out**, reset to 0.0.0.0"
authcert.override=/path/to/override.crt # **wiped out** unless authcert.use is specified to ANT
```

So one possibility is to build qz-tray from source to with the `authcert.use` parameter pointing to a LetEncrypt RootCA, which will re-build the `*-keygen.sh` files with the proper value of `authcert.override` and bundle it into the application install.  This will make sure `auth.override` keeps getting rewritten, but it will not fix the `wss.host` problem or any other values that are getting wiped out.

The other possibility is for us to be kinder to existing properties files in general and just write the above values that are **always generated by \*-keygen.sh** and leave everything else as-is.

Opinions welcome. :)

**Comment by dsanders11** [comment]
> The other possibility is for us to be kinder to existing properties files in general and just write the above values that are always generated by *-keygen.sh and leave everything else as-is.

This is the option I was imagining, or as I said earlier, just keeping the keypass and storepass the same so that the properties don't have to be updated at all. Whichever is easier to implement in the scripting you've already got for the keygen stuff.

> The "public cert running on isolated lan" problem is a problem we've encountered as well. The only recommendation I can make to that is to simply make the print-server publicly accessible, or clone it to a network that is and mirror the settings back to isolated device on change.

Making it publicly accessible is a no-go from a security standpoint for us, in addition to the extra configuration to the local area network to make the one host publicly accessible.

I've thought about it a decent amount and decided proxying through a web server to get the new certs seemed like the cleanest way to do it. I'm looking for a solution that doesn't require extra network configuration, extra long-running processes, or manual steps. The more "it just works" the better. I don't mind writing some extra code to get to those ends, so I'll be pursuing the plan I outlined in my previous comment. Since it's only needed once every 3 months that seems like a far more practical solution than setting up VPNs or public access, or anything else that requires additional pre-requisites.

**Comment by tresf** [comment]
> I'll probably try to fully integrate the renewal process into QZ Tray itself to make it less painful and increase the bus factor.

> >  so I'll be pursuing the plan I outlined in my previous comment. Since it's only needed once every 3 months that seems like a far more practical solution than setting up VPNs or public access, or anything else that requires additional pre-requisites.

This is the part I'm concerned with.  I'd rather not argue in the PR and have you wasted effort.  I don't feel QZ Tray is the right place to patch `certbot`'s shortcomings.  Can you elaborate on the design of this all, such as a newcomer wanting a LetsEncrypt QZ Tray instance using the future "integrated" design?

**Comment by dsanders11** [comment]
@tresf, I wasn't necessarily planning a PR, I'm perfectly happy to run a forked version of QZ Tray. I was merely mentioning my plans in case it was anything that interested you.

Off the top of my head (which always means it'll change since no plan survives first contact) it would introduce two new properties: `http.credentials` and `http.letsencrypt_proxy_url`. Those would be set appropriately, with the latter being something like `https://www.foobar.com/letsencrypt/`. QZ Tray would make a `POST` request to that URL when it needs to renew the cert, with old cert and a signature that confirms it has the private key. Server responds with the new cert and private key (could be avoided if a CSR is used instead, but everything is over SSL so not too worrying to move the private key this way).

Having poked around a bit more it looks like there is a direct Python API these days to avoid shelling out to `certbot`, via [`acme`](https://pypi.python.org/pypi/acme). There's also a project for directly integrating it into Django called [`django-autocert`](https://pypi.python.org/pypi/django-autocert/0.1.1) which I'd probably look into for how to use the `acme` project.

It's not really something a newcomer would really be able to dive into if only because it also requires them having a webserver, but they could always run a Raspberry Pi or the server could even be implemented to run on AWS Lambda (serverless, pay as you use) with a bit of work.

**Comment by tresf** [comment]
Yeah, it appears [manipulating DNS records temporarily and then cleaning them up](https://certbot.eff.org/docs/using.html#hooks) via `manual-auth-hook` is the preferred method for manually renewing a certificate.  Some cloud ISVs already having scripts ready as well.

**Comment by dsanders11** [comment]
There are definitely ways to do it manually and support the private/isolated network setup, they just require some work and knowledge.

I guess I'm trying to minimize the bus-to-failure-time (BFT) which would be how long after I get hit by a bus things that otherwise normally worked would fail. With a lot of things they could go indefinitely, web stuff is probably solid for years as long as you're not using any currently deprecated APIs, but the renewing certificates for QZ Tray means the BFT is capped at 3 months currently. :-) Trying to raise that in a way that adds as few new systems as possible, i.e. QZ Tray is already installed and can be installed in one go on new systems, the web server will continue to exist, etc.

So while it may not be an ideal place to stick it into QZ Tray, I've also jammed webcam control into QZ Tray to get around shortcomings in browser APIs, so I'm more about the end result here.

**Comment by tresf** [comment]
> So while it may not be an ideal place to stick it into QZ Tray, I've also jammed webcam control into QZ Tray to get around shortcomings in browser APIs, so I'm more about the end result here.

But webcams are native hardware and the exact purpose of QZ Tray.  LetsEncrypt will email when a cert is about to expire and if configured properly that would go to a shared inbox and work from a documented procedure.   QZ Tray's source code is simply the wrong place from a design perspective unless it's something standardized.

> It's not really something a newcomer would really be able to dive into if only because it also requires them having a webserver

This depends on your definition of "newcomer".  Most ( >90%) of QZ Tray newcomers aren't newcomers to IT specifically, so if the approach is e.g. `brew install certbotslave` versus something that only your organization uses, it would have some scalability justification.  Otherwise, it would appear a desktop application is being forked and repurposed for a one-off that could just as easily be a non-compiled script. 
 Java just seems like you're kicking that bus down the road a bit further.  The short-term (e.g. 3 months) everything's in good shape, but once the fork goes stale, everything else still has the problem of falling apart.

Sorry to argue design and maintainability on a bug report about a properties file, it's just we usually benefit from forked repositories, so my motivation for discussion generally starts with that assumption. :)

**Comment by dsanders11** [comment]
> but once the fork goes stale, everything else still has the problem of falling apart.

Unless something majorly changes with the way WebSockets work then the fork can keep on without falling apart even if it is stale. Just look at banks using software written decades ago. :-)

If QZ Tray had a plugin system then this would be built as a plugin, it's adding functionality. There's no reason that I can think of that it shouldn't be a plugin versus an external script, since the external script would need knowledge of QZ Tray and be updated when QZ Tray updates as well, like the recent change to include hostname in the keygen arguments.

If something is tightly coupled with another process, I see no benefit to running it separately. It increases the footprint, separate configuration and knowledge needed, in addition to needing extra firewall rules for outbound connections and the likes. Also provides an opportunity for the two to diverge, the script may stop working or accidentally get uninstalled, or QZ Tray would get uninstalled and the script would remain.

> LetsEncrypt will email when a cert is about to expire and if configured properly that would go to a shared inbox and staff may work from a documented procedure.

I'm coming at this from the perspective of a zero IT staff organization. There is no staff to work documented procedure. There is no documented procedure. A startup selling merchandise on Shopify can't afford an IT guy and doesn't need one if all they want is to be able to print shipping labels from a browser to a thermal printer. Even if there's an IT guy, he shouldn't need to go and renew SSL certificates for printers so he can go on vacation for 2 weeks and not have the business crumble, it should be automated. Automated in a way that if the computer running QZ Tray catches fire while he's on vacation and the business replaces it with a new one from Best Buy, all they have to do is install QZ Tray using a user-friendly installer and they're back to fully operational, including SSL cert renewal.

My own perspective is as a lone developer for an organization. Automate all the things. Any time taken to maintain infrastructure is time taken away from developing things with business value. If I can spend 2 days building a feature that removes a manual process that needs to be done at least 4 times a year, I'm going to do that. Especially when it instantly scales to new systems. Sure, it's unfortunate to have a fork, and I'll avoid it when possible, but if the existing software is stable and feature-complete then there's not much lost from divergence, especially if the fork was written in a way that has a small hook into the existing code that can easily be re-applied to newer versions.

**Comment by tresf** [comment]
We're driven primarily by popular use-cases and demand.  We do attempt to pick up new, bleeding-edge and state-of-the-art ideas as well.

We have some large cloud users (not Shopify, yet) and these cloud providers simply ask users of the product to install QZ Tray locally and move on with business.  This is how they survive the hypothetical "fire" today.  That's our primary use-case.

For the few that truly need the print-server option in a private setting (e.g. mobile devices on an isolated lan) they either use a dedicated app to talk to the printers already (e.g. native Android or iOS), or, for the cost of an iPad, they do buy a 3-year wildcard certificate which covers their various dev, test and production domains that they can use with the print-server (or any lan-only server for that matter).

So to follow an 80/20 rule we naturally would advise against any clients on a isolated LAN leveraging LetsEncrypt in general and even more caution if they're integrating it with QZ Tray due to the influx of support requests it will cause.  That's today though.  In the event a third party process for renewal is born (perhaps by you in 2 days 😃), farming the renewal process from Java may *slightly* ease the burden and warrant the technology but I can't in good faith say that without expressing my own bias as well.  Although I do fundamentally agree with the "free SSL" option, I also find it irrationally pragmatic to put something of such critical nature using a short-life certificate to begin with.  It reduces the size of the bus, but now it visits more often. :)

I have considered using a Java API internally for certbot renewal in general, so perhaps the silver lining would be to keep in mind those that CAN afford to have the print-server exposed publicly, as it would provide the baseline needed.

This may also open the door for the sale and support of QZ Tray print-servers in general and even give birth to a new product, but I'd ask that the mass appeal is a bit more "selling".

**Comment by dsanders11** [comment]
> they do buy a 3-year wildcard certificate which covers their various dev, test and production domains that they can use with the print-server (or any LAN-only server for that matter, doesn't need to be used for QZ Tray).

That sets off alarm bells in my head. Reusing the certificate (and the private key, which is the security risk) across servers is OK since they're limited access and have proper security protocols. Distributing that private key to machines with far wider access (and physical access to boot) would keep me up at nights. That key getting stolen because the Windows machine in the warehouse got hit by malware is not a good potential, when it allows anyone to impersonate your production website.

> For the few that truly need the print-server option in a private setting (e.g. mobile devices on an isolated LAN) they either use a dedicated app to talk to the printers already (e.g. native Android or iOS)

We've only recently "truly" needed the print-server option due to mobile devices, before that all systems could have had a local QZ Tray instance installed. The print-server option is superior in almost every case, as far as I'm concerned. It truly works on any device, there's no per-device configuration or installation required. No technical knowledge is required to enable printing from any device. If a computer bites the dust and a new one is swapped in there's zero setup, just having a browser installed.

The beauty of the print-sever option is it scales without me doing anything. I've already got a backlog longer than the River Nile, anything that just works without my involvement is a godsend. Anything that doesn't artificially limit the type of devices that can be used, even more so.

I understand this isn't something you may want to incorporate into QZ Tray mainline, I was just pointing it out because some of the changes to allow the flexibility may be general enough (and potentially useful) to backport to mainline without taking everything.

> This may also open the door for the sale and support of QZ Tray print-servers in general and even give birth to a new product

Yes, it would make it far easier to do so. You could sell a pre-rolled Raspberry Pi with a way to input the configuration necessary (WiFi network details, hostname). We have one taped to the side of a Zebra thermal printer which acts as a print server. You can almost actually power the Pi directly off of the extra USB port on the back of most Zebra thermal printers, but in our testing it couldn't quite draw enough juice (was very close, it worked and then cut out).

If making a pre-rolled Raspberry Pi print-server, the other piece to the puzzle would be the server aspect, which again, you could probably run yourself in the cloud. The client would simply point their internal domain name's DNS entry (e.g. `thermal-printer.internal.foobar.com`) to your hosted service so that it could renew via LetsEncrypt.

That would only work if their internal network redirected that domain name to the IP of the print-server, which is unfortunate because it takes away from plug and play, and would also preclude a publicly accessible print-server (which personally makes me cringe), but there may be some tricks you could pull there. I haven't actually thought anything through, just typing stream of consciousness. :-)

**Comment by dsanders11** [comment]
@tresf, is the `wss.keypass` actually used? I see no references to it in the Java code, and if changed to gibberish there's no change to QZ Tray's behavior. It looks like QZ Tray is taking advantage of the automatic behavior where the `storepass` is tried as the `keypass` first before declaring failure, and since that's how the keystore was generated then it always works. Seems like dropping `wss.keypass` would simplify things if it isn't used, and prevent possible confusion.

**Comment by tresf** [comment]
> @tresf, is the wss.keypass property actually used? 

It looks like we're not using it currently, but we should to be consistent and switch to using it [if jetty supports it](http://download.eclipse.org/jetty/stable-9/apidocs/org/eclipse/jetty/util/ssl/SslContextFactory.html#setKeyManagerPassword-java.lang.String-).

> Seems like dropping `wss.keypass` would simplify things

I've always felt this way as it feels rather silly using two separate replace statements in all of the scripts, but I haven't worked with enough 3rd party keystores to know how common this is.  I think we've one support ticket fix their problems by syncing the two passwords, which makes more sense since you've pointed this out.

For the lowest impact to the codebase without stripping granularity, I would add it to Jetty and keep it.

> if changed to gibberish there's no change to QZ Tray's behavior

Can you test `sslContextFactory.setKeyManagerPassword(trayProperties.getProperty("wss.keypass"));` in `PrintSocketServer` and see if it starts to behave as expected afterward?

**Comment by dsanders11** [comment]
@tresf, yes, adding that line causes QZ Tray to throw an exception on launch and enter an error state if `wss.keypass` is set to gibberish, but everything works OK if it is set to the same as `wss.storepass`, as expected.

Is there any benefit to having the two separate passwords, though? There's only a single key in the keystore, and the passwords are stored in the same properties file. I'm struggling to see a use case where there'd be a benefit in having them diverge. I believe the canonical reason for having them is so that access can be given to individual keys in a keystore without giving access to all the keys, but that doesn't have any benefit to QZ Tray since it is the owner and only user of the keystore, and it's only storing one key.

**Comment by tresf** [comment]
Thanks for testing.

The benefit would only be to third parties that have a keystore made by hand with non-matching passwords.  I do not have enough experience with this parties to speak on behalf, but an example is a Trusted RootCA Tomcat server key being repurposed for Jetty.

I favor the one-line approach as it costs the project less development time and less regression testing time.

**Comment by tresf** [comment]
Part of the luxury of installing (or reinstalling) software to thousands of computers is the comfort in knowing the software is installed the exact same way every time.

In the case of a default install (the vast majority of the QZ Tray users), we really don't want to preserve the properties file.

In the case of a print-server install, we do want to preserve the properties file.  Unfortunately a print-server and an `authcert.override` are not tied exclusively.

It can get worse.  In an environment that was once `community-mode` and has since paid a license, we don't want this `authcert.override` coming back as support issues for QZ.  We want to wipe this property out if it's not provided in the installer, which we [already allow through `ant`](https://github.com/qzind/tray/wiki/Compiling#advanced) leaving really the IP, password and a few others to remain the same when a trusted SSL cert has been provided.  I think this is a good idea.

Would it be sane to simply keep the properties file if-and-only-if a trusted SSL cert is provided, or is this a case of it being too late since the Windows installer has already blown it away? (we don't have this problem in Linux because [the installer itself can take the keygen command line options](https://qz.io/wiki/print-server#linux)).

Open to ideas, but I think this is a matter of coding to the exact use-case rather than trying to preserve a file that has no place being reused for 99% of installations.

**Comment by tresf** [comment]
**Edit:** TL;DR.  The original bug report is asking for SSL mode only, so that's what we'll code to.  It really limits the scope of this change.

**Comment by dsanders11** [comment]
> In the event a third party process for renewal is born (perhaps by you in 2 days 😃)

@tresf, I finally got a chance to loop back around to this, and that 2 day estimate turned out to be spot on. The longest bit was working with [`acme-python`](http://letsencrypt.readthedocs.io/projects/acme/en/latest/) as the documentation is a bit shallow in how to string things together to complete the full process, save the relevant in progress data, etc.

If you're interested you can find the relevant QZ code on my [`letsencrypt-renewal` branch](https://github.com/dsanders11/tray/tree/letsencrypt-renewal). It's built on top of another branch I have which adds the (no frills) ability for QZ to pull jobs from an HTTP queue. The Let's Encrypt relevant stuff starts at commit 12239a0d178a1372f6f9aaf123650dce996b06e2, which is also a generic change you may consider pulling which makes reloading the main server cleaner so it can pick up the new certs. The code is rough and may have sharp edges (and should be in a separate file), for example it has no regard for current connections or jobs so it will reload immediately when it gets a new cert and may cause a job to get lost.

The mechanism is fairly simple:

* Every 1 day (not currently configurable) open the keystore and check when the certificate expires. If it's within N days of expiration (configurable), attempt to renew it.
* To renew the certificate, contact a web server (configurable URL and credentials) and initiate the process
  * First send just a `GET` to receive a challenge (server has to be stateful and remember the challenge it sent)
  * Once the challenge is received, sign the challenge with the private key from the keystore, create a new key pair and CSR for the same domain name found in the existing certificate, and send the signed challenge, the CSR, and the original cert to the server
  * The server will verify that the original cert is from Let's Encrypt, that the CSR is for the same domain, and that the challenge was signed with the private key for the original cert. This proves to the server that the client has the private key for the original cert and it's safe to continue the process.
  * Server initiates HTTP challenge with Let's Encrypt, gets the CSR turned into a cert, and provides a URL for the client to get the new cert at
  * QZ checks the URL after 30 seconds (polling would be better) and if the process was successful finds the new cert there. It installs the new cert with the new private key it generated during the process into the existing keystore (and reuses the keystore password), then reloads. This process never touches the properties file so it avoids the original issue this was opened for, about properties getting blown away when swapping in new certs.

The process has basic auth checking throughout to make sure nothing nefarious happens, and the private keys are never sent over the wire, just a CSR and proof that it owns a private key. More security checks could be implemented on the server - check the original cert against a CRL, disallow certs past their expiration date, etc. If QZ fails to renew the cert it logs the error and will try again the next day.

The web server code (in Python) isn't too complex, mostly is just dealing with the Let's Encrypt servers. I can provide you with it as an example if you'd like to pursue this, but would take a little bit to pull just it (and it's Django code).

**Comment by tresf** [comment]
> starts at commit 12239a0, which is also a generic change you may consider pulling which makes reloading the main server cleaner so it can pick up the new certs. 

Sure, please submit a PR.  This would be a welcome addition.  What's the `StatisticsHandler` used for on your end?

> ability for QZ to pull jobs from an HTTP queue.

This sounds like something fairly sane to add but we'd have to also add the documentation to the API and wiki so this would be a bit more to setup.  We have a few clients that prefer to work this way for job queuing so we'd welcome a PR with this feature as well.

> To renew the certificate, contact a web server (configurable URL and credentials) and initiate the process

Thanks.  This is very nice work. I'm not sure if this feature will make it into mainline, we'll have to put some more thought into it.  We don't mind the application being used in this manner but it's not something we have intentions to offer support for to our clients for, so getting it through our own internal QA process would be difficult to justify the time for.

That said, we do test our print-server, and we do use letsencrypt for one of our test machines, but we use it with a plain Apache instance for now.

Since this bug report is about the `.properties` file which we still plan to address, I would recommend we track this feature in a dedicated bug report or Pull Request so that the information does not get forgotten on bug close.

**Comment by tresf** [comment]
@dsanders11 if interested, I'v added support for LetsEncrypt certificates into the `cert` branch on my fork.

https://github.com/tresf/tray/tree/certs

I have SSL reload working thanks to some Jetty improvements.

The syntax to install the cert is:

```bash
java -jar qz-tray.jar certgen --key privkey.pem --cert fullchain.pem
```

Internally, I'm using `certbot` for renewal.  This probably isn't ideal in your scenario, but was chosen out of simplicity.  I'd be happy to bring in the acme changes as well.

Note, thanks to Apple, cert renewal is a critical problem even for our internal certificates, so the expiration check is created with the hopes to be helpful for other services.

The code will be brought into 2.1 soon if it makes more sense to do the PR later.

Note, the properties should be preserved now on this branch, closing the original bug report.  I'd be happy to open a new one on ACME renewal if you wish.

**Comment by tresf** [comment]
@dsanders11 support for this has been officially added as of 873c0e8.  Ideas as to how to incorporate `authcert.override` without changing the default install behavior is appreciated.

**Comment by dsanders11** [comment]
@tresf, unfortunately I don't have time at the moment to catch-up on this. Glad to see you're continuing to improve QZ Tray though. 👍

**Comment by tresf** [comment]
> I don't have time at the moment to catch-up on this

No worries.  Well, we support a System property `trustedRootCert`, the old `authcert.override` is still supported, but deprecated but `override.crt` should work just fine now and be picked up automatically (and not be deleted on reinstall).

That said, I think we're good from the SSL perspective.  I invite a reopen if warranted.  Any bugs with the new implementation can be filed as dedicated reports.
