### ISSUE TITLE
Make qz.tools.hash Return A Promise

### ISSUE THREAD

**Issue by dsanders11** [qzind/tray#209]
If `qz.tools.hash` returned a promise, the dependency on `sha-256.js` would be replaceable with native support via [Web Crypto](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest). It's a bit messy due to the extra code needed to make a hex representation, but it's nice that it would drop the dependency for native support, for those who wanted to.

So, to move towards that end, `qz.tools.hash` would need to be made to return a promise. Since this would break the API for some users who used `setSha256Type`, `qz-tray.js` could check if the function set is a promise via `typeof data.then === 'function'` and if not, wrap it in a promise, maybe with a warning to console that in the future this auto-wrapping will be dropped.

**Comment by tresf** [comment]
Since hashing is already part of a promise chain, changing the logic internally to support both shouldn't be a problem; we could keep both without changing the API logic.  Eventually dropping `sha-256` (or equivalent) would be great.

What I'm curious about is if the promise and return type will eventually become the norm, since currently `sha-256,` `sha.js` and Node 6.5's native `crypto` don't.

From the compatibility chart, it also appears only Chrome (and thus Opera) have adopted this, so would it be worth waiting for wider adoption before coding against the API?

**Comment by dsanders11** [comment]
I've found that `developer.mozilla.org` is a great resource, but for some perplexing reason their compatibility charts are always woefully out of date. I use [caniuse.com](http://caniuse.com/) for more accurate compatibility. It's data for [Web Crypto](http://caniuse.com/#feat=cryptography) shows much higher adoption, including Microsoft Edge. It does have a note that it's hidden behind a prefixed name in Safari 10.1, although it seems to suggest it isn't in Safari 11 (I can't test, unfortunately), even though that contradicts it being behind a prefix in Safari Technology Preview, which should be newer than 11.

So yea, I believe it's got decent support these days.

> What I'm curious about is if the promise and return type will eventually become the norm, since currently sha-256, sha.js and Node 6.5's native crypto don't use this technique.

Feels like most new web specs these days use promises liberally, probably a concerted effort to keep things from blocking the UI.

**Comment by tresf** [comment]
Ouch: https://bugs.chromium.org/p/chromium/issues/detail?id=373032

**Comment by tresf** [comment]
Looks like Chrome blocks crypto.suble with non-localhost HTTP origins. This is a show stopper for the built-in API at least: https://bugs.chromium.org/p/chromium/issues/detail?id=373032

We can still wrap the promise functionality, but it won't ever be a built-in function if we can't use it on HTTP.

**Comment by dsanders11** [comment]
Not surprising, the train is heading to HTTPS everywhere and it isn't stopping. :-)

Understand the need to support HTTP, just the option of overriding it via `setSha256Type` to remove the dependency on `sha-256.js` is enough.

**Comment by tresf** [comment]
> the option of overriding it via `setSha256Type` to remove the dependency on sha-256.js is enough.

Since `setFooType` instantiates a class, `setFooPromise` sets a promise resolver, we would use `setSha256Promise` for consistency and `setSha256Type` would just be `wrap[ped] in a promise` as you've mentioned.

**Comment by tresf** [comment]
This feature will be publicly available in 2.0.5.
