### ISSUE TITLE
ESC/P isn't ESC/POS

### ISSUE THREAD

**Issue by tresf** [qzind/tray#210]
After some troubleshooting with a client, we've identified that our wiki, website, sample.html and codebase incorrectly uses `ESC/P` in place of `ESC/POS` code and code examples.  Although these languages are very similar, [`ESC/POS` is a variation of `ESC/P`](https://en.wikipedia.org/wiki/ESC/P) and uses many incompatible commands.

This is going to be some work to reverse, but here's the proposal:

* [x] @lite1979 will test and then change the wiki documentation to reference `ESC/POS` in title and API examples
* [ ] @klabarge will patch all instances of this wording on our site and samples
* [x] @tresf will patch the codebase

~~The plan is to phase out `ESCP` entirely and issue a soft console warning and select `ESC/POS` (`ESC_POS`) if used.  Internally to the codebase, we'll get ride of `ESCP` and instead map it functionally to a new value `ESC_POS`.  `ESC/P` (`ESC_P`) will be added as a new stub which will throw `UnsuportedOperationException` if provided.  Moving forward with `ESC/P` features, we'll use the version with the slash for the API and the version with the underscore internal to the Java application.~~

Since the image command is the only command that uses this, we'll simply keep the old one around but update our samples and documentation to use the new `ESCPOS`.

**Comment by jass-trix** [comment]
@tresf So does it means that ESCP = ESCPOS?

**Comment by tresf** [comment]
QZ Tray will treat them the same, but it's technically wrong.  ESC/P uses a different image syntax which we don't yet have coded but we'd welcome a PR for it.  ESC/POS is technically what we support in our codebase.  For 99% of users, `ESCPOS` is what should be provided and is backwards compatible with older QZ Tray versions.
