### ISSUE TITLE
ESC/POS raw printing right and left alignment

### ISSUE THREAD

**Issue by vijaythecoder** [qzind/tray#212]
How do I achieve table like structure with raw printing?  
![img_7052](https://user-images.githubusercontent.com/1809727/28242377-acfeb5de-69c7-11e7-802d-aab5f9d176bf.JPG)

I am having hard time getting text aligned to left, center and right on same line. Any help would be highly appreciated

**Comment by lite1979** [comment]
You have to use math to align the columns in a higher level language. 

You cannot issue justification commands on the same line in ESC/POS, so you must determine the number of characters in your line and add/subtract the appropriate number of spaces to fill the gaps for alignment.

Here is an example in the answer to a similar question:

https://stackoverflow.com/questions/15509437/opposite-of-n-esc-pos-and-php-right-left-justify-on-the-same-line

**Comment by lite1979** [comment]
Closing as this is a limitation of the raw markup language ESC/POS, and not an issue with QZ-Tray. :)

**Comment by talhamughal10** [comment]
Hi can any one tell me how can i center the image in the receipt form.
i want my image to be in the center. currently it is left aligned.

 i am trying to use this command to center the image.public static byte[] ESC_Align = new byte[] {0x1b, 0x61, 0x01 };
In addition i am unable to center the bar code as well.
Any help would be appreciated.

**Comment by lite1979** [comment]
Use the center align command:

'\x1B' + '\x61' + '\x31'
