### ISSUE TITLE
Print to multiple printer at time

### ISSUE THREAD

**Issue by riyask** [qzind/tray#213]
I have developed a POS for Restaurant, It will have multiple kitchen, When order different item, each item will print on respective kitchen as KOT. How it is possible. Please assist me.

**Comment by tresf** [comment]
You may print your content to any printer you wish.

If you have a defined number of printer, you should hard-code the chain request:
https://qz.io/wiki/2.0-raw-printing#chaining-requests

If you have an undefined number of printers, you should use a promise loop:
https://qz.io/wiki/2.0-raw-printing#promise-loop

Raw examples are provided.  If you require Pixel examples, replace the word "Raw" with the word "Pixel" in the URL.
