### ISSUE TITLE
Ability to disable logs

### ISSUE THREAD

**Issue by tresf** [qzind/tray#214]
Some environments have to protect sensitive information which has been processed by QZ Tray and require the ability to suppress log output through a configuration option.

**Comment by jwalstrum** [comment]
Hi, Tres.

We've emailed a bit recently. I'm with JMT Technology Group, you've been working with us on MAC filtering issue. Recently, same client has asked us to verify that logging is disabled. Is there a way to do that?

Thanks,
John

**Comment by tresf** [comment]
Not yet.  This is milestoned for a future release but we'll see if we can get it bumped up.

**Comment by tresf** [comment]
Temporary workaround:

**Windows**
```bat
rmdir /s /q "%appdata%\qz"
mkdir "%appdata%\qz"
mklink "%appdata%\qz\debug.log" NUL:
```

**Linux**
```bash
rm -rf "$HOME/.qz/"
mkdir "$HOME/.qz/"
ln -s /dev/null "$HOME/.qz/debug.log"
```

**MacOS**
```bash
rm -rf "$HOME/Library/Application Support/qz/"
mkdir "$HOME/Library/Application Support/qz/"
ln -s /dev/null "$HOME/Library/Application Support/qz/debug.log"
```
