### ISSUE TITLE
Setting page size in HTML/PDF/Image

### ISSUE THREAD

**Issue by klabarge** [qzind/tray#22]
QZ Tray 2.0-RC4
Windows 10

I have only tested this in Windows so far, I will report back with Mac/Linux results.

* In RC3, setting the page size for HTML, PDF, and Image printing worked great.
* In RC4, the page size seems unaffected in HTML and Image printing. The page size for PDF's seems to work, but the PDF is cut off.

*This was tested using the `sample.html` page.  The only options that are not default are `width` and `height`.*

Below are my results in RC3 and RC4 when trying to force `size: {width: 5, height: 4};`

### HTML

* These images have been scaled to 50% their original size
* It's hard to see, but notice that the asterisks are even in different positions
 
![image](https://cloud.githubusercontent.com/assets/12505463/14301511/7aba03b0-fb66-11e5-923a-303e1f53176c.png)

### PDF

* These are the original sizes, 100%

![image](https://cloud.githubusercontent.com/assets/12505463/14301680/ce7c2dec-fb67-11e5-956b-ec700e19dad2.png)

### Image

* These images are scaled to 50% of their original size

![image](https://cloud.githubusercontent.com/assets/12505463/14301752/52404974-fb68-11e5-9bb9-a39ad5e6a764.png)

**Comment by bberenz** [comment]
I had stopped explicitly setting the paper size after moving to a different way to set drawable area. Forgetting that printers like these actually change to it. Added it back in 9f97ad47213793c66251f76b90d6ae9dc917faec.

**Comment by bberenz** [comment]
>It's hard to see, but notice that the asterisks are even in different positions

This is related to changes in how the html view sizes content, rather than the change in paper size. So you should still see this difference.

**Comment by klabarge** [comment]
PDF's seem to still be getting chopped off.  This is happening in both Windows and Mac.

Setting (inches)  `size: {width: 8, height: 9};` with no other options results in the bottom of the PDF to be chopped.  Testing in earlier versions using smaller dimensions worked.

### Windows

*This size has been scaled to 75%*
 ![image](https://cloud.githubusercontent.com/assets/12505463/14369307/f85681b8-fcf1-11e5-8b54-018b6aa785e3.png)

### Mac

*This has been scaled... "zoomed out twice"*
![image](https://cloud.githubusercontent.com/assets/12505463/14369417/d7a41ce0-fcf2-11e5-8581-781ff8023f06.png)

**Comment by klabarge** [comment]
I may have used an unreliable printer... Using PDF Architect as my virtual printer I get different results, however the bottom is still slightly cut off.

![image](https://cloud.githubusercontent.com/assets/12505463/14371254/dab1aca2-fd03-11e5-9123-fabd27014cae.png)

**Comment by tresf** [comment]
Is `8inx9in` a valid page size?  Perhaps testing with `Letter` and `A4` is a better test case.

With RC4, we rasterize by default, so keep that in mind when comparing.  I can't remember if RC3 did or did not rasterize by default, but assuming it does not, the results would be more accurate by unchecking the new `rasterize` option when comparing the odd page dimensions.

**Comment by klabarge** [comment]
The results are the same with and without `rasterize`

Using A4 (8.3 x 11.7) does print properly.  I thought custom page sizes were fully supported.  If QZ Tray is just "accepting" of custom page sizes, this issue is void and can be closed.

**Comment by bberenz** [comment]
At best QZ is just accepting of custom sizes.  Especially for pdfbox, which internally uses the MediaSize class for layouts, and thus is restricted to the page sizes internal to the java print libraries.

**Comment by tresf** [comment]
> At best QZ is just accepting of custom sizes. Especially for pdfbox, which internally uses the MediaSize class for layouts, and thus is restricted to the page sizes internal to the java print libraries.

We'll close this out for now then.  I don't like this at all... it seems like a pretty big gap for PDF printing but can be tracked separately.
