### ISSUE TITLE
2.1 sporadic HTML behavior when modifying printer preferences

### ISSUE THREAD

**Issue by klabarge** [qzind/tray#225]
Using the latest compiled 2.1 branch on Windows 10 (I used [these installers](https://github.com/klabarge/tray/releases/tag/v2.1))

HTML printing has sporadic behavior when the printer preferences , specifically paper size, are modified. The issues are resolved once QZ Tray is restarted.

1. Sometimes the printout is blank
1. Two pages are always printed, when one is expected

#### Steps to Reproduce
1. Connect to sample.html bundled with the 2.1 installer (linked above) and print (I used PDFCreator)
   * Note the expected/desired outcome. Perform this several times for bench marking. All printouts are identical
1. Go to Devices and Printers, Right click the printer, Printing Preferences, Advanced
1. Change Paper size from Letter to A4
1. Print again from the sample.html page using print HTML
   * Observe the blank(s) printed
1. Print a second time from the sample.html using Print HTML
   * Observe multiple pages printed
1. Restart QZ Tray and print again
   * Observe no blank pages and no additional pages

**Comment by Vzor-** [comment]
I can reproduce this issue with the bin you provided, however I cannot with the current code base. We may have accidently fixed this one already. @klabarge Could you retest this the current 2.1 branch?

**Comment by tresf** [comment]
The desktop app may be using a different JVM.  @vzor-, can you verify your JVMs before we retest?

**Comment by tresf** [comment]
> I retested with a full ant nsis install. The issue still did not present.

👍
