### ISSUE TITLE
HTML content scaling

### ISSUE THREAD

**Issue by klabarge** [qzind/tray#231]
There's a bug with HTML Printing in 2.1 when switching between `rasterize: false` and `rasterize: true` during print jobs.

QZ Tray Version: [2.1.0-RC2](https://github.com/tresf/tray/releases/tag/v2.1.0-RC2)

This issue was exposed when having issues with an HTML page scaling all the way to the right margin, but following the below steps will reproduce a similar issue with the sample HTML content.

Let me know if you would like an HTML sample for reproducing the horizontal scaling issue.

1. Print HTML with the below config, note result
   `var config = qz.configs.create('PDFCreator',{rasterize: false});`
   ![image](https://user-images.githubusercontent.com/12505463/30141697-051b1ea4-934b-11e7-8fa8-41dcbc770a11.png)

1. Change config to `rasterize: true` and observe different sizing
   `var config = qz.configs.create('PDFCreator',{rasterize: true});`
   ![image](https://user-images.githubusercontent.com/12505463/30141746-42198bb0-934b-11e7-9830-c0e59146f29c.png)

1. Change config back to `rasterize: false` and observe sizing matches the print with `rasterize: true`, and is different than the first print, despite identical `configs`
   `var config = qz.configs.create('PDFCreator',{rasterize: false});`
    ![image](https://user-images.githubusercontent.com/12505463/30141793-93d2fffe-934b-11e7-8fd2-42dd6b4eae07.png)

1. If you restart QZ Tray, the size will be the same as in print 1.

**Comment by Vzor-** [comment]
I can reproduce this issue with the bin provided, however I cannot with the current code base. It looks like we accidentally fixed this one as well.
