### ISSUE TITLE
Untrusted website after successful signing 

### ISSUE THREAD

**Issue by guncebektas** [qzind/tray#233]
Hello, 

I have signed it with openssl and it's working on `startConnection()`
![image](https://user-images.githubusercontent.com/1319474/30252161-cdf7243a-9675-11e7-92d4-060f07155d90.png)

But when i try to find printers, the pop up appears again.
![image](https://user-images.githubusercontent.com/1319474/30252170-efb8dd48-9675-11e7-9dfa-b63b7d0dfbfd.png)

I know i have to sign every requests. I think, all requests are using `qz.security.setSignaturePromise` to complete signing, am i right? What should i do?

**Comment by onurguzel** [comment]
> I know i have to sign every requests. I think, all requests are using `qz.security.setSignaturePromise` to complete signing, am i right? What should i do?

Yes, you need an endpoint to give you signatures. You also need to `qz.security.setCertificatePromise()` to fetch the public key.

More info is available on https://qz.io/wiki/2.0-signing-messages

By the way, for getting answers faster, you may want to consider using [Community Support](https://qz.io/support/).

**Comment by guncebektas** [comment]
@onurguzel i'm currently fetching public key with `qz.security.setCertificatePromise()` and i'm able to sign it. My domain name is in the list of "Alloweds" but somehow it's not working on other functions like `findPrinters()`

![image](https://user-images.githubusercontent.com/1319474/30269810-eecf860c-96f2-11e7-8022-1206c649e1fb.png)

**Comment by tresf** [comment]
> i'm currently fetching public key with qz.security.setCertificatePromise()

You should be fetching the `digital-certificate.txt` with that.  The public key is not used in signing.

> I have signed it with openssl and it's working on startConnection() ... but somehow it's not working on other functions like findPrinters()

As @onurguzel states, the signature needs to be correct.  The initial connection uses the certificate.  `findPrinters()` use the signature.  Since your certificate says "Verified by QZ Industries, LLC`, that means you have premium support.  Please contact `support@qz.io` and we can remote in and walk you through this.

**Comment by guncebektas** [comment]
Hi, @tresf . I'm using digital-certificate which is starting with `-----BEGIN CERTIFICATE-----` for `setCertificatePromise` and private key which is starting with` -----BEGIN RSA PRIVATE KEY-----` for `setSignaturePromise` It seems the signing is wrong, am i right? 

I didn't pay for premium support.

**Comment by tresf** [comment]
> I didn't pay for premium support.

I'm afraid we do not offer signing assistance for non-supported clients.

> It seems the signing is wrong, am i right?

Correct.

**Comment by tresf** [comment]
Closing as `invalid` as there do not seem to be any code defects in the product.  If you change your mind about premium support, please reach out through the ordinary channels.

**Comment by guncebektas** [comment]
I solved my problem and want to share it here. Meteor.js users can use this code blog. As you mentioned before there isn't any problem on 
`setCertificatePromise` and I focused on `setSignaturePromise`

client.js
```
qz.security.setSignaturePromise(function(toSign) {
  return function(resolve, reject) {
    HTTP.call('get', 'http://****.com/sign-message.php?request='+ toSign, function(e,r) {
      resolve(r.content);
    });
  };
});  
```

And add `header("Access-Control-Allow-Origin: *");` to allow CORS into sign-message.php

**Comment by tresf** [comment]
@guncebektas thanks for the feedback.  It appears the issue you were having was specific to the JavaScript library and the CORS settings (fetching the signing function across domains).  Neither of these are typical problems, but we do appreciate you sharing your troubleshooting and resolution.

**Comment by jibraniqbal666** [comment]
> I solved my problem and want to share it here. Meteor.js users can use this code blog. As you mentioned before there isn't any problem on
> `setCertificatePromise` and I focused on `setSignaturePromise`
> 
> client.js
> 
> ```
> qz.security.setSignaturePromise(function(toSign) {
>   return function(resolve, reject) {
>     HTTP.call('get', 'http://****.com/sign-message.php?request='+ toSign, function(e,r) {
>       resolve(r.content);
>     });
>   };
> });  
> ```
> And add `header("Access-Control-Allow-Origin: *");` to allow CORS into sign-message.php

@guncebektas 
i am also this exact problem, can you help, i have tried using fetch, axios, it just show that second unverified dialog on calling any privileged function.

**Comment by klabarge** [comment]
> i am also this exact problem, can you help, i have tried using fetch, axios, it just show that second unverified dialog on calling any privileged function.

@jibraniqbal666 You are getting a CORS error?

If you are a premium client, please email support@qz.io and we will assist you with signing messages.

Please email us code snippets of:

1. `setCertificatePromise();`
1. `setSignaturePromise();`
1. server-side signing function (e.g. `sign-message.php`)
1. Any browser console log errors

For reference, here's our tutorial: https://qz.io/wiki/2.0-signing-messages
