### ISSUE TITLE
Error JSONObject["data"] is not a JSONArray (Microsoft Edge only)

### ISSUE THREAD

**Issue by s-berney** [qzind/tray#235]
Hello,

We have an issue on Microsoft Edge (v40) when launching the print, we got this error :
image
![image](https://user-images.githubusercontent.com/10452430/30473613-4986e354-9a01-11e7-8648-cb8757f15ba8.png)

Code is :
```
        var config = qz.configs.create(printer_name, {
          margins: { top: 0, right: 0, bottom: 0, left: 0 },
          size: {width: 210, height: 297}, units: 'mm', 
          interpolation: "nearest-neighbor",
          scaleContent: "false",
          orientation: 'portrait',
          copies: 1
        });
        var data = [{ 
          type: 'pdf', 
          data: getPath() + "/temp/file16201.pdf"
        }];
        qz.print(config, data).catch(function(e) {
          console.error(e);
          alert('Error printing:\n\n\t' + e);
        });
```
On Firefox, all is working...

**Comment by tresf** [comment]
@s-berney I tried to reproduce your issue and was unable to.

The following code prints just fine with QZ Tray 2.0.4 on Edge 50.  Is there anything special about your setup that could be causing this?

```js
var config = qz.configs.create("Microsoft XPS Document Writer", {
   margins: { top: 0, right: 0, bottom: 0, left: 0 },
   size: { width: 210, height: 297 },
   units: 'mm',
   interpolation: "nearest-neighbor",
   scaleContent: "false",
   orientation: 'portrait',
   copies: 1
});

var data = [{
   type: 'pdf',
   data: getPath() + "/assets/pdf_sample.pdf"
}];

qz.print(config, data).catch(function(e) {
   console.error(e);
   alert('Error printing:\n\n\t' + e);
});
```

**Comment by s-berney** [comment]
Here's the log trace on QZ.io :
![image](https://user-images.githubusercontent.com/10452430/30490710-1a41e6ae-9a3b-11e7-9032-8ece3d93de0b.png)

We had same problem on IE10 on a different computer...

**Comment by s-berney** [comment]
For information, all was working fine with 1.9.4 plugin version - this error happend after migrate to v2 !

**Comment by tresf** [comment]
@s-berney this may be an unhandled character in your printer name.  See how it overflows?  What happens if you use a different printer name, does it fix it?

**Comment by s-berney** [comment]
It's "overflow" because of the space on the name, but with Firefox (on the same computer) it's working fine...
And error talk about "data" object...

**Comment by tresf** [comment]
Thanks for the information.  Can you please reinstall Java 8 from offline mode and see if that corrects the problem?  The data should be getting prepared the same and I cannot find a problem with the data you are sending.  If that doesn't work, I'd like to gain access to the offending workstation to see where the malformatted data is originating from.

**Comment by tresf** [comment]
@s-berney I'm going to close this issue out as it is not reproducible on two test PCs running Windows 10, QZ Tray 2.0.4 and the latest version of Java 8u144 64-bit.

Please post any updates to the issue here.
