### ISSUE TITLE
Printer prints code instead of EPL commands

### ISSUE THREAD

**Issue by pep108** [qzind/tray#245]
I'm using a Zebra LP 2844 to print labels. I have successfully printed EPL using the code in the sample, however, if I remove the image and use the following printData, just the code is printed on the label.
```js
var printData = [
            '\nN\n',
            'q609\n',
            'Q203,26\n',
            'B5,26,0,1A,3,7,152,B,"1234"\n',
            'A310,26,0,3,1,1,N,"SKU 00000 MFG 0000"\n',
            'A310,56,0,3,1,1,N,"QZ PRINT APPLET"\n',
            'A310,86,0,3,1,1,N,"TEST PRINT SUCCESSFUL"\n',
            'A310,116,0,3,1,1,N,"FROM SAMPLE.HTML"\n',
            'A310,146,0,3,1,1,N,"QZ.IO"\n',
            '\nP1,1\n'
        ];
```

Is this a bug, or is there something that I'm missing? Either way, I believe the answer could improve the documentation.

**Comment by tresf** [comment]
Which OS and which driver?  The ZDesigner driver for Windows is usually very good at detecting the print flavor (Raw vs. Pixel), but you can force the raw language by following this guide:

https://qz.io/wiki/setting-up-a-raw-printer-in-windows

There are some bugs with certain label sizes and printer models that can be exposed by EPL commands, but the symptoms are different (bad EPL commands usually cause the label to print half way or not at all).

**Comment by pep108** [comment]
@tresf thanks for your feedback. I'm on OSX which seems to partially limit the capabilities of the printers. I did solve the problem by switching the CUPS driver to the raw driver.

**Comment by lite1979** [comment]
Please create a separate queue for the printer following the instructions
below:

https://qz.io/wiki/setting-up-a-raw-printer-in-osx

**Comment by CindyLulu** [comment]
Thanks @lite1979 , I've printed it correctly now!
