### ISSUE TITLE
Non-rasterize to honor rendering hints

### ISSUE THREAD

**Issue by tresf** [qzind/tray#249]
Per https://issues.apache.org/jira/browse/PDFBOX-2450, we should be able to pass on rendering hints to the printer driver.  We do this for `rasterize: true` (when we turn the PDF into an intermediary image) but we don't do this for `rasterize: false` which is faster and much higher quality.

**Comment by bberenz** [comment]
After looking into this a bit further I've a couple concerns:
1. We don't set rendering hints for any pdf, rasterized or not (both are internal to pdfbox). 
2. The linked pdfbox report was closed as not fixed, they still hardcode their renderinghints internally

**Comment by tresf** [comment]
@bberenz we can test against various hardware to see what happens.  Can we have some prototype code to test against and then we can determine if there are serious regressions?

I understand the bug report wasn't conclusive to that particular hardware/driver combination.  It was provided more as evidence that PDFBOX should support it.  There is a use-case we're trying to resolve where a PDF barcode is unreadable by a barcode scanner unless we use the new rasterize-raw feature in 2.1.  If we can provide rendering hints to fix this, the print will be much faster.

**Comment by bberenz** [comment]
So I tried to setup some code that would set rendering hints on the graphics object for pdf printing, but there's two related issues that prevent it from doing anything.
The first is that for rasterized prints, pdfbox [creates and uses](https://github.com/apache/pdfbox/blob/2.0.8/pdfbox/src/main/java/org/apache/pdfbox/printing/PDFPrintable.java#L180) a new graphics object _during_ printing, so we have no way to alter the rendering hints on the graphics object actually being used.
The second is that for any graphics object used during printing, it goes through the PageDrawer class, which [applies its own rendering hints](https://github.com/apache/pdfbox/blob/2.0.8/pdfbox/src/main/java/org/apache/pdfbox/rendering/PageDrawer.java#L171-L179) that would override the ones we care about for precise scaling.

> unless we use the new rasterize-raw feature in 2.1

I have no idea what you are referring to here. Do you mean the non-rasterized pdf printing? That should be an option in 2.0 as well, just not the default option.

**Comment by tresf** [comment]
I'm closing this as `wontfix` for now.  It's not practical or feasible at this time.

**Comment by tresf** [comment]
@bberenz just got this new information from PDFBOX.  Should we reopen this?  https://issues.apache.org/jira/browse/PDFBOX-4435?focusedCommentId=16747031&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16747031
