### ISSUE TITLE
Kubuntu 16.04 Firefox SSL

### ISSUE THREAD

**Issue by tresf** [qzind/tray#250]
When reinstalling QZ Tray on Kubuntu 16.04, SSL in Firefox breaks.

During troubleshooting, killing java (e.g. `pkill -9 java`) and reinstalling seems to fix the issue, but it is uncertain why Java is not being killed through the installer.

@lite1979 can you please reproduce.

**Comment by lite1979** [comment]
I cannot reproduce using Ubuntu 16.04 with Oracle Java.

Re-installing QZ-Tray does give an error if Firefox is left open, but after restarting Firefox, SSL connection to https://demo.qz.io works fine.

I will attempt to reproduce with Kubuntu 16.04 and Oracle Java.

**Comment by lite1979** [comment]
After installing and updating Kubuntu 16.04.3, adding the Oracle Java ppa and installing QZ-Tray, I reinstalled QZ-Tray 2.0.4 and could not connect to wss until restarting Firefox.  After restarting Firefox, QZ-Tray works as expected when visiting https://demo.qz.io

I believe this is normal behavior, and a restart of Firefox is always recommended after installation of QZ-Tray.

**Comment by tresf** [comment]
Will close as invalid then.  If this resurfaces, we can reopen, thanks for testing.
