### ISSUE TITLE
macOS interpolation

### ISSUE THREAD

**Issue by klabarge** [qzind/tray#256]
* `nearest-neighbor` does not appear to be honored when using `rasterize: false`

**OS:** macOS Sierra
**QZ Tray:** Tested using [2.0.5 RC1](https://github.com/tresf/tray/releases/tag/v2.0.5-RC1) and 2.0.4
**Code:** sample.html `printImage()` function

Looks similar to issue #38 

**`nearest-neighbor` + `rasterize: true` (macOS)**

![screen shot 2017-11-15 at 10 16 18 pm](https://user-images.githubusercontent.com/12505463/32872067-a4a2dce4-ca52-11e7-8e1a-8c837441ee34.png)

**`nearest-neighbor` + `rasterize: false` (macOS)**

![screen shot 2017-11-15 at 10 18 30 pm](https://user-images.githubusercontent.com/12505463/32872114-f1d8fb92-ca52-11e7-9091-49fe908ac2f4.png)

**`nearest-neighbor` with `rasterize: true` and `false` look identical on Windows 10**
![image](https://user-images.githubusercontent.com/12505463/32872425-a2bc03a4-ca54-11e7-984c-0bfa5f26f5b0.png)

**Comment by tresf** [comment]
This will have to be slated for 2.0.6.  Thanks for reporting.

**Comment by klabarge** [comment]
> nearest-neighbor with rasterize: true and false look identical on Windows 10

This may be an invalid test as described in bug #257, `rasterize: false` results in a similar, pixelated image in Windows 10

**Comment by tresf** [comment]
@bberenz I believe the problem stems from here... 

https://github.com/qzind/tray/blob/2.0/src/qz/printer/PrintOptions.java#L234-L236

If I switch the logic to this, the bug goes away.

```diff
-        if (psOptions.isRasterize() && psOptions.getDensity() == 0) {
+        if (psOptions.getDensity() == 0) {
             psOptions.density = defOptions.density;
         }
```

@bberenz any ideas?

**Comment by bberenz** [comment]
The problem with that logic change is it just forces raster to be true, which we know to work.

Given that this is html printing, its possible that its down the way the html interpreter on macOS handles image scaling. We get no control over how that handles the images, but raster turns it into an image at its normal size which we then control how the scaling works. The windows variant of this issue could be the same cause.
Have we tested this with CSS scaling properties in the html itself yet?

**Comment by tresf** [comment]
@bberenz this bug is for `printImage()`. :D

**Comment by bberenz** [comment]
You are right, that makes this simpler. All images should always be rasterized anyways, so 3b8789935c0fae769f1db5e41329fcba702b6a93 will ensure that is enforced.

**Comment by tresf** [comment]
Tested, fixed!
