### ISSUE TITLE
Image becomes pixelated when rotating

### ISSUE THREAD

**Issue by klabarge** [qzind/tray#26]
Tested on Windows 10 using the `sample.html` page

When I give an image a rotation of 15 degrees, the image becomes pixelated.

### Original Image

![image](https://cloud.githubusercontent.com/assets/12505463/14339111/15150bc4-fc4a-11e5-9943-782bbe5098d0.png)

### Rotated Image

![image](https://cloud.githubusercontent.com/assets/12505463/14339123/319b8e12-fc4a-11e5-8b5f-35c15aa6606e.png)

**Comment by bberenz** [comment]
The the image rendering on rotation now responds to the `interpolation` field. So pixelated is still possible if desired.

**Comment by tresf** [comment]
> responds to the `interpolation` field

:+1: 

Great, as we may need this for barcodes, etc.  Much obliged.

**Comment by klabarge** [comment]
Below is the result when using the default `interpolation`. It seems to come out partially pixelated (but different than `nearest-neighbor`)

![image](https://cloud.githubusercontent.com/assets/12505463/14413522/a7224a9c-ff4a-11e5-8055-9e7e14cbef47.png)

Specifying `nearest-neighbor` does work, though.

![image](https://cloud.githubusercontent.com/assets/12505463/14413529/f28e5480-ff4a-11e5-8598-81477119628a.png)

**Comment by tresf** [comment]
The behavior is very close.  Probably a small setting we're missing.  At a glance, the only thing i can see happening incorrectly is the blending on the outer pixels seems to be aliasing whereas the rest of the inner pixels are what we'd expect.

Here's a comparison of Gimp vs. QZ:

![image](https://cloud.githubusercontent.com/assets/6345473/14415272/23dabd42-ff6b-11e5-8e34-8ec3cce5358f.png)

**Comment by tresf** [comment]
After reading a bit more on this, it appears that rotation inherently requires something called "extrapolation", where the `VALUE_INTERPOLATION_BILINEAR` must make an assumption about what the pixels beyond the edge of the image are.

In the event of QZ, I have the feeling that the rotation assumes the pixels beyond the edge are the same color as the edge pixels (black) whereas GIMP assumes they're either white or clear.

Here's a mockup of what I believe is happening.... 

![image](https://cloud.githubusercontent.com/assets/6345473/14415554/8b134ca6-ff6e-11e5-8495-25bdd7ca739a.png)

As can be observed by the inner pixels, the blending is correct when Java knows black is bordered with white.

@bberenz do you think there's a way of telling the graphics object to use white or transparent by default?

![image](https://cloud.githubusercontent.com/assets/6345473/14415621/15824a68-ff6f-11e5-999c-f860443805b5.png)

**Comment by bberenz** [comment]
> do you think there's a way of telling the graphics object to use white or transparent by default? I'd rather not paint a huge white border around it prior to rotating, if possible.

I couldn't find anything to this effect, but I did happen upon a work-around from stackoverflow, using the image as a rectangle texture.

**Comment by klabarge** [comment]
Tested on all platforms:+1:
