### ISSUE TITLE
Performance issues with large raw files

### ISSUE THREAD

**Issue by tresf** [qzind/tray#263]
Large raw files (e.g. > 3MB) cause performance issues with QZ Tray.

1. QZ Tray currently turns all web requests into a Java `String`, which is taxing on memory for large chunks of data.  This affects large raw requests specifically since the data is often sent in raw or base64 format and must live internally as `String` storage.
2. This issue is made worse when QZ Tray makes a copy of the raw data during processing, such as signature validation.
3. For Base64 requests, QZ Tray makes yet another copy of the data from Base64 to String during Base64 conversion.  Java provides no direct way to free unused String objects in memory, it uses a Garbage Collector for memory management and clears data as it deems necessary.
4.  Some advanced operations - such as raw EPL/ZPL/ESCPOS image injection cause Strings to be copied as well.

To illustrate how this all adds up, here are some memory benchmarks using QZ Tray 2.0.5 on Java 8 and Windows 10 for printing ~3MB raw text data:

| Printing Technique | Memory Utilized |
|----------------------|-------------------|
| `type: "raw", format: "base64"` | 170MB |
| `type: "raw", format: "xml"`| 90MB |
| `type: "raw", format: "file"` | 70MB |

In all cases, the Java Garbage Collector eventually cleans up the memory, but this can be quite alarming to a developer or support personal, especially for a small, 3MB file.

Currently, the recommended technique to mitigate this overhead is to use the `file` URL format for printing raw files, but this is still inefficient from a memory perspective.

The proposed technique is to offer a `direct` printing mode where a raw file can be sent directly to the printer using a Java `InputStream`.

```java
InputStream stream = new URL("file://my_large_raw_file.txt").openStream();
SimpleDoc doc = new SimpleDoc(stream, DocFlavor.INPUT_STREAM.AUTOSENSE, null);
```

| Printing Technique | Memory Utilized |
|----------------------|-------------------|
| `type: "direct", format: "file"` | *3MB |

*\*Not yet available*

This API change will be added to a future version as a viable workaround for high-memory utilization for large raw files.  Some features -- such as raw image generation -- will be unavailable with `direct` mode.

**Comment by lite1979** [comment]
Testing the print-direct branch (type: 'raw' in this branch was already tested and yielded identical results to 2.0.5 stable)

https://github.com/qzind/tray/compare/print-direct


Memory numbers are RAM usage by QZ-Tray/Java  from OS monitoring tools
    
    Windows 10, raw to PDFCreator
    format: file (.ps file)
    startup:  231 MB
    first print:  370MB

    Windows 10, direct to PDFCreator
    format:  file (.ps file)
    startup:  231MB
    first print:  241MB

    Windows 10, raw to PDF Creator
    format:  base64
    startup:  229MB
    first print:  419MB

    Windows 10, direct to PDF Creator
    format:  base64
    startup:  227MB
    first print:  412MB

**Comment by lite1979** [comment]
Mac OS to PDFWrite:

type: 'raw'
format:  'file'
Before:  266MB
After:  332MB

type: 'direct'
format: 'file'
Before:  270MB
After:  280MB

type: 'raw'
format: 'base64'
Before:  270MB
After:  280MB

type: 'direct'
format: 'base64'
Before:  267MB
After:  343MB

**Comment by lite1979** [comment]
type:  'raw'
format:  'file'
Before:  268MB
After:  408MB

type:  'direct'
format:  'file'
Before:  268MB
After:  277MB

type:  'raw'
format:  'base64'
Before:  267MB
After:  464MB

type:  'direct'
format:  'base64'
Before:  267MB
After:  451MB

Re-did the Mac tests since the machine died shortly after finishing last night's tests(bad A/C outlet - running laptop on battery power) .  These results looks closer to the Windows results.
