### ISSUE TITLE
2.0.5 Update causes pdfs to print rotated 90 degrees

### ISSUE THREAD

**Issue by CCooperBH** [qzind/tray#264]
After updating to 2.0.5, pdfs are rotating 90 degrees where they were not with 2.0.4. This affects all printers on the host.

**Comment by tresf** [comment]
2.0.5 specifically fixed rotation issues with PDFs.  Can you send the configuration and a sample PDF?  Disabling `orientation` on QZ Tray versions >= 2.0.5 should help as they're configured to print with `auto` rotation now.

**Comment by tresf** [comment]
See also https://github.com/qzind/tray/issues/158

**Comment by CCooperBH** [comment]
scaleContent: "false" is the only config option.

[samplePdf.pdf](https://github.com/qzind/tray/files/1612733/samplePdf.pdf)

**Comment by tresf** [comment]
This document properly prints in portrait mode for me.

![image](https://user-images.githubusercontent.com/6345473/34688369-e00aa260-f47f-11e7-97f6-4d4e9149eceb.png)

I'm using `sample.html` without any changes printing to a virtual printer "PrimoPDF".

Are you printing to portrait or landscape oriented paper?  Can you offer some information to help reproduce?

1. OS
2.  Printer make/model
3. Paper/label/receipt page size

**Comment by tresf** [comment]
Closing due to lack of response from OP.
