### ISSUE TITLE
Decimal points in jobName, virtual printers macOS

### ISSUE THREAD

**Issue by klabarge** [qzind/tray#270]
There doesn't appear to be any issue with the way QZ Tray handles decimal points (observing the printer queues, they are properly sent to the printer) but virtual printers seem to vary in the way they handle writing a decimal point to the file system.

Should decimal points in `jobName` be converted to an underscore ("_")?

**CUPS-PDF for OS X:** If there are less than 4 alphanumeric characters following a decimal in `jobName`, characters after the decimal are stripped.

   * `jobName: '123.456'` on the file system will be "123.pdf"
   * `jobName: '123.4567'` on the file system will be "123_4567.pdf"

**RWTS PDFCreator:** All characters after a decimal point are stripped

Windows printers seem to handle this fine.

**Comment by tresf** [comment]
> Should decimal points in jobName be converted to an underscore ("_")?

I can see the use-case, but this seems like an upstream bug.  The best we could do is detect one of the PDF drivers in use and hack a work-around.  2.1 has the ability to detect the underlying driver although I'm inclined to say `wontfix` and just reference this issue if anyone runs into a similar problem.

**Comment by tresf** [comment]
Sorry, is this for all CUPS job names, not just PDFs?

**Comment by klabarge** [comment]
> Sorry, is this for all CUPS job names, not just PDFs?

This effects HTML and Images as well, if that is what you're asking.

I only tested against PDF printers, so that's where the PDF extension came from. The actual job name in the printer queue looks correct while it is being spooled.

**Comment by tresf** [comment]
> The actual job name in the printer queue looks correct while it is being spooled.

Thanks for clarifying.  So the bug's with the virtual driver.  Normal prints are not affected.

**Comment by tresf** [comment]
Reproduced.  This is a "feature" of CUPS-PDF, as illustrated in `/etc/cups/cups-pdf.conf`.

```properties
###########################################################################
#                                                                         #
# Filename Settings                                                       #
#                                                                         #
###########################################################################

### Key: Cut
##  removing file name extensions before appending .pdf to output
##  extensions will only be removed if _both_ the following criteria are met:
##   - the extension (w/o the dot) is not longer than <Out> characters
##   - the remaining filename has a minimal length of 1 character
##  set Cut to -1 in order to disable cutting
##  recommended values: pure UNIX environment : -1
##                      mixed environments    :  3
### Default: 3

Cut 3
```

Setting this to `-1` will suppress this symptom you are seeing.

```bash
lp -t "TEST PRINT.foo" /Applications/QZ\ Tray.app/demo/assets/pdf_sample.pdf
```

Set to -1 yields:  `job_1-TEST_PRINT_foo.pdf`
Set to 3 yields:  `job_1-TEST_PRINT.pdf`

Closing as this is configurable on the client-side if needed.  Please open a bug report with CUPS-PDF if you believe this default behavior is undesired. :)
