### ISSUE TITLE
The demo website is down 

### ISSUE THREAD

**Issue by Flog71** [qzind/tray#271]
[demo website](https://demo.qz.io/)

" No input file specified. "

**Comment by sumodevelopment** [comment]
Confirmed

**Comment by tresf** [comment]
Thanks.  We just upgraded the server and must have missed something.  We're on it.

**Comment by Flog71** [comment]
"403 Forbidden"
nginx/1.10.3 (Ubuntu)

In progress 👍

**Comment by tresf** [comment]
Ubuntu 16.04 doesn't play well with our build scripts.  I've got it working for now, I had to remove the signing step from the `ant` task on this back-end.  Not sure why.  Anyway, thanks for the FYI, it's back up and running.

**Comment by Flog71** [comment]
Thank's a lot !! ;D
