### ISSUE TITLE
Support raw image to brother td 4000

### ISSUE THREAD

**Issue by lite1979** [qzind/tray#274]
This is a placeholder for progress on the below mentioned commit:

https://github.com/qzind/tray/commit/4109761236f01aa8ae2b38192d3303d3050d6793

This adds support for the Brother TD 4000  to our current image wrapper (using BRASTER, if I'm reading correctly)

* [x] Obtain hardware
* [ ] Test commit
* [ ] Merge

**Comment by tresf** [comment]
@lite1979 any update on testing this?

**Comment by tresf** [comment]
Code we are using... 

```js
var config = qz.configs.create("Brother TD-4000");

var data= [{
    type: 'raw',
   format: 'image',
   data: 'assets/img/image_sample_bw.png',
   options: { language: 'BRASTER' }
}];

qz.print(config, data).catch(function(err) { console.error(err); });

**Comment by tresf** [comment]
I'll provide an update on Lite's behalf... all attempts to use the community contributed code has failed on his printer.  @chunlinyao can you provide some insight?

**Comment by tresf** [comment]
I found this information from both the Brother QL800's and TD4000's raster programming guidse interesting... It breaks down the raw `.prn` file that is created when the print output is directed to file.

![image](https://user-images.githubusercontent.com/6345473/49450224-928cc480-f7aa-11e8-8679-3d8d5030f714.png)

Although I believe with enough R&D we could tackle this, there is currently very little demand for Brother raw support and the guides are quite complex.  I'm closing this issue out as `wontfix` for now.  We will reopen when we have time  to dive deeper into the programming guides.
