### ISSUE TITLE
Support Vietnamese Codepage

### ISSUE THREAD

**Issue by tresf** [qzind/tray#281]
We use Java's character mapping for printing and have a use-case that requires vietnamese characters.

**Assumptions**

I believe the thermal printers use [TCVN3](https://github.com/bamarni/escpos/blob/master/charset.go#L43) encoding.  Documentation is very slim for this, the client's hardware is not Epson, but a [hardware clone](https://user-images.githubusercontent.com/6345473/36746510-7eea432e-1bc0-11e8-850d-6ef7bf674b23.png) which claims to support Vietnamese.  As we've established in previous emails it's very unlikely that this printer supports UTF8 natively (and the client claims it does not).  VNI encoding may need to be supported as well.

> *"Many Vietnamese fonts intended for desktop publishing are encoded in VNI or TCVN3.  Such fonts are known as "ABC fonts".  Popular Web browsers lack support for specialty Vietnamese encodings, so any webpage that uses these fonts appears as unintelligible mojibake on systems without them installed."<br> -[wikipedia.com](https://en.wikipedia.org/wiki/Vietnamese_language_and_computers)*

Sample API call:
```js
var config = qz.configs.create("Printer Name", { encoding: 'TCVN-3-1' });  // TCVN3 is NOT a built-in Java encoding.
var data = [ '\x1B' +  '\x74' + '\x1E' ];
qz.print(config, data);
```

**Comment by tiendat0811** [comment]
I'm having trouble to print Vietnamese using TCVN-3-1 encoding.

I'm trying to print Vietnamese using qz-tray.js but it not working. 
Model of printer: RoCo Q80C

I get this error on all encoding I tried ("TCVN-3-1", "TCVN3-1", "TCVN-3-2", "TCVN3-2")

``` 
qz-tray.js:343 Uncaught (in promise) Error: Cannot parse (PLAIN)t into a raw COMMAND command: TCVN-3-1
    at _qz.websocket.connection.onmessage (qz-tray.js:343:48)
_qz.websocket.connection.onmessage	@	qz-tray.js:343
```

This is my demo.html

```
<html>
  <script src="./qz-tray.js"></script>
  <script>
    function print() {
      qz.websocket
        .connect()
        .then(() => {
          console.log("Connected to QZ Tray")
          return qz.printers.find("Printer POS-80")
        })
        .then((found) => {
          console.log("Found: " + found)
          //   get all encoding support: https://www.qz.io/api/qz/encoding

          var config = qz.configs.create(found, { encoding: "TCVN-3-1" })

          var data = [
            "\x1B" + "\x74" + "\x1E",
            "Tiếng Việt, còn gọi tiếng Việt Nam hay Việt ngữ, là ngôn ngữ của người Việt (người Kinh) và là ngôn ngữ chính thức tại Việt Nam.\n",
          ]

          qz.print(config, data)
        })
        .catch((e) => {
          console.error(e)
        })
    }

    print()
  </script>
</html>
```

Many thanks for any help!

**Comment by tresf** [comment]
@tiendat0811 opened issue #1290 for tracking.

**Comment by tresf** [comment]
@tiendat0811 I've fixed this on master branch, but it won't be available until QZ Tray 2.2.5.  I'll happily provide you a one-off build until 2.2.5 is released. What OSs do you require?  We offer Windows, Mac and Linux on Intel or ARM64.

**Comment by tiendat0811** [comment]
@tresf Thank you so much for your prompt support! I'm testing on Mac OS.

**Comment by tiendat0811** [comment]
> > @tresf Thank you so much for your prompt support! I'm testing on Mac OS.
> 
> 
> 
> Intel or Apple Silicon?

It's Apple Silicon. Thank you again!

**Comment by tresf** [comment]
> > > @tresf Thank you so much for your prompt support! I'm testing on Mac OS.
> > 
> > 
> > Intel or Apple Silicon?
> 
> It's Apple Silicon. Thank you again!

Here you are: https://github.com/tresf/tray/releases/download/v2.2.5/qz-tray-2.2.4+7-arm64.pkg

Note, you'll have to Right Click, Open since it's not notarized and stapled.
