### ISSUE TITLE
Basic serial improvements

### ISSUE THREAD

**Issue by tresf** [qzind/tray#305]
While working with a 250,000 baud Arduino we noticed that the serial port settings work fine without any configuration, but once data is sent to the device, they get out of whack.

Currently, the baud properties are part of the `qz.serial.sendData(...)` method, however, data may be sending to QZ Tray before a message is sent.

```js
qz.serial.sendData(port, command, properties);
```

~~Furthermore, the Arduino sends a CRLF (`\r\n`) after each message.  This type of `scrolling log` is something that should be supported natively in QZ Tray, but it would require the `end` without the `start`.  Is this possible?~~ **Edit:** This will be tracked separately.

QZ Tray needs:
* [x] `qz.serial.sendData(...)` properties parameter to be optional
* [x] `qz.serial.openPort(...)` to allow the properties to be specified so that data that is initially received not to be malformed.
* [x] ~~Allow QZ Tray to listen for CRLF to distinguish between messages.~~<br>This should be tracked separately.

**Comment by bberenz** [comment]
Serial port parameters moved to passed through `openPort` on [serial](https://github.com/qzind/tray/tree/serial) branch.

**Comment by tresf** [comment]
Closed via 3711308
