### ISSUE TITLE
2.1 vs 2.0 Legacy HTML Printing

### ISSUE THREAD

**Issue by klabarge** [qzind/tray#307]
The output from legacy HTML printing is different between 2.1 and 2.0 on macOS

**Java Version:** 8u172
**OS:** macOS 10.13.4 (17E199)

~~Below is a screenshot using the sample.html with default settings (besides `legacy: true`)~~

**Update:** It was brought to my attention that my explanation was confusing.

* (The Screenshot below is comparing 2.0 (left) vs 2.1 (right) printing with `legacy: true` using the sample.html

  ![image](https://user-images.githubusercontent.com/12505463/38653616-9f2f0da0-3dd9-11e8-93b4-b0e8aa8afd3d.png)

* This screenshot is 2.1 HTML printing using `legacy: false` for a baseline.

  ![image](https://user-images.githubusercontent.com/12505463/38653798-6aad0432-3dda-11e8-8cfe-3b8c6488e928.png)

**Comment by tresf** [comment]
@klabarge can you please retest this since 2.1 has changed a bit since it was originally reported in June?

**Comment by tresf** [comment]
A few issues.

1. @bberenz we seem to be improperly starting JavaFX for legacy prints.  No downside I can see other than performance, but seems like it should be skipped unless `legacy: false` is provided.
2. When @bberenz wrote HTML support for 2.1 it stripped out some style information from the `<HTML>` tag which should have been moved to a new `<body>` tag.

    ```diff
                     type: 'pixel',
                     format: 'html',
                     flavor: 'plain',
    -                data: '<html style="font-family: monospace; border: 1px solid #000;">' +
    +                data: '<html>' +
    +                      '<body style="font-family: monospace; border: 1px solid #000;">' +
                           '    <div style="float: left; margin-left: .5em;">' +
                           '        <h2>* QZ Tray HTML Sample Print *</h2>' +
                           '        <p>' +
    @@ -1578,6 +1579,7 @@
                           '    <div style="float: right">' +
                           '        <img src="' + getPath() + '/assets/img/image_sample.png" />' +
                           '    </div>' +
    +                      '</body>' +
                           '</html>',
    ```

3. With the above patch, there still seems to be a bug with the sizing of the print content.  I'll defer that to @bberenz.

<img width="1117" alt="screen shot 2018-10-03 at 3 50 21 pm" src="https://user-images.githubusercontent.com/6345473/46435556-9a85a500-c724-11e8-8c41-107ad1baa207.png">

**Comment by bberenz** [comment]
Patch under 4b4680aec5a2aab15644bc66c4d9dc6a8b760194 changes the HTML back over to a table layout. The sizing and line break issues were due entirely to the legacy system having issues with `div` tags.
The legacy system still seems to have trouble with relative dimensions (`width=100%`), and best I can tell the words were spaced out juust so in the old version to fit a 8.5in paper. Absolute dimensions would work to match this, but I wasn't sure if it was a big enough deal to pursue though?
I've also addressed not starting jfx on only legacy prints.

**Comment by tresf** [comment]
Tested, works!
