### ISSUE TITLE
HTML fails to fall back to 1x zoom

### ISSUE THREAD

**Issue by tresf** [qzind/tray#312]
For HTML documents that are too large with 2.0.6, HTML fails with the error: 

`java.lang.UnsupportedOperationException: Failed to capture HTML`.

Full log available here: [view full log](https://gist.githubusercontent.com/tresf/2eeb32e38538d286acb7ffe5e51eb31f/raw/73e604ab0f973ecf6be4d0ee9bd2060239fd3ed8/html_crash.log)

In 2.0.5 with the same document, the printing initially fails, but then QZ Tray silently falls-back to a default zoom level of 1x and the document prints (albeit blurry).

**Comment by bberenz** [comment]
We apparently lost a whole exception in the stack after the refactor. Not sure how/where, but 45e40f4350415b4b98172cacdab911b36edc18e5 updates to handle both.

**Comment by tresf** [comment]
> but 45e40f4 updates to handle both.

Confirmed.  This regression will be fixed in 2.0.7 release.  Please contact support@qz.io if you require a patch prior.  Note, downgrading to 2.0.5 will correct this problem as well.
