### ISSUE TITLE
Install parameters ignored on Ubuntu

### ISSUE THREAD

**Issue by klabarge** [qzind/tray#320]
Tested against Ubuntu 16.0.4 and Raspbian Jessie

One can pass in an SSL certificate during installation for trusted HTTPS certificates:

```bash
sudo bash qz-tray-2.x.x.run -- "-y '' path/to/fullchain.pem path/to/privkey.pem"
```

Passing in a bogus path fails the websocket certificate installation on version 2.0.4 and earlier.

2.0.5 + does not throw an error, and shows a successful certificate installation, indicating that the parameters are ignored

**2.0.5**
![image](https://user-images.githubusercontent.com/12505463/39607142-5e185ab2-4f07-11e8-97fe-018a8584607b.png)

**2.0.4**
(doesn't show path failure)
![image](https://user-images.githubusercontent.com/12505463/39607108-1cec7a46-4f07-11e8-9cc1-b4fc251c2c22.png)

**2.0.1**
![image](https://user-images.githubusercontent.com/12505463/39607064-d7eb45b2-4f06-11e8-856e-c36aebaf110f.png)

**Comment by tresf** [comment]
SSL requires a `localhost` **override**.  Passing in `''` will cause the script to treat it as a zero-length string and it will fallback into standard `localhost` mode and the other parameters should be ignored.

Tested using:

```bash
sudo ./qz-tray-2.0.6.run -- -y fakedomain.com 'cert.pem' 'key.pem' 
```

... and it works perfectly.  Closing as invalid. :)

**Comment by tresf** [comment]
ah bollocks... you're right... reopening... 

I re-reviewed the [Trusted SSL documentation](https://github.com/qzind/tray/pull/89#issue-169268163) and it specifically states to use `''` for the hostname, which make sense, we aren't making a cert, we don't need it.

I guess for now you can use the workaround of providing the hostname until this is patched.  Reopening....

**Comment by tresf** [comment]
Ok, now I'm confused.  Just tested with the following syntax and it works... 

```bash
sudo ./qz-tray-2.0.6.run -- -y '' 'cert.txt' 'key.txt'
```

And if I break the path for `cert.txt` or `key.txt` it properly displays an error.

**Comment by tresf** [comment]
@klabarge I think the example we use in our documentation is wrong.  Can you try it without the double-quotes around "-y '' ... ..."

**Comment by klabarge** [comment]
Yes, that's exactly the problem. The discrepancy between 2.0.6 and 2.0.4 was that 2.0.6 ignores the parameters when the syntax is wrong, installing the software normally, while *<2.0.4 fails the certificate installation piece

```diff
# Does not work
- sudo ./qz-tray-2.0.6.run  -- "-y '' "/home/klabarge/Desktop/fullchain.pem" "/home/klabarge/Desktop/privkey.pem""

# works
+ sudo ./qz-tray-2.0.6.run  -- -y '' "/home/klabarge/Desktop/fullchain.pem" "/home/klabarge/Desktop/privkey.pem"
```

Also updated the example in https://github.com/qzind/tray/pull/89
