### ISSUE TITLE
Malicious found in qz-tray-2.0.6.exe

### ISSUE THREAD

**Issue by zxchen89** [qzind/tray#321]
Please take a look of the attachment. 

![qz-tray-2 0 6](https://user-images.githubusercontent.com/1573526/39614532-27e37fac-4fa3-11e8-9ae1-cce1f5596496.png)

**Comment by tresf** [comment]
These are false-positives.  Closing as invalid.  We use Homebrew's NSIS to package our installers on MacOS.  We've found no evidence whatsoever to these claims.

**Comment by tresf** [comment]
We'll see to get this whitelisted, but these AV engines seem to have a habit of doing this.

**Comment by klabarge** [comment]
Kaspersky, CAT-QuickHeal, Antiy-AVL, and ZoneAlarm* have been contacted.

*Zone Alarm uses the Kaspersky AV engine. Two 🐦's :)

**Comment by tresf** [comment]
Quickheal has replied stating false-positive.

**Comment by zxchen89** [comment]
After some time, my security team has tried to check again, but it seems there are more engines treating its as a virus. Please help, we couldn't buy this plugin if it's not whitelisted. 
![image](https://user-images.githubusercontent.com/1573526/40524280-4e614a32-600c-11e8-8e35-1a4b072cc9f8.png)

**Comment by klabarge** [comment]
Is there a specific AV you need whitelisted? As mentioned before, these are false positives.

**Antiy-AVL:** We've attempted to reach out several times, but their inbox is full and are not receiving our requests. I've reached out to other email addresses without response.

   ![image](https://user-images.githubusercontent.com/12505463/40549634-ff2031dc-6005-11e8-99e9-193ba2571ee5.png)

**CAT-QuickHeal:** They responded to us on May 12th saying within 24 hours they are going to release an update of their software, whitelisting QZ Tray. The last time VirusTotal ran an analysis on the software was 5/12. It should be whitelisted.

**McAfee:** To request a whitelist, McAfee requires licensing and product information (Engine, DAT version, etc.) in order to submit. They have many, many different products. I tried to reproduce this using McAfee VirusScan Enterprise under strict corporate rules, and QZ Tray came back clean. If you have a client experiencing an issue with McAfee, please let us know, as we may need them to escalate the request.

**TrendMicro-HouseCall:** I've submitted a request to their support team.

**Rising:** I'm having a hard time finding any contact information for "Rising". [According to their website](http://www.rising-global.com/), they haven't supported English since 2013.

**Comment by liushuyu** [comment]
>Rising: I'm having a hard time finding any contact information for "Rising". According to their website, they haven't supported English since 2013.

They have a report site here: http://mailcenter.rising.com.cn/filecheck_en/ Remember to select "Report False Positive" Option. 

The English translation on this website is very bad, but I think at least can be understood.

**Comment by liushuyu** [comment]
Good news. The VT showed an all green status now.

https://www.virustotal.com/#/url/d6cf4c49c42a55fadecda65b32302194abcbf012c27cfaf32ffa937b93d1d441/detection

**Comment by klabarge** [comment]
Thanks @liushuyu !

At the time of writing, I had the same results as @zxchen89

**Comment by liushuyu** [comment]
>Thanks @liushuyu !

At the time of writing, I had the same results as @zxchen89

Ah, sorry, VT is very inconsistent now, I clicked on reanalyze and it now turn red again...

**Comment by liushuyu** [comment]
After several re-tries, the results stabilized and shown as follows:

![image](https://user-images.githubusercontent.com/6829345/40567944-f08ac130-6034-11e8-9fdc-19c5560741a3.png)

**Antiy-AVL** and **TrendMicro-HouseCall** are still having problems with the installer.

**Comment by liushuyu** [comment]
@klabarge So quick update here:

AV Software | Status
----------------- | -----------
**Antiy-AVL** | Seems to be a Chinese company, I'll try to communicate with them with their CN domain email.
**TrendMicro-HouseCall** | Waiting for your result.
**Rising** | No false positive in latest scan
**McAfee** | No false positive in latest scan
**CAT-QuickHeal** | No false positive in latest scan

**Comment by klabarge** [comment]
> Ah, sorry, VT is very inconsistent now, I clicked on reanalyze and it now turn red again...

@liushuyu you aren't kidding. I'v rescanned several times, results coming back all green.

> Seems to be a Chinese company [Antiy-AVL], I'll try to communicate with them with their CN domain email.

Great!

I'll update when I hear back from TrendMicro-HouseCall

**Comment by zxchen89** [comment]
Thanks! @liushuyu & @klabarge 

I got 2 red in result as well. The result will come with red when you upload the exe file, instead of using the URL. 
![image](https://user-images.githubusercontent.com/1573526/40600938-c0a9871e-6285-11e8-8c5d-2e0eec02e49b.png)

**Comment by liushuyu** [comment]
@zxchen89 if I understand correctly, basically what is your company's security team doing is they rely on all green on VirusTotal to decide whether buy the product?

**Comment by zxchen89** [comment]
@liushuyu Yes, you are right! If there is 1 red in the result, the security team won't approve us to buy and even use the product, it will be blocked by my company anti-virus software that has already installed in each of my company PCs.

**Comment by liushuyu** [comment]
>it will be blocked by my company anti-virus software that has already installed in each of my company PCs.

What's the antivirus your company currently using?

**Comment by klabarge** [comment]
We are still getting the same 2 false positives in VirusTotal.

I still have not heard back from TrendMicro, but I just followed up with them.

@liushuyu did you have any luck contacting Antiy-AVL?

**Comment by tresf** [comment]
I emailed Antiy-AVL last night, no reply.  They claim all files must be validated using their public key, although I'm not sure what purpose that serves over a hash.

I just sent them a hard link.  I don't expect a reply though.

**Comment by liushuyu** [comment]
>@liushuyu did you have any luck contacting Antiy-AVL?

I didn't get any reply from their Chinese submission email address either. I think maybe the only working email addresses might be from their sales department.

**Comment by tresf** [comment]
I've reached out to VirusTotal informing them that Antiy-AVL has been unresponsive to false-positive/whitelist requests.

**Comment by tresf** [comment]
VirusTotal send a typical robot reply, but they did provide a different email address for submission... `avlsdk_support_vt<at>antiy.cn`.  I'll try this one out.

**Comment by tresf** [comment]
So here's something interesting... 

GitHub URL (marked as 0/68 unsafe):
https://www.virustotal.com/#/url/d6cf4c49c42a55fadecda65b32302194abcbf012c27cfaf32ffa937b93d1d441/detection

Dragged in file (marked as 2/68 unsafe):
https://www.virustotal.com/#/file/c7b7b016fc5a48d83f147fc7426f71bbb57eda186af915893c6808f7a4c9158f/detection

Note that the irreversible sha256 hash for both URLs are identical: `c7b7b016fc5a48d83f147fc7426f71bbb57eda186af915893c6808f7a4c9158f`

**Comment by tresf** [comment]
Ok, I think I found the source of this... Hybrid-Analysis has marked the installer as malicious on suspicion.  The suspicions seems to stem from a few "heuristic" flags such as using the free `nsis` tool for creating the win32 installer as well as spawning processes during install.

I've placed a support request through Hybrid-Analysis to whitelist.  What a mess this whole process is.

https://www.hybrid-analysis.com/sample/c7b7b016fc5a48d83f147fc7426f71bbb57eda186af915893c6808f7a4c9158f?environmentId=120

**Comment by tresf** [comment]
Hybrid-Analysis got back... 

> Tres, The whitelisting status is going to be sourced from the the repository listed.  Moving forward, I can have this specific hash analyzed further via our internal teams to see if there is any issues with the analysis, or to look into any modification to the status that has been applied. Upon completion of our analysis, I will update this [ticket].

> [Normally, in] order to remove this information, you would need to reach out to the vendor that is registering the submission as malicious via their AV analysis. Also, you may want to look into submitting your info to the National Software Reference Libaray as that is where we source our whitelisting from - https://www.nist.gov/software-quality-group/national-software-reference-library-nsrl

I've reached out to a contact we have at NIST to see if he can help us with this process -- since -- [they use QZ](https://user-images.githubusercontent.com/6345473/41307628-b7742f5a-6e47-11e8-97b2-27a7ab6cd0d6.png) too. :)

**Comment by tresf** [comment]
NIST can add 2.0.6 to the list, but it won't be until September as they're backlogged.  Meanwhile, a 3rd AV engine "Rising" is making claim `Trojan.Generic!8.C3 (CLOUD)`, which isn't even a virus signature, it's a behavior analysis.

A visit to Rising's website says the following:

![image](https://user-images.githubusercontent.com/6345473/42041361-c38b8264-7abf-11e8-86b1-a63e891538cc.png)

They do still have a whitelist page though, so I'm trying that.

As an aside, this process is atrocious and I challenge any company that's taking VirusTotal's whitelist as the only curated mechanism for software approval as severely flawed.  As VirusTotal increases the amount of engines they scan with, it makes it harder and harder for a tech startup to publish anything online.  Using VirusTotal as a requirement for software approval are unreasonable, inaccurate and flawed.

Meanwhile, we invite anyone to download and compile the software itself.  It's just a JAR file with a few installation scripts wrapped around it.  Compilation [takes seconds](https://github.com/qzind/tray/wiki/Compiling).
