### ISSUE TITLE
Unable to start JavaFX service

### ISSUE THREAD

**Issue by tresf** [qzind/tray#327]
Been going back and forth with @bberenz on this one...

The error message generally looks like this:

```
java.lang.UnsupportedOperationException: Unable to start JavaFX service
	at qz.printer.action.PrintHTML.parseData(Unknown Source)
	at qz.utils.PrintingUtilities.processPrintRequest(Unknown Source)
```

The cause appears to be a timeout issue occurring while the JavaFX process starts up for the first time. We've made attempts to patch this but we're still getting reports of it.

Opening an official bug report to better track the progress.

At time of writing this, the attempts live in a30d537, 50023b1.

Log available: https://gist.github.com/tresf/7fe5c3551aa6c0b6584061fa1053294d

**Comment by tresf** [comment]
@bberenz is there a chance we're getting stuck incrementing this counter after a successful load rather than just using the instance?

https://github.com/qzind/tray/blob/2.0/src/qz/printer/action/WebApp.java#L138-L157

**Comment by bberenz** [comment]
We enter the loop, but if `started` is true, we break immediately. The exception seen is only thrown if that value is still false after the loop completes.
We never reset this value either. It's only false when the class is initialized and only set true when `start()` gets called.

The logs linked also show a restart of qz, so this isn't an issue of it suddenly not seeing jfx is ready. It only occurs on the first html print after startup. The cause of which is still uncertain right now.

**Comment by tresf** [comment]
>  The exception seen is only thrown if that value is still false after the loop completes.

👍 

> The logs linked also show a restart of qz, so this isn't an issue of it suddenly not seeing jfx is ready. It only occurs on the first html print after startup. The cause of which is still uncertain right now.

👍 

Yes, the startup took 9 seconds on that time it failed, so I guess it was working properly.  Why it failed is a mystery though.  I expect to find some type of resource not being released.  Is there a chance we're not freeing something?  It appears from the logs that the client is doing an abrupt disconnect.

**Comment by tresf** [comment]
After reviewing the logs and doing further testing, we believe this is simply a slow load situation.  Patch available under `fxload` branch, ready for testing. 
 https://github.com/qzind/tray/commit/6859f88273fa2dd6118bfd2daf0bd33181a59861

**Comment by tresf** [comment]
Confirmed fixed by client.  Merged, closed.
