### ISSUE TITLE
Periodically force certificate refresh

### ISSUE THREAD

**Issue by tresf** [qzind/tray#336]
A large part of our troubleshooting emails stem from the default behavior of the browser to cache static `.txt` files for a long time, breaking certificate updates when the cert has changed.

As a result, our signing examples should have a way to force refresh of the `digital-certificate.txt` every minute or so.

For example... references to `setCertificatePromise` should -- by default -- assume the cert has expired and force refresh periodically so that new, annual certificates are immediately recognized.

**BEFORE**

```js
qz.security.setCertificatePromise(function(resolve, reject) {
   $.ajax("assets/signing/digital-certificate.txt").then(resolve, reject);
});
```

**AFTER**

```js
qz.security.setCertificatePromise(function(resolve, reject) {

   // Periodically force cert refresh by appending URL
   var refresh = "?" + Math.floor(Date.now() / (1000 * 60));

   $.ajax("assets/signing/digital-certificate.txt" + refresh).then(resolve, reject);
});
```

**Comment by bberenz** [comment]
Do we just want this in sample.html or set it up some way inside the qz-tray.js api?

**Comment by tresf** [comment]
Just in the `sample.html` example and our [wiki examples](https://qz.io/wiki/2.0-signing-messages) as most clients copy and paste this verbatim.

We could consider adding our own AJAX function that takes the cert as a parameter, but that would be an API change.

**Comment by bberenz** [comment]
Jquery's ajax has a convenient `cache: false` value for this. And I don't think we need any periodic buffering thrown in as the certificate is only called on connect, which we'd probably want to force to the newest every time anyways. b048ff49e3bfe655688dd064bf7e0fbff0cdc73c

The `dataType: "text"` in there is to help avoid some "xml parsing" error messages in the console when pulling the plain text file. Not really necessary for this, but not bad to have either.

**Comment by tresf** [comment]
> Jquery's ajax has a convenient cache: false value for this. And I don't think we need any periodic buffering thrown in as the certificate is only called on connect, which we'd probably want to force to the newest every time anyways. b048ff4

From jQuery's documents... 

> **Note:** Setting cache to false will only work correctly with HEAD and GET requests. It works by appending "_={timestamp}" to the GET parameters. 

So this is identical to our approach, but less scalable because 1. Cache frequency isn't controllable. 
 2. Not everyone uses jQuery for AJAX.   3. May be less obvious for offline clients.

**Comment by tresf** [comment]
Spoke with @bberenz about this and we've agreed to use `cache: true` flag as other AJAX libraries provide a similar mechanism and the points about cert only being sent on first connection mean more than one per second would be rare.  Wiki updated.
