### ISSUE TITLE
LoopbackExemption decision for Microsoft Edge

### ISSUE THREAD

**Issue by tresf** [qzind/tray#338]
@slprogrp I hope you don't mind, I've moved your question to our active bug tracker from it's original home at https://github.com/qzind/qz-print/issues/165#issuecomment-402619997.

> @tresf , Isn't it a security issue to make Edge exempt from this? By running the command:
`CheckNetIsolation.exe LoopbackExempt -a -n="Microsoft.MicrosoftEdge_8wekyb3d8bbwe"`

Yes.

> You are saying, not only your application, but any local application can send network traffic to Edge?

No, the other way around.  This tells Edge it can send HTTP and WebSocket requests back to `localhost`.

> I can understand if you had a way to whitelist just your application, but you are essentially turning this security check off for MS Edge meaning all local applications can now send network traffic to it.

As explained above, this is the other way around.  I'm not aware of a way to send localhost requests back to edge or even what that would imply.

> And if you roll it out in the installer of your product, the user will not even know they have lost this security feature...

Correct.  It's an interoperability flag because Microsoft puts sandbox restrictions on all UWP (Universal Windows Platform) application.  Although this makes sense for titles like `Angry Chicken`, but not so much for Edge as it cripples it and prevents it from behaving like these browsers... 

| | Chrome | Opera | Safari | Firefox | IE11 | Edge |
|-|----------|--------|--------|------|---------|------|
| Can talk to `localhost` | ✅ | ✅ | ✅ | ✅ | ⚠️* | ⚠️** |

\*Except on domain, requires `locahost.qz.io`
\**Loopbacks forbidden in UWP without `CheckNetIsolation` command, except on domain, requires `locahost.qz.io`

> How can you justify this?

I hope the above helps explain how we've justified this.  Websites can prevent non-origin communication using a special page header, which will prevent communication outside of the originating domain.  I'm not sure how widely adopted this is though.  Here's more information on it: https://gist.github.com/subudeepak/9897212#websockets---help-me-from-this-nightmare-please

Quick installation and interoperability are paramount when delivery software to the masses and we believe the above is justification.  We believe whitelisting Edge loopbacks actually enables Edge to be used by the masses and puts all browsers on a level playing field and improves its adoption by embracing it as a supported browser and -- as such -- **this appears to be an oversight by Microsoft when making the decision to bundle Edge as a UWP application**.  If Edge is to become the successor of IE11, it must be able to work as good or better than IE11 better yet Chrome and Firefox.  Blocking `loopback` is a result of strict UWP sandboxing and we strongly feel this is a sane feature to toggle on if Edge is to be widely adopted in a competitive browser world.

**Comment by tresf** [comment]
I'll allow a few more days for comments and then close this out.

**Comment by slprogrp** [comment]
@tresf Thanks for the detailed response mate.

So are you aware of exactly what the actual security risks are of opening this up.   Like does Edge play a role in the execution of Microsoft App Store Apps?  As it is more integrated with the OS are there other parts of the OS that use it?

It would be great to know exactly what the ramifications are of enabling Loopbacks for Edge.  All the examples I have seen on the web just say stuff like: 
"This might put your device at risk."....
Like what exactly is made possible when enabling Loopbacks for Edge that puts the device at risk?
And is it only Edge or other windows components that depend on it?

**Comment by tresf** [comment]
> And is it only Edge or other windows components that depend on it?

This should only be Edge.  If UWP allows Edge to be embedded as a sandboxed app, I think that would defeat the purpose of sandboxing it.  AFAIK `Microsoft Help` uses embedded IE for HTML rendering, and I believe `WebBrowser` API does too (I assume this because of ActiveX support, which Edge doesn't have) but I would assume any project that embeds Edge would actually be a complete separately compiled instance of [`ChakraCore`](https://github.com/Microsoft/ChakraCore/wiki/Embedding-ChakraCore) or whatever the latest and greatest .NET bundles.
  
> It would be great to know exactly what the ramifications are of enabling Loopbacks for Edge. All the examples I have seen on the web just say stuff like:
> "This might put your device at risk."....

We'd be happy to enable this loopback more specifically for just the ports and protocols we use if `CheckNetIsolation` offers such granularity but my research has turned up nothing.  It may be a good question for the Microsoft devs or perhaps even a conversation for a security channel.

To view all active `LoopbackExcept` entries:

```
CheckNetIsolation LoopbackExempt -s
```

To clear all active `LoopbackExcept` entries:

```
CheckNetIsolation LoopbackExempt -c
```

This topic may be better suited for a security channel where the pros and cons can be weighed.  If allowing Edge to talk to `localhost` the same was as the other browsers is such a risk, we'd just drop support for it.  We're in the business of making printing easier and it's in good faith that we toggle a compatibility flag like this on, but we're also receptive to clear, imminent and serious security concerns when they're raised so we're all ears here.

**Comment by tresf** [comment]
@slprogrp I've found several article that **claim** Microsoft Edge is required for normal Windows operation and cannot be removed, however I've also found these same sites offering a CMD file that allow the browser to be quickly purged from the system.  It's hard to find much else through a standard internet search.

To truly know which components rely on Edge, I would recommend setting up a Windows 10 VM and using the purge script and seeing what breaks.  If no Windows components break, I would say that helps understand the scope.

I'm still not entirely sure what risks can be opened up by enabling `localhost` communication, so I'll leave the thread open for a bit incase anyone else can offer some insight.

**Comment by tresf** [comment]
Did some of my own Sans-Edge testing... Some components that don't work.. 

1. Links from Microsoft Help don't launch
2. PDFs don't open
3. "Try Microsoft Edge" links don't work in IE11

The rest of the built-in apps (Settings, Camera, Calendar, Feedback Hub, Tips, Store, Groove, Mixed Reality, Solitaire) seem to work without issue.

This is anecdotal evidence to suggest that Edge is not used widely by the Window OS and -- in time that is is -- appear to be a shell launch of the standalone application.

I invite further research and evidence to suggest otherwise.

**Comment by slprogrp** [comment]
@tresf Thanks for the time you are putting into this.

I found this article on an MSDN blog:
[https://blogs.msdn.microsoft.com/fiddler/2011/12/10/revisiting-fiddler-and-win8-immersive-applications/](https://blogs.msdn.microsoft.com/fiddler/2011/12/10/revisiting-fiddler-and-win8-immersive-applications/)

And in the comments section at the bottom there is a response from EricLaw where he says the following regarding enabling Loopback for edge:

"_...The primary security value derived from this restriction is that it helps prevent anyone from building a dual-headed system that uses loopback network connections as a form of IPC from the A/C process to a higher-integrity desktop process. By forbidding such connections by default, there is significantly lower potential attack surface, since an A/C process will have no interesting targets to attack. Since Fiddler must inherently assume that traffic sent to it may be malicious, it's already coded for safety against such threats...._"

I am guessing IPC is Interprocess Communication, and not really sure what an A/C process is.

**Comment by tresf** [comment]
> I am guessing IPC is Interprocess Communication, and not really sure what an A/C process is.

In this context, he's (rather obscurely) abbreviating AppContainer.  It's funny because the original bug report uses [a near identical tool](https://github.com/qzind/qz-print/issues/165#issuecomment-181447426) to add the Edge exemption.

Back on topic, [Chrome agrees with EricLaw and they have a plan to disable it too](https://bugs.chromium.org/p/chromium/issues/detail?id=378566).  The day this happens, our plugin will likely see it's demise.  Fortunately for us, this decision has been delayed 4+ years.  When it's disabled, Chrome will allow an "enterprise feature" to turn it back on.  It's more likely that our clients will simply leverage a [`locahost` workaround](https://github.com/qzind/tray/commit/b30beb70046bc4ad0ef929d8d971a302548ad3e2) but this will require each desktop install to ask for a DNS entry.  It'll be ugly.

Note, the above workaround is live since 2.0.1 and default fallback behavior since 2.0.2 but it **still doesn't work on Edge** without the loopback exception; Edge still blocks the final destination as -- what it is -- a loopback address.

**Comment by tresf** [comment]
Side note, among the comments on the Chromium bug report linked above include "Please don't"-type comments from developers at GitHub, Spotify and DropBox to name a few. 😕 They use a similar WebSocket technique as us.

**Comment by tresf** [comment]
> relay server in the cloud. 

This is Google Cloud Print.

We'll see how it progresses.  We may be able to come up with a browser plugin before then that addresses Chrome, but it would require a very large rewrite and would segment our codebase.
