### ISSUE TITLE
Data block only supports one image

### ISSUE THREAD

**Issue by tresf** [qzind/tray#34]
When using `type: 'image'`, the data block only allows a single image to be printed.

The expected behavior is to allow multiple jobs per data block.

Code snippet to reproduce:

```javascript
function printImage() {
	var config = qz.configs.create("PDFCreator");
	var data = [
		// FIRST IMAGE, PRINTS
		{ type: 'image', data: 'assets/img/image_sample.png' },

		// SECOND IMAGE, NEVER PRINTS
		{ type: 'image', data: 'assets/img/image_sample_bw.png' }
	];

	qz.print(config, data).catch(function(err){console.log(err)});
}
```

**Comment by bberenz** [comment]
> The expected behavior is to allow multiple jobs per data block.

Is it? Currently it will be one print job with two pages. 
ex: [twopages.pdf](https://github.com/qzind/tray/files/226514/twopages.pdf)

**Comment by tresf** [comment]
The expected behavior is to allow multiple jobs per data block.

> Is it? Currently it will be one print job with two pages. 
> ex: twopages.pdf

That's actually what was requested by the bug submitter, so that's fine too. :+1:

**Comment by tresf** [comment]
Opened in error.  Works as expected. :+1:

**Comment by tresf** [comment]
![image](https://cloud.githubusercontent.com/assets/6345473/14650306/3a1e3c80-0639-11e6-8a51-3b2988a50e60.png)
