### ISSUE TITLE
Depreaction of Raw support by cups

### ISSUE THREAD

**Issue by blaggacao** [qzind/tray#340]
I just stumbled over this article which announces deprecation of Raw printing support from CUPS 2.2.7 (2018) and removal from CUPS 2.3 (ETA 2020):
https://www.cups.org/blog/2018-06-06-demystifying-cups-development.html

**Comment by tresf** [comment]
More details here: https://github.com/apple/cups/issues/5271

@blaggacao thanks for sharing.  This is sad news indeed.  I'm curious what the scope of this is... if they're also be deprecating the `lpr -o raw ...` syntax as well (something that allows raw printing without a designated raw driver).

I'll see what Michael Sweet has to say about it.  He's been very responsive on his tracker and the fact that he's got an open discussion for the topic already is a good sign.

**Comment by blaggacao** [comment]
>Today the only printers that “need” a raw printing interface are dedicated label, receipt, or logging printers, and those same printers are poorly served by CUPS because the applications using them assume they have exclusive access to the printer, send a single “page” of arbitrary length that is not known ahead of time, and/or have specific timing requirements that CUPS cannot guarantee.

I can't see that problem. But I'm sure missing information here... Is this the buzzer-tone functionality of Epson Kitchen printers, we are talking about?

**Comment by tresf** [comment]
>  It only fails when the advanced status messaging is needed which I always assumed was just a driver limitation

I guess to this point, yes... printer failover would be one shining example of how badly raw needs to be dropped.  I guess we're lucky on Windows because with the right driver and WinSpool we can have our RAW but listen on our printer statuses too (a 2.1 feature).  I just hope that we have something similar for the CUPS side of the fence.

**Comment by tresf** [comment]
Closing since this is an upstream problem that won't see a solution for some time.  Please feel free to reopen when CUPS starts offering workarounds so that we can put some R&D into whatever comes in to replace it.

**Comment by tresf** [comment]
Just an update.... Michael Sweet has created a new project called `lprinter` to start addressing the concerns of Linux/Unix systems that rely on raw: https://github.com/michaelrsweet/lprint
