### ISSUE TITLE
AccessDeniedException using FileIO on Mac

### ISSUE THREAD

**Issue by tresf** [qzind/tray#342]
2.1 branch, Mac can't write to either the sandboxed or the shared location... 

A workaround is to switch permissions from `666` to `777` but I'm not exactly sure why...

```bash
sudo chmod 777 /Library/Application\ Support/qz
mkdir /Library/Application\ Support/qz/sandbox
```

**Comment by tresf** [comment]
Apparently execute is needed on the directory... here's why... https://unix.stackexchange.com/a/21252/190347

> When applying permissions to directories on Linux, the permission bits have different meanings than on regular files.
> * The read bit allows the affected user to list the files within the directory
> * The write bit allows the affected user to create, rename, or delete files within the directory, and modify the directory's attributes
> * **The execute bit allows the affected user to enter the directory, and access files and directories inside**
> * The sticky bit states that files and directories within that directory may only be deleted or renamed by their owner (or root)

So it looks like the execute flag is needed afterall.

**Comment by bberenz** [comment]
Adjusted the permissions on install via 1e7d83802800c3b0f3a9a281342184dbec87051c

**Comment by tresf** [comment]
Repeated for Linux 50a781c

**Comment by tresf** [comment]
Ran into this but ended up being an old install had the wrong permission setup, fixed via:

```bash
sudo rm -rf /Library/Application\ Support/qz/
```

And then reinstalled.
