### ISSUE TITLE
Move JSON About Page To Main Endpoint

### ISSUE THREAD

**Issue by dsanders11** [qzind/tray#343]
As discussed in #334, move the JSON version of the about page under the `/` and determine whether to return HTML or JSON based on the HTTP `Accept` header. This means the `/` endpoint can serve WS, HTML, or JSON depending on the interaction.

Can probably be accomplished via a servlet filter.

**Comment by bberenz** [comment]
Pages are combined under 66b8b2869358649c747705e208f782415ab693a6, taking the "Accept: application/json" header for json responses instead of a separate page.

> We only have one client live with this, so we'll have to ask them if if they'll need the old endpoint still.

@tresf, did we determine if we still need to still support the "/json" endpoint too?

**Comment by tresf** [comment]
> @tresf, did we determine if we still need to still support the "/json" endpoint too?

Reaching out now. 👍

**Comment by bberenz** [comment]
Supporting old `/json` path added back under 3c4fdd1e72506fb9a6290ca9c775b81f4caed43f

**Comment by klabarge** [comment]
Looks good, merging now.

*  ✅ returns `json` format
`$ curl -H "Accept: application/json" https://localhost:8181`

* ✅ returns `json` format
`$ curl https://localhost:8181/json`

* ✅ returns `html` format
`$ curl https://localhost:8181`
