### ISSUE TITLE
Problems with HTML Printing

### ISSUE THREAD

**Issue by padagoal** [qzind/tray#347]
Hello,

My machine is a MBP High Sierra, with qz-tray 2.0.7, java version "1.8.0_121", when i tried this

```javascript
qz.websocket.connect().then(function() {

        return qz.printers.find("STM")               // Pass the printer name into the next Promise
    }).then(function(printer) {
        console.log('connected');
        console.log(printer);
        var config = qz.configs.create(printer);       // Create a default config for the found printer
        var data = [{
            type: 'pixel',
            format: 'html',
            flavor: 'plain', // or 'plain' if the data is raw HTML

            data: '<html><body><h1>test</h1></body></html>'
        }];
        //qz.print(config, data).catch(function(e) { console.error(e); });
        return qz.print(config, data);
    }).catch(function(e) { console.error(e); });
```
Always gives me this error!

Error: No enum constant qz.utils.PrintingUtilities.Type.PIXEL
    at WebSocket._qz.websocket.connection.onmessage

**Comment by tresf** [comment]
The syntax for HTML with 2.0 is:

```js
var data = [{
   type: 'html',
   format: 'file', // or 'plain' if the data is raw HTML
   data: 'assets/html_sample.html'
}];
```

You appear to be using the newer, 2.1 syntax, which is OK, but you would need to be using the newer JavaScript file.

Here's a snapshot of the 2.1 JavaScript file that we're working on to allow both APIs simultaneously: https://github.com/qzind/tray/blob/f27a56261f2df3fee0a07506c76669fcb56664d6/js/qz-tray.js

**Comment by tresf** [comment]
Closing as this appears to be a support issue and the OP hasn't replied in a month.
