### ISSUE TITLE
instalation aborted

### ISSUE THREAD

**Issue by irwanhl** [qzind/tray#352]
![qz](https://user-images.githubusercontent.com/13036072/45582618-59486500-b8dd-11e8-9b02-934cd621dc7f.PNG)

why?? i use jdk 1.8, ant 1.10.5 and nsis  3.03

**Comment by klabarge** [comment]
Have you baseline tested against our official release? Please do so [here](https://qz.io/download/).

It looks like the installer is failing in the certificate install script. Please run the following and provide us with any errors.
```cmd
cd "%PROGRAMFILES%\QZ Tray\"
cscript auth\windows-keygen.js
```

Our [FAQ wiki page](https://qz.io/wiki/faq#cannot-launch-software) highlights common issues. Specifically, please run through the corrupt Java installation and custom `JAVA_HOME` environment variables section.

Going forward, please be as specific as possible. For example, knowing the *exact* version of JDK, what branch you compiled, etc. helps immensely with troubleshooting and avoids any assumptions on our end.

**Comment by tresf** [comment]
Closing because this is a sign of a setup error and the OP has not responded in 12 days.
