### ISSUE TITLE
further steps

### ISSUE THREAD

**Issue by bhargav2496** [qzind/tray#353]
I have followed the steps of the compiling the code and after the successful compilation what are the steps to be followed

**Comment by tresf** [comment]
The software is intended to be run from our desktop installers.  If you're not sure how to run a Java application, this isn't the place to find out how.

**Comment by lite1979** [comment]
If you want to test QZ-Tray locally, you just run the .exe, .pkg, or .run on your system. 

Explore the installation directory for the 'demo' folder, and open sample.html in the browser of your choice.
