### ISSUE TITLE
HTML + Landscape cuts off content

### ISSUE THREAD

**Issue by tresf** [qzind/tray#359]
<img width="648" alt="screen shot 2018-10-08 at 7 32 18 pm" src="https://user-images.githubusercontent.com/6345473/46638848-ec696900-cb30-11e8-807a-db9969cd0e2b.png">

HTML to reproduce: 

[landscape.html.zip](https://github.com/qzind/tray/files/2458325/landscape.html.zip)

Config:

```js
{ size: { width: 5.83, height: 8.27 }, margins: { top: 0.75, right: 0.5, bottom: 0.75, left: 0.5 }, orientation: 'landscape', rasterize: false }
```

**Comment by bberenz** [comment]
038cca74908fc7cf61a8f68289e93de6c5a5c33a uses the paper height for a default render width if landscape orientation is selected.

**Comment by tresf** [comment]
Tested, working.
