### ISSUE TITLE
Headless is not the same as trayless

### ISSUE THREAD

**Issue by tresf** [qzind/tray#360]
@bberenz in https://github.com/qzind/tray/commit/eb1805cb2ec644d1165a2c46c7392b67f9ae5d61 you made the assumption that `headless` and `trayless` were the same but they're not.

Now, 2.1 won't load on 18.04 without [special whitelisting steps](https://github.com/qzind/tray/wiki/2.1-Headless) and signing setup.

Can we revisit this please?

**Comment by bberenz** [comment]
So this was implemented because about [2 years ago](https://github.com/qzind/tray/issues/51#issuecomment-263984515) we could rely on a failure to support the tray as indication there was no GUI and fallback to headless.

I've made changes under c5f0a45b98b68d3e6c9ffc2994fb32bd8e68519a to use java's `GraphicsEnvironment` check instead, but I don't have any headless systems at the moment to test this fallback works as expected.

**Comment by klabarge** [comment]
I disabled the Desktop on an Ubuntu 16.0.4 VM and launched QZ Tray over SSH. It looks like the software runs in `headless` mode.

I also launched the software in Ubuntu 18.0.4, and the dialogue prompts appear as expected.

```diff
parallels@parallels-vm:~$ java -jar /opt/qz-tray/qz-tray.jar
[INFO] 2018-10-20 10:30:28,614 @ qz.ws.PrintSocketServer:?
	QZ Tray version: 2.1.0-RC5
[INFO] 2018-10-20 10:30:28,615 @ qz.ws.PrintSocketServer:?
	QZ Tray vendor: QZ Industries, LLC
[INFO] 2018-10-20 10:30:28,616 @ qz.ws.PrintSocketServer:?
	Java version: 1.8.0+181
[INFO] 2018-10-20 10:30:28,628 @ qz.ws.PrintSocketServer:?
	Starting QZ Tray 2.1.0-RC5
[INFO] 2018-10-20 10:30:28,645 @ qz.common.TrayManager:?
+	Running in headless mode
[DEBUG] 2018-10-20 10:30:28,710 @ qz.utils.ShellUtilities:?
	Executing: [uname, -a]
[DEBUG] 2018-10-20 10:30:28,718 @ qz.utils.ShellUtilities:?
	Executing: [gconftool-2, --get, /desktop/gnome/shell/windows/theme]
[DEBUG] 2018-10-20 10:30:28,723 @ qz.utils.ShellUtilities:?
	Executing: [grep, dark_bg_color, /usr/share/themes/Ambiance/gtk-3.0/gtk.css]
[DEBUG] 2018-10-20 10:30:28,725 @ qz.utils.ShellUtilities:?
	Executing: [grep, dark_bg_color, /usr/share/themes/Ambiance/gtk-3.0/gtk-main.css]
[INFO] 2018-10-20 10:30:28,737 @ qz.deploy.DeployUtilities:?
	Main properties file /opt/qz-tray/qz-tray.properties
[DEBUG] 2018-10-20 10:30:28,738 @ qz.utils.ShellUtilities:?
	Executing: [certutil, -d, sql:/home/parallels/.pki/nssdb, -A, -t, TC, -n, QZ Industries, LLC, -i, /opt/qz-tray/auth/root-ca.crt]
[INFO] 2018-10-20 10:30:28,791 @ qz.deploy.DeployUtilities:?
	Main properties file /opt/qz-tray/qz-tray.properties
[DEBUG] 2018-10-20 10:30:29,010 @ qz.ws.SingleInstanceChecker:?
	Checking for a running instance of QZ Tray on port 8283
[DEBUG] 2018-10-20 10:30:29,036 @ qz.ws.SingleInstanceChecker:?
	Checking for a running instance of QZ Tray on port 8384
[DEBUG] 2018-10-20 10:30:29,045 @ qz.ws.SingleInstanceChecker:?
	Checking for a running instance of QZ Tray on port 8485
[INFO] 2018-10-20 10:30:29,049 @ qz.common.TrayManager:?
	QZ Tray 2.1.0-RC5: [INFO] Server started on port(s) 8182, 8181
[INFO] 2018-10-20 10:30:29,051 @ qz.ws.PrintSocketServer:?
	Server started on port(s) 8182, 8181
```

**Comment by tresf** [comment]
Wow that was elegantly simple.  Closing as Kyle's tested this already.  I'll nudge the 2.1 RC that our premium clients are on. @lite1979, we'll need to fast forward the printer status branch before you'll have it for that PR.
