### ISSUE TITLE
Replace $.ajax with fetch()

### ISSUE THREAD

**Issue by tresf** [qzind/tray#369]
Placeholder to document fetch API and eventually update wiki and sample with `fetch()` examples.

Working example, tested with Chrome, Firefox, Safari, Edge:

```js
qz.security.setCertificatePromise((resolve, reject) => {
 fetch("assets/digital-certificate.txt", {cache: 'no-store', headers: {'Content-Type': 'text/plain'}})
  .then(data => resolve(data.text()));
});

qz.security.setSignaturePromise(hash => {
 return (resolve, reject) => {
  fetch("assets/signing/sign-message.php?request=" + hash, {cache: 'no-store', headers: {'Content-Type': 'text/plain'}})
  .then(data => resolve(data.text()));
   };
});
```

**Comment by bloodf** [comment]
Great addition glad could help :)

**Comment by tresf** [comment]
Turns out there's a pollyfill available by -- no other than -- github. :) https://github.com/github/fetch

Somewhat related, I've decided to use `fetch()` for the [new AngularJS signing example](https://github.com/qzind/tray/blob/2.0/assets/signing/sign-message.ts)  as well as `=>` [arrow functions](https://medium.freecodecamp.org/when-and-why-you-should-use-es6-arrow-functions-and-when-you-shouldnt-3d851d7f0b26).  Combined they make the code considerably shorter.  PRs welcome for any style "faux pas". :)
