### ISSUE TITLE
Mac crash while laptop closed, possibly from lost internet connection

### ISSUE THREAD

**Issue by tlrobrn** [qzind/tray#375]
We're not sure of the exact cause, but since it happened while walking between buildings that's our theory.

[Crash Dump](https://github.com/qzind/tray/files/2551204/crash.txt)

**Comment by tresf** [comment]
Yeah, I have QZ Tray running 24/7 on my main Mac and it crashes all the time.   Low-level JVM crashes are difficult to pinpoint.

My theory currently with my running crash is that the UI can't handle switching displays (mines on a shared monitor).

With steps to reproduce and small chunk of code we can file a bug report with Oracle.

**Comment by tresf** [comment]
Mine hasn't been crashing with Mojave.  Not sure if it's a fix with the OS or the newer JREs.  Please request a reopen if this continues happening.
