### ISSUE TITLE
Concurrent `qz.file.read` reusing params

### ISSUE THREAD

**Issue by mrloop** [qzind/tray#376]
The below examples look similar but behave differently on Windows Chrome 70.0 using qz 2.1 alpha 69

```
readFilesConcurrentlySameParams() {
  const params = {};
  ['test1', 'test2', 'test3'].forEach(filename => qz.file.read(filename, params));
}

readFilesConcurrentlyDifferentParams() {
  ['test1', 'test2', 'test3'].forEach(filename => qz.file.read(filename, {}));
}
```

Running `readFilesConcurrentlySameParams` results in 2 Untrusted website dialog boxes appearing for signed requested. 
Running `readFilesConcurrentlyDifferentParams` results in no untrusted website dialog boxes appearing for signed requested. 
I'd expect to get no untrusted website dialog boxes for running either function.

**Comment by tresf** [comment]
Confirmed. Thanks.  We'll take a look.

**Comment by tresf** [comment]
Confirmed, fixed.  This will be part of the next 2.1 alpha.  White-label subscribers will have access to it immediately via the portal.
