### ISSUE TITLE
Authenticated page to generate the layout

### ISSUE THREAD

**Issue by luanlazzarin** [qzind/tray#379]
The code below is used to access a .php page that generates the coupon content dynamically based on the authenticated client.

```
qz.websocket.connect (). then (function () {
                                 return qz.printers.find (printer);
                             } {
                                 var config = qz.configs.create (found);
                                 var data = [{
                                     type: 'html',
                                     format: 'file',
                                     date: 'gera.layout.php',
                                 }];
(...)
```

If you access the content page through the browser the content is being generated, but when qztray passes the impression that it gives is that it uses "other browser" to generate the content, which obviously will not be authenticated.

How can we solve this?

**Comment by tresf** [comment]
We're unaware of a way to safely pass authentication from browser to Java in the example you've provided.

The workaround is to use something like jQuery's `$.ajax` or `fetch(...)` to fetch and append the data through either plain text or base64, depending on the type of data you're printing. (HTML should work very well with plain text).

**Comment by luanlazzarin** [comment]
Perfect, I'll create a function to bring the coupon into a variable. Thanks.
