### ISSUE TITLE
Interpolation on OSX

### ISSUE THREAD

**Issue by klabarge** [qzind/tray#38]
Interpolation on OSX seems to only work when using `rotation`

> **Note:** `rotation` alone is working as expected

* This is the result of `nearest-neighbor` and `rotation`:

![image](https://cloud.githubusercontent.com/assets/12505463/14756620/dc3078a4-08b8-11e6-9a77-339ab8174302.png)

***

* This is the result of just `nearest-neighbor`
 
![image](https://cloud.githubusercontent.com/assets/12505463/14756656/305d3bf6-08b9-11e6-826d-3d3143a9f5fa.png)

**Comment by tresf** [comment]
Due to the amount of bug reports surrounding image interpolation, I have a feeling this is an upstream OSX-only bug.

Here are a few I found in my searching.  I don't think they're related, but `JDK-8017247` specifically mentions some slow/double rendering of bicubic on Darwin/OS X which makes me wonder if there are some other issues.



https://bugs.openjdk.java.net/browse/JDK-8017247
https://bugs.openjdk.java.net/browse/JDK-8091506

**Comment by tresf** [comment]
So the rotation "still working" comment actually is a bit inaccurate.... 

Here's the results of rotating the image `1°`.

Although the rotation correctly uses interpolation, the scaling still does not.  @bberenz can you think of any creative hack to fix this for Mac?  This bug means https://github.com/qzind/qz-print/issues/149 won't work on Mac.

![screen shot 2016-04-23 at 3 31 57 pm](https://cloud.githubusercontent.com/assets/6345473/14763618/a40b5ae2-0968-11e6-8891-87e7c520d3de.png)

**Comment by tresf** [comment]
@bberenz I'm having difficulty proving an upstream bug here...

Test scenario: https://gist.github.com/tresf/34dd6e5b95c36f62ffe8b685bb736957 (click image to toggle).

I'm unable to reproduce the anti-aliasing on Mac with code very close to our own.

These test results suggest something else is happening which is triggering this.  Any ideas?

Below are test results, all pass.


**Original:**
> :white_check_mark: 

**Scaled, using `BufferedImage.getScaledInstance(...)`**
> ![image](https://cloud.githubusercontent.com/assets/6345473/14773220/79643378-0a75-11e6-9530-b950aa99ed04.png)

**Scaled, using `GC` + `G2D` using `NEAREST_NEIGHBOR`**
> ![image](https://cloud.githubusercontent.com/assets/6345473/14773274/1663611c-0a76-11e6-9d27-99aec80b9cbb.png)


**Scaled, using `GC` + `G2D` using `BICUBIC`**
> ![image](https://cloud.githubusercontent.com/assets/6345473/14773251/d7c516e4-0a75-11e6-9a06-6411e20997f0.png)

**Comment by bberenz** [comment]
@tresf How does your test image show up when printed through QZ? It's possible this is only an issue with the print libraries on OSX, rather than just how the interpolation is interpreted.

Also, does this issue still show up when using different printers?

**Comment by tresf** [comment]
> @tresf How does your test image show up when printed through QZ?

![image](https://cloud.githubusercontent.com/assets/6345473/14795825/40173e70-0af8-11e6-956d-883c46ba8b8c.png)

> Also, does this issue still show up when using different printers?

Valid question.  I'll defer to @klabarge.  Neither of us have anything except the Lisanet PDFWriter driver on our Macs in regards to "Pixel" style printers.

Am I wrong in assuming this is all Java image i/o?  It seems like the print processor would be too late.  @klabarge can you go back on an early `NEAREST_NEIGHBOR` release and see if it exists there (e.g. before rotation was added, etc?)

**Comment by klabarge** [comment]
> Also, does this issue still show up when using different printers?

I used [VipRiser](https://onflapp.wordpress.com/vipriser/) which is suppose to use a different driver than CUPS-PDF.  The results were identical.

> @klabarge can you go back on an early NEAREST_NEIGHBOR release and see if it exists there (e.g. before rotation was added, etc?)

I went as far back as [alpha-6](https://github.com/tresf/qz-print/releases/tag/v2.0.0-alpha6) when `NEAREST_NEIGHBOR` was introduced and this exact behavior was happening then (both `NEAREST_NEIGHBOR` and the rotation issue).

**Comment by tresf** [comment]
@klabarge thanks, confirmed.

@bberenz I think it is related to the printing, but I'm still a bit unsure how (and if that is the case, we should be able to circumvent it by drawing to a fresh graphics object (right?)

Well, I was able to find some debug commands for the 2d rendering, perhaps it has something in the log  that helps... 

https://gist.github.com/tresf/621c8380155bd131b657f4eab4126ef1

**Comment by tresf** [comment]
Here's a very old (but mostly relevant) writeup about graphics2d and hardware acceleration.  Not sure if any of it helps, but I'd be happy to try some of the techniques.

http://www.oracle.com/technetwork/java/javase/java2d-142140.html#gcghe

PDF backup, incase the link dies... 
[Troubleshooting Java 2D - Troubleshooting Guide for Java SE 6 Desktop Technologies.pdf](https://github.com/qzind/tray/files/235773/Troubleshooting.Java.2D.-.Troubleshooting.Guide.for.Java.SE.6.Desktop.Technologies.pdf)

**Comment by bberenz** [comment]
Can you try altering some of the other rendering hints?
I think setting `RenderingHints.KEY_ANTIALIASING` to `RenderingHints.VALUE_ANTIALIAS_OFF` has the best chance to work with nearest neighbor. 
The others seem to be just setting render process to slow/quality, but possibly worth adjusting to see if they improve the outcome.

**Comment by tresf** [comment]
@bberenz I tried this as well as many other settings from the rendering hints block to no avail (note, they work as-is when used with a JFrame)

**Comment by tresf** [comment]
@bberenz Can we consider a wrapper which when invoked on Apple devices out-sources the transforms to swing and then copies back `graphics` object back over for printing?

I have a strong feeling this is directly related to `JDK-8017247` which states swing isn't impacted by the bug.  The bug doesn't specifically mention the bicubic-despite-nearest-neighbor behavior exactly, but it say the revisiting of the logic won't happen until JDK9.

**Comment by robertcasto** [comment]
Detecting the platform is fairly easy.

On Thu, Apr 28, 2016 at 10:46 AM, Tres Finocchiaro <notifications@github.com
> wrote:

> @bberenz <https://github.com/bberenz> Can we consider a wrapper which
> when invoked on Apple devices out-sources the transforms to swing and then
> copies back graphics object back over for printing?
>
> I have a strong feeling this is directly related to JDK-8017247 which
> states swing isn't impacted by the bug. The bug doesn't specifically
> mention the bicubic-despite-nearest-neighbor behavior exactly, but it say
> the revisiting of the logic won't happen until JDK9.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/qzind/tray/issues/38#issuecomment-215449523>
>



-- 

Robert Casto
p: 1-513-847-4942
c: 1-513-886-1550
e: casto.robert@gmail.com

**Comment by bberenz** [comment]
> @bberenz Can we consider a wrapper which when invoked on Apple devices out-sources the transforms to swing and then copies back graphics object back over for printing?

I'm not sure this would fix the issue. Can you add
```java
try {
    BufferedImage bi = new BufferedImage((int)boundX+imgW, (int)boundY+imgH, imgToPrint.getType());
    bi.createGraphics().drawImage(imgToPrint, (int)boundX, (int)boundY, (int)boundX + imgW, (int)boundY + imgH,
                                  0, 0, imgToPrint.getWidth(), imgToPrint.getHeight(), null);

    ImageIO.write(bi, "png", File.createTempFile("qz_", ".png"));
}
catch(Exception ignore) {}
```
just before `return PAGE_EXISTS` in the PrintImage class. This will create a file with the same image data as the `graphics2D.drawImage` call above it is writing for the printer.
If this new file doesn't have any rendering issues, then the issue is inside the print libraries, and likely anything we do to the graphics object won't matter. If it comes out the same as the print, I'll look into shimming swing into our render process to see it helps.

**Comment by tresf** [comment]
It looks like the file is ok... what does that mean?

![image](https://cloud.githubusercontent.com/assets/6345473/14902332/5bddf58c-0d68-11e6-9c37-4492f1f6f8d1.png)

**Comment by tresf** [comment]
> If this new file doesn't have any rendering issues, then the issue is inside the print libraries, and likely anything we do to the graphics object won't matter.

Out of curiosity I added `graphics.drawImage(bi, 0, 0, null);` at the end of your codeblock and this is what I get.... (Note the PDF file size jumps from 10KB to 20KB)

![image](https://cloud.githubusercontent.com/assets/6345473/14907065/7eb8ffa6-0d91-11e6-8019-d73f5a9f5f40.png)

**Comment by tresf** [comment]
And the checkmark using the same logic... 

![image](https://cloud.githubusercontent.com/assets/6345473/14907134/8e8a49ac-0d92-11e6-866a-8fc4a3c48d02.png)

**Comment by tresf** [comment]
*corrected

![screen shot 2016-04-28 at 10 42 43 pm](https://cloud.githubusercontent.com/assets/6345473/14907141/97e03110-0d92-11e6-9642-6b8debbf180a.png)

**Comment by bberenz** [comment]
So, to be clear, you are drawing this new BufferedImage object to the graphics object supplied by the print function, and it comes out cleanly? And are you using the `graphics` object directly from the parameters or the casted `graphics2d` of the same object?

**Comment by tresf** [comment]
I had a problem using the casted g2d, so I used the print function `graphics` object directly.

**Comment by bberenz** [comment]
Hmm, it could be the lack of rendering hints on the buffered image, or a really unexpected fix.
Can you remove the `withRenderingHints` call on the [cast to Graphics2D](https://github.com/qzind/tray/blob/2.0/src/qz/printer/action/PrintImage.java#L139) and print without any of this buffered image rewriting.
If that produces the expected results we''ll know the problem is actually with the hints. If it still fails I'll rewrite the buffered image code to be our new drawing method.

**Comment by tresf** [comment]
> Can you remove the withRenderingHints call on the cast to Graphics2D and print without any of this buffered image rewriting.

I spent several days troubleshooting this with many combinations of rendering hints -- as well as removing them completely -- to no avail.  The built-in graphics object must be broken.  I read somewhere that not all `graphics` are created equally.  `JDK-8017247` illustrates this because one portion of the code behaves differently than the other, so `BufferedImage` must be successfully side-stepping it without having to invoke any ugly AWT/Swing workarounds.

I assume the next step is an `if (apple) { // hack }`.  Let me know if you want me to tackle this.

**Comment by bberenz** [comment]
I have the next step to try, just wanted to know where the efforts needed to lie.
Make these changes to PrintImage:
```diff
-Graphics2D graphics2D = withRenderHints((Graphics2D)graphics);
-log.trace("{}", graphics2D.getRenderingHints());
```
```diff
// Now we perform our rendering
+BufferedImage buffer = new BufferedImage((int)boundX + imgW, (int)boundY + imgH, imgToPrint.getType());
+Graphics2D g2d = withRenderHints(buffer.createGraphics());
-graphics2D.drawImage(imgToPrint, (int)boundX, (int)boundY, (int)boundX + imgW, (int)boundY + imgH,
+g2d.drawImage(imgToPrint, (int)boundX, (int)boundY, (int)boundX + imgW, (int)boundY + imgH,
                                  0, 0, imgToPrint.getWidth(), imgToPrint.getHeight(), null);
+
+graphics.drawImage(buffer, 0, 0, null);
+g2d.dispose();

// Valid page
return PAGE_EXISTS;
```
This will use the buffered image (with rendering hints as to still get the custom interpolation values) and should reduce the large jump in file size you saw with the edited buffer test.
And if this works we won't need any OS testing logic here.

**Comment by tresf** [comment]
I won't be able to test until a bit later.  I'll post my results.

**Comment by tresf** [comment]
> should reduce the large jump in file size you saw with the edited buffer test.

Well, I'm not sure how that could be true, it appears to be the same logic I was using (minus my lack of `g2d.dispose()`).

Anyway... tests fail... 

 * With **default interpolation**: `205 KB` !!!! (previously 10 KB w/ master branch).
 * With **nearest neighbor**: `31 KB` (previously 31 KB w/ [this code](https://github.com/qzind/tray/issues/38#issuecomment-215613905))
  * :no_entry: Test fails, blurry.

    ![image](https://cloud.githubusercontent.com/assets/6345473/14929248/988f883e-0e2a-11e6-89c3-d7229a7106d3.png)

However, if I remove the rendering hints, it's back to working again.... :confused: 

... and out of paranoia (as well as reassurance to you), I tried again without rending hints with the original `graphics` object to no avail.

So your next question will probably be what hints are turned on by default.... Here's the hints that I was able to gather from console... 

**Using Buffered Image, No Hints** :white_check_mark: (PASS)
 * Global rendering quality key=Default rendering methods
 * Text-specific antialiasing enable key=Default antialiasing text mode
 * Stroke normalization control key=Default stroke normalization
 * Fractional metrics enable key=Integer text metrics mode
 * Global antialiasing enable key=Nonantialiased rendering mode
 * Text-specific LCD contrast key=140

**Using print graphics object as-is, No Hints** :no_entry: (FAIL)
 * Global rendering quality key=Default rendering methods
 * Text-specific antialiasing enable key=Default antialiasing text mode
 * Stroke normalization control key=Default stroke normalization
 * Fractional metrics enable key=Integer text metrics mode
 * Global antialiasing enable key=Nonantialiased rendering mode
 * Text-specific LCD contrast key=140

**Using print graphics object With Hints** :no_entry: (FAIL)
 * Color rendering quality key=Highest quality color rendering mode
 * Image interpolation method key=Nearest Neighbor image interpolation mode
 * Fractional metrics enable key=Integer text metrics mode
 * Global rendering quality key=Highest quality rendering method
 * Text-specific antialiasing enable key=Nonantialiased text mode
 * Stroke normalization control key=Pure stroke conversion for accurate paths
 * Alpha blending interpolation method key=Highest quality alpha blending methods
 * Global antialiasing enable key=Antialiased rendering mode
 * Text-specific LCD contrast key=140

I didn't yet begin troubleshooting the rendering hints to make the `BufferedImage` work.  I ran out of time.

Raw output:
```
[TRACE] 2016-04-29 17:10:16,777 @ qz.printer.action.PrintImage:175
	BI: {Global rendering quality key=Default rendering methods, Text-specific antialiasing enable key=Default antialiasing text mode, Stroke normalization control key=Default stroke normalization, Fractional metrics enable key=Integer text metrics mode, Global antialiasing enable key=Nonantialiased rendering mode, Text-specific LCD contrast key=140}
[TRACE] 2016-04-29 17:10:16,778 @ qz.printer.action.PrintImage:176
	VANILLA: {Global rendering quality key=Default rendering methods, Text-specific antialiasing enable key=Default antialiasing text mode, Stroke normalization control key=Default stroke normalization, Fractional metrics enable key=Integer text metrics mode, Global antialiasing enable key=Nonantialiased rendering mode, Text-specific LCD contrast key=140}
[TRACE] 2016-04-29 17:10:16,794 @ qz.printer.action.PrintImage:182
	W/ HINTS: {Color rendering quality key=Highest quality color rendering mode, Image interpolation method key=Nearest Neighbor image interpolation mode, Fractional metrics enable key=Integer text metrics mode, Global rendering quality key=Highest quality rendering methods, Text-specific antialiasing enable key=Nonantialiased text mode, Stroke normalization control key=Pure stroke conversion for accurate paths, Alpha blending interpolation method key=Highest quality alpha blending methods, Global antialiasing enable key=Antialiased rendering mode, Text-specific LCD contrast key=140}
```

**Comment by tresf** [comment]
A bit confused how the mistake was made, but I repeated my test results... and it's working.

Here's nearest-neighbor and default (bicubic) side-by-side: (code from https://github.com/qzind/tray/issues/38#issuecomment-215780733 is good! :+1: )

![image](https://cloud.githubusercontent.com/assets/6345473/14933194/a394d3d6-0e54-11e6-85ea-259b79022a2b.png)
