### ISSUE TITLE
Fix required dependencies for Fedora

### ISSUE THREAD

**Issue by egegunes** [qzind/tray#398]
`java-1.8.0-openjdk-openjfx-devel` is also required for Fedora to compile from source.

**Comment by tresf** [comment]
Closed via [`wiki/9e9bcdc`](https://github.com/qzind/tray/wiki/Install-Dependencies/_compare/fc45b52c5a57a6fe233bf6b81552ac12b53d790b...9e9bcdcc82a53d128cdf9604e3a4c06a9c0a0aa0).
