### ISSUE TITLE
PDF to honor nearest-neighbor

### ISSUE THREAD

**Issue by tresf** [qzind/tray#405]
Per [`PDFBOX-4435`](https://issues.apache.org/jira/browse/PDFBOX-4435?focusedCommentId=16750271&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16750271) rendering hints will be honored with the next release.

Quoting the bug report... 

> @tresf please test whether this solves the bad quality problems. What you should do is to pass these renderingHints to PDFPrintable:
>
>
>
> ```java
>RenderingHints r = new RenderingHints(null);
>r.put(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_NEAREST_NEIGHBOR); // maybe, maybe not
>r.put(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY); // don't know
>r.put(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_OFF); // important
> ```

**Comment by bberenz** [comment]
Support for rendering hints with pdfs is added under the `pdfhints` branch for when they release the next version.

**Comment by klabarge** [comment]
I tested and `interpolation: nearest-neighbor` is honored with PDF's. It was hard to tell when physically printed, however I printed to PDFCreator and zoomed in on the barcode

## With Nearest Neighbor
![image](https://user-images.githubusercontent.com/12505463/53779952-341dd200-3ed0-11e9-83e9-9df1650af8a7.png)

## Without Nearest Neighbor
![image](https://user-images.githubusercontent.com/12505463/53779960-3f70fd80-3ed0-11e9-832e-356834caea89.png)

**Comment by tresf** [comment]
@klabarge thanks.  I've added a feature that should turn off text aliasing when nearest-neighbor is provided as well. 

@klabarge @lite1979 can you test on thermal paper and see what type of differences we get?

**Comment by klabarge** [comment]
>I've added a feature that should turn off text aliasing when nearest-neighbor is provided as well.

This works, I printed to PDFCreator and was able to zoom in on the text, and `nearest-neighbor` is clearly being honored.

I tested to thermal printers (Zebra LP2844 and an Epson EpsonTM-T88VI Receipt), using our demo PDF and the PDF provided in the PDFBOX report, and I am unable to detect a difference in the output with my eyes.
