### ISSUE TITLE
System-wide allowed.dat

### ISSUE THREAD

**Issue by tresf** [qzind/tray#41]
Currently `allowed.dat` is user-scope only.

The proposal is to first look for a system-wide allow list (e.g. C:\Program Files\QZ Tray\allowed.dat) first and combine what is found with the user settings.

This logic should work for both `allowed.dat` as well as `blocked.dat`

Marking for 2.0 scope as this should be relatively benign change.

**Comment by bberenz** [comment]
Implemented via b297efcc4538575c6b6b4163eeab7f796d5a2949

Folder "shared" will be created in the install location for global scope lists. This will subsequently require elevated privileges to write to (either adding or deleting).
Any items in the shared lists will take priority over the user lists.
A new checkbox is shown in the gateway dialog to extend persistence to all users. 
Any items added to this shared list will show with a different icon on the site manager dialog.

**Comment by bberenz** [comment]
Writing removed with 4e72ec968708c4ac075e575e567e8966f7a0e4fb

**Comment by tresf** [comment]
Tested, works. :+1:
