### ISSUE TITLE
EPL on macOS fails unless altPrinting is set

### ISSUE THREAD

**Issue by tresf** [qzind/tray#415]
When the `epl_sample.txt` from our sample.html is printed using CUPS on macOS, it just prints the EPL code on the label.  The "EPL" button works until the image line is removed, then it behaves the same.

* Specifying `altPrinting: true`, it works just, this is a viable workaround
* Attempted to force encoding, but did not help (`IBM437`, `Cp1252`, `UTF8`)

**Wireshark**
Looking at a packet capture:
* The `altPrinting: true` job is sent as one packet.
* The normal print job (`altPrinting: false`) job is truncated and mostly `FFFFFFFF` 

The job seems to become corrupted at fourth character of the `q609 ` line and shortened in overall length (e.g. 124 bytes instead of 232).

Possible similar reports: https://lists.samba.org/archive/samba/2016-June/200600.html

**Comment by tresf** [comment]
@onurguzel any interest in hunting this one down for a bounty?

**Comment by klabarge** [comment]
@lite1979 ran into this issue on Ubuntu 18.0.4 as well. He had to specify `altPrinting: true` in order to print EPL.

Perhaps this is a CUPS problem? It might be worth attempting to reproduce on older versions of CUPS.

**Comment by tresf** [comment]
> @lite1979 ran into this issue on Ubuntu 18.0.4 as well. He had to specify altPrinting: true in order to print EPL.

@Vzor- and I tried reproducing the issue with Ubuntu 18.04 and were unable to.  Mac is still reproducible.  If there are more details to get this to reproduce on 18.04 please offer them.

**Comment by tresf** [comment]
Some more information:

* NOT REPRODUCIBLE: @Vzor- 10.13.6 - Sending EPL to LP2844 over WAN
* NOT REPRODUCIBLE: @tresf - 10.13.6 - Sending EPL to LP2844 over LAN

So far, this seems to be isolated to Mojave.

**Comment by tresf** [comment]
After troubleshooting, found this was a configuration error.  The printer was setup as an Zebra EPL2 printer, not a raw device.  Closing as invalid.
