### ISSUE TITLE
Add dithering flags

### ISSUE THREAD

**Issue by tresf** [qzind/tray#417]
Some drivers such as the ZDesigner driver from Zebra allows specifying the dithering which can improve print quality.  @bberenz can we [control this through Java](https://docs.oracle.com/javase/8/docs/api/java/awt/RenderingHints.html#KEY_DITHERING)?

![image](https://user-images.githubusercontent.com/6345473/52579853-15f31380-2df5-11e9-8971-ed3def5af8fb.png)

**Comment by bberenz** [comment]
Testable code on branch `flags`

**Comment by klabarge** [comment]
For completeness, I posted my testing results on the pull request; https://github.com/qzind/tray/pull/429#issuecomment-469931101

> The dithering seems to have no effect, but we'll leave it as a hidden setting incase another driver honors this setting in the future.

@tres do you want the `dither` radio button removed from the sample.html page then?

**Comment by tresf** [comment]
> @tres do you want the dither radio button removed from the sample.html page then?

Sure.

**Comment by tresf** [comment]
Closing as this feature has been merged.  Kyle, follow-up with sample at your own convenience.

**Comment by klabarge** [comment]
>Kyle, follow-up with sample at your own convenience.

done via 5f71d0ced3843fce9f77d47ee85d9f7f8b0319dc (and sadly 2ff16a20ebb69d5493a71021c6f0e09fce8402da - I deleted an extra line)
