### ISSUE TITLE
About page won't load Java 11/Windows 10

### ISSUE THREAD

**Issue by klabarge** [qzind/tray#425]
I cannot load `https://localhost:8181` or `http://localhost:8182` when using Java 11 (Oracle) on Windows 10.

Chrome just shows "Waiting on localhost..." indefinitely.
![image](https://user-images.githubusercontent.com/12505463/53612115-0cacc980-3b9f-11e9-8ed8-369c0b25ca44.png)

I can, however, download the certificate by loading: https://localhost:8181/cert/qz-tray

**Comment by tresf** [comment]
Closed via 217f9da.
