### ISSUE TITLE
PDF with width greater than height gets rotated, even when printing to label with width greater than height

### ISSUE THREAD

**Issue by lite1979** [qzind/tray#428]
A PDF, 6 inches wide by 4 inches high, gets rotated 90 degrees (probably by PDFBOX; test/pics to follow), even though the paper dimensions are 4 inches wide by 3 inches high. The rotation is unnecessary and produces undesired results.

The same PDF printed with Adobe does not get rotated.

QZ-Tray relevant config: default orientation
Driver: portrait orientation

This does not occur when sending a similar PNG to the same label stock.

[one label.pdf](https://github.com/qzind/tray/files/2927980/one.label.pdf)

**Comment by lite1979** [comment]
![adobevsqztray](https://user-images.githubusercontent.com/3408749/53780524-dfc82180-3ed2-11e9-8d73-c15306350079.jpg)

Top Left: Adobe result (Auto-orientation; clicking on "Properties" before printing shows Portrait orientation, 4"wide x3"high paper size.

Bottom Left: QZ-Tray result (Orientation: Default) Control Panel > ZDesigner Driver also shows Portrait Orientation and a 4"wide x 3"high paper size. This will remain the same for the other two examples.

Top Right: QZ-Tray result (Orientation: Portrait) - same as Adobe result

Bottom Right: QZ-Tray result (Orientation: Landscape)

Other config options that were not considered a part of the problem:

Adobe: Fit to page 

QZ-Tray: Scale Content: true
              Size: not defined (use driver definition for size)

**Comment by lite1979** [comment]
Of note from the QZ logs:

Orientation: Default 

[DEBUG] 2019-03-04 22:32:25,491 @ qz.printer.action.PrintPDF:?
	Parsed 1 files for printing
[TRACE] 2019-03-04 22:32:25,507 @ qz.printer.action.PrintPixel:?
	DPI: 0.0	CNV: 72.0
[TRACE] 2019-03-04 22:32:25,507 @ qz.printer.action.PrintPixel:?
	Drawable area: 0.0,0.0:4.0,3.0
[TRACE] 2019-03-04 22:32:25,507 @ qz.printer.action.PrintPixel:?
	[color, (0.0,0.0)->(101.6,76.2)mm]
[TRACE] 2019-03-04 22:32:25,507 @ qz.printer.action.PrintPixel:?
	DPI: 0.0	CNV: 72.0
[TRACE] 2019-03-04 22:32:25,507 @ qz.printer.action.PrintPixel:?
	Drawable area: 0.0,0.0:4.0,3.0
[TRACE] 2019-03-04 22:32:25,522 @ qz.printer.action.PrintPixel:?
	[color, (0.0,0.0)->(101.6,76.2)mm]
[INFO] 2019-03-04 22:32:25,522 @ qz.printer.action.PrintPDF:?
	Adjusting orientation to print landscape PDF source
[INFO] 2019-03-04 22:32:25,522 @ qz.printer.action.PrintPixel:?
	Starting printing (1 copies)

Orientation: Portrait

[DEBUG] 2019-03-04 23:25:16,422 @ qz.printer.action.PrintPDF:?
	Parsed 1 files for printing
[TRACE] 2019-03-04 23:25:16,437 @ qz.printer.action.PrintPixel:?
	DPI: 0.0	CNV: 72.0
[TRACE] 2019-03-04 23:25:16,437 @ qz.printer.action.PrintPixel:?
	Drawable area: 0.0,0.0:4.0,3.0
[TRACE] 2019-03-04 23:25:16,437 @ qz.printer.action.PrintPixel:?
	[color, portrait, (0.0,0.0)->(101.6,76.2)mm]
[TRACE] 2019-03-04 23:25:16,437 @ qz.printer.action.PrintPixel:?
	DPI: 0.0	CNV: 72.0
[TRACE] 2019-03-04 23:25:16,437 @ qz.printer.action.PrintPixel:?
	Drawable area: 0.0,0.0:4.0,3.0
[TRACE] 2019-03-04 23:25:16,437 @ qz.printer.action.PrintPixel:?
	[color, portrait, (0.0,0.0)->(101.6,76.2)mm]
[INFO] 2019-03-04 23:25:16,437 @ qz.printer.action.PrintPixel:?
	Starting printing (1 copies)

>>No mention of orientation adjustment in the logs.

Orientation: Landscape

[DEBUG] 2019-03-04 23:21:28,481 @ qz.printer.action.PrintPDF:?
	Parsed 1 files for printing
[TRACE] 2019-03-04 23:21:28,496 @ qz.printer.action.PrintPixel:?
	DPI: 0.0	CNV: 72.0
[TRACE] 2019-03-04 23:21:28,497 @ qz.printer.action.PrintPixel:?
	Drawable area: 0.0,0.0:3.0,4.0
[TRACE] 2019-03-04 23:21:28,497 @ qz.printer.action.PrintPixel:?
	[color, landscape, (0.0,0.0)->(76.2,101.6)mm]
[TRACE] 2019-03-04 23:21:28,502 @ qz.printer.action.PrintPixel:?
	DPI: 0.0	CNV: 72.0
[TRACE] 2019-03-04 23:21:28,502 @ qz.printer.action.PrintPixel:?
	Drawable area: 0.0,0.0:3.0,4.0
[TRACE] 2019-03-04 23:21:28,502 @ qz.printer.action.PrintPixel:?
	[color, landscape, (0.0,0.0)->(76.2,101.6)mm]
[INFO] 2019-03-04 23:21:28,502 @ qz.printer.action.PrintPixel:?
	Starting printing (1 copies)
>> no mention of rotation adjustment

**Comment by tresf** [comment]
@bberenz would it help to check that the page height is greater than the page height first?  

```diff
diff --git a/src/qz/printer/action/PrintPDF.java b/src/qz/printer/action/PrintPDF.java
index da3a0a0..a822a71 100644
--- a/src/qz/printer/action/PrintPDF.java
+++ b/src/qz/printer/action/PrintPDF.java
@@ -129,7 +129,7 @@ public class PrintPDF extends PrintPixel implements PrintProcessor {
 
                 if (pxlOpts.getOrientation() == null) {
                     PDRectangle bounds = pd.getBBox();
-                    if (bounds.getWidth() > bounds.getHeight() || (pd.getRotation() / 90) % 2 == 1) {
+                    if ((page.getImageableHeight() > page.getImageableWidth() && bounds.getWidth() > bounds.getHeight()) || (pd.getRotation() / 90) % 2 == 1) {
                         log.info("Adjusting orientation to print landscape PDF source");
                         page.setOrientation(PrintOptions.Orientation.LANDSCAPE.getAsFormat());
                     }
```

**Comment by bberenz** [comment]
@tresf, I think so. This looks to be caused by our helper assuming we only print on 'portrait' ratio paper. What you're proposing is exactly the fix I had in mind.

**Comment by tresf** [comment]
@lite1979, patch available on `pdfrotate` branch.

**Comment by lite1979** [comment]
This appears to be fixed by the pdfrotate branch
![qzvsadobe2 0 9pdfrotate](https://user-images.githubusercontent.com/3408749/53857044-bf679800-3fa2-11e9-8d6d-b0e456de0fc1.jpg)
. Checking the logs, there is no indication of any automatic rotation. :+1:

**Comment by lite1979** [comment]
It's also worth mentioning that the QZ-Tray DOES automatically rotate the PDF when printing to a paper size that has _height greater than width_, such as my Brother HL-L2380DW (8.5"x11") :+1:
