### ISSUE TITLE
OpenJDK + RPi performance

### ISSUE THREAD

**Issue by klabarge** [qzind/tray#437]
OpenJDK has some severe performances issues compared to Oracle Java. This was originally identified in https://github.com/qzind/tray/issues/50#issuecomment-386180502, but we were happy with using Oracle Java at the time.

**OS:** Raspbian GNU/Linux 8 (jessie)
**Oracle Java:** 1.8.0_91
**OpenJDK:** build 1.8.0_40-internal-b04

|   Operation                  |Oracle Java          |OpenJDK                    |
|----------------------|---------------------|---------------------------|
|Time to launch        |**real:** 0m9.017s   | **real:** 4m39.295s       |
|`qz.websocket.connect`| 1-2s                |  20-30s                   |

To reproduce, simply install OpenJDK and launch QZ Tray.

```bash
# Install Oracle Java
sudo apt-get install openjdk-8-jdk
# switch to OpenJDK
sudo update-alternatives --config java
# prefix with time to record time
time java -jar /opt/qz-tray/qz-tray.jar
```

Since the repositories for this version of Raspbian have an outdated version of OpenJDK, I'll upgrade and retest.

**Comment by tresf** [comment]
@klabarge thanks for filing this.  Our original goal was to escalate with AdoptOpenJDK on offering support for the RaspberryPi, but they don't seem to offer a 32-bit ARM download yet.  They appear to be tracking the issue here: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/630#issuecomment-458146514

**Comment by klabarge** [comment]
I upgraded to Raspbian Stretch, upgraded to OpenJDK 1.8.0_181 and I can no longer reproduce.

**Comment by tresf** [comment]
Awesome news!

**Comment by liurenjin** [comment]
how about Amazon Corretto  vs AdoptOpenJDK.Since  AWS hired James Gosling and some others with Java expertise some time ago

**Comment by tresf** [comment]
Thanks.  They only list x86 on their download pages.  Which build are you referring to?

**Comment by liurenjin** [comment]
Just noticed. Amazon Corretto don't support  Linux 32 and 64 bit arm right now, refer to https://github.com/corretto/corretto-8/issues/60

**Comment by tresf** [comment]
@liurenjin good to know, thanks.

**Comment by tresf** [comment]
FYI, our commercial support contracts are with Oracle and AdoptOpenJDK currently.
