### ISSUE TITLE
qz-tray.properties only works if i reload!

### ISSUE THREAD

**Issue by astrO1** [qzind/tray#447]
I put this command on qz-tray.properties authcert.override=override.crt and is working fine.

But when I put the option automatically start when I turn off and turn on my pc the certification is not overriding, only if I close and re-open the qz-tray application that works what i must do?

**Comment by tresf** [comment]
@astrO1 please try using the absolute path to the `override.crt` file, I believe that will fix it.  The issue is the "working directory" of Java is likely different.  Absolute path will fix this.  In a future version we'll treat this path as relative to `qz-tray.jar` we just haven't coded it yet.

**Comment by astrO1** [comment]
it works, really thanks. 

You guys have an amazing product congratz!
