### ISSUE TITLE
Low quality HTML printing with rasterize

### ISSUE THREAD

**Issue by klabarge** [qzind/tray#45]
Tested on Windows and OS X

![image](https://cloud.githubusercontent.com/assets/12505463/14937499/19009cc2-0ed7-11e6-9d23-665757332bdd.png)

Notice "Version" and "Visit" are unreadable...

Changing `rasterize: false` results in a good quality print

**Comment by tresf** [comment]
@klabarge RC8?  I assume you're on Java 8 on both platforms?

**Comment by klabarge** [comment]
> RC8?

Yes
> I assume you're on Java 8 on both platforms?

Yes
* Windows: 1.8_60
* Mac: 1.8_73

**Comment by tresf** [comment]
Confirmed, Java 8, RC8.

**Comment by tresf** [comment]
We set the default density here:
https://github.com/qzind/tray/blob/2.0/src/qz/printer/PrintOptions.java#L192

And we use it here to set the zoom:
https://github.com/qzind/tray/blob/2.0/src/qz/printer/action/PrintHTML.java#L51

@bberenz is there an order of operations issue going on?

**Comment by tresf** [comment]
Actually.... @bberenz perhaps we're incorrectly assuming the printer resolution is listed as supported here?

https://github.com/qzind/tray/blob/2.0/src/qz/printer/action/PrintPixel.java#L101

Although if that were the case, it would only affect CUPS, right? 😕

**Comment by tresf** [comment]
> Changing rasterize: false results in a good quality print

I don't agree with this statement...  On Mac, this should yield 300dpi print.  Are you getting that with `rasterize` checked?  I'm not.  This is probably 72dpi:

![screen shot 2016-04-30 at 8 37 38 pm](https://cloud.githubusercontent.com/assets/6345473/14939417/7d73cdfa-0f13-11e6-9df1-fa76b48fe6ce.png)



![screen shot 2016-04-30 at 8 37 38 pm](https://cloud.githubusercontent.com/assets/6345473/14939416/677b5d24-0f13-11e6-9bc2-66ecbb9f1a44.png)

**Comment by tresf** [comment]
Unchecking `Scale content` yields a zoomed-in much higher quality print (test still fails, but may help investigation).

![screen shot 2016-04-30 at 8 44 07 pm](https://cloud.githubusercontent.com/assets/6345473/14939429/60a213ac-0f14-11e6-9fe4-fa35b7af7977.png)

**Comment by bberenz** [comment]
> @bberenz is there an order of operations issue going on?

No, we [build the options](https://github.com/qzind/tray/blob/2.0/src/qz/ws/PrintSocketClient.java#L442) object before calling the `parseData` method.

**Comment by tresf** [comment]
@bberenz this goes away when I revert to RC7, so it was introduced with one of our recent commits.  I suspect https://github.com/qzind/tray/commit/4a7ce106a3194da23c0863063a6f4e6cc4e7bdd2 although I'm failing to understand why or how.  Ideas?

RC7 test results (PASS):
![screen shot 2016-04-30 at 9 00 05 pm](https://cloud.githubusercontent.com/assets/6345473/14939472/86f011ec-0f16-11e6-87d4-01c0faa9aa50.png)

**Comment by klabarge** [comment]
> Are you getting that with rasterize checked? I'm not. This is more likely rendering at 72dpi:

You're right... it looks like it is 72dpi.  Perhaps this is a `density` issue?

#### Forcing `density` of 72dpi:

![image](https://cloud.githubusercontent.com/assets/12505463/14944525/f020e800-0fc3-11e6-823c-f424f5f75579.png)


#### Forcing `density` of 300dpi:

![image](https://cloud.githubusercontent.com/assets/12505463/14944532/186adb40-0fc4-11e6-86fc-c7d6750a9cd0.png)

These results are identical with and without `rasterize`

**Comment by bberenz** [comment]
> so it was introduced with one of our recent commits. I suspect 4a7ce10 although I'm failing to understand why or how. Ideas?

Confirmed. Looks like the buffered image might have issues down-scaling our images.
Can you make sure the follow code change to PrintImage doesn't break #38 before I commit?
```java
// Now we perform our rendering
BufferedImage buffer = new BufferedImage(imgToPrint.getWidth(), imgToPrint.getHeight(), imgToPrint.getType());
Graphics2D g2d = buffer.createGraphics();
g2d.drawImage(imgToPrint, 0, 0, imgToPrint.getWidth(), imgToPrint.getHeight(), null);

withRenderHints((Graphics2D)graphics).drawImage(buffer, (int)boundX, (int)boundY, imgW, imgH, null);
g2d.dispose();

// Valid page
return PAGE_EXISTS;
```

**Comment by tresf** [comment]
> Can you make sure the follow code change to PrintImage doesn't break #38 before I commit?

Confirmed, it breaks #38 

Here is the result of `Nearest neighbor` on Mac with the above patch (as I'd expect, the `graphics` object is bugged)

![image](https://cloud.githubusercontent.com/assets/6345473/14972818/42127d0a-10ae-11e6-90b4-1b70fc028a57.png)

**Comment by bberenz** [comment]
Just compared a wide set of down-scaling options, and it's not looking good for OSX, the best we might get is degraded text quality on that platform and smooth prints on windows / linux.

![options](https://cloud.githubusercontent.com/assets/5912715/14991133/e4fced00-112d-11e6-9ae1-fea0e6d2719c.png)
(these all use the default settings on print)

**Comment by tresf** [comment]
Some scale-up results.  Summary, both `nearest-neighbor` as well as `bicubic` quality is better with the addition of 0449418.  Details below.

---


QZ Tray vs. Original Image

**Scale up density** (0449418, dpi branch):
 * Interpolation: `nearest-neighbor`
 * Size: `29KB`

![screen shot 2016-05-04 at 8 15 00 pm](https://cloud.githubusercontent.com/assets/6345473/15033581/236ef3be-123a-11e6-8088-f6dea06f5a67.png)

QZ Tray vs. Original Image

**Original BufferedImage logic** (4a7ce10, RC8/broken):
 * Size: `20KB`
 * Interpolation: `nearest-neighbor`
![screen shot 2016-05-04 at 8 51 46 pm](https://cloud.githubusercontent.com/assets/6345473/15033607/82936be0-123a-11e6-9721-326951ce813a.png)

**`dpi` branch vs. RC7**:
 * Size: `115KB` / `10KB` respectively
 * Interpolation: `Bicubic`

![screen shot 2016-05-04 at 9 01 01 pm](https://cloud.githubusercontent.com/assets/6345473/15033697/8906d1be-123b-11e6-9cff-54e8e6806d59.png)

**Comment by tresf** [comment]
HTML test results, I could find a different in file size or quality between RC7 and RC9.

Here's a star wars release: https://github.com/tresf/tray/releases/tag/v2.0.0-RC9

(May the 4th be with you!)

**Comment by tresf** [comment]
Windows (PASS):

 * No visual differences between RC7 and RC9.
 * File size differences:
  * `bicubic`: `84.7KB`, `85.1KB`, respectively
  * `nearest-neighbor`: `46.5KB`, `45.9KB`, respectively

**Comment by tresf** [comment]
Windows Print HTML (PASS):

 * No visual differences between RC7 and RC9.
 * No file size differences.
