### ISSUE TITLE
Windows installer cannot resume after installing Java

### ISSUE THREAD

**Issue by klabarge** [qzind/tray#455]
When the QZ Tray installer is launched without Java, the software links to AdoptOpenJDK to install Java. Once Java is installed, clicking "OK" to resume the installation still fails to detect Java on the system. The installer needs to be re-launched in order for Java to be detected.

**QZ Tray:** tested against versions 2.0.10-RC4 and 2.0.8
**Java:** tested with AdoptOpenJDK 8 and 11, as well as Oracle Java 7 and 8
**OS:** Windows 10

![image](https://user-images.githubusercontent.com/12505463/58999397-95a55380-87d3-11e9-8856-95507aa65fd5.png)

**Comment by tresf** [comment]
Thanks.  It appears I forget to put the app back in 64-bit registry mode.

https://github.com/qzind/tray/blob/2.0/ant/windows/windows-packager.nsi.in#L109-L123

**Comment by tresf** [comment]
Hmm... that doesn't seem to fix it... still investigating...

**Comment by tresf** [comment]
Ok, so the 64-bit `cscript` fixes it for Oracle JDK8/11, but Adopt appends to the `PATH` environment variable and I'm not sure how to re-read it for a running process...
