### ISSUE TITLE
Untrusted website

### ISSUE THREAD

**Issue by MedAmineBenyettou** [qzind/tray#465]
I tryied to use my own generated certificate by following this Tutorial :

(Link removed)

But I changed the function "setSignaturePromise" to use POST and the one from  :

https://github.com/qzind/tray/blob/2.0/assets/signing/sign-message.js

And here's my function :

```
qz.security.setSignaturePromise(function(toSign) {
  return function(resolve, reject) {
   try {
    var pk = KEYUTIL.getKey(privateKey);
    var sig = new KJUR.crypto.Signature({ alg: "SHA1withRSA" });
    sig.init(pk);
    sig.updateString(toSign);
    var hex = sig.sign();
    console.log("DEBUG: \n\n" + stob64(hextorstr(hex)));
    resolve(stob64(hextorstr(hex)));
   } catch (err) {
    console.error(err);
    reject(err);
   }
  };
 });
```

and here's the php file :

```
// Sample key.  Replace with one used for CSR generation
$KEY = 'key.pem';

$req = $_POST['request'];
$privateKey = openssl_get_privatekey(file_get_contents($KEY));


$signature = null;
openssl_sign($req, $signature, $privateKey);

if ($signature) {
   header("Content-type: text/plain");
   echo base64_encode($signature);
   exit(0);
}

echo '<h1>Error signing message</h1>';
exit(1);

```

But then I get that everything is ok except the Trusted value saying 'Untrusted website'.
Even the FingerPrint is there and OK.

I am using this script with Electron, so that means that this will run locally without a server.

Thanks for any help in advance.

**Comment by tresf** [comment]
Sorry,

We do not assist with bypassing licensing on this bug tracker.

As a hint, if you're using JavaScript, you can do everything client side (no POST, no AJAX).

Best of luck
