### ISSUE TITLE
Printing slows to a crawl on MacOS, Linux

### ISSUE THREAD

**Issue by tresf** [qzind/tray#479]
A major regression in 2.0.10 was discovered as a result of https://github.com/qzind/tray/commit/023843e56da9ab8307a5334601e7ae3c5bf32ab7.  What happened is -- a workaround for printer listings refreshing has caused a major performance bug with CUPS and Java.

More details about the history of this patch are available in https://github.com/qzind/tray/issues/393.  The temporary workaround is to revert QZ Tray to 2.0.9.

Quoting @Vzor- 

> it's interesting how both lines need to execute to cause the bug

```java
import sun.awt.AppContext;
import javax.print.PrintServiceLookup;

public class Main {

    public static void main(String[] args) {
        int count = 0;
        while (true) {
            count++;
            long time1 = System.currentTimeMillis();

            //If either line is commented out, the program will run full speed
            AppContext.getAppContext().put(PrintServiceLookup.class.getDeclaredClasses()[0], null);
            PrintServiceLookup.lookupPrintServices(null, null);

            long time2 = System.currentTimeMillis();

            System.out.println("Try #" + count + " delta time " + (time2 - time1) + " ms");
        }
    }
}
```

**Comment by tresf** [comment]
On MacOS the symptoms are as follows:
* Each `lookupPrintServices` (effectively each print, as we search every time) causes a 2 second delay.
* After approximately 100 calls to `lookupPrintServices`, the delay increases to 20 seconds.
* The 2 second delay continues until another 100 calls.

Over time the delay increases gradually, 2 seconds turns to 4.

**Comment by tresf** [comment]
Upstream bug report filed: https://github.com/AdoptOpenJDK/openjdk-build/issues/1212

**Comment by Vzor-** [comment]
The issue is caused by a 'Printer Listener' thread becoming orphaned when we reinitialize the PrintServiceLookup class. To fix this we can simply interupt() the threads when we go to reinitialize the class. This should stop the issue until we get a safer upstream fix.

            Set<Thread> setOfThread = Thread.getAllStackTraces().keySet();
            for(Thread thread : setOfThread){
                if(thread.getName().equals("PrinterListener")){
                    thread.interrupt();
                }
            }
            AppContext.getAppContext().put(PrintServiceLookup.class.getDeclaredClasses()[0], null);
            PrintServiceLookup.lookupPrintServices(null, null);

**Comment by tresf** [comment]
Patched in 43209f5 (2.1), d6cbc7f (2.0).

These fixes will be available in 2.0.11 and 2.1.0-RC8 respectively.

**Comment by tresf** [comment]
QZ Tray 2.0.11 has been released which corrects this problem. https://qz.io/download/

**Comment by tresf** [comment]
Upstream OpenJDK PR filed https://github.com/openjdk/jdk/pull/16167.
