### ISSUE TITLE
Uncaught (in promise) Error: Cannot parse (BASE64)Ck4KcTYwOQpRMjAzLDI... as a PDF file 

### ISSUE THREAD

**Issue by godfern** [qzind/tray#480]
I'm trying to print a streamed file.

Implementation Steps

- Fetch a pdf file as a stream(application/octet-stream) or (application/pdf) using fetch web api
- Convert the stream file in base64 format
- Pass the base64 data to qztray print
`var data = [{ 
			type: 'pdf',
			format: 'base64',
			data: response
		  }];
QZTrayWrapper.printFile(invoicePrinter, data);`

Getting the below error

```
qz-tray.js?f872:309 Uncaught (in promise) Error: Cannot parse (BASE64)Ck4KcTYwOQpRMjAzLDI2CkI1LDI2LDAsMUEsMyw3LDE1MixCLCIxMjM0IgpBMzEwLDI2LDAsMywx... as a PDF file
    at WebSocket._qz.websocket.connection.onmessage (qz-tray.js?f872:309)
```

**Comment by tresf** [comment]
Base64 is supported.  If it's not printing, your data is wrong.  We'll work on this through email.
