### ISSUE TITLE
Can't force headless mode when GUI available

### ISSUE THREAD

**Issue by miketheath** [qzind/tray#485]
On a Linux (Ubuntu 18.04) host building from the latest source, you are unable to force QZ Tray to run headless if there is a GUI available. It will fail to start with error "Could not start tray manager" and a NullPointerException in qz.common.TrayManager.addMenuItems.

This seems to be related to this condition:
`else if (!GraphicsEnvironment.isHeadless()) {
            tray = TrayType.TASKBAR.init(exitListener);
            tray.setImage(iconCache.getImage(IconCache.Icon.DANGER_ICON, tray.getSize()));
            tray.setToolTip(name);
            tray.showTaskbar();
        }`

This runs if the system supports a GUI, even if you are trying to force QZ Tray into headless mode.

Replacing that snipit with this appears to fix the problem, although I haven't tested any use cases other than headless:
`else if (!GraphicsEnvironment.isHeadless() && !headless) {
            tray = TrayType.TASKBAR.init(exitListener);
            tray.setImage(iconCache.getImage(IconCache.Icon.DANGER_ICON, tray.getSize()));
            tray.setToolTip(name);
            tray.showTaskbar();
        }`

**Comment by bberenz** [comment]
The else just needs changed to `(!headless)` since it covers the environment and user mode checks and the block itself is used for systems running the UI without icon tray support.

Should be fixed in a4426682290be16d80959a387cedb91f003e4587
