### ISSUE TITLE
Image printing when using MM

### ISSUE THREAD

**Issue by klabarge** [qzind/tray#49]
Reproducible on Mac and Windows (Linux untested)

When using `mm` image printing quality is :neutral_face:

However, both `in` and `cm` are fine

![image](https://cloud.githubusercontent.com/assets/12505463/15093352/91e94b44-1453-11e6-84d2-263a1220ebd9.png)

**Comment by tresf** [comment]
Likely introduced with fd535b6. @bberenz any idea?

**Comment by bberenz** [comment]
If you change [PrintImage#82](https://github.com/qzind/tray/blob/2.0/src/qz/printer/action/PrintImage.java#L82) to `dpiScale = (options.getPixelOptions().getDensity() * options.getPixelOptions().getUnits().as1Inch()) / 72.0;` does it fix this issue? (I'm not able to test at the moment)

**Comment by tresf** [comment]
@bberenz building/uploading now.

https://github.com/tresf/tray/releases/tag/v2.0.0-RC11

**Comment by tresf** [comment]
Yes, appears to fix it... Will send patch.

![screen shot 2016-05-07 at 2 07 44 pm](https://cloud.githubusercontent.com/assets/6345473/15093692/1a3b6226-145d-11e6-959a-28eca275f21d.png)
