### ISSUE TITLE
Headless Support

### ISSUE THREAD

**Issue by tresf** [qzind/tray#51]
The Linux community is showing an increasing amount of interest in a headless QZ Tray mode.
* [ ] Everything done via GUI must be well documented (@klabarge)
* [x] Command-line alternative for whitelisting a certificate (done via https://github.com/qzind/tray/commit/ac32c8f00f3319492f78775fc568f63815e68eb0)
* [x] Code must be written in a way to allow soft failure when GUI is not present (done via 5bf6094 d73312f)
* ~~Command line option to functionally disable GUI at launch may be preferred~~ (out of scope)
* ~~Syslog/Log4j support~~ (out of scope)

**Comment by bberenz** [comment]
So this turned out to be much simpler to implement than I anticipated, given that all dialog and tray calls are handled by the TrayManager class.

Basic headless support is ready for testing via b087e4fd6c1b529ad8489669d8016d8acef142d3, this just involves removing any tray interaction and only looking at the allowed sites rather than presenting a dialog (blocking any unknown sites/requests).
It can be enabled by using the `-h` or `--headless` flag, or by including the line `tray.headless=true` in the _prefs.properties_ file.
Worth noting that rasterized html prints still require a window element. I wasn't sure if you wanted this documented or outright blocked.

Aside from the basic headless support, what command-line alternatives do you want included with this feature?

**Comment by tresf** [comment]
> Basic headless support is ready for testing via b087e4f, this just involves removing any tray interaction and only looking at the allowed sites rather than presenting a dialog (blocking any unknown sites/requests).
It can be enabled by using the -h or --headless flag, or by including the line tray.headless=true in the prefs.properties file.

Per "allow soft failure when GUI is not present", do we catch the tray-not-found-ish exceptions yet?  This seems like we could fallback to GUI-less without the explicit directive.

> Worth noting that rasterized html prints still require a window element. I wasn't sure if you wanted this documented or outright blocked.

Roger that.  No need to document this for now but good to know.

> Aside from the basic headless support, what command-line alternatives do you want included with this feature?

Well, any GUI action that isn't intuitive really.  I think for starters, being able to white-list a certificate on command line (or config) is a must.  This way shops have an alternative to "Always Allow".

**Comment by bberenz** [comment]
> ... do we catch the tray-not-found-ish exceptions yet? 

No, though if the `SystemTray.isSupported()` call (TrayManagerL#97) can be relied on, it can easily be adjusted to such.

> ... being able to white-list a certificate on command line (or config) is a must. 

How do you want the command for this to work? `qz-tray.jar --add thiscert.txt` where _thiscert.txt_ is the certificate to whitelist?
Should we include a "remove" command as well, or will we expect that to be handled by just deleting the line in the config file?

**Comment by tresf** [comment]
> No, though if the `SystemTray.isSupported()` call (TrayManagerL#97) can be relied on, it can easily be adjusted to such.

I'd say `--allow` or `--whitelist` and yes, `--block` or `--blacklist` too just for API consistency although I don't fathom anyone using it.  Opinions welcome.  I'm also not sure if we should make it a stub and just exit afterward or if we should start up the software with the command.  I think it would be more conventional to make it a stub.

**Comment by tresf** [comment]
> No, though if the `SystemTray.isSupported()` call (TrayManagerL#97) can be relied on, it can easily be adjusted to such.

I think it can still throw an exception due to some bugs with different OS implementations e.g. https://github.com/qzind/tray/issues/60.

**Comment by bberenz** [comment]
White and black lists via ac32c8f00f3319492f78775fc568f63815e68eb0 (as stub commands)
Forcing headless when the tray fails via d73312f33b796f8aa138f9041a4844d0cb77815d

**Comment by lite1979** [comment]
Ubuntu 14.04, Oracle J8U111: success

Linux Mint 17.3, Oracle J8U101: success

**Comment by lite1979** [comment]
Ubuntu 16.04, OpenJDK8:

could not compile w/openJDK8, but install script built from another machine worked fine. Started fine w/GUI running X, then started fine headless from Terminal (still running X)

**Comment by lite1979** [comment]
Running from TTY1 (or 2,3,4,5, et cetera) with or without X running, QZ-Tray does not launch in headless mode.

https://gist.github.com/lite1979/de08719fa097c0a4ec19fe19293e2011

**Comment by bberenz** [comment]
So even creating the dialogs throws an exception on a truely headless system. I've changed the code around a bit to avoid doing as much via 5bf60941a48e1a7e5c8dc42734abc9b1ed3712ae.

**Comment by lite1979** [comment]
Linux Mint 17.3 (Cinnamon): starts fine after killing X from tty1,2...6
Note: To stop Cinnamon if it's already running: sudo service mdm stop

Ubuntu 14.04 (Unity): starts fine after killing X

**Comment by tresf** [comment]
Positive results on Windows Server 2016 Core

![image](https://cloud.githubusercontent.com/assets/6345473/21381218/fba189ca-c727-11e6-9ffc-9d3532473b88.png)

**Comment by lite1979** [comment]
Working fine on Ubuntu 16.04 after killing X :)

**Comment by dorkbox** [comment]
Of note: The `HeadlessException` (when in headless mode) has been removed from the SystemTray Release Candidate. It now returns a `null` instance.

**Comment by tresf** [comment]
So what is left for this enhancement:

* [ ] A better way to white-list a certificate.  @bberenz ideas?
* [ ] Documentation in the wiki.  Tagging @klabarge

**Comment by klabarge** [comment]
The feature is ready for 2.1 and is [documented here](https://github.com/qzind/tray/wiki/2.1-Headless-Deployment).
