### ISSUE TITLE
windows-keygen.js no openssl missing error

### ISSUE THREAD

**Issue by amishHammer** [qzind/tray#512]
When running:

`
cscript auth\windows-keygen.js . install "hostname" auth\hostname.crt auth\hostnamecrt
`

The script does not generate the intermediate p12 file when openssl is not installed, no meaningful error is reported to the user, only that the p12 file is missing.

**Comment by tresf** [comment]
Thanks for the bug report.  I'm closing as `wontfix` but please don't let this discourage you from submit more bugs reports.  We read and consider every proposal.
