### ISSUE TITLE
 HTML printing blank page is printed intermittently

### ISSUE THREAD

**Issue by sanojmathew** [qzind/tray#513]
i'm trying to use QZ tray 2.1 version due to the print quality issues with the HTML raw printing with the version 2.0.11. 
QZ is intermittently printing blank page for the same HTML content. the attached is the sample HTML file that i'm using. i don't think it is printer driver problem. i'm seeing the same behaviour  while printing to Microsoft XPS using QZ . Below are the configurations that i use

* Java: 1.8.0+144 (64-bit)
* Windows 8.1 Enterprise (64-bit)

```js
let config = {
   jobName: "POD_EE645129012IN",
   margins: "0",
   rasterize: "false",
   scaleContent: "false",
   units: "in",
   size:{width: 5.83, height: 8.27}
}

let printData = [{
   type: 'pixel',
   format: 'html',
   flavor: 'plain'
   data= '<Content of the attached html file>'
}];
```
[pod_1.zip](https://github.com/qzind/tray/files/3820688/pod_1.zip)

**Comment by tresf** [comment]
Thanks.  We'll take a look.

**Comment by sanojmathew** [comment]
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

Windows 8.1 enteprise, 64 bit OS

**Comment by sanojmathew** [comment]
[sampleTest.zip](https://github.com/qzind/tray/files/3821323/sampleTest.zip)
you can replicate the behaviour using the QZ demo test html page as well. I've added the complete html that i'm trying to print in to this sampletest html file for your convenience

**Comment by bberenz** [comment]
@sanojmathew, I'm having trouble replicating your issue, even in a matching environment. How often is this happening for you, and if it's still occurring could you provide us log files from around the incident?

**Comment by sanojmathew** [comment]
[log and xps_file.zip](https://github.com/qzind/tray/files/3826961/log.and.xps_file.zip)
Hi,
i've included the log file during the time xps file was created blank(2019-11-09 08:54:30,878 [INFO] Printing complete) as well as the log file when xps file was not blank (2019-11-09 08:57:53,454 [INFO] Printing complete). 
First time it printed blank and second time i tried again, the content came in successfully.. i m facing this issue intermittent
Please note that i'm using oracle java 1.8 and QC tray source code compiled latest from git (version 2.1.0 -RC7)

Hope this helps

Thanks
Sanoj

**Comment by sanojmathew** [comment]
[blank_screen_video.zip](https://github.com/qzind/tray/files/3827059/blank_screen_video.zip)

@bberenz 
i've the steps to replicate this .. See the attached video as well
1) changed the render width to 9
2) clicked on 'Print HTML' .. it printed the xps file as blank
3) tried second time.. it printed fine 
4) tried third time.. it printed fine
5) changed the render width to 10
6) clicked on 'Print html'.. it printed blank
7) tried second time.. it printed fine 
8) tried third time.. it printed fine

it appears like the changing the configuration and printing the first time is causing the blank screen
Hope this help. I'm using the sampleTest.html attached in my previous comment

**Comment by tresf** [comment]
> changed the render width to 9

Thanks.  This sounds very similar to #225.  We'll re-test with the steps provided.

**Comment by sanojmathew** [comment]
@bberenz / @tresf 
any luck in replicating the issue ?

**Comment by tresf** [comment]
@sanojmathew yes, sorry for the lack of updates here.  @bberenz has successfully reproduced the issue.  It's a previously patched code regression that was reverted (a code regression).

We're able to reproduce it every time now thanks to your steps, thank you.  We have a branch open with code to correct this for regular desktops.  This fix causes a problem with headless environments, so we issue a warning.  The code is completed, but has not yet been merged in to 2.1. https://github.com/qzind/tray/commit/7fe0ce179fef3d958743c127ed5deddc534a1ea2

**Comment by sanojmathew** [comment]
Thanks a lot !

**Comment by tresf** [comment]
@bberenz after using your [unit test](https://github.com/qzind/tray/files/3845134/JfxBugSample.java.zip), I think I got reproducible prints using the following patch... 

```diff
            webView.setMinSize(model.getWebWidth(), model.getWebHeight());
            webView.setPrefSize(model.getWebWidth(), model.getWebHeight());
            webView.setMaxSize(model.getWebWidth(), model.getWebHeight());
            webView.autosize();
+           webView.impl_updatePeer();
```

`impl_updatePeer` is deprecated, but it seems to fix the issue in my tests and should work with headless.

**Comment by tresf** [comment]
Bad news, `impl_updatePeer` is no longer available on JDK11.

**Comment by tresf** [comment]
I think I found a technique that works... 

JavaFX 11 just renamed `impl_updatePeer` to `doUpdatePeer` and made it private.

Using reflection, I should be able to detect and call whichever is available.

```java
// Invoke deprecated/private method for fixing blank pages
// See: https://github.com/qzind/tray/issues/513
// Java 8: impl_updatePeer
// Java 11: doUpdatePeer
String[] methods = { "impl_updatePeer", "doUpdatePeer" };

for(String method : methods) {
    for(Method m : webView.getClass().getDeclaredMethods()) {
        if(m.getName().equals(method)) {
            if(!m.isAccessible()) {
                m.setAccessible(true);
            }
            try {
                m.invoke(webView);
            } catch(IllegalAccessException | InvocationTargetException e) {
                e.printStackTrace();
            }
            break;
        }
    }
}
```

**Comment by tresf** [comment]
* ✅ PASS: Tested 10 prints in a row changing `pageWidth` in between JDK8
* ✅ PASS: Tested 10 prints in a row changing `pageWidth` in between JDK11

New installer with 79f25bb patch is available [here](https://github.com/tresf/tray/releases/tag/v2.1.0-RC7).

**Comment by tresf** [comment]
This issue has been reported upstream:

https://support.gluonhq.com/browse/SUPQZ-1 (license required)
https://bugs.openjdk.java.net/browse/JDK-8235831 (public)
