### ISSUE TITLE
/lib/javafx/linux/javafx-sdk-11.0.2/lib/javafx.graphics.jar class file has wrong version 54.0, should be 52.0

### ISSUE THREAD

**Issue by gloaguen** [qzind/tray#515]
When I run "ant" I get this error, how can I fix this?

compile-socket:
    [mkdir] Created dir: /tmp/qz-tray2.1/out/build/qz-tray
    [javac] Compiling 116 source files to /tmp/qz-tray2.1/out/build/qz-tray
    [javac] /tmp/qz-tray2.1/src/qz/printer/action/PrintHTML.java:14: error: cannot access PrintHelper
    [javac] import com.sun.javafx.print.PrintHelper;
    [javac]                            ^
    [javac]   bad class file: /tmp/qz-tray2.1/lib/javafx/linux/javafx-sdk-11.0.2/lib/javafx.graphics.jar(com/sun/javafx/print/PrintHelper.class)
    [javac]     class file has wrong version 54.0, should be 52.0
    [javac]     Please remove or make sure it appears in the correct subdirectory of the classpath.

installed versions:
ant: 1.10.5
openjdk-8-jdk: 8u222-b10-1ubuntu1 18.04.1
openjfx: 11.0.2+1-1 18.04.2

**Comment by gloaguen** [comment]
I have already found the solution

This may be an issue with the OpenJFX version in the Ubuntu repositories. They currently ship only v11 which is incompatible with OpenJDK 8. You can install OpenJFX v8 explicitly:

sudo apt install openjfx=8u161-b12-1ubuntu2 libopenjfx-java=8u161-b12-1ubuntu2 libopenjfx-jni=8u161-b12-1ubuntu2

**Comment by klabarge** [comment]
@gloaguen thanks for sharing.

Did you manually install OpenJFX prior to compiling the software?

We automatically download JavaFX as part of the `ant` task when it's not bundled with the Java version (and store it here (`~/tray/lib/javafx/`)

![image](https://user-images.githubusercontent.com/12505463/68764241-55e76100-05e8-11ea-9078-34ac6953e651.png)

**Comment by gloaguen** [comment]
@klabarge I first installed only ant and run the installer, but I got the same error. Then I have installed manually openjfx and also got this error. The only method that's working for me is the fix I posted.

**Comment by tresf** [comment]
> Did you manually install OpenJFX prior to compiling the software?
>
> We automatically download JavaFX as part of the ant task when it's not bundled with the Java version (and store it here (~/tray/lib/javafx/)

We do, but it's the same problem he already had, it downloads JavaFX 11, but his build system is using Java 8.  Java 8 needs the matching JavaFX version to compile.

Alternately, switching the compiler to Java 11 would also have worked.
