### ISSUE TITLE
View logs + HTML crashes software on Ubuntu

### ISSUE THREAD

**Issue by klabarge** [qzind/tray#53]
Ubuntu 14.04
1. Open "View Logs"
2. Print HTML
3. Witness QZ Tray crash
   - Printing never happens
   - Cannot close out of View Logs
   - QZ Tray stays on the Launcher (usually goes away quickly when HTML printing)

![image](https://cloud.githubusercontent.com/assets/12505463/15102633/bb567174-156f-11e6-8f3c-66e8d07a7536.png)

The "Untitled window" is the HTML image that gets displayed to the screen and is quickly suppressed.

**Comment by klabarge** [comment]
In case this is of any help,  here is the output where it crashes (I can't copy and paste the log because it's crashed).

![image](https://cloud.githubusercontent.com/assets/12505463/15133462/e57599f0-1630-11e6-9f57-38c0b872313a.png)

**Comment by tresf** [comment]
Yeah, we use some [`interrupting cow`](http://uncyclopedia.wikia.com/wiki/Interrupting_cow) modal dialogs and I have a feeling JafaFX on Linux isn't very happy with this...

**Comment by tresf** [comment]
Turning off modal dialogs didn't fix this.  @bberenz any ideas?  If not perhaps a shim to hide the log dialog on Linux when printing HTML to circumvent the issue?

**Comment by bberenz** [comment]
This isn't a memory issue, is it?

**Comment by tresf** [comment]
@bberenz maybe....   How would we know?

**Comment by bberenz** [comment]
Increase the starting memory, say `-Xms1g` and see if the problem goes away

**Comment by tresf** [comment]
> Increase the starting memory, say -Xms1g and see if the problem goes away

No dice. It actually deadlocks the entire JVM.

If you CTRL+C, you get an interesting stracktrace... 


```
[DEBUG] 2016-05-16 22:44:33,146 @ qz.printer.action.WebApp:?
	Started JavaFX
^C#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f17adbabbf0, pid=21561, tid=0x00007f17f4963700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_92-b14) (build 1.8.0_92-b14)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.92-b14 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libglsl.so+0x14fbf0]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/tres/tray/hs_err_pid21561.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
Aborted (core dumped)
```

In case you're interested in the 1,000-line full crash... 

https://gist.github.com/tresf/3b4d428e719793eb981f0d7d9c1e45e2

**Comment by tresf** [comment]
@bberenz not sure if it's related, but similar at least in description... 
http://stackoverflow.com/questions/27826874/swing-jframe-causes-javafx-application-to-crash-on-os-x

**Comment by tresf** [comment]
The deadlock seems to occur [here](https://github.com/qzind/tray/blob/2.0/src/qz/printer/action/WebApp.java#L133:L139):

```java
        if (instance == null) {
            new Thread() {
                public void run() {
                    Application.launch(WebApp.class);
                }
            }.start();
        }
```

This may be best explained here:  http://stackoverflow.com/a/20420380/3196753 although I'm not sure the exact cause of the deadlock.
