### ISSUE TITLE
QzTray HTML Printing Bug

### ISSUE THREAD

**Issue by Read1337** [qzind/tray#531]
I'm developing a project where I send orders from a APP directly to the kitchen printer in a restaurant, after the payment is confirmed. Everything is working fine but sometimes the "ticket" printed is huge and I can't understand the problem.

Take a look at this examples:
On the right you have a regular ticked printed as expected.
On the left a similar ticket is printed with a huge font.

![IMG_6831](https://user-images.githubusercontent.com/12657826/70797298-21f48c80-1d9c-11ea-8cde-7d3f33f0b887.jpg)

I can reprint the same order multiple times and 1 in 20 tickets is printed in this weird format.
Anyone had a similar issue?

The computer connected with the printer is brand new, running windows 10 and the printer is a TM-T88VI-111

**Comment by klabarge** [comment]
It looks like the "incorrect print" is using `scaleContent: "false"`.

@Read1337 Can you please share with us your printing code, including the HTML that we can reproduce the issue with?

What version of Java are you using? Is it 64-bit?

**Comment by Read1337** [comment]
I changed my code when the problem started so I'm following the promiseLoop provided in the documentation.

`
		function promiseLoop( ret ) 
		{
		    data = JSON.parse(ret);
		    var chain = [];

		    for(var i = 0; i < data.length; i++) {
		        (function(i_) {
		            var link = function() {
		                return qz.printers.find(data[i_]['printer']).then(function(found) {return qz.print(qz.configs.create(data[i_]['printer'], { scaleContent: "true" }), [{type: 'html', format: 'plain', data: '<!DOCTYPE html> <html> <head></head> <body>'+data[i_]['html']+'</body> </html>' }]); }); };
		            chain.push(link);
		        })(i);
		    }
		    var firstLink = new RSVP.Promise(function(r, e) { r(); });
		    var lastLink = null;
		    chain.reduce(function(sequence, link) {
		        lastLink = sequence.then(link);
		        return lastLink;
		    }, firstLink);
		    lastLink.catch(function(err) {
		        console.error(err);
		    });
		}
`
I added the scaleContent as true after your comment.

Here is a sample of the HMTL:

`<div style="width: 100%; text-align: left; font-family: arial, tahoma, helvetica, verdana; font-size:16px; line-height:25px;">
   <div><strong>Mesa: </strong>5</div>
   <div><strong>Data/Hora: </strong>13/12/2019 15:05</div>
   <div><strong>Pedido: </strong>44</div>
   <table id="ImprimirPedidoCozinhaTable" cellpadding="10" cellspacing="0" border="1"  width="100%">
      <tbody>
         <tr style="border-bottom:2px dashed black;">
            <th align="left">Produto</th>
            <th align="left">Quantidade</th>
         </tr>
         <tr>
            <td>Gamba Tigre Gigante</td>
            <td>1</td>
         <tr>
      </tbody>
   </table>
</div>`

The Java installed on the machine is jdk-13.0.1_windows-x64_bin

**Comment by tresf** [comment]
Sounds like the opposite of #505, which we couldn't reproduce. @Read1337 what version of QZ Tray?

**Comment by Read1337** [comment]
The version of QZTray is 2.0.11

**Comment by klabarge** [comment]
@Read1337 I was able to reproduce your exact issue. I'm looking more into the logs now, and will let you know when we have more information.

My environment:

**OS:** Windows 10
**Printer:** Epson TM-T88VI
**Java:** AdoptOpenJDK 11.0.4 64-bit
**QZ Tray:** 2.0.11

**Comment by tresf** [comment]
@klabarge this sounds strikingly familiar to https://github.com/qzind/tray/issues/32 which we assumed at that time was due to some nuances with running Java in a VM.

Despite the difference between versions, I wonder if https://github.com/qzind/tray/pull/516 would help this?  I'll see if I can get a unit test so we don't have to click print 30 times.

**Comment by klabarge** [comment]
> I wonder if #516 would help this?

I'll try it.

> I'll see if I can get a unit test so we don't have to click print 30 times.

I've got a promise loop example for printing 40 jobs

**Comment by Read1337** [comment]
@klabarge thanks for the feedback let me know if you find a solution. I had to change my code and I'm using raw printing instead of HTML had no problems so far. I would like to keep using HTML if possible.

**Comment by klabarge** [comment]
>I wonder if #516 would help this?

I was unable to reproduce this issue in 2.1. I compiled from a commit prior to #516, and I was still unable to reproduce this.

It seems that this issue was fixed somewhere along the way in 2.1...

@Read1337 are you open to using version 2.1 (it's in beta)? We've added many HTML enhancements in 2.1. In addition, we've also baked [looping configs/data into the API](https://github.com/qzind/tray/issues/161#issuecomment-314610362) which should really simplify your code.

**Comment by Read1337** [comment]
> @Read1337 are you open to using version 2.1 (it's in beta)? 
Yeah sure, I'm going to download it today and do some testes while I make the changes to the code.

**Comment by Read1337** [comment]
I installed the 2.1 version and I haven't had the issue.
The only thing that I noticed is a significant diference in "print quality".

This is a ticked printed yesterday:
![IMG_6833](https://user-images.githubusercontent.com/12657826/71077739-eda81400-217f-11ea-93d5-9f2c74a89d63.jpg)

This is a ticked printed today with 2.1 QZTray
![IMG_6834](https://user-images.githubusercontent.com/12657826/71077751-f3055e80-217f-11ea-977b-62c4d0082466.jpg)

This problem is even more noticeable when printing an invoice.

I printed this example with 2.1 installed.
![IMG_6842](https://user-images.githubusercontent.com/12657826/71078851-18936780-2182-11ea-80e9-9991b1b45637.jpg)

I uninstalled 2.1, used 2.0.11 and printed same invoice.
![IMG_6843](https://user-images.githubusercontent.com/12657826/71078964-437dbb80-2182-11ea-8bfd-dd8c27b8f475.jpg)

Close up with more details:
![IMG_6845](https://user-images.githubusercontent.com/12657826/71079000-51334100-2182-11ea-9443-cc65ce964d27.jpg)

**Comment by klabarge** [comment]
@Read1337 Interesting, I am unable to reproduce your issue.

* When you installed QZ Tray 2.1, did you also update the API (`qz-tray.js`) on your webserver?
* Are you using the new syntax for 2.1? https://github.com/qzind/tray/wiki/2.1-Pixel-Printing#html-printing
   * The old syntax should be fully compatible, but I'd like to rule this out

If you still get poor results after the above, we'll need:
* The new code snippet your using in 2.1 (I assume it's changed)
* The logs from the poor print quality: https://github.com/qzind/tray/wiki/FAQ#logs

**Comment by Read1337** [comment]
I was trying to instal QZ Tray 2.1 in my development machine, iMac 27" 2012 running macOS Mojave 10.14.4, but the installation fails.

![Screenshot 2019-12-19 at 09 41 52](https://user-images.githubusercontent.com/12657826/71162993-18f43700-2244-11ea-8f60-2da360113f59.png)

**Comment by Read1337** [comment]
> When you installed QZ Tray 2.1, did you also update the API (qz-tray.js) on your webserver?

This was the problem, I updated the API and the print quality is fixed.
Unfortunately I have a new problem. Now the print is cropped.  

![IMG_6849](https://user-images.githubusercontent.com/12657826/71168910-a2f5cd00-224f-11ea-922c-8355e271e33f.jpg)

Take a look at this example with the new syntax.

```
var config = qz.configs.create("EPSON TM-T88VI Receipt");
var data = [{
   type: 'pixel',
   format: 'html',
   flavor: 'plain',
   data: '<p>123123123</p>'
}];
qz.print(config, data).catch(function(e) { console.error(e); });
```
This is the printing result.
![IMG_6850](https://user-images.githubusercontent.com/12657826/71169170-362f0280-2250-11ea-94a3-0f92a8c61f24.jpg)

**Comment by klabarge** [comment]
@Read1337 It looks like it is printing outside of the printable margins of your paper. You could add a slight margin to your HTML content to prevent this.

```html
<style>
   body {
      margin-left: 1em;
      margin-right: 1em;
   }
</style>
```
Or, you could use the [`margins` in our API](https://qz.io/api/qz.configs#.setDefaults).

Here's my print job using the CSS margins:

![20191223_170239](https://user-images.githubusercontent.com/12505463/71382705-1167c180-25a7-11ea-9012-8e416a1ea151.jpg)

**Comment by Read1337** [comment]
I mande some changes to the HTML and all my issues are fixed.
Thanks for the help and happy holidays.

**Comment by tresf** [comment]
@Read1337 thanks kindly for the update.  I've opened a new bug report https://github.com/qzind/tray/issues/547 to track the status of the 2.0 bug so that it does not get lost.
