### ISSUE TITLE
page-break-* Ignored

### ISSUE THREAD

**Issue by designgears** [qzind/tray#532]
page-break-before: always;
page-break-after: always;

I compiled using the latest commits, 2.1.0-RC9, I'm also not using any `@media` tags.

```
config = qz.configs.create(printer, {
    scaleContent: false,
});

var data = [{
    type: 'pixel',
    format: 'html',
    flavor: 'file',
    data: 'test2.html',
}];
qz.print(config, data).catch(function (e) {
    console.error(e);
});
```

```
<html>
<head>
    <title>Test Page</title>
    <style type="text/css">
        div {
            page-break-after: always;
        }
    </style>
</head>
<body>
    <div>Page 1</div>
    <div>Page 2</div>
    <div>Page 3</div>
</body>
</html>
```

Printing in Chrome: 
![image](https://user-images.githubusercontent.com/799451/70818090-32066f00-1d90-11ea-96b3-ba178a979e99.png)

HTML via QZ:
![image](https://user-images.githubusercontent.com/799451/70818165-5b26ff80-1d90-11ea-8944-1ad7ffac78b2.png)

**Comment by klabarge** [comment]
Unfortunately JavaFX does not honor page breaks.  This is a hard-limitation of JavaFX and we're not aware of an alternative HTML renderer for Java that offers this feature

To accomplish this in 2.1, you'll need to set your HTML page size to the exact length of your print paper.

Closing this, but feel free to comment if you need help getting your HTML correct.

**Comment by designgears** [comment]
I was afraid of that after reading the the limitations with media tags. It's a standard sheet of paper, 8.5x11, how would I go about configuring qz to handle that?

**Comment by klabarge** [comment]
You'll need to make your content pixel-perfect so it fits on 1 page.

Example below sets the `div`'s to be 1056px long. Each div will be printed on a different 8.5x11in page

```js
function printHTML() {
    var config = qz.configs.create("Printer", {scaleContent: false, size: {width: 8.5, height: 11}});

    var printData = [
        {
            type: 'pixel',
            format: 'html',
            flavor: 'plain',
            data:   '<!DOCTYPE html>' +
                    '<html>' +
                    '<head>' +
                    '    <title>Test Page</title>' +
                    '    <style type="text/css">' +
                    '        div {height:1056px;}' +
                    '    </style>' +
                    '</head>' +
                    '<body>' +
                    '    <div>Page 1</div>' +
                    '    <div>Page 2</div>' +
                    '    <div>Page 3</div>' +
                    '    <div>Page 4</div>' +
                    '    <div>Page 5</div>' +
                    '    <div>Page 6</div>' +
                    '    <div>Page 7</div>' +
                    '    <div>Page 8</div>' +
                    '    <div>Page 9</div>' +
                    '    <div>Page 10</div>' +
                    '</body>' +
                    '</html>',
            options: opts
        }
    ];

    qz.print(config, data).catch(function(e) { console.error(e); });
}
```

**Comment by designgears** [comment]
I think works nicely when everything is on a single page, I'm printing anywhere between 1-3 pages per batch. While I can make that work by checking the div size with js and adjusting it to fit 2-3 pages the margin doesn't exist in the content spanning pages so you end up with it getting cut off instead. 

![image](https://user-images.githubusercontent.com/799451/70830488-82d89080-1dad-11ea-89ee-a2e18c903580.png)

I guess I will have to modify my pages to generate a pdf instead, seems like a less error prone way to go.

**Comment by tresf** [comment]
Agreed, PDF is much more reliable.  JavaFX simply lacks any concept of pagination unfortunately.
