### ISSUE TITLE
Display Firefox restart warning

### ISSUE THREAD

**Issue by tresf** [qzind/tray#533]
QZ Tray won't work unless Firefox is restarted after install.  This is fine if Firefox is closed, but poses a problem if Firefox is currently running.

This is a placeholder to raise an install-time warning if Firefox is currently running, optionally adding the option to terminate the process after install.

**Comment by Vzor-** [comment]
I should be able to send firefox a WM_CLOSE message on windows using JNA's [PostMessage](https://github.com/java-native-access/jna/blob/cc1acdac02e4d0dda93ba01bbe3a3435b8933dab/contrib/platform/src/com/sun/jna/platform/win32/User32.java#L824). I could also use the taskkill command. Is there a preference?

**Comment by tresf** [comment]
> I should be able to send firefox a WM_CLOSE message on windows using JNA's PostMessage. I could also use the taskkill command. Is there a preference?

Is there a behavioral difference?
