### ISSUE TITLE
Darkmode icon in Windows Task Manager

### ISSUE THREAD

**Issue by klabarge** [qzind/tray#548]
When using the darkmode theme, the icon in Task Manager is white, making the icon appear missing until it is hovered / clicked on.

**Environment:** QZ Tray 2.1, Windows 10 19.09, AdoptOpenJDk 11.0.4 64-bit

![image](https://user-images.githubusercontent.com/12505463/71583704-9a1dba80-2add-11ea-90ee-a385ca5af319.png)

![image](https://user-images.githubusercontent.com/12505463/71583692-883c1780-2add-11ea-87a3-9a0f620d9070.png)

**Comment by tresf** [comment]
Yeah, the issue is I've historically used the tray icon for the task manager icon.  We need to split the two, but it would first require a separation of the two icon resources, as the dark/light mode icons are created programmatically and currently overwrite the green resource in memory.

**Comment by tresf** [comment]
So this won't fix it in Task Manager, only if a window is showing.  The explanation for this behavior is here:
https://devblogs.microsoft.com/oldnewthing/20180301-00/?p=98135

Quoting:

> [...] A customer had a process which showed only a notification icon most of the time, so they ended up at step 2: Task Manager uses the notification icon. Their notification icon was designed to look good against a dark background (which is the default for the notification are), but it looks bad on a light background (which is the default for Task Manager). They were hoping for a way to specify a custom icon just for Task Manager.
>
> Sorry. There is no custom override just for Task Manager.  [...]
