### ISSUE TITLE
Don't clobber java.library.path

### ISSUE THREAD

**Issue by tresf** [qzind/tray#564]
We should check before setting the library path... 

https://github.com/qzind/tray/blob/822a1695842a776ff5f49d445654230f0e4fe1ae/src/qz/printer/action/WebApp.java#L123

Reasoning: If upstream projects begin to rely on this property, we can have strange behavior once we overwrite it... See also https://github.com/java-native/libloader/issues/6#issuecomment-581506422.

**Comment by bmhm** [comment]
Hi @tresf,

This statement will have no effect. This path can only be set at startup:
https://stackoverflow.com/a/5419120/1549977

**Comment by tresf** [comment]
Wrong, it's used by JavaFX.

**Comment by bmhm** [comment]
@tresf maybe javafx is parsing this property manually. But I can assure you, that the call 
`System.loadLibrary("lib")` will NOT look up updated values set by the program.

**Comment by tresf** [comment]
@bmhm there are many projects which [`get`](https://github.com/search?q=System.getProperty%28%22java.library.path%22%29&type=Code) or [`set`](https://github.com/search?q=System.setProperty%28%22java.library.path%22&type=Code) this standard property.  Please don't assume that the fact that this bug report was inspired by a library in which you maintain that the bug is irrelevant.  You're arguing against code improvements on a project in which you have no affiliation.

> maybe javafx is parsing this property manually

JavaFX DOES parse this value manually.  There's no maybe about it.  It does, otherwise JavaFX won't load (well, the module system is preferred, but this project isn't on code level 9 yet).

This project blindly wipes out whatever value was placed here, and it's our responsibility to track and eventually fix this.

**Comment by tresf** [comment]
FYI, this introduced a regression on Ubuntu, patched via https://github.com/qzind/tray/issues/808#issuecomment-834697189.
