### ISSUE TITLE
Investigate browserstack testing

### ISSUE THREAD

**Issue by tresf** [qzind/tray#565]
https://www.browserstack.com/open-source

@klabarge any interest?

**Comment by klabarge** [comment]
I've created an account and submitted the project to qualify for the Open Source license. We should hear back in 48 hours.

**Comment by klabarge** [comment]
They got back to us already and have given us 5 licenses for their automation tool. This might include the manual testing as well.

I've invited @lite1979 and @tresf for now.

**Comment by tresf** [comment]
@klabarge it appears my browser sessions are limited to one minute.  Are yours doing the same?

**Comment by tresf** [comment]
Hmm... well, Browserstack tests can be automated remotely (e.g. through Java) but I'm not sure how we'd get the browser instance to talk back to a running instance of QZ Tray. Any ideas?

**Comment by tresf** [comment]
![image](https://user-images.githubusercontent.com/6345473/74067258-d25ec580-49c6-11ea-9200-270b26685882.png)

Well, that's a bummer.  They can fire up iOS and Android apps, but not Desktop apps.  Closing.
