### ISSUE TITLE
Support asymmetric density 

### ISSUE THREAD

**Issue by tresf** [qzind/tray#570]
Currently, when specifying density (e.g. `{ density: 300 }`) QZ Tray will create a resolution of 300x300.  However some printers, such as the Dymo Labelwriter 450 support a resolution of 300x600.

By leveraging the Windows print driver, it's possible to obtain this higher quality... 
> <img src="https://user-images.githubusercontent.com/6345473/73961488-aebe5100-48da-11ea-9dd1-d4ab5bad3319.png" width="400px"/>

Note, this does slow printing considerably, but the output is undeniably better.

I would like to propose the following:

* The ability for density to allow asymmetric density values
* The ability for density to be triggered by qualitative keywords, e.g. "Best".

**Comment by bberenz** [comment]
How do we want to go about supporting this in the api? 

- Take an array for [cross, feed] densities 
  - `{ density: [300, 600] }`
- Take an object with cross and feed as the key names
  - `{ density: { cross: 300, feed: 600 } }`
- Add an additional config property for cross density, leaving 'density' as feed density
  - `{ crossDensity: 300, density: 600 }`

And I'm assuming "best" would just go for the highest supported values of both? Are there other string keywords we'd want to support?

**Comment by tresf** [comment]
> 2. `{ density: { cross: 300, feed: 600 } }`

^--- This is the winner.  I'll explain why...

> 1. `{ density: [300, 600] }`

This [allows an array already,](https://qz.io/api/qz.configs#.setDefaults) so it's used up already.

> 3. `{ crossDensity: 300, density: 600 }`

I think `density: { density: ... } }` is confusing.

> And I'm assuming "best" would just go for the highest supported values of both?

Yes.

> Are there other string keywords we'd want to support.

The most common I'm finding are:

* `BEST`
* `NORMAL`
* `DRAFT`

We can probably infer `BEST` and `DRAFT` by choosing the highest and lowest values respectively, but I have no idea how to compute NORMAL.  Since most drivers will ship with `NORMAL` as the default, perhaps we just support the prior and latter for now and then we can do a separate study at a later time (not in this PR) titled "what is `NORMAL`" where we sample a handful of drivers on various platforms to determine if there's a programmatic way to support `NORMAL`.
