### ISSUE TITLE
DNSSD - printers added via this protocol must use "altPrinting: 'true'" to be able to print

### ISSUE THREAD

**Issue by lite1979** [qzind/tray#579]
Adding a printer using "Bonjour" or DNSSD:// in CUPS should be fairly straightforward.

Not all printers support it natively, but Epson thermal receipt printers do, and I have tried to replicate the customer's issue without success. 

What I've tried so far: 

Adding a printer via DNSSD that is on the LAN, sharing that printer, adding that shared printer in MacOS via CUPS. - success - CUPS finds the shared printer, prints to it as expected

Adding a printer via DNSSD that is connected via USB, sharing that printer, adding that shared printer in MacOS via CUPS - success - CUPS finds the shared printer, prints to it as expected

Adding a printer via DNSSD that is connected via USB, sharing that printer, adding that shared printer in Linux Mint 18.3 via CUPS - failure - CUPS does not list the printer as a network printer

**Comment by lite1979** [comment]
Once I can add the DNSSD printer to another Linux system, we will have replicated the environment of the client who originally brought this to our attention, but I cannot definitively make the statement that altPrinting: true is necessary until we replicate.

In both of my tests in MacOS; altPrinting: true was _not_ necessary for a successful print.

**Comment by tresf** [comment]
This is lacking context... the history of this came in through our mailing list... 

> Deep,
>
> Thanks for the patience.
>
>So what I'm seeing:
>
> **WORKS:** Configuring an Epson printer using CUPS web interface and usb:// protocol.
> **DOES NOT WORK:** Configuring an Epson printer using CUPS web interface and dnssd:// protocol.
Can you please try to print to the printer using IP address according to "For Network Printer" on this tutorial?
> 
>
> I believe dnssd (basiciall "Apple Bonjour") is creating problems.  We've never tried using Bonjour for raw printing, so we'll have to reproduce this on our own hardware and reproduce.
> 
> https://qz.io/wiki/setting-up-a-raw-printer-in-ubuntu-linux
> 
> Furthemore, you may have luck specifying { altPrinting: true }.  Lite explained this in the previous post, but it will bypass the driver for raw printing.

Deep then replied with:

>   Tres and Lite , issues is resolved now. Issue was due to absence of `{ altPrinting: true }`, after including this to the config now we are able to print the exact data from both the printer (network and physically connected printer) and also we are able to print the exact data by configure the printer via cups and  directly by ubuntu.
> 
> So issues is resolve now you can close this ticket and thanks once again for your help.

... and then Lite replied with:

> I'm curious, in case we run into another environment that's set up like yours; are you using Avahi for printer discovery? I was trying to reproduce your problem, but I think I was still missing some details. In particular, I could not add a printer using the dnssd:// protocol in either of my Linux machines (one uses Ubuntu 19.04, the other uses Linux Mint 18.3), and using the following command
> 
> ```bash
> lpinfo --include-schemes dnssd -v
>```
> yielded nothing, despite having installed avahi-daemon and having several network-connected printers on my LAN.
> 
> Since this is off-topic, you may reply to me off-list if you prefer.

But since it was our first time using Bonjour with raw/thermal, I wanted to make sure we had tested and reproduced the issue so that we had it documented in our wiki.

So the real question is how to discover a printer using Bonjour on Linux, right?

**Comment by lite1979** [comment]
Correct. I just need to be able to add a DNSSD printer to replicate their environment; perhaps Mint didn't include Bonjour/Avahi capability, or it's in a repo that was removed more recently.

**Comment by lite1979** [comment]
I have added multiple dnssd:// protocol print queues across various Ubuntu-based versions of Linux, using multiple physical printers that have been connected both via ethernet and USB, and and I cannot reproduce the original problem related to using altPrinting: true. All raw print jobs arrived at the destination printer without this flag.

It is possible that the affected client had a unique driver on the host system, or that differing versions of CUPS caused it, but I will close this issue for now, with the recommendation that anyone affected by it should use altPrinting: true

I would also kindly request that anyone affected by this issue provide the linux version, CUPS version, printer make/model, and connection type and network details.
