### ISSUE TITLE
Duplex should support long/short edge

### ISSUE THREAD

**Issue by tresf** [qzind/tray#581]
[`Sides`](https://docs.oracle.com/javase/7/docs/api/javax/print/attribute/standard/Sides.html) offers the following options:
* `DUPLEX`
* `ONE_SIDED`
* `TUMBLE`
* `TWO_SIDED_LONG_EDGE`
* `TWO_SIDED_SHORT_EDGE`

We should offer a string parameter (e.g. "short", "long") so that Duplex can handle these scenarios.  This came up when testing the flipper on a Fargo printer (#573).

Example:

```diff
- qz.configs.create("Fargo", { duplex: true });
+ qz.configs.create("Fargo", { duplex: "short" });
```

**Comment by bberenz** [comment]
Branch `added-duplex` adds support for this. 
A value of "duplex", "two sided long edge", "two sided long", "long edge" or "long" should all work the same (and similar for tumble/short).
