### ISSUE TITLE
Demo raw language should be closer to buttons

### ISSUE THREAD

**Issue by tresf** [qzind/tray#585]
![image](https://user-images.githubusercontent.com/6345473/74546709-01ba8880-4f19-11ea-8a63-8c007dd754bb.png)

**Comment by bberenz** [comment]
Moved in c5f75651f0d57108267d62679b4c267ecb27fd23

**Comment by tresf** [comment]
Looks good!

![image](https://user-images.githubusercontent.com/6345473/74947564-08d61080-53c9-11ea-92d2-395a5b0edd4c.png)
