### ISSUE TITLE
Tray icon wrong color Windows 10

### ISSUE THREAD

**Issue by tresf** [qzind/tray#597]
I think we have some of our logic backwards, the tray icon on Windows 10 sometimes doesn't match the theme.  I believe it's caused on a default Windows 10 install because when I click the theme options it seems to be corrected.

**Comment by klabarge** [comment]
I haven't been able to reproduce this yet. I reverted to a snapshot of a Windows 10 Pro 64-bit fresh installation. First install of QZ Tray honored the dark theme.

![image](https://user-images.githubusercontent.com/12505463/75835381-bdd6d880-5d8c-11ea-84af-7c20c60ee149.png)

I will proceed with installing a VM from scratch to rule out any setting changes I may have made before the snapshot.

**Comment by klabarge** [comment]
After a fresh install of Windows 10 Pro 1909 64-bit, I was still unable to reproduce the tray icon being the incorrect color. I tested using both AdoptOpenJDK 11.0.6 and Oracle Java 8u241.

Here's the default theme options for Windows 10 Pro 1909:

Choose your color: **Custom**
Choose your default Windows mode: **Dark**
Choose your default app mode: **Light**

Each combination of Dark/Light resulted in the correct color QZ Tray icon.

@tresf Do you have any additional information on the environment that reproduces this issue? Perhaps it's a specific version of Windows 10

**Comment by tresf** [comment]
> @tresf Do you have any additional information on the environment that reproduces this issue? Perhaps it's a specific version of Windows 10

I think it is a specific version, or perhaps the consequence of an upgrade.  I've seen this three times remoting into machines now, but never took the time to export these registry keys.

Thanks for the sanity check, at least we know it's correct out of the box.  I'll close this for now and re-open once I can capture details from the environment which causes it.

**Comment by tresf** [comment]
@lite1979's machine is exhibiting this issue currently.  @klabarge can you take a look?

![image](https://user-images.githubusercontent.com/6345473/77092462-39b55f80-69e0-11ea-9f2b-680c2fc21104.png)

**Comment by tresf** [comment]
Found another one today... 
![image](https://user-images.githubusercontent.com/6345473/77253200-2cda7b00-6c2f-11ea-9b07-e61c4858fa10.png)

**Comment by tresf** [comment]
So the issue is that we properly detect that the desktop is NOT using Dark Mode (no value for `SystemUsesLightTheme` or `AppsUseLightTheme`) but the task bar is dark, which means we're falling back to the correct theme for the desktop, but the wrong theme for the icon.  Unfortunately, different versions of Windows seem to ship with different defaults, so any assumptions may end up bring wrong.

![image](https://user-images.githubusercontent.com/6345473/77448979-d2285700-6dc7-11ea-9a46-17c418438a56.png)

Interestingly enough, this computer is running 1909 and the above theme preferences are documented as anything older than 1903, so it appears some type of "keep the current theme" is happening on machines that were upgraded.

I have a theory on how to properly detect and fix this using JNA, but it won't be pretty.  I'll work with @Vzor- to see if he's up for the task.

**Comment by tresf** [comment]
Asked on StackOverflow... https://stackoverflow.com/q/60837862/3196753

**Comment by tresf** [comment]
So I went back to the oldest Windows 10 install I could find (using Rufus) and it appears the window theme should fallback to light mode; the taskbar should fallback to dark mode.

This is a bit different from how we have it coded currently, so the code need to separate the two properties so that the ui elements (such as the About dialog) can utilize the desktop theme while the taskbar utilizes the task bar theme.

Experimenting with these registry value, I can confirm that even the task bar prefers them (it changes immediately when they're changed) so they're the right way to monitor this.

New code available in `dark` branch per 012c03f.

**Comment by tresf** [comment]
New feature in action.  Note it handles the system tray and the window decorating separately.
<img src="https://user-images.githubusercontent.com/6345473/79153618-23f74800-7d9c-11ea-847c-042a6ec6d760.gif" width="400px"/>
