### ISSUE TITLE
Printer Tray Support

### ISSUE THREAD

**Issue by tresf** [qzind/tray#61]
Support for querying and select printer tray on a LaserJet style printer.

**Comment by bberenz** [comment]
Implemented with 6246771eb3ffeb466ae6b64ff7d0eef2e35f5543

**Comment by tresf** [comment]
Great however since 6246771 doesn't yet offer the ability to return a list of printer trays, I'm reopening this until we have the detail API finished.

**Comment by tresf** [comment]
> > are you sure toString() is the best way to parse this object

> ..it's the only way actually.. The constructor takes a single int to follow `EnumSyntax` class, `getCategory` only returns `Media.class`, and `getName` returns the literal string "media" ..

> In regards to the listing we can return an array of what's reported in media (ie `["Manual Feed in Tray 1", "Tray 1", "Tray 2", ...]` and then accept either that exact string or a number and default to "Tray X"?


@bberenz Perhaps I still don't get it.  Can we get the printer tray names using this technique?

http://stackoverflow.com/a/9396884/3196753

---

**Copied from** https://github.com/qzind/tray/issues/47#issuecomment-233833011, "Network printers aren't listing the printer trays."

> > Network printers aren't listing the printer trays.

> What output do you get from the following code for printer `<NAME>`?

> ```java
public static void main(String[] args) {
    PrintService ps = PrintServiceMatcher.matchService("<NAME>");
    for(Media m : (Media[])ps.getSupportedAttributeValues(Media.class, null, null)) {
        System.out.println(m.toString());
    }
}
```

Here's what I get:

```
na-letter
na-legal
executive
iso-a3
iso-a4
iso-a5
jis-b4
jis-b5
b
na-number-10-envelope
iso-designated-long
iso-c5
iso-b5
monarch-envelope
oufuko-postcard
16K
folio
B5 (ISO)
8K
B5 ISO 176x250mm
Double Japan Postcard Rotated
Executive (JIS)
 Printer Auto Select
 Manual Feed in Tray 1
 Tray 1
 Tray 2
 Tray 3
 Tray 4
Unspecified
Plain
Preprinted
Letterhead
Transparency
Prepunched
Labels
Bond
Recycled
Color
Light 60-75 g/m2
Heavy 106-163 g/m2
Cardstock >164 g/m2
Glossy 75-105 g/m2
Heavy glossy
Tough paper
Envelope
```

**Comment by bberenz** [comment]
>  Can we get the printer tray names using this technique?
> http://stackoverflow.com/a/9396884/3196753

We are using this technique. The tray names are literally the `toString` output of the Media class:
```
Printer Auto Select
Manual Feed in Tray 1
Tray 1
Tray 2
Tray 3
Tray 4
```

**Comment by tresf** [comment]
Great, so how do we go about mapping the tray name to our existing interface?

**Comment by bberenz** [comment]
Currently all we do right now is take a number. Then we map that to the matching `Tray N` media class, and apply that to the printer attribute list.
We don't take strings, unless you want us to. Which is what I asked if you wanted earlier. And if we do take a string, it would have to be a match of what is returned from the media iteration.

**Comment by tresf** [comment]
Knowing now that the trays are arbitrarily numbered, the number of the tray won't help so I'll have to recant treat them like printer names.

**Comment by bberenz** [comment]
I don't think it's exactly arbitrary, as the media numbering matches with the physical numbering on the printer I have to test with. 
Regardless, I've adjusted the code so it also takes the full tray name as returned from the Media class (8ac41f2f640e1bbfb975bd619ef469ef38a3fe8d), allowing for any tray option to be selected.

**Comment by tresf** [comment]
> I don't think it's exactly arbitrary, as the media numbering matches with the physical numbering on the printer I have to test with. 

I meant more in regards to `Tray 1` versus media class slot `0`.  e.g. the `Manual Feed` wouldn't have been selectable through an intuitive manner previously.

> I've adjusted the code so it also takes the full tray name as returned from the Media class 

:+1:

**Comment by lite1979** [comment]
P1 - Rotate 180 seems to be working on the Boca now with PDF.

**Comment by tresf** [comment]
Thanks @lite1979 will close.
