### ISSUE TITLE
Landscape PDF with 270° pages prints incorrectly

### ISSUE THREAD

**Issue by tresf** [qzind/tray#617]
Printing the following PDF with "auto" rotation results in the second page being printed incorrectly:

Page 1: Landscape dimensions, no rotation
Page 2: Landscape dimensions, 270° rotation

**Comment by klabarge** [comment]
I tested (on macOS) using the PDF used to identify this issue, and this does fix the bug.

However, I started regression testing and our sample.pdf cannot be landscaped at all with this patch. Using default, `portrait`, and `landscape` orientations yield identical results.

**Comment by klabarge** [comment]
This passes with the last patch (12a7bc00d5bd1e3a6d9d7f692cf76177c4308082).

Tested on macOS using PDF, HTML, and Images.

**Comment by klabarge** [comment]
Also tested on Windows 10 and this looks good 👍
