### ISSUE TITLE
Serial sendData throws NPE if properties are missing

### ISSUE THREAD

**Issue by tresf** [qzind/tray#630]
If a port is opened with a blank configuration, QZ Tray throws a `NullPointerException` when attempting to use `sendData()`

```js
qz.serial.openPort(port).then(() => qz.serial.sendData("foo"));
```

A temporary workaround is to provide an empty properties object:
```js
qz.serial.openPort(port, {} /* <=== HERE */).then(() => qz.serial.sendData("foo"));
```

**Comment by bberenz** [comment]
Should be fixed under 2cffd2e30993967d1d4c5516c225a75c1143115e
