### ISSUE TITLE
Barcode reader - Serial send END

### ISSUE THREAD

**Issue by thbl** [qzind/tray#647]
When open Serial how can i defind the end byte in the option ? 
Using demo.html i tried to set end to "1313" but diddnt work

**data from sample.html ->**
Serial COM9 received output 9
sample.html:2376 Serial COM9 received output 78
sample.html:2376 Serial COM9 received output 87
sample.html:2376 Serial COM9 received output 4
sample.html:2376 Serial COM9 received output 29
sample.html:2376 Serial COM9 received output 40
sample.html:2376 Serial COM9 received output 44
sample.html:2376 Serial COM9 received output 0
sample.html:2376 Serial COM9 received output 

**RAW Data (HEX)**
39 37 38 38 37 34 32 39 34 30 34 34 30 13 13  

**Wanted result**
COM9 received output 788742940440

**Comment by tresf** [comment]
Have you set the length to 1 byte? You cannot use the byte delimiter and the length delimiter at the same time you must choose one or the other.

Please provide a reproducible code snippet if this advice does not help.

**Comment by thbl** [comment]
![image](https://user-images.githubusercontent.com/19774996/83164992-34297380-a10d-11ea-8419-1022f206f015.png)
i just used the sample

**Comment by tresf** [comment]
Currently, the API requires both start and end to be filled out, otherwise it falls back to `STX` for start, which doesn't appear in your data stream.

https://github.com/qzind/tray/blob/1148e5b1fa53022e8b107f981b94bf1559cf89d0/src/qz/communication/SerialIO.java#L83

**Comment by thbl** [comment]
what can i do if i dont have a start byte tho ?
as my barcode reader dont have a start byte just possible to set a end byte

**Comment by tresf** [comment]
I don't know.  We could refactor the API to blindly allow just an end-byte, but then anyone relying on the default `STX`|`ETX` values would regress as a result.

As a stop-gap you can try `start: 'x13', end: 'x13'` but the first scan will probably be skipped, then subsequent scans should come through as normal.

**Comment by thbl** [comment]
i will try play with it tomorrow thanks
is start and stop hex or ascii value ?

**Comment by tresf** [comment]
> is start and stop hex or ascii value

Hex.  Since `x13` is <kbd>Enter</kbd> we might be able to add a feature that captures data until a newline is received so that `start | end` can be avoided.

**Comment by thbl** [comment]
@tresf  i tried to set start and end to 'x13'
and scanned muitple barcodes, but site dont get any date when this is set to x13 :(

**Comment by tresf** [comment]
> and scanned muitple barcodes, but site dont get any date when this is set to x13 :(

I was worried about this because it can potentially return the empty space between the two `x13` values instead.

I think the newline feature will be pretty easy to implement, I've filed a bug report here: #648.

**Comment by thbl** [comment]
@tresf i manged to add x02 and x03 to my reader so thats works now... :)
But when i get date it looks like
![image](https://user-images.githubusercontent.com/19774996/83328821-3a8f2b00-a286-11ea-8db8-1940543525ab.png)

Why is there a CRC for every number  ? (in raw serial terminal i dont have this)

**Comment by tresf** [comment]
> Why is there a CRC for every number ? (in raw serial terminal i dont have this)

Did you set `crcBytes`?

https://github.com/qzind/tray/blob/1148e5b1fa53022e8b107f981b94bf1559cf89d0/src/qz/communication/SerialIO.java#L127

Assuming you're still using `sample.html`, it's good to look at the logs to see what's being sent in the stream, just incase.

Unrelated, but if you have time to checkout #650, that will help us know if it's mergeable, so you can use the device with the default configuration.

**Comment by thbl** [comment]
@tresf  sry late reply been on holiday..
about CRC it works fine it was my fault, i use an arduino usb host, to convert usb barcode scanner to serial, and used println instead of print...
so all good
