### ISSUE TITLE
Serial newline delimeter

### ISSUE THREAD

**Issue by tresf** [qzind/tray#648]
Serial supports start/end/width but in some scenarios the device only sends newline characters.

As observed in #647, the device sends <kbd>Enter</kbd> (ascii `x13`) between scans.

* Capture data between newline characters (`\n|\r`)
* Only send if captured data is not blank

**Comment by tresf** [comment]
@thbl, I don't have a device to test on, but #650 adds experimental support for newline characters.

The syntax is:

```js
var options = {
   rx.untilNewline: true
}
```

If you're comfortable compiling from source, I'd love to know if this works.  Note, this feature is awaiting code review, but due to some 2.1.1 delays it could land on 2.1.1 proper if we have testing and review completed quickly. 🍻

**Comment by thbl** [comment]
@tresf  sry its 1000years since i have programmed java xD and dont have env setup for it :i

**Comment by tresf** [comment]
@thbl no worries.  I'll provide a test build for you.

**Comment by tresf** [comment]
@thbl we've added newline support.  If you'd like a custom build, ping us over at support@qz.io and we'll send you one.
