### ISSUE TITLE
macOS no dialogue when toggling Monocle 

### ISSUE THREAD

**Issue by klabarge** [qzind/tray#655]
There's no dialogue when toggling "Use Monocle for HTML" on macOS. There should be a warning that QZ Tray needs to be restarted.

**Comment by tresf** [comment]
@klabarge are you sure you don't have notifications turned off?

![image](https://user-images.githubusercontent.com/6345473/83768510-df29b800-a64c-11ea-9d3a-dc06bbcd3906.png)

**Comment by tresf** [comment]
![image](https://user-images.githubusercontent.com/6345473/83769036-5eb78700-a64d-11ea-9c7c-40b599afc0d8.png)

I know it's not ideal, but since Moncole should only be turned off on rare occasion, I figure we can use this until we write a better notification system.

**Comment by klabarge** [comment]
Hmm I did have notifications turned off for Java. After enabling, I still don't see the dialogues.

**Comment by klabarge** [comment]
Hmm I did have notifications turned off for Java. After enabling, I still don't see the dialogues.

I also tried running using IntelliJ with the same the results, no errors.

**Comment by klabarge** [comment]
I restarted my laptop, and as soon as QZ Tray launched the dialogues flooded in.... 😕 

<img width="349" alt="image" src="https://user-images.githubusercontent.com/12505463/83830391-05823e80-a6b3-11ea-91c2-fcc3b5cd7b17.png">

**Comment by klabarge** [comment]
Closing as the dialogues are working as expected now.
