### ISSUE TITLE
2.1.0+2 Raw Printing Html Garbled

### ISSUE THREAD

**Issue by xiaoshi164** [qzind/tray#673]
**This is my test code**

[codesandbox](https://codesandbox.io/s/boring-burnell-3dmzm?file=/src/printer.page.tsx)

**Print result**
![image](https://user-images.githubusercontent.com/50538586/84740176-83154b00-afdf-11ea-934b-15808b9c7f7e.png)

**Operating environment**
**Operating System：** windows10
**QZ Tray  Version：**  2.1.0+2
**Openjdk Version：**  11.0.7
**Thermal Printer Model：** XP-80C

**Comment by tresf** [comment]
@showzhou1 by default, `pageWidth` defaults to inches, so you're overflowing the image buffer for this printer.  Can you reduce that to something like `2.2` and see if it's any better?

**Comment by showzhou1** [comment]
@tresf  This is the code i changed：[codesandbox](https://codesandbox.io/s/boring-burnell-3dmzm?file=/src/printer.page.tsx)

**Printer paper is** 72mm
`pageWidth` is set to 2.8 inches

**Print result：**
![image](https://user-images.githubusercontent.com/50538586/84852303-10fc3f00-b08f-11ea-83ec-2fa65cea1d22.png)

**Comment by tresf** [comment]
Sorry I believe I gave some bad sizing advice.  Let me test the code out and get back to you.

**Comment by tresf** [comment]
Sorry for the bad values.. can  you try this:

80mm paper:

```js
{ ..., pageWidth: (80 / 25.4) * 180 }
```

72mm paper:

```js
{ ..., pageWidth: (72 / 25.4) * 180 }
```

Explanation:

-  `72mm` paper ÷ `25.4` mm/in conversion = `2.83` inch paper
-  `2.83` inch paper x `180` dots/in resolution = `510.2` pixels

`pageHeight: ...` should be calculated automatically.

Note, those using 2.1.1, there's a regression, you'll need to provide the undocumented `zoom: 1` value in addition to `pageWidth` above.

**Comment by tresf** [comment]
@showzhou1 also, your text was way too big.  I had to remove the `<h1>` tags and change the `font-size` to something that fit on the paper.

**Comment by showzhou1** [comment]
@tresf Thanks for your advice 

 I made new changes 
**Attach the code** [codesandbox](https://codesandbox.io/s/boring-burnell-3dmzm?file=/src/printer.page.tsx:682-695)

I have removed the `h1` tag , and set `zoom: 1`

If the `width` of the `table` is not set,
**Print result**

![image](https://user-images.githubusercontent.com/50538586/84984111-c5b85e00-b16c-11ea-896a-cabe251817a8.png)

After many attempts, I set the `table` `width: 306px`
**Print result**
![image](https://user-images.githubusercontent.com/50538586/84986335-fdc1a000-b170-11ea-8e91-44cdf05685a5.png)

Looks very unclear

**Comment by tresf** [comment]
Sorry please use `dotDensity: 'double'` which will correct the aspect ratio.  If quality is still bad we may be able to work from 2.1.2 (beta) and yield better results, after testing of #675 is completed.

**Comment by tresf** [comment]
@showzhou1 We've patched the zoom and fixed the density to match most receipt printers.  Can you please remove `zoom` and test the new `2.1.1-RAW-HTML` build here: 

https://github.com/tresf/tray/releases/tag/TEMP

The width will be in pixels, and it will be this way moving forward until we can properly expand the API to accept inches/mm for HTML.  Also please use  `dotDensity: 'double'` which should correct the aspect ratio.

**Comment by tresf** [comment]
Closing, no response from OP.  Please request a reopen if this was closed in error.
