### ISSUE TITLE
Trays aren't properly listing

### ISSUE THREAD

**Issue by tresf** [qzind/tray#679]
QZ Tray currently filters for the word "Tray" when fetching printer trays:

https://github.com/qzind/tray/blob/1781b104314484a83ea1a027b5c65d2d717d8d94/src/qz/printer/PrintServiceMatcher.java#L134-L136

This has serious limitations.  For starters, Dutch calls "Tray 1" "Lade 1" in localized printer drivers.

Second, some printers refer to Trays as a "Cartridge" or even "Auto Select".

QZ Tray should be able to list all trays, regardless of their name.  Instead of filtering by "Tray", we may be able to filter by "MediaTray" type:

```java
for(Media m : (Media[])ps.getSupportedAttributeValues(Media.class, null, null)) { 
     if (m instanceof MediaTray) { jsonService.accumulate("trays", m.toString()); } 
 } 
```

**Comment by bberenz** [comment]
Changes on `tray-selection` branch.
Our actual tray selection seemed to have diverged slightly from what we were finding for listing as well. I've implemented a rather rudimentary fuzzy search so its less dependent on an known strings to match to the tray name (as the original intention was to be able to specify only a number and get the tray of that value).

Both changes could use some testing on your end, as none of the printers I have on hand list trays by number.

**Comment by staalduinen** [comment]
I could assist in testing this. How can I get my hands on a windows executable of this branch?

I've been testing QZ without the actual printer available, by just grabbing the driver of a printer (Xerox 6510 for instance) and attaching it to PDFCreator (on windows). Seems to mimic the actual behaviour of the printer pretty good. But I have access to a few printers with trays.

**Comment by tresf** [comment]
> How can I get my hands on a windows executable of this branch?

@staalduinen thanks for offering, I've produced some temporary builds [here](https://github.com/tresf/tray/releases/tag/TEMP).
