### ISSUE TITLE
Density *Normal OS X

### ISSUE THREAD

**Issue by tresf** [qzind/tray#68]
Some LaserJet printers report `*Normal` instead of `*600dpi`.  We need a way of falling back on a default density when `*Normal` is detected.

Without this, density defaults to `0` for these printers on OS X, causing a hard-crash of QZ Tray.

**Comment by bberenz** [comment]
Code under fe38f7ca02799f8ccdc1431378e7ee4534f4a40f, I don't have an environment that can test this properly though.

**Comment by tresf** [comment]
Testing is underway by a 3rd party.  Will report back with results.

**Comment by tresf** [comment]
Testing passes.  :+1: Closed via fe38f7c.
