### ISSUE TITLE
Waiting on capture v2.0.11

### ISSUE THREAD

**Issue by nathanytc** [qzind/tray#688]
First time asking for help so apologies if you need more info, try to print using QZ tray and it appears to be getting stuck "Waiting on Capture..". Included some of the log below, but it appears to get stuck in this indefinitely. We've got the same setup on 24 different machines but 2 of of them have randomly started doing this. We have recently installed a new firewall on site if that might have anything to do with it but I'm clutching at straws a little bit now, so any help would be greatly appreciated!

Cheers

```
[DEBUG] 2020-07-10 21:02:22,713 @ qz.utils.PrintingUtilities:?
	Allowing 1 simultaneous processors based on memory available (518 MB)
[TRACE] 2020-07-10 21:02:22,714 @ qz.utils.PrintingUtilities:?
	Waiting for processor, 0/1 already in use
[DEBUG] 2020-07-10 21:02:22,723 @ qz.utils.PrintingUtilities:?
	Using qz.printer.action.PrintHTML to print
[DEBUG] 2020-07-10 21:02:22,723 @ qz.printer.PrintServiceMatcher:?
	Searching for PrintService matching Citizen CL-S521
[DEBUG] 2020-07-10 21:02:22,724 @ qz.printer.PrintServiceMatcher:?
	Found 6 printers
[DEBUG] 2020-07-10 21:02:22,724 @ qz.printer.PrintServiceMatcher:?
	Found match: Citizen CL-S521
[DEBUG] 2020-07-10 21:02:22,866 @ qz.utils.PrintingUtilities:?
	Found Resolution: 20300x20300 dphi
[TRACE] 2020-07-10 21:02:22,952 @ qz.printer.action.WebApp:?
	Waiting for JavaFX..
[DEBUG] 2020-07-10 21:02:23,170 @ qz.printer.action.WebApp:?
	Started JavaFX
[DEBUG] 2020-07-10 21:02:23,204 @ qz.printer.action.PrintHTML:?
	Parsed 1 html records
[TRACE] 2020-07-10 21:02:23,205 @ qz.printer.action.WebApp:?
	Waiting on capture..
[TRACE] 2020-07-10 21:02:23,631 @ qz.printer.action.WebApp:?
	Done: -1.0 > 0.0
[TRACE] 2020-07-10 21:02:23,631 @ qz.printer.action.WebApp:?
	New state: READY > SCHEDULED
[TRACE] 2020-07-10 21:02:23,632 @ qz.printer.action.WebApp:?
	New state: SCHEDULED > RUNNING
[TRACE] 2020-07-10 21:02:24,206 @ qz.printer.action.WebApp:?
	Waiting on capture..
[TRACE] 2020-07-10 21:02:25,207 @ qz.printer.action.WebApp:?
	Waiting on capture..
[TRACE] 2020-07-10 21:02:26,214 @ qz.printer.action.WebApp:?
	Waiting on capture..
[TRACE] 2020-07-10 21:02:27,214 @ qz.printer.action.WebApp:?
	Waiting on capture..
[TRACE] 2020-07-10 21:02:28,216 @ qz.printer.action.WebApp:?
	Waiting on capture..
[TRACE] 2020-07-10 21:02:29,218 @ qz.printer.action.WebApp:?
	Waiting on capture..
[TRACE] 2020-07-10 21:02:30,220 @ qz.printer.action.WebApp:?
	Waiting on capture..
[TRACE] 2020-07-10 21:02:31,221 @ qz.printer.action.WebApp:?
	Waiting on capture..
[TRACE] 2020-07-10 21:02:32,222 @ qz.printer.action.WebApp:?
	Waiting on capture..
[TRACE] 2020-07-10 21:02:33,223 @ qz.printer.action.WebApp:?
	Waiting on capture..
[TRACE] 2020-07-10 21:02:34,225 @ qz.printer.action.WebApp:?
	Waiting on capture..
[TRACE] 2020-07-10 21:02:35,227 @ qz.printer.action.WebApp:?
	Waiting on capture..
[TRACE] 2020-07-10 21:02:36,228 @ qz.printer.action.WebApp:?
	Waiting on capture..
[TRACE] 2020-07-10 21:02:37,229 @ qz.printer.action.WebApp:?
	Waiting on capture..
[TRACE] 2020-07-10 21:02:38,232 @ qz.printer.action.WebApp:?
	Waiting on capture..
[TRACE] 2020-07-10 21:02:39,234 @ qz.printer.action.WebApp:?
	Waiting on capture..
[TRACE] 2020-07-10 21:02:40,235 @ qz.printer.action.WebApp:?
	Waiting on capture..
[TRACE] 2020-07-10 21:02:41,237 @ qz.printer.action.WebApp:?
	Waiting on capture..
[TRACE] 2020-07-10 21:02:42,239 @ qz.printer.action.WebApp:?
	Waiting on capture..
```

**Comment by tresf** [comment]
Which version of QZ Tray?  We've made significant improvements to the HTML capture code in both 2.0.12 as well as 2.1.1 which may correct this problem.

**Comment by tresf** [comment]
Oh, I see the title says `v2.0.11`.  Can you try on 2.0.12 and see if it goes away?  We've improved this quite a bit.

**Comment by nathanytc** [comment]
Hi @tresf , that seems to have solved that issue on one of our devices, but now when I go to print Java appears to load the image for printing but it never goes to our printer.  Again I've put an excerpt of the log below, any ideas? Thank you for your help with the first part as well :)

[TRACE] 2020-07-13 17:09:03,338 @ qz.printer.action.WebApp:?
	Waiting on capture..
[TRACE] 2020-07-13 17:09:03,668 @ qz.printer.action.WebApp:?
	Done: -1.0 > 0.0
[TRACE] 2020-07-13 17:09:03,668 @ qz.printer.action.WebApp:?
	New state: READY > SCHEDULED
[TRACE] 2020-07-13 17:09:03,669 @ qz.printer.action.WebApp:?
	New state: SCHEDULED > RUNNING
[TRACE] 2020-07-13 17:09:03,718 @ qz.printer.action.WebApp:?
	Done: 0.0 > 100.0
[TRACE] 2020-07-13 17:09:03,718 @ qz.printer.action.WebApp:?
	New state: RUNNING > SUCCEEDED
[TRACE] 2020-07-13 17:09:03,742 @ qz.printer.action.WebApp:?
	Zooming in by x2.0 for increased quality
[TRACE] 2020-07-13 17:09:03,743 @ qz.printer.action.WebApp:?
	Setting HTML page height to 132.0
[DEBUG] 2020-07-13 17:09:03,754 @ qz.printer.action.WebApp:?
	Attempting image capture
[DEBUG] 2020-07-13 17:09:03,775 @ qz.printer.action.PrintHTML:?
	Parsed 5 html records
[TRACE] 2020-07-13 17:09:03,776 @ qz.printer.action.WebApp:?
	Waiting on capture..
[TRACE] 2020-07-13 17:09:03,799 @ qz.printer.action.WebApp:?
	Done: 100.0 > -1.0
[TRACE] 2020-07-13 17:09:03,799 @ qz.printer.action.WebApp:?
	New state: SUCCEEDED > READY
[TRACE] 2020-07-13 17:09:03,800 @ qz.printer.action.WebApp:?
	Done: -1.0 > 0.0
[TRACE] 2020-07-13 17:09:03,801 @ qz.printer.action.WebApp:?
	New state: READY > SCHEDULED
[TRACE] 2020-07-13 17:09:03,802 @ qz.printer.action.WebApp:?
	New state: SCHEDULED > RUNNING

**Comment by tresf** [comment]
Can you please attach the entire log?  If it contains sensitive information, you can email it to support@qz.io, just reference #688 in the email so we know what it pertains to.

https://qz.io/wiki/faq#logs

**Comment by nathanytc** [comment]
Hi Tres, I've just sent an email across now

**Comment by tresf** [comment]
@nathanytc got it.  The logs don't show that Monocle is being used, which suggests it may be using Java 8 instead of Java 11.

Monocle should fix some issues that are intrinsic to the HTML engine we use, but it's only compatible with Java 11 or higher.

Specifically, AdoptOpenJDK 11 is what we currently recommend.

**Comment by nathanytc** [comment]
@tresf I've just set another log email through, it seems to be stopping at the same point again

**Comment by tresf** [comment]
Thanks kindly, we'll take a look.

**Comment by tresf** [comment]
@nathanytc I've extracted and run your code examples on 2.1.1 and 2.0.12 without issue, but I assume that something about our machines is not the same.

Whereas your logs seem to always stop at:

```
[TRACE] 2020-07-15 16:08:48,385 @ qz.printer.action.WebApp:64
	New state: SCHEDULED > RUNNING
```

Mine continue past this point and print the document.

What's most confusing is the point in which this is failing.  The logs indicate that the test snapshot is fine, indicated by: `Running a test snapshot to size the stage...`, but for some reason the actual HTML snapshot never makes it to `RUNNING > SUCCEEDED` like my machine.


> We have recently installed a new firewall on site if that might have anything to do with it but I'm clutching at straws a little bit now, so any help would be greatly appreciated!

This may be part of the issue.  If the firewall is blocking the image resource, the page may be indefinitely hanging.  If you switch the small image to a base64 embedded image, does the problem go away?

Also, if this is the culprit, I'd expect the problem to happen 100% of the time on this machine.

**Comment by tresf** [comment]
@nathanytc I'm checking in to see if you can troubleshoot the suspicions that we share that this is an environmental problem caused by the firewall preventing that image from loading, thus preventing the entire HTML page to wait.

**Comment by nathanytc** [comment]
@tresf I've been looking into this this morning as well and I believe I've got down to the issue. We use an API to generate a QR code onto the image we are printing and it appears that we cannot access this API at the sites where we are having issues. Apologies for wasting your time on this

**Comment by tresf** [comment]
> Apologies for wasting your time on this

Not at all.  As opposed to other projects, we tend to prefer environmental bug reports, they improve the chances of others finding the same solution. 👍
