### ISSUE TITLE
Getting an exception during headless deployment on Raspberry Pi OS

### ISSUE THREAD

**Issue by petriichuk** [qzind/tray#692]
`
java -jar /opt/qz-tray/qz-tray.jar --whitelist Documents/digital-certificate.txt 

Exception in thread "main" java.lang.ExceptionInInitializerError
	at qz.utils.FileUtilities.addToCertList(Unknown Source)
	at qz.utils.ArgParser.intercept(Unknown Source)
	at qz.ws.PrintSocketServer.main(Unknown Source)
Caused by: java.lang.NullPointerException
	at qz.ws.PrintSocketServer.getTrayProperties(Unknown Source)
	at qz.auth.Certificate.checkOverrideCertPath(Unknown Source)
	at qz.auth.Certificate.<clinit>(Unknown Source)`

**Comment by klabarge** [comment]
@petriichuk Can you please provide us with the QZ Tray, Java (`java -version`), and OS information (`cat /etc/os-release` and `uname -a`)?

We'll likely need to be able to reproduce the issue to assist further.

**Comment by petriichuk** [comment]
@klabarge sure

java -version
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Raspbian-3deb10u1)
OpenJDK Server VM (build 11.0.7+10-post-Raspbian-3deb10u1, mixed mode)

cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

uname -a
Linux raspberrypi 4.19.118-v7+ #1311 SMP Mon Apr 27 14:21:24 BST 2020 armv7l GNU/Linux

**Comment by klabarge** [comment]
@petriichuk thanks. What version of QZ Tray are you using?

It'll take us a bit to get this environment set up.

After that command an `allowed.dat` file should be created/modified under `/home/user/.qz/` with the fingerprint of that certificate. Can you check to see if the `allowed.dat` file was created?

**Comment by petriichuk** [comment]
@klabarge 
I have the latest 2.1.1, 
this file (allowed.dat) exists but empty.

**Comment by tresf** [comment]
@klabarge this bug is reproducible on macOS as well.

**Comment by tresf** [comment]
@petriichuk thanks for reporting.  Here's a one-off build with this bug patched, can you make sure it works for us?

https://github.com/tresf/tray/releases/download/TEMP/qz-tray-2.1.2-NPE.run

**Comment by petriichuk** [comment]
@tresf great, it works. Thank you

**Comment by tresf** [comment]
@petriichuk great thanks.  This will be fixed in the official 2.1.2 release as well at which point the above link will be removed.
