### ISSUE TITLE
Dymo 30336 size can't be configured solely via QZ Tray 

### ISSUE THREAD

**Issue by CindyLulu** [qzind/tray#696]
After sending print configurations to the qz tray client, do we still need to configure the related layout size in the windows printer preference modal?
For example, when I used qz tray to print Dymo 30336 label, even though I sent correct label size for the qz config parameters, the label scale on the printed label was not correct due to the default layout size in windows printer preferences modal was 30252, not 30336. I have to manually adjust the the printer layout size on windows also to make the print layout correct.

**Comment by tresf** [comment]
> After sending print configurations to the qz tray client, do we still need to configure the related layout size in the windows printer preference modal?

Ideally, no. In practice, it seems some drivers honor our dimensions, some do not.  It's probably a bug, but I'm not sure where it lives.  For example, if we send a 4x6 PDF to PDFCreator, it sizes properly, but as you've indicated it's not honored for Dymo printers.

**Comment by CindyLulu** [comment]
Right, I find the zebra driver doesn't have this issue, but Dymo and Rollo meet with this issue. Please let me know if this issue can be fixed in the future. Thanks!

**Comment by tresf** [comment]
Assigning @lite1979 to investigate this as to whether it's a bug with QZ Tray/Java (isolated) or if it's just a bug with the driver implementation in general (affecting apps like Acrobat, etc).

**Comment by lite1979** [comment]
Unfortunately, outside programs cannot override the driver page size settings for the Dymo 450 printers. I have tested this against both QZ-Tray and Adobe Acrobat with the same PDF, intended for 30336 label size, and similar results were observed for both applications when the driver was not set to 30336 (2.13x1").

From the manual, page 10: http://download.dymo.com/dymo/technical-data-sheets/LW%20450%20Series%20Technical%20Reference.pdf

>LabelWriter 450 Series Technical Reference Manual Page 10 The 450 series printers do not compare the label length variables sent by the host with the actual length of the currently loaded label stock. The printers only use the information provided to maintain the logical position counter. In addition, the printer does not check for inter-label gap when printing. It is the responsibility of the host computer to avoid overrunning the label area.
