### ISSUE TITLE
Raw Printer Detection

### ISSUE THREAD

**Issue by tresf** [qzind/tray#71]
**Edit:** This feature will require the addition of the `sift` library, found here: https://github.com/qzind/sift

---

A placeholder for ideas about raw printer detection.

This may be driven by the driver information we're able to get back in #47.  One recommendation was to provide a hosted web service API to lookup a printer's capabilities.  In the event this is available, we may need to inventory the driver information to steer capability lookup.

 * Ideally, QZ Tray would know out-of-the-box whether or not a printer supports raw/pixel printing although some drivers -- such as Zebra's ZDesigner -- support both.
 * This may also involve some JNI against the driver's libraries (DLLs, DYLIBS, SOs, etc) and thus would involve working directly with the printer manufacturer for gathering this information.
 * Another approach may be to use a DPI filter and assume anything with DPI less than 200 is a thermal/raw printer (this isn't necessarily true for Dymos, BTW).

**Comment by tresf** [comment]
This is partially implemented in 2.1, which adds the ability to crawl CUPS and the Windows registry for some driver information.

The puzzle piece to complete this is the following:

> QZ Tray would know out-of-the-box whether or not a printer supports raw/pixel printing 

Which will be implemented as as stand-alone JavaScript helper library called `sift` which will contain the listing of raw printer drivers as well as the listing of well-known virtual printer drivers.  This will be available at `qzind/sift` when 2.1 is closer to a release candidate.

I've come across a new problem for CUPS though... 

Apparently the `.ppd` files are created on-the-fly when a printer is added and they always match the printer name typed into the add printer dialog, which means the current technique needs improvement.

**Comment by tresf** [comment]
> Apparently the `.ppd` files are created on-the-fly when a printer is added and they always match the printer name typed into the add printer dialog, which means the current technique needs improvement.

Fixed via: https://github.com/qzind/tray/commit/838320b2996d3826c37bfa6d25f689e6d65a2d14.  Next steps:

 * Test out the sift library
 * Document the feature for the 2.1 branch.

**Comment by klabarge** [comment]
### Windows Testing

* sift library with the following code:
 ```js
 function detailPrinters() {
    qz.printers.details().then(function(data) {
    console.log(data);

    var data2 = sift.keep( data, { type: 'raw' });
   console.log(data2);
    });
 }
 ```

* available printers:

 ![image](https://cloud.githubusercontent.com/assets/12505463/18975052/654911d4-8675-11e6-9645-2246ce5f8794.png)

**Test 1:** `var data2 = sift.keep( data, { type: 'raw' });`
 
 ✔️ returns just "Raw Print To File"

**Test 2:** `var data2 = sift.toss( data, { type: 'raw' });`

 ✔️ returns everything except "Raw Print To File"

**Comment by tresf** [comment]
@klabarge 👍 .  Shall we add this to the draft 2.1 wiki and close?

**Comment by klabarge** [comment]
I tested the sift library on Windows, Mac, and Linux and it seems to work great!

> Shall we add this to the draft 2.1 wiki and close?

 I added a code snippet to the [2.1 Raw Printing draft](https://github.com/klabarge/qz-tutorials/wiki/2.1-Raw-Printing#filter-printers), although I will need to polish it up a bit.

I will add a similar example to the Pixel Printing guide.

**Comment by CindyLulu** [comment]
Hi @tresf @lite1979, sift library needs driver and name in the data, but currently I didn't find the details function in qz.printers, and qz.printers.find only returns printer names array,  I'm using qz 2.0.6 version. Could you help check the issue?

**Comment by CindyLulu** [comment]
Find the api in qz tray version 2.1

**Comment by tresf** [comment]
> Find the api in qz tray version 2.1

Correct, the raw printer filter is a 2.1-only feature.
