### ISSUE TITLE
Hard crash printing large images

### ISSUE THREAD

**Issue by tresf** [qzind/tray#72]
This affects 2.0.0-stable.

When using the image printing feature, the image is scaled to `8.3x` zoom regardless of it's original size.

Sample `1700 x 2387 px` image [here](https://cloud.githubusercontent.com/assets/6345473/16675414/b328ef10-448e-11e6-827a-09d193488bbd.png).  When this image is printed, it attempts to scale to `8.3x`, which yields `14,110 x 19,812 px` image which crashes the JVM. 

Introduced with the following commit: https://github.com/qzind/tray/commit/04494188f859d956af28f55922b291850c3e773e

```diff
[DEBUG] 2016-07-07 21:30:32,871 @ qz.utils.PrintingUtilities:?
        Found Resolution: 60000x60000 dphi
[DEBUG] 2016-07-07 21:30:33,335 @ qz.printer.action.PrintImage:?
+       Scaling image up by x8.333333333333334
[ERROR] 2016-07-07 21:30:33,676 @ qz.ws.PrintSocketClient:?
        Connection error
java.lang.RuntimeException: Cannot call method public void qz.ws.PrintSocketClient#onMessage(org.eclipse.jetty.websocket.api.Session, java.io.Reader) with args: [org.eclipse.jetty.websocket.common.WebSocketSession, org.eclipse.jetty.websocket.common.message.MessageReader]
        at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.unwrapRuntimeException(CallableMethod.java:93)
        at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:75)
        at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:68)
        at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver$2.run(JettyAnnotatedEventDriver.java:210)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at java.awt.image.DataBufferByte.<init>(Unknown Source)
        at java.awt.image.Raster.createInterleavedRaster(Unknown Source)
        at java.awt.image.BufferedImage.<init>(Unknown Source)
        at qz.printer.action.PrintImage.parseData(Unknown Source)
        at qz.ws.PrintSocketClient.processPrintRequest(Unknown Source)
        at qz.ws.PrintSocketClient.processMessage(Unknown Source)
        at qz.ws.PrintSocketClient.onMessage(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:70)
        ... 5 more
```

**Comment by bberenz** [comment]
How do you best want to handle this? 
The point of the current code is so that any image will be printed at the appropriate DPI for the printer (dpi/72=scale-factor). We scale it up, then draw it at the original size for printing so it retains quality.
Should we cut it off at an arbitrary size or if it is over the page size? If the latter, should there be a difference in how it acts if the 'scale to page' option is turned off?

**Comment by bberenz** [comment]
Code has been adjusted (0f897c5bc955a70bf26acd22b9a14a2a367faf4c) so that for images larger than the page it will assume it is partially scaled to the required dpi and only scale the minimum amount from that point to the printer's dpi.

For instance, with the sample image on a standard letter page, it assumes the image is already at ~200dpi, and will scale by ~x3 to achieve a 600dpi print.

**Comment by klabarge** [comment]
This prints much faster now (about 30 seconds) after that commit.

It looks like the image is getting scaled up twice, does that look right @bberenz ?

```
[DEBUG] 2016-07-14 18:42:46,154 @ qz.utils.PrintingUtilities:?
	Found Resolution: 60000x60000 dphi
[DEBUG] 2016-07-14 18:42:46,445 @ qz.printer.action.PrintImage:?
	Parsed 1 images for printing
[TRACE] 2016-07-14 18:42:46,534 @ qz.printer.action.PrintPixel:?
	DPI: 600.0	CNV: 72.0
[TRACE] 2016-07-14 18:42:46,536 @ qz.printer.action.PrintPixel:?
	Drawable area: 0.0,0.0:8.3,11.7
[TRACE] 2016-07-14 18:42:46,541 @ qz.printer.action.PrintPixel:?
	[60000x60000 dphi, color, (0.0,0.0)->(210.82,297.18)mm]
[INFO] 2016-07-14 18:42:46,542 @ qz.printer.action.PrintPixel:?
	Starting printing (1 copies)
[TRACE] 2016-07-14 18:42:54,456 @ qz.printer.action.PrintImage:?
	Requested page 0 for printing
[DEBUG] 2016-07-14 18:42:54,458 @ qz.printer.action.PrintImage:?
	Scaling image up by x2.9182352941176477
[DEBUG] 2016-07-14 18:43:03,236 @ qz.printer.action.PrintImage:?
	Paper area: 0,0:595,841
[TRACE] 2016-07-14 18:43:03,238 @ qz.printer.action.PrintImage:?
	Image size: 595.3199999999999,835.8
[TRACE] 2016-07-14 18:43:03,242 @ qz.printer.action.PrintImage:?
	{Text-specific antialiasing enable key=Default antialiasing text mode, Stroke normalization control key=Pure stroke conversion for accurate paths, Image interpolation method key=Bicubic image interpolation mode, Fractional metrics enable key=Integer text metrics mode, Global antialiasing enable key=Antialiased rendering mode, Global rendering quality key=Highest quality rendering methods, Color rendering quality key=Highest quality color rendering mode, Alpha blending interpolation method key=Highest quality alpha blending methods, Text-specific LCD contrast key=140}
[TRACE] 2016-07-14 18:43:04,282 @ qz.printer.action.PrintImage:?
	Requested page 0 for printing
[DEBUG] 2016-07-14 18:43:04,283 @ qz.printer.action.PrintImage:?
	Scaling image up by x2.9182352941176477
[DEBUG] 2016-07-14 18:43:12,740 @ qz.printer.action.PrintImage:?
	Paper area: 0,0:595,841
[TRACE] 2016-07-14 18:43:12,742 @ qz.printer.action.PrintImage:?
	Image size: 595.3199999999999,835.8
[TRACE] 2016-07-14 18:43:12,746 @ qz.printer.action.PrintImage:?
	{Text-specific antialiasing enable key=Default antialiasing text mode, Stroke normalization control key=Pure stroke conversion for accurate paths, Image interpolation method key=Bicubic image interpolation mode, Fractional metrics enable key=Integer text metrics mode, Global antialiasing enable key=Antialiased rendering mode, Global rendering quality key=Highest quality rendering methods, Color rendering quality key=Highest quality color rendering mode, Alpha blending interpolation method key=Highest quality alpha blending methods, Text-specific LCD contrast key=140}
[INFO] 2016-07-14 18:43:17,442 @ qz.utils.PrintingUtilities:?
	Printing complete
[TRACE] 2016-07-14 18:43:17,445 @ qz.utils.PrintingUtilities:?
	Returning processor back to pool
```

**Comment by bberenz** [comment]
Not quite. I had to move the logic into the actual print call since it has to be aware of the page size. And each page in a print can get called multiple times depending on the print service used (You can see the line `Requested page _ for printing` everytime this occurs). So there are two separate instances where it draws the page and had to perform the scaling from its original size.

**Comment by tresf** [comment]
> This prints much faster now (about 30 seconds) after that commit.

Kyle and I were testing with a proprietary image which was rendered at 200dpi.  It appears Java isn't handling the 200dpi very well and from research, it's just less fuss to have the clients use 72dpi images.

In my testing with a 200dpi image, printing took 20 seconds.  At 72dpi, printing took 6 seconds.

I also forced nearest neighbor which should be slightly faster rendering and better barcode scan-ability.

I'll create a test build for the client and see if the results are acceptable.

**Comment by tresf** [comment]
@bberenz what is the ended behavior of this new logic when `scaleContent` is set to `false`?

**Comment by tresf** [comment]
> @bberenz what is the ended behavior of this new logic when scaleContent is set to false?

@bberenz any feedback on this?

**Comment by bberenz** [comment]
It scales it the same amount as if it was going to draw scaled to the page.
So the same image used in the posted logs would still scale by `x2.9182352941176477` even if it was still being drawn at its original size.

**Comment by tresf** [comment]
> It scales it the same amount as if it was going to draw scaled to the page.

Should this be the behavior?

**Comment by bberenz** [comment]
That's really up to you. Unless you have another alternative, the options are: no scaling at all, scale up to the dpi, or this custom upscaling.

**Comment by tresf** [comment]
> That's really up to you.

Well, the DPI allows a scaling option to be disabled, so sensibly, I believe "no scaling at all" would be the preferred behavior if `scaleContent` is set to false.

**Comment by bberenz** [comment]
fff8e5f5bb59b61e9da9ac68a4b0c3e0954b33a4

**Comment by tresf** [comment]
Thanks.  @klabarge can you test this functionality please?  If it's all good and working we can close this out.

**Comment by klabarge** [comment]
Setting `scaleContent` to `false` actually makes the image much smaller than the original size.

Scaling should only make the image smaller, not larger, correct?

#### `scaleContent: true`

![image](https://cloud.githubusercontent.com/assets/12505463/17041952/df73e4c8-4f77-11e6-9db1-fdfe4083567b.png)

#### `scaleContent: false`

![image](https://cloud.githubusercontent.com/assets/12505463/17041980/0b4b6030-4f78-11e6-8a79-8dbeca885bd2.png)

**Comment by tresf** [comment]
Scaling will generally make it smaller at 600dpi, but it can have either effect.

If the image, with printer's DPI considered is still larger than the print area, scaling it will shrink.  Otherwise it'll  be bigger when scaling is enabled.

**Comment by klabarge** [comment]
Then I'd say we can close this out  :+1:
