### ISSUE TITLE
Suggested Edit: update SHA algorithm for ruby example

### ISSUE THREAD

**Issue by dougshippit** [qzind/tray#722]
Hi there, I noticed that the example for signing messages in ruby still uses SHA1 . Got stuck on this for a bit until i realised 2.1 uses SHA512.

so in `assets/signing/sign-message.rb`
 `digest   = OpenSSL::Digest.new('sha1')`
should be
` digest = OpenSSL::Digest.new('sha512')`

Cheers,
Doug

**Comment by tresf** [comment]
Hi,

> the example for signing messages in ruby still uses SHA1 

As of https://github.com/qzind/tray/commit/d50b0f7b252ba5b54830a988b9b146136edc50dc#diff-1d8a92d99dbbb2f7ee13b5e5729fb4d8R28, all examples have been updated to use SHA512 so I think this can be safely closed.

**Comment by dougshippit** [comment]
Ah I see, thanks for that. Looks like I was being directed to the 2.0 version via the website. Thanks
