### ISSUE TITLE
Easier Let's Encrypt Support

### ISSUE THREAD

**Issue by dsanders11** [qzind/tray#73]
Now that [Let's Encrypt](https://letsencrypt.org/) is out of beta and is easy to use, it's possible to get a legitimate SSL certificate for free quite easily. I'd love to see it be made easier for QZ Tray to take external certificates rather than generating self-signed ones always.

First, here's a bit more background on the use case I have and why I think free SSL certificates from Let's Encrypt are great. I've got a single label printer (soon to be two) in an office/warehouse environment, where the label printer is connected to a Windows machine in the warehouse. Labels need to be printed from any computer in the building, including office computers. I've chosen not to install QZ Tray on every computer to avoid driver differences between OS versions (mixed environment) and any other potential gotchas. Having all computers interface with the WebSocket works great, and provides a common OS-agnostic interface to send labels to the printer.

Previously the setup was similar to the [Wiki guide for Print Server](https://qz.io/wiki/print-server) although instead of step 3 where a certificate was regenerated, I manually created a certificate and signed it with the root certificate that we've installed on all company computers. This ensures that when we setup extra label printers then they can be trusted by default without having to distribute the certificate generated in step 3 of the Wiki guide.

You can take this a step further (which is what I've done) and get a Let's Encrypt certificate for a subdomain used for internal purposes (in my case it was warehouse.corp.foobar.com). That certificate will be trusted by an modern web browser without any certificate installation, which is awesome. This effectively removes steps 3, 4, and 5 in the Wiki guide, as no certificate must be distributed to clients. I'm not always on site so this is a huge benefit - if a computer breaks and is replaced, or a laptop is swapped in, everything will continue to work with no setup for that computer. No technical knowledge is required by anyone else, just go to the internal website and press print. Can even do it from mobile devices, tablets, etc.

Currently to accomplish this is a little tricky, as there's no tool (that I'm aware of, @tresf correct me if I'm wrong) for nicely packaging up the certificate I get from Let's Encrypt into a JKS to be used by QZ Tray. What I've done is given the private key a password, create a `PCKS #12` keystore with the certificate and the private key, then convert it to a JKS keystore and give the keystore a password, then drop it into place in QZ Tray's folder and change the passwords in `qz-tray.properties` accordingly.

I think it would be great to have a tool similar to step 3 in the Wiki guide, which took in the existing certificate and private key and wrapped it up in a JKS keystore and put it into place for you, including generating a random password and updating `qz-tray.properties`.

This could also possibly be a step in the installer, under some advanced options.

@tresf, thoughts? And thanks for the great product! Loving version 2.0, the new JavaScript interface is very slick.

**Comment by tresf** [comment]
I agree whole heartedly.  This is actually quite commonly requested.

The Java keystore format works great for jetty and jsign, but is often an afterthought for Root CAs.

The only major downside of this technique is any time a Trusted Certificate is available for free to the masses, the repercussions if key leakage become less obvious and encouraging clients to use this technique could quickly start encouraging bad behavior.

But back on topic..... how woudl you envision this feature?  Shim the install-time cert scripts with an additional parameter?

Also, how successful were you getting this technique working?  Last, did you use it for the -trustedRootCert as well?  Would you want this to also shim the 3rd party internal root CA as well?

**Comment by dsanders11** [comment]
> The only major downside of this technique is any time a Trusted Certificate is available for free to the masses, the repercussions if key leakage become less obvious and encouraging clients to use this technique could quickly start encouraging bad behavior.

True, all the information to leak the private key is available in the QZ Tray properties and the key store. Personally I'm OK with this because I trust the security of the print server computer, and the benefits outweigh the small risk.

> But back on topic..... how woudl you envision this feature? Shim the install-time cert scripts with an additional parameter?

Personally I think the 'best implementation' is built into the installer. I'm not familiar with that code (haven't had a need to dig deep into it), but since a normal install generates a self-signed certificate and the JKS keystore, it seems like this is possible. Some sort of advanced setting which lets you provide file paths to the cert and the private key, and the installer would use those to create the JKS keystore instead of generating the self-signed certificate. For simplicity it'd probably want to have an error if the private key is encrypted so it doesn't have to handle prompting the user for the password.

Next best would be a script that could be used similar to the one used to re-generate the self-signed certificate when removing the localhost bindings.

> Also, how successful were you getting this technique working?

Very successful. I upgraded the print server to QZ Tray 2.0 and swapped in the Let's Encrypt certificate in the keystore, updated the client JavaScript to use the new promises framework and got it deployed over the weekend. On Monday no one noticed anything had changed, it worked exactly as it had before (with the added benefit that now any client computer can print with no set up).

> Last, did you use it for the -trustedRootCert as well? Would you want this to also shim the 3rd party internal root CA as well?

I used a separate certificate for the trusted root. I left that the same as before I upgraded to 2.0, which meant less work changing the server software (I think the only thing was the POST request for signing a message changed the JSON from 'message' to 'request').

I like using a separate certificate here as the private key resides only on the server, where it's easier to keep safe. Since that key is the gatekeeper for print access it's good to keep it more secure. If I reused it for the keystore certificate then as you mentioned earlier there's a security risk of that private key leaking, which would compromise the message signing for print requests.

I think #64 covers everything I'd want for dealing with the trusted root certificate. My main concern there is foolproof autostart with the correct trusted root certificate so a power outage doesn't muck with things. Actually had that exact problem earlier (power outage), I found I needed to disable autostart in QZ Tray to ensure that it started with the -trustedRootCert flag via startup files (less than ideal, IMO).

**Comment by tresf** [comment]
@dsanders11 can you hold my hand a bit in how this certificate process works?  It appears there are some Unix command line utilities that seem to be intended to do the entire SSL setup automagically, but I can't find instructions on their site for simply gaining an SSL certificate.  What am I missing?  Did you lie and just use `certbot` and then grab the files from Apache?  What were your preliminary steps to get the cert from LetsEncrypt prior to the JKS conversion?

**Comment by dsanders11** [comment]
You can tell `certbot` to be 'certonly' and avoid the install step, at which point it is web server agnostic and just needs to be pointed to a webroot so that it can place the file (temporarily) it needs to verify domain ownership.

So here are the steps I did:

1. Point target domain at web server (let DNS propagate)
2. Run `certbot` as such: `certbot certonly --webroot /usr/qz/webroot -d target.corp.foobar.com`
3. Retrieve certificate and private key from `/etc/letsencrypt/live/target.corp.foobar.com/` (at least on CentOS)

Some software is adding Let's Encrypt support by being an endpoint for the service to authenticate against (I believe it just needs an HTTP endpoint) like [Docker Distribution](https://github.com/docker/distribution/commit/9198d642ba1d6106623372c6fcd3fac025703a18), but I think that's a bit much for QZ Tray and not what I had in mind. :-) Just pointing it out.

**Comment by tresf** [comment]
Initial support added in the `2.0-letsencrypt` branch via https://github.com/qzind/tray/commit/2a6f740a658524cb1a35ce09fa88cac237781ba7.  Testing appreciated.

Once OK'd, we'll merge in for the 2.0.1 release.

Usage:

**Windows**

 1. Install QZ Tray
 2. Run this command

   ```cmd
cscript "%PROGRAMFILES%\QZ Tray\auth\windows-keygen.js" "%PROGRAMFILES%\QZ Tray" install "" "" "path\to\fullchain.pem" "paht\to\privkey.pem"
```

**Mac**
 1. Install QZ Tray
 2. Run this command
  
   ```bash
sudo "/Applications/QZ Tray/auth/apple-keygen.sh" install "" path/to/fullchain.pem path/to/privkey.pem
```

**Linux**
 1. Parameters must be passed directly to the installer
   
   ```bash
sudo qz-tray-2.x.x.run -- "-y '' path/to/fullchain.pem path/to/privkey.pem"
```

**Comment by tresf** [comment]
> You can tell `certbot` to be 'certonly' and avoid the install step, at which point it is web server agnostic and just needs to be pointed to a webroot so that it can place the file (temporarily) it needs to verify domain ownership.
>
> So here are the steps I did:
> 1. Point target domain at web server (let DNS propagate)
> 2. Run `certbot` as such: `certbot certonly --webroot /usr/qz/webroot -d target.corp.foobar.com`
> 3. Retrieve certificate and private key from `/etc/letsencrypt/live/target.corp.foobar.com/` (at least on CentOS)
> 
> Some software is adding Let's Encrypt support by being an endpoint for the service to authenticate against (I believe it just needs an HTTP endpoint) like [Docker Distribution](https://github.com/docker/distribution/commit/9198d642ba1d6106623372c6fcd3fac025703a18), but I think that's a bit much for QZ Tray and not what I had in mind. :-) Just pointing it out.

@dsanders11 FYI, we'll have the basic framework for this ready once #275 and #491 are resolved.  I'll ping you when there's something code-wise to look at.
