### ISSUE TITLE
One bad URL in multi-URL HTML print job deadlocks QZ-Tray and prints nothing

### ISSUE THREAD

**Issue by lite1979** [qzind/tray#731]
Using printHTML for multiple URLs, if one of the URLs is bad, the entire function will hang, deadlocking QZ-Tray.

Works:

`function printHTML() {
        var config = getUpdatedConfig();
        var opts = getUpdatedOptions(true);
        var printData = [            
            {type: 'html', format: 'file', data: 'https://validurl1.html'},
	    {type: 'html', format: 'file', data: 'https://validurl2.html'},	
	    {type: 'html', format: 'file', data: 'https://validurl3.html'}
        ];
        qz.print(config, printData).catch(displayError);
    }`

Doesn't work:

`function printHTML() {
        var config = getUpdatedConfig();
        var opts = getUpdatedOptions(true);
        var printData = [
            {type: 'html', format: 'file', data: 'https://validurl1.html'},
	    {type: 'html', format: 'file', data: 'https://validurl2.html'},	
	    {type: 'html', format: 'file', data: 'https://invalidurl3.html'},
            {type: 'html', format: 'file', data: 'https://validurl4.html'}
        ];
        qz.print(config, printData).catch(displayError);
    }`

We should be able to ignore the bad URL and continue with printing the valid URLs' HTML, and QZ-Tray should not deadlock on this error.

**Comment by tresf** [comment]
> We should be able to ignore the bad URL and continue with printing the valid URLs' HTML

@bberenz and I discussed and we believe it should still error when the bad URLs are encountered, otherwise there's no way to report the error.

> and QZ-Tray should not deadlock on this error.

Agreed.

**Comment by lite1979** [comment]
After more testing, Windows didn't crash, but the bad URL caused the print spooler to hang. Printing to this queue was interrupted until the bad print job was cancelled.

In both Linux (Ubuntu 20.04), the bad url caused the application to crash, but we could not reproduce this on Ubuntu 18.04

On MacOS Big Sur, the bad url caused the application to crash as well.

Looking into possible conflicts with environment variables for both.
