### ISSUE TITLE
Making qz-tray work on Electron

### ISSUE THREAD

**Issue by astrO1** [qzind/tray#737]
Hi guys,

I have a project in Angular on the web that works fine with qz-tray, now I'm making an electron app from this app that i have and i make the same configuration.

this is my service:

```

    constructor() {

        this.reloadPrint$ = reloadPrint$;

        qz.api.setSha256Type(data => sha256(data));
        qz.api.setPromiseType(resolver => new Promise(resolver));
        
        qz.security.setCertificatePromise(function(resolve, reject) {
          $.ajax(configMain.ROOT_URL + 'js/config/override.crt').then(resolve, reject);
        });
    
        qz.security.setSignaturePromise(function(toSign) {
            return async function(resolve, reject) {
                try {
                  let privateKey;
                    await fetch(configMain.ROOT_URL + 'js/config/key.pem')
                    .then(response => response.text())
                    .then(text => privateKey = text);
                    const pk = KEYUTIL.getKey(privateKey);
                    const sig = new KJUR.crypto.Signature({'alg': 'SHA1withRSA'});
                    sig.init(pk);
                    sig.updateString(toSign);
                    const hex = sig.sign();
                    resolve(stob64(hextorstr(hex)));
                } catch (err) {
                    console.error(err);
                    reject(err);
                }
            };
        });

    }
```

And works great on my Angular on web, but when i make this same approach on my Angular from Electron always show to me, the famous modal from Untrusted Certification, but my certification is fine.

I need to make some additional configuration?

![qztray_electron](https://user-images.githubusercontent.com/4139900/101790288-0de38800-3ae1-11eb-8097-0bb993d4648a.png)

**Comment by tresf** [comment]
I'd recommend starting with [hard-coding the cert in, like we do for the demo](https://github.com/qzind/tray/blob/f3d2d9f58a68349423d59b1a5d50383eb3b90ae6/sample.html#L1245-L1304) just for troubleshooting.  That message "An anonymous request wants to connect to QZ Tray" is a sign that the cert is either empty or invalid.

**Comment by astrO1** [comment]
Hi tresf, thanks for the fast response.

But is strange because I have the same APP on the web and works fine with the same code and I use the same certificate for all my projects.

So I'm thinking that I'm making some mistake that doesn't need additional configuration because is an electron app.

**Comment by tresf** [comment]
Please try the recommended steps.  If they work, you will know your problem lies in the call to `$.ajax(...)` and you can proceed from there.  I'd recommend deleting the certificate entry from Certificate Manager so that you know if the certificate is coming through.

Alternately you can start QZ Tray from command line and inspect the logs for any suspicious data in the `"certificate":` field.  If you don't have a valid cert, you won't be able to use the signing function.

**Comment by astrO1** [comment]
Thank you very much.

It worked with HARD-CODED, i pick the string from another project of mine and put directly and working, I will search what is the problem.

**Comment by tresf** [comment]
Great.   I would recommend trying [`fetch()`](https://qz.io/wiki/signing-messages#loading-the-trusted-certificate) next incase it's a jQuery issue.  If the issue still occurs with `fetch()`, I'd recommend trying to log the failure somewhere and that should allude to the problem.

Note, if you switch to `fetch()` and  the app needs IE support, we have a pollyfill for fetch that we bundle with our demo that will work with IE.

**Comment by astrO1** [comment]
I'm using fetch and now is working perfectly, it was a problem with JQUERY. Thanks

**Comment by tresf** [comment]
Thanks for the update.  Here's the pollyfills for `fetch()` and `Promise()` incase your web app ever gets used in an IE-only environment: https://github.com/qzind/tray/tree/master/js/sample (specifically `whatwg-fetch-3.0.0.min.js`, and `promise-polyfill-8.1.3.min.js`).  I've never tested these with Electron but they're nice to have incase a customer has a strict IE dependency.
