### ISSUE TITLE
Request Blocked.

### ISSUE THREAD

**Issue by chadwalt** [qzind/tray#75]
This is the  error am getting if I press any of the buttons. Error: Request blocked

**Comment by tresf** [comment]
This is usually a sign that "block" was selected when the security dialog was displayed.

Another cause is accidentally clicking "block anonymous" requests through the advanced menu.

What is listed under "block" in the Certificate Manager"?

**Comment by chadwalt** [comment]
where do I find that?

**Comment by tresf** [comment]
From the menu located in the system tray.

**Comment by chadwalt** [comment]
How do I put it right?

**Comment by chadwalt** [comment]
Where do I find that?

**Comment by klabarge** [comment]
You can find this in the system tray by going to QZ Tray > Advanced > Site Manager

![image](https://cloud.githubusercontent.com/assets/12505463/16738186/a76c75b2-4762-11e6-85fa-33d763b703a6.png)

Go to the "Blocked" tab and make sure you did not accidentally block the certificate (delete any entries).

![image](https://cloud.githubusercontent.com/assets/12505463/16738213/c4d8f666-4762-11e6-9c58-dffb25c729dd.png)

**Comment by chadwalt** [comment]
Thanks
