### ISSUE TITLE
Websocket connection is closed. isActive returns true

### ISSUE THREAD

**Issue by jkatsiotis** [qzind/tray#751]
readyState:3 = Connection is closed. Is this a bug or it's intended?

![image](https://user-images.githubusercontent.com/751955/106755770-2f6f7480-6637-11eb-804f-c19c969f660b.png)

**Comment by tresf** [comment]
Thanks for the bug report.  We require steps to reproduce.

**Comment by jkatsiotis** [comment]
Closed callback is being called before setting null the connection while I think it should be the other way round. First make the connection null and then call the closed callback
![image](https://user-images.githubusercontent.com/751955/106761429-7c564980-663d-11eb-9a1f-782c9985ea4f.png)

I am using breakpoints and the "Reload" button of the tray icon to reproduce

**Comment by tresf** [comment]
Yeah, I think you're right.   Probably could be renamed `callClosed` (with a `d`) and placed after nulling the connection, effectively setting `isActive()` to false.

Pinging @bberenz for a second set of eyes.

https://github.com/qzind/tray/blob/9785106e566558fe9168e2882023e2704492f972/js/qz-tray.js#L199-L200

**Comment by jkatsiotis** [comment]
Maybe also check the promise above

**Comment by bberenz** [comment]
It looks like that whole function is calling things in a weird order..
Well there's a pr up to fix it now

**Comment by jkatsiotis** [comment]
When the connection becomes null it looks like the promise can't run on my local copy. Worth taking another look ?

**Comment by bberenz** [comment]
Might need more information on your setup then?
It looks to work for me regardless of how qz losses its connection.

**Comment by tresf** [comment]
@jkatsiotis can you help use reproduce?  If not, we'll merge #754 and close this as resolved.

**Comment by jkatsiotis** [comment]
Feel free to close it

**Comment by tresf** [comment]
Reopening, as the original issues is reproducible until https://github.com/qzind/tray/pull/754 is merged.

**Comment by tresf** [comment]
Closed via d16df4a. 

Since the OP has declined to pursue this further, this is the best we can do for now.

This patch will be available starting with qz-tray.js 2.1.3.
