### ISSUE TITLE
EPL PrintRawPDF only prints tops half of supplied PDF

### ISSUE THREAD

**Issue by lite1979** [qzind/tray#756]
A user brought up that while ZPL PrintRawPDF prints the entire PDF on a Zebra label printer, EPL does not. 

I have reproduced his issue with our sample PDF.

![EPLvsZPLrawPDF](https://user-images.githubusercontent.com/3408749/107822054-7b16d200-6d4b-11eb-96b9-0af32cddf11d.jpg)

**Comment by lite1979** [comment]
This shortened result was caused by the 'Q' value in our rawPDF function, which sets the vertical height in dots.  I was able to print the entire height of the PDF by changing this value to 1218 (203 * 6).

Additionally, the _width_ of the EPL rawPDF print job can be modified with the lower case 'q' value, which I set to 812.

Here's my modified code, as found starting in line 1716 of the current sample.html

`function printRawPDF() {
        var config = getUpdatedConfig();
        var opts = getUpdatedOptions();

        var printData;
        switch(opts.language) {
            case 'EPL':
                printData = [
                    '\nN\n',
                    'q812\n', //set page width in dots (203dpi * 4 inches)
                    'Q1218,26\n', //set page height in dots (203dpi *6 inches)
                    { type: 'raw', format: 'pdf', flavor: 'file', data: 'assets/pdf_sample.pdf', options: opts },
                    '\nP1,1\n'
                ];`

Note: I also used a Render Width (a.k.a. pageWidth ) setting of 812 dots
![updatedEPLresult](https://user-images.githubusercontent.com/3408749/107853952-b6b2aa00-6de6-11eb-9a7f-0865755721ec.jpg)

**Comment by tresf** [comment]
Reopening so we can fix it in our sample directly.

**Comment by tresf** [comment]
@lite1979 reminder, I think you can tackle this in our sample.html.

**Comment by tresf** [comment]
@lite1979 I believe you patched this via 6ce2cbd.  Closing.  Please reopen if I'm wrong.
