### ISSUE TITLE
DYMO Twin Turbo - Left & Right Roll not working for HTML printing (Windows)

### ISSUE THREAD

**Issue by amuhtar** [qzind/tray#759]
Using the Demo page, if I connect to a DYMO LabelWriter 450 Twin Turbo, regardless of the tray selected ("left roll" or "right roll"), the printer will  only print to the last one used.

This is not the case with the Image or PDF print.

On the demo page
* ✅ Print an image to "right roll". (prints to right roll)
* ⛔ Print HTML to "left roll". (prints to right roll)
* ✅ Print a PDF to "left roll". (prints to left roll)
* ✅ Print HTML to "left roll". (prints to left roll).
* ⛔ Print HTML to "right roll". (prints to left roll).

**Comment by tresf** [comment]
@amuhtar thanks kindly for the detailed testing.   We'll attempt to reproduce and escalate accordingly.

**Comment by tresf** [comment]
@amuhtar at a glance it appears the code could benefit from adopting some of our AWT tray selection that we use elsewhere.

https://github.com/qzind/tray/blob/4bed8e38b7eeab08bbae8cc8485c0129a167f92d/src/qz/printer/action/PrintPixel.java#L47-L77

Currently, JavaFX requires a dead-on match,  This means "Roll" would not match "roll".  We'll continue our investigation.

**Comment by amuhtar** [comment]
Ok... I didn't realize the precise tray names were "Left Roll" and "Right Roll".  
Thanks!  Most of the options seem to be lower case.

**Comment by tresf** [comment]
We rewrote the Tray match behavior for HTML to be the same as Images and PDFs, so this should be working as expected now.  Please request a reopen if this issue persists.  This fix will be available starting with QZ Tray 2.1.3.  If you need a build prior, email support@qz.io. 🍻

**Comment by amuhtar** [comment]
Thank you.
I appreciate all the work and effort you and your team have done to make QZ as good as it is!

Andrew
