### ISSUE TITLE
QR code image print result is distorted

### ISSUE THREAD

**Issue by lite1979** [qzind/tray#76]
QR code images should have equal height and width to be scan-able, but the printout here appears to have double width to singular height:

![wp_20160711_002](https://cloud.githubusercontent.com/assets/3408749/16752015/ed8ee928-47ab-11e6-8a24-dd2f4e7afc31.jpg)

Changing print density does not help. This occurs on a Posifiles PP-6900 thermal receipt printer.

Relevant code block:

https://github.com/qzind/tray/blob/2.0/src/qz/printer/ImageWrapper.java

**Comment by bberenz** [comment]
Can you provide logs of the print?
And is this using the raw printing or pixel printing? As image printing should keep any aspect ratio, and the text appears fine.

**Comment by tresf** [comment]
This is raw, and likely printer specific.

**Comment by lite1979** [comment]
Confirmed on a TM-T88V. The density parameter _used_ to adjust the width of the image, but it no longer does this. Single and Double density print jobs look the same for both the user's .png file and our sample .png file:

![img_20160712_104121857](https://cloud.githubusercontent.com/assets/3408749/16771206/a10f5cb4-481d-11e6-8051-9c902c4ae7bb.jpg)

**Comment by lite1979** [comment]
Log of both prints (with stock .png file) here:

https://gist.github.com/lite1979/2dd3e4b8c846122c895a889cc9c819ca

Perhaps printing to file will give us more insight.

**Comment by bberenz** [comment]
Double checked if the dot density was being set correctly after your previous post. Turns out the class has been trying the wrong parameter name the entire time..
Can you verify if ec63645d1a5f86e74fbfe234647222b3c712f883 fixes this issue?

**Comment by Majstr** [comment]
Tested on Posifiles PP-6900. Now QR code is printed correctly.

**Comment by tresf** [comment]
> Tested on Posifiles PP-6900. Now QR code is printed correctly.

:+1:   Fixed via ec63645.
