### ISSUE TITLE
Add orientation flag to rawHTML printing

### ISSUE THREAD

**Issue by lite1979** [qzind/tray#762]
Users want to be able to manipulate the raster graphic when sending rawHTML data to printers using ZPL. 

This is currently not possible with QZ-Tray.

This feature could also enhance abilities for EPL and ESC/POS if we can make it work with ZPL.

My first thought is to study the ZPL manual for an option to adjust orientation for the raster image.

**Comment by tresf** [comment]
> My first thought is to study the ZPL manual for an option to adjust orientation for the raster image.

Yes, but this won't scale well, we'd have to inject more raw for ESC/POS and EPL, if they support this.

I think this is best short-term to handle via CSS, long-term through something like rotation.  Rotation might be the easiest.  Orientation is really reserved for when we know the paper dimensions and raw bypasses all of that stuff.

**Comment by MilanVilov** [comment]
Thank you, the rotation with transform function works well enough. :)

**Comment by tresf** [comment]
Related #506

**Comment by lite1979** [comment]
Tested using both rotation: '90' and orientation: 'landscape' in the config for the following languages:

 ESC/POS, EPL, and ZPL - all work as expected

Tested regular raw image, PDF and HTML printing with a stock sample.html from 2.1.2 and I did not observe any regressions.

Also tested Pixel printing with orientation and rotation options with a stock sample.html from 2.1.2 and no regressions were observed.
