### ISSUE TITLE
PC reboot after scanning printers

### ISSUE THREAD

**Issue by aldesrahim** [qzind/tray#773]
Hello, i'm current nya using a 2.1.2 version of QZ Tray and somehow the PC rebooting after i clicked the allow button when prompted, but i'm really confused why, because i tried on my laptop and it works fine, i dont know what cause this but i think its from java (?). anyways thanks in advance.

**Comment by tresf** [comment]
This isn't a bug with QZ Tray, bit rather a Windows update bug.  More information here: https://www.theverge.com/2021/3/15/22332916/windows-10-update-fixes-printer-blue-screen-of-death-issue-crash-microsoft
