### ISSUE TITLE
Support encoding for non-String formats

### ISSUE THREAD

**Issue by tresf** [qzind/tray#774]
Currently, encoding conversions [only apply to `PLAIN` formats](https://github.com/qzind/tray/blob/c2bf27b13c86c675efd6da811c2987f843888109/src/qz/printer/action/PrintRaw.java#L139).

In some occasions, data may be provided in `BASE64`, `FILE` (or even `HEX`) in the wrong encoding and a programmer may wish to leverage Java to do encoding conversion.

One potential downside of this is, it assumes quite a few things:
* It assumes the data being sent can easily be converted to String
* It assumes the data being sent can be guessed as UTF8<br>---- OR ----
* It would require informing Java about the source format as to make no assumptions

I'm thinking we can use something like:

```js
{ encoding: 'Cp1252', sourceEncoding: 'UTF8' }
``` 

Or perhaps... 
```js
{ encoding: 'UTF8:Cp1252' }
```

... although this may be undesired, since a colon is a valid delimiter in some encodings [aliases](https://docs.oracle.com/javase/8/docs/technotes/guides/intl/encoding.doc.html) like `ISO_8859-1:1987`.

Or perhaps... 
```js
{ encoding: { from: 'UTF8', to: 'Cp1252' } }
```

We should also add a warning for all raw formats that have provided `encoding` and it's being ignored.  It can then hint to supply `sourceEncoding`|`from:` to remedy the issue.

**Comment by bberenz** [comment]
Not sure this is needed since we never convert base64, file, or hex to string values?
We only need an encoding for strings to know how to get them to their byte format; the rest of the formats are decoded straight to a byte array and appended to the raw commands.

**Comment by tresf** [comment]
> Not sure this is needed since we never convert base64, file, or hex to string

No, but I'd like the option to as the flavors may be out of the control of the programmer, and I'd like to offer explicit control.
