### ISSUE TITLE
Pole Display

### ISSUE THREAD

**Issue by Read1337** [qzind/tray#779]
I'm trying to develop am integration with a "Pole display/Client Display" with QzTray for my software. I saw the presentation video and it looks like they are supported. I started testing with one of these devices, connected via USB, but I don't know how to send the information to the display. I think that the usb is providing me a COM port but the display doesn't show anything when I try to send data to it.

I've been using qztray for a while now and successufly integrated printers and scales but I cant get this display working.

Can someone point me to the right direction? I tried a lot of the Demo options on the website but none worked for me.

**Comment by tresf** [comment]
We've had issues too; the commands aren't very well known. Can you please share the make and model?

**Comment by Read1337** [comment]
After 1 day trying everything to work I found that I had a faulty display.
Now I have a new display and I can use the demo page to test and figure how to implement the communication.

The default send Command is writing a JSON that's not being parsed by the display.

If i try to write some string to the display ( for example "teste 123" ). It works, but the next string will be append right after the old one, I need something to clear the screen. I imagine that there are specific commands to clear the screen, change line etc. I tried to search but no luck.

![IMG_0860](https://user-images.githubusercontent.com/12657826/113591308-a3280080-962b-11eb-909b-da578464be0b.jpg)

![IMG_0858](https://user-images.githubusercontent.com/12657826/113591330-a8854b00-962b-11eb-8275-0aa16ee4b73d.jpg)

**Comment by tresf** [comment]
If it's compatible with Bematech's standard, you can try `\x0E` to clear it.

http://www.bematechus.com/wp-content/uploads/2014/09/PDX_LDX_LTX_UserManual.pdf ([mirror](https://drive.google.com/file/d/1Ti6JsWcT7L4lmZHKvJU42VS0OjOLyjzL/view?usp=sharing))

**Comment by tresf** [comment]
@Read1337 Hi, checking in to see if you require further help with this?

**Comment by tresf** [comment]
@Read1337 closing to due to lack of response.  Feel free to request a reopen if needed.
