### ISSUE TITLE
EPSON TM-T20III always reporting status OK

### ISSUE THREAD

**Issue by DaniWinter** [qzind/tray#784]
For my application I need to display a message when the printer has no paper left, however when asking for printer status it always reports: OK: Level INFO, StatusCode 0, From EPSON TM-T20III Receipt

Even when the paper is out or the lid is open.

**Comment by tresf** [comment]
@DaniWinter closing due to lack of response.  Feel free to request a re-open if needed.  Note, the above features will be available starting with QZ Tray 2.1.3, expected this week.
