### ISSUE TITLE
Serial RFID support

### ISSUE THREAD

**Issue by momoko-squid** [qzind/tray#795]
Hello, 
Just got my hands on this gadget
![178011803_2821694291288506_531642086798480342_n](https://user-images.githubusercontent.com/56092911/116700097-f7d75500-a9f8-11eb-8674-f421393c328a.jpg)

This is an affordable RFID, QR code, Barcode scanner; 3-in-1 device!!
And it's available in  RS232 and USB mode!

Everything works fine, EXCEPT the device return the **\<data\>\x0d\x0a**. This means the device is using \x0d\0x0a as delimeter!

When I set the **untilNewline:true**, the effect is that I don't get data from every card I tap. It's like maybe I  tap 3 times, 1 get 2 strings. I think it's because of the double newlines that are being used to delimit the data.

Can we configure Qz to allow both together?

**Comment by momoko-squid** [comment]
Sorry, what I meant was, that the data is delimited by ]\x0d\0xa. So,

**Comment by tresf** [comment]
> Everything works fine, EXCEPT the device return the <data>\x0d\x0a. This means the device is using \x0d\0x0a as delimeter!

Yeah, we don't yet support an end delimiter without a beginning, but it seems like a bug with how we're parsing newlines.  CR LF is common and we should handle it.

@bberenz do you think something like this would work?

https://gist.github.com/tresf/b766c4c6442de276b1d2c90dfcdde677

**Comment by bberenz** [comment]
@tresf, looks like it should work

**Comment by tresf** [comment]
@momoko-squid 
Can you test these builds and see if it fixes the issues you're having?

Windows:
https://github.com/tresf/tray/releases/download/TEMP/qz-tray-2.1.2+NEWLINE.exe

Mac:
https://github.com/tresf/tray/releases/download/TEMP/qz-tray-2.1.2+NEWLINE.pkg

Linux:
https://github.com/tresf/tray/releases/download/TEMP/qz-tray-2.1.2+NEWLINE.run

**Comment by tresf** [comment]
@momoko-squid we'll have this feature ready in QZ Tray 2.1.4.  If you get time to confirm the patch, please let me know, I'd be happy to provide new desktop installers.
