### ISSUE TITLE
Firefox blocks localhost cert unless user goes to https://localhost:8181 and manually accepts the cert

### ISSUE THREAD

**Issue by lite1979** [qzind/tray#796]
QZ-Tray 2.1.3-RC.1, AdoptOpenJDK 11, HotSpot, Ubuntu 20.04, Firefox 88.0

After being prompted to restart Firefox, navigating to https://demo.qz.io will not work unless the user specifically navigates to https://localhost:8181 and chooses to accept the risk

**Comment by lite1979** [comment]
![Screenshot from 2021-05-03 12-02-01](https://user-images.githubusercontent.com/3408749/116901025-70136580-ac07-11eb-97c1-f30ef53c1b04.png)

**Comment by lite1979** [comment]
![Screenshot from 2021-05-03 12-03-09](https://user-images.githubusercontent.com/3408749/116901139-91745180-ac07-11eb-8134-22495bdbac9e.png)
![Screenshot from 2021-05-03 12-03-45](https://user-images.githubusercontent.com/3408749/116901219-a4872180-ac07-11eb-9569-115c191fdae1.png)

**Comment by tresf** [comment]
Tested with latest master branch, and it seems OK.

Please retest against 2.1.3-RC.1 and let me know if it still happens.

![image](https://user-images.githubusercontent.com/6345473/116909010-95a56c80-ac11-11eb-9aa4-37fc5fd5c969.png)

**Comment by tresf** [comment]
For some reason on Lite's machine, the `PemWriter` will preserve the old certificate and write the new certificate over it, sometimes leaving trailing data.  This might be a bug with `PemWriter`, but for now, we'll just delete the file before writing.

**Comment by zaqueoae** [comment]
Is there any solution to this problem?
It is happening to me with qz 2.2., ubuntu 22.04, openjdk version "11.0.15" and with chrome and firefox.

Regards

**Comment by zaqueoae** [comment]
> For some reason on Lite's machine, the `PemWriter` will preserve the old certificate and write the new certificate over it, sometimes leaving trailing data. This might be a bug with `PemWriter`, but for now, we'll just delete the file before writing.

¿Podrías decirme la ruta del archivo que hay que borrar? ¿Sería una solución permanente?
Gracias.

**Comment by tresf** [comment]
> 

This issue is resolved.  If you're having a similar issue, please open a new bug report with as many details as possible.
