### ISSUE TITLE
USB Read Data Frozen Values

### ISSUE THREAD

**Issue by dsanders11** [qzind/tray#81]
**OS**: Windows 7
**QZ Tray Version**: 2.0.0
**USB Device**: Dymo M10 Digital Postal Scale
* * *
I'm finding that I'm getting the same value returned every time I try to read USB data from the scale, if I read the values individually. It appears to freeze to the value the first time it is read on a new QZ Tray instance. The value stays frozen no matter what the weight on the scale is, and persists between connects to QZ Tray.

Steps to Reproduce:
1. Open demo and connect to QZ Tray
2. Read scale via 'Read Raw Data' with nothing on it
3. Place items on scale
4. Read scale again via 'Read Raw Data'

The reads are the same in my testing, despite the weight change.

**However**, if I have an open stream and do individual 'Read Raw Data' calls, the values are different with each read.

Another observation is that if you set a longer (for a computer) 'Stream Interval' such as 500ms, the streaming values get behind.

Steps to Reproduce:
1. Open demo and connect to QZ Tray
2. 'Open Stream' for USB scale
3. Change weights on scale and observe stream value

It seems to get further and further behind, if you let it run for 20 seconds, it will take seconds to hit 0 after removing everything from the scale.

* * *

Working Theory
---

Based on those two data points I believe that what is happening is that the for some reason after the initial `syncSubmit` read of the USB data, that subsequent reads are reading from a buffer. This is why streaming gets behind if there's a longer 'Stream Interval' and that's why it appears that individual reads are duplicates. The individual reads aren't duplicates, it's just that the scale sent out dozens of packets with that weight reading, and each read is pulling them off the buffer one at a time.

This actually matches with behavior I've seen where a read did seem to change value at some point, and I'd previously thought it was random.

**Comment by tresf** [comment]
Yeah, we're well aware.  It appears to be a problem with the way the library reads data.  We've recommended streaming the data instead (which isn't as convenient with a user-driven poll request, but it's the best we can offer at this time).

We're open to ideas though but we put quite a bit of research into it and were unable to get a "live" read of the scale without streaming.

**Comment by tresf** [comment]
Also, somewhat related, the USB library won't work on Mac, so we've added a new HID tab.  I believe it still suffers the same bug though.

**Comment by dsanders11** [comment]
I've opened [a bug report with libusb](https://github.com/libusb/libusb/issues/196) as a result of my digging into the issue. I was able to reproduce the issue with libusb1, a thin Python wrapper around libusb which makes me pretty confident that is where the issue is. It seems to start buffering the moment a device handle is created for the USB device, even before an interface is claimed.

Unfortunately the streaming option isn't great for me as we need the scale to stay active for a bit and the computer it is running on is old and known to momentarily freeze. Once it falls behind on reading the scale data it is going to become noticeably laggy.

**Comment by tresf** [comment]
@dsanders11 turns out HID circumvents this problem and returns the actual scale value, not one from 5 seconds ago.  I feel it should be a suitable replacement until `libusb` provides a patch.

HID support was fast tracked for 2.0.1 because of the issues with HID scale devices on Mac, but it looks like it's going to be a better overall solution for scales in general.

Closing out as `not our bug` anyway, but I hope the workaround is suitable for your needs.

**Comment by dsanders11** [comment]
@tresf, sounds good to me, I think HID should work well. I believe [pywin](https://pypi.python.org/pypi/pywinusb/) that I tested with is using HID and I got stable results with that, which makes me believe HID will work well. Looking forward to 2.0.1.
