### ISSUE TITLE
Change charset (encode)

### ISSUE THREAD

**Issue by petrklic16** [qzind/tray#813]
Hi, i would like to ask you,

I use QZTray with RockPOS (https://rockpos.com) and if i print receipt, from my printer ESPON TM-T20III print receipt with wrong characters...

![image](https://user-images.githubusercontent.com/38321400/118144714-0e27dc80-b40d-11eb-8e0c-5d4255d6dd75.png)

I check QZTray log and i think problem is in encoding - 

![image](https://user-images.githubusercontent.com/38321400/118144842-37e10380-b40d-11eb-8280-ce8c1b711459.png)

Where i can change this encoding type please ?
Thank you

**Comment by tresf** [comment]
> Where i can change this encoding type please ?

Hi, I'm sorry about the trouble.  If encoding is incorrect, you will need to reach out to RockPOS to see if they can offer this functionality.  I've forwarded this bug report to our contact there.

**Comment by tresf** [comment]
If you're using Java 8, I believe the encoding is case-sensitive as well.  e.g. `Cp1252` instead of `CP1252`.  I'm closing this since the issue must be raised with RockPOS vendor.
