### ISSUE TITLE
How to print HTML data as raw data using Dot matrix printer?

### ISSUE THREAD

**Issue by crossdsection** [qzind/tray#82]
I want to print HTML data using Dot Matrix, but want the printer to use the Dot Matrix font it have already. Instead of rendering the HTML content.

I have tried this using the documentation.

`var printData = function(){
		var config = getUpdatedConfig();
		var data = document.documentElement.innerHTML;
        var printData = [{
			type: 'html',
			format: 'plain', // or 'plain' if the data is raw HTML
			data: data
		}];
        qz.print(config, printData).catch(function(e){console.log(e);});
	}`

One possibility I was able to find out from the documentation, was the Raw data has to be passed in Raw Data format.

So, should I have to convert my Data in String of Alphabets and special characters only?
Even If I was able to print it using the above process, will it be generic for Inkjet printers or other printers?

**Comment by tresf** [comment]
> So, should I have to convert my Data in String of Alphabets and special characters only?

Yes.

> Even If I was able to print it using the above process, will it be generic for Inkjet printers or other printers?

Unlikely, you'd have to try.  From testing, some support it some do not.  I do not believe the virtual print drivers do (PrimoPDF, PDFCreator, CutePDF, Microsoft XPS Document Writer) but some LaserJets I've tested with (HP mostly) do print plain text so you'd have to test with a few devices to know for sure.

**Comment by tresf** [comment]
Furthermore, you may have success with both formats if you switch to a [markdown language](https://en.wikipedia.org/wiki/Markdown) and then render the HTML for the browser only.  Just a thought. :+1:

**Comment by crossdsection** [comment]
Thanks, will check that..

**Comment by tresf** [comment]
Closing this as a support question.  Please feel free to continue using this thread if needed.

**Comment by jass-trix** [comment]
Is there any clear documentation for this thing? 
I'm still confuse with this thing.
So can i just print HTML as raw data right away?

**Comment by tresf** [comment]
@jass-trix HTML->Raw is a 2.1 feature, which is why it's not documented on the wiki.  If you're a premium subscriber, please contact us through official support channels and we will offer support.  If you're not, feel free to clone the 2.1 branch and build it and test this out.  We're still working hard on 2.1 and it has not been officially released yet.

**Comment by jass-trix** [comment]
@tresf can you elaborate which function to convert HTML into RAW? So i can just print directly from html to raw with the function?

**Comment by tresf** [comment]
Again, the 2.1 example has everything you need for this.  More information is available in #19.  Further prying will get this issue locked as it devalues the premium service we offer.
