### ISSUE TITLE
autoSize not scaling properly

### ISSUE THREAD

**Issue by klabarge** [qzind/tray#83]
The image is not scaling to the paper size unless `size` is specified .  I have tested this on both Ubuntu (Cups PDF) and Windows (PDFwriter, XPS).

The first image is the result from grabbing the default printer page size of A6.
The second image is from specifying an A6 page size in the config.

1. Set the default printer size to A6
1. Print image with no size specified (scaled to 50%)

  ![image](https://cloud.githubusercontent.com/assets/12505463/17045769/859b76d2-4f9a-11e6-83bd-9649d25ab46b.png)

1. Explicitly set `size` to A6 (4.1 x 5.8)

  ![image](https://cloud.githubusercontent.com/assets/12505463/17045962/63c72428-4f9c-11e6-9f93-39696c6d7d43.png)

**Comment by bberenz** [comment]
This was an interesting oversight. Apparently we were just starting with a generic paper instead of getting the printer's default.
Fixed with 7a50742467a045f0606f86ba683b90162278d4ee

**Comment by klabarge** [comment]
Works :+1:
