### ISSUE TITLE
When clicking "Remember the Decision" checkbox then "Allow" checkbox disabled.

### ISSUE THREAD

**Issue by ParvejK** [qzind/tray#834]
Hi, All

When the updated digital certificate. we are facing an issue.
when clicking the "Remember the decision" checkbox, then the "Allow" checkbox disabled.
How can fix the issue?

![disable_checkbox](https://user-images.githubusercontent.com/19271660/124546156-d86d0600-de47-11eb-95ba-c83abedf85cd.PNG)

**Comment by tresf** [comment]
This can be a variety of causes:
* [Invalid signature](https://qz.io/wiki/signing#supplying-the-signature)
* [Certificate which is not trusted](https://qz.io/wiki/signing#loading-the-trusted-certificate)

Since the certificate handling is a premium feature, this is normally handled by emailing support@qz.io.

**Comment by ParvejK** [comment]
Hi, Trest

We analyze on different computers and some points which are related to the issue which is mention with a screenshot after clicking "certificate information".
How Can fix?

![QZ Tray Certificate 2021-07-06 (1)](https://user-images.githubusercontent.com/19271660/124764403-89f85e00-df52-11eb-9fa5-6abd2b9b306e.jpg)
![image_2021_07_02T08_41_53_870Z](https://user-images.githubusercontent.com/19271660/124764408-8b298b00-df52-11eb-9054-0e20f92a9022.jpg)

**Comment by tresf** [comment]
I've replied to your email, let's continue talking there.

**Comment by tresf** [comment]
When we replaced the `private-key.pem` and `digital-certificate.txt` with new files, it started working.

@ParvejK some notes:

* Please use [`cache: false` in your `$.ajax(...)`](https://github.com/qzind/tray/blob/05a7c30cf63b81810cae1949f50590cf8f1db1a9/sample.html#L782) calls to ensure the browser does not cache the previous certificate.
https://github.com/qzind/tray/blob/05a7c30cf63b81810cae1949f50590cf8f1db1a9/sample.html#L782
* QZ Tray 2.0 will only work with `SHA1` signatures.  QZ Tray 2.1 will work with both `SHA1 `and `SHA512` signatures.  `SHA1` signatures will be removed at a future date, please upgrade `qz-tray.js` and QZ Tray to 2.1 versions as soon as possible.
