### ISSUE TITLE
QZ-Tray cannot manipulate duplex printing for PDF printing - only honors CUPS default setting - MacOS, Linux

### ISSUE THREAD

**Issue by lite1979** [qzind/tray#844]
A client brought to our attention that if they try to print a two-page PDF using QZ-Tray with the config set to single page (not duplex), it still prints duplex. 

This has been reproduced with QZ-Tray 2.1.3+1, MacOS Big Sur, and a Brother HL-L2380DW.

If the default setting in CUPS is set to Duplex, long side (portrait), then QZ-Tray will _only_ print PDFs in portrait duplex, despite the config being for single page printing.

If the default setting in CUPS is set to Single Page, then QZ-Tray will _only_ print PDFs on a single page, no duplex, despite config options.

Identical results were observed in Ubuntu 20.04

**Comment by tresf** [comment]
@Vzor- can you help write a small, reproducible code example so that we can file this with our JDK support provider?

**Comment by tresf** [comment]
Two-page document for testing: [two-pages.pdf](https://github.com/qzind/tray/files/11518257/two-pages.pdf)

**Comment by tresf** [comment]
So the plain java example works, so this is something QZ-specific.

**Comment by tresf** [comment]
Oddly, HTML printing (JavaFX) defaults to two-sides as well.

**Comment by tresf** [comment]
This has been patched upstream, just awaiting a proper OpenJDK 11 release number that receives the patch.

https://bugs.openjdk.org/browse/JDK-8311033

**Comment by tresf** [comment]
> This will be backported to OpenJDK 11.0.21, 17.0.9.

This behavior was patched in QZ Tray 2.2.4.
