### ISSUE TITLE
Allow Button Grey Out When Selecting Remember this decision button

### ISSUE THREAD

**Issue by meVineyK** [qzind/tray#845]
Hi

I am using qz tray 2.1.3+1 for printing cloudtail shipment labels through Unicommerce in Google chrome browsers. Whenever I select Remember this decision, Allow button greys out.

![image](https://user-images.githubusercontent.com/88085652/127303334-5d26de94-6717-47ff-9510-8f1e3007638c.png)

Whenever I am using qz tray 2.0.9, it is working without showing this Action Required prompt but still a new browser tab is opening.

**Comment by tresf** [comment]
Hi,

QZ Tray is continually improving and there are some stricter certificate rules in newer versions to handle certain misconfigured web servers.

I haven't heard of Unicommerce, but please reach out to them directly.  If they have a support contract with QZ, it's most likely a misconfiguration on their end and we'd love to help fix this problem right away.

I'm closing this issue, assuming it's a problem out of our control here project-side, but please feel free to comment on it if needed or request a reopen if you believe the newer QZ Tray version has a defect.
