### ISSUE TITLE
New line hex code not working for raw printing

### ISSUE THREAD

**Issue by XamuelUG** [qzind/tray#858]
Hey, Designed a raw print receipt but on printing, the '\x0A' does no effect of giving a line feed. 
Any Help will be Welcomed. My code is here...
![png-tray](https://user-images.githubusercontent.com/61344732/132121184-4267d903-66d3-4f19-9f09-dbeab82c903f.png)

**Comment by tresf** [comment]
The code snippet seems to quote our ESC/POS tutorial.

Does the printer normally accept ESC/POS?  A newline should work just fine, but if it's in another mode expecting another language, it may require another character instead.

If the printer supports ESC/POS and is ignoring `\n` or `\0x0A`, this would be incorrect behavior.

Note, some ESC/POS capable printers (such as Star 600 series) may ship configured for Star Line Mode by default and require a configuration option to change to ESC/POS.  Also, certain printers use drivers to interpret ESC/POS, so a raw command set may be incorrectly interpreted by ESC/POS-capable hardware when the driver is bypassed.

The more information about your printer you can offer (and how you're sending the data) the better.

**Comment by tresf** [comment]
Closing due to lack of response.  Please request a re-open if you believe this was closed in error.
