### ISSUE TITLE
QZ Tray JS does not resolve Promise

### ISSUE THREAD

**Issue by DasWolke** [qzind/tray#860]
Hello,

The JS lib (2.1.4) seems to connect to the websocket, but does not resolve the promise.
Code is as follows:
```
    qz.security.setCertificatePromise((resolve, reject) => {
      resolve(CERT)
    })

    qz.security.setSignatureAlgorithm('SHA256')

    qz.security.setSignaturePromise((toSign) => {
      return (resolve, reject) => {
        try {
          let pk = new jsrsasign.RSAKey()
          pk.readPrivateKeyFromPEMString(KEY)
          let hex = pk.sign(toSign, 'sha256')
          console.log('DEBUG: \n\n' + jsrsasign.stob64(jsrsasign.hextorstr(hex)))
          console.log('done')
          resolve(jsrsasign.stob64(jsrsasign.hextorstr(hex)))
        } catch (err) {
          console.error(err)
          reject(err)
        }
      }
    })

    console.log("test2")
    qz.websocket.connect({host: '10.0.2.8'}).then((a, e) => {
      console.log(a)
      console.log(e)
      console.log('test')
    }).catch(e => {
      console.error(e)
    })
```
Done and "test2" get logged
But the log inside the resolved promise of connect never runs.

**Comment by tresf** [comment]
You have a `resolve()` for cert, but no `reject()`.  Is there a chance it's erroring before the signature is being called?

**Comment by DasWolke** [comment]
That's not the case as setSignaturePromise works fine, CERT is just a var containing the certificate string. That's why I've omitted the reject.

**Comment by tresf** [comment]
> That's not the case as `setSignaturePromise` works fine, CERT is just a var containing the certificate string. That's why I've omitted the reject.


I think you mean `set`**`Certificate`**`Promise`?  That makes sense.  I don't see anything wrong with the code although it historically these issues are a problem with missing the `jsrsasign` import.  Can you run the `setSignaturePromise` code in a standalone function to capture the error that way?  We did attempt to improve catch handling in 2.1.4, perhaps we made a mistake.

**Comment by tresf** [comment]
Note, if you're using any transpilers, please state that.  They have a tendency to break our promises in an attempt to pollyfill them for older browsers.

**Comment by DasWolke** [comment]
Yep, that could be the case. I'm using it inside of a react app created with createReactApp.

**Comment by tresf** [comment]
Do you use IE-compatible polyfills?

**Comment by DasWolke** [comment]
I'm not sure I do. When Isolating the function it works as well.
Current Error is as follow: 
```
qz-tray.js:600 Uncaught (in promise) TypeError: Promise resolver undefined is not a function
    at new Promise (<anonymous>)
    at Object.promise (qz-tray.js:600)
    at Object.callSign (qz-tray.js:584)
    at qz-tray.js:255
```

Current Code is as follows:
```
initialize () {
    qz.security.setCertificatePromise((resolve, reject) => {
      resolve(CERT)
    })
    qz.security.setSignatureAlgorithm('SHA256')
    qz.security.setSignaturePromise((toSign) => {
      this.setSignaturePromise(toSign)
    })
    console.log("test2")
    this.setSignaturePromise("a").then(a => {
      console.log(a)
    }).catch(e => {
      console.error(e)
    })
    qz.websocket.connect({host: '10.0.2.8'}).then((a, e) => {
      console.log(a)
      console.log(e)
      console.log('test')
    }).catch(e => {
      console.error(e)
    })
    console.log(qz.websocket.isActive())
  }

  setSignaturePromise(toSign) {
    return new Promise((resolve, reject) => {
      try {
        let pk = new jsrsasign.RSAKey()
        pk.readPrivateKeyFromPEMString(KEY)
        let hex = pk.sign(toSign, 'sha256')
        console.log('DEBUG: \n\n' + jsrsasign.stob64(jsrsasign.hextorstr(hex)))
        console.log('done')
        resolve(jsrsasign.stob64(jsrsasign.hextorstr(hex)))
      } catch (err) {
        console.error(err)
        reject(err)
      }
    })
  }
```

**Comment by tresf** [comment]
> Promise resolver undefined is not a function

That's odd.   You can try to debug around that line by editing `qz-tray.js`, but when we ran into this in the past, it was due to transpiler oddness.

Can you move the code to pure JavaScript and see if it executes?  That might be a good baseline.  I'll share what I use locally for testing:

```
var privateKey = "====== ... ";
var cert = "====== ... ";

qz.security.setSignatureAlgorithm("SHA512"); // Since 2.1
qz.security.setSignaturePromise(function(toSign) {
    return function(resolve, reject) {
        try {
            var pk = KEYUTIL.getKey(privateKey);
            var sig = new KJUR.crypto.Signature({"alg": "SHA512withRSA"});  // Use "SHA1withRSA" for QZ Tray 2.0 and older
            sig.init(pk); 
            sig.updateString(toSign);
            var hex = sig.sign();
            console.log("DEBUG: \n\n" + stob64(hextorstr(hex)));
            resolve(stob64(hextorstr(hex)));
        } catch (err) {
            console.error(err);
            reject(err);
        }
    };
});

qz.security.setCertificatePromise(function(resolve, reject) {
        resolve(cert);
});
```

**Comment by tresf** [comment]
Also, if you're using the older JS signing code, you'll need an RSA-based private key, our examples all use PKCS#8 now which do not contain the RSA private key header.  jsrsasign can handle both formats, albeit different code.

**Comment by DasWolke** [comment]
The Promise Error Above was something different, which was caused by me directly returning a new Promise instead of a function in setSignaturePromise.
I've went to the good as good as I could and got to openConnection where qz first retrieves the version which works.
But then this call is made:
```
{certificate: '-----BEGIN CERTIFICATE-----\nXXXXX\n-----END CERTIFICATE-----', promise: {…}, timestamp: 1631231380652, uid: '8t1gck', signAlgorithm: 'SHA256', …}certificate: "-----BEGIN CERTIFICATE-----\nxxxxx\n-----END CERTIFICATE-----"position: {x: 896, y: 538}promise: {resolve: ƒ, reject: ƒ}reject: ƒ ()resolve: ƒ ()[[Prototype]]: ObjectsignAlgorithm: "SHA256"timestamp: 1631231380652uid: "8t1gck"[[Prototype]]: Object
qz-tray.js:46 Signature for call undefined
```
Interestingly there is no call property on this second websocket event as well as no signature property.

**Comment by DasWolke** [comment]
A Log of the pending calls inside QZ shows that exact call being still in pending after 5s.
Code:
```
openConnection: function(openPromise) {
                    setTimeout(() => {
                        console.log(_qz.websocket.pendingCalls)
                    }, 5000)
                    _qz.websocket.connection.established = true;
```
Browser Console
```
{u917xs: {…}}
u917xs: {resolve: ƒ, reject: ƒ}
```

**Comment by DasWolke** [comment]
Which happens because I did not notice the qz tray window on the vm......
My bad for that whole trouble.
Problem was before the PC.

**Comment by tresf** [comment]
> Which happens because I did not notice the qz tray window on the vm......
> My bad for that whole trouble.
> Problem was before the PC.

Thanks kindly for the update!

**Comment by another-yxmg** [comment]
> > Promise resolver undefined is not a function
> 
> That's odd. You can try to debug around that line by editing `qz-tray.js`, but when we ran into this in the past, it was due to transpiler oddness.
> 
> Can you move the code to pure JavaScript and see if it executes? That might be a good baseline. I'll share what I use locally for testing:
> 
> ```js
> var privateKey = "====== ... ";
> var cert = "====== ... ";
> 
> qz.security.setSignatureAlgorithm("SHA512"); // Since 2.1
> qz.security.setSignaturePromise(function(toSign) {
>     return function(resolve, reject) {
>         try {
>             var pk = KEYUTIL.getKey(privateKey);
>             var sig = new KJUR.crypto.Signature({"alg": "SHA512withRSA"});  // Use "SHA1withRSA" for QZ Tray 2.0 and older
>             sig.init(pk); 
>             sig.updateString(toSign);
>             var hex = sig.sign();
>             console.log("DEBUG: \n\n" + stob64(hextorstr(hex)));
>             resolve(stob64(hextorstr(hex)));
>         } catch (err) {
>             console.error(err);
>             reject(err);
>         }
>     };
> });
> 
> qz.security.setCertificatePromise(function(resolve, reject) {
>    resolve(cert);
> });
> ```

Hello, our company has encountered the same problem recently. Pure JS can indeed run normally, but we cannot locate where qz-tray.js is affected in the project. Can you provide us with more details, such as what will be affected? The resolve here or why it affects

**Comment by tresf** [comment]
Please see:
* https://github.com/qzind/tray/issues/906

Quoting an email we sent:

> Sorry about the trouble.
> 
> This is most commonly caused by transpilers converting JavaScript syntax.  For example, the behavior of async() is mutated with transpilers because it converts an AsyncFunction to something else (such as a promise or callback), so the API is not able to predict the proper callback type.
> 
> More details are available here:
> https://stackoverflow.com/a/38510353/3196753
> 
> Our recommendation is to use a Promise constructor or a Promise signature.  Alternatively, you may be able to change the target ECMAScript to maintain the async keyword.
