### ISSUE TITLE
When installing on Linux, the pre task fails on version 2.1+. Works on 2.0.11-1 >= .

### ISSUE THREAD

**Issue by sage-132** [qzind/tray#864]
When attempting to install on linux, you get the error message "Preinstall Task failed, run with DEBUG=TRUE for more information"

I couldn't figure out how to actually run with DEBUG=true, but I do know it's consistent across Ubuntu distributions (Kubuntu, Ubuntu Mate, Ubuntu, etc.)

**Comment by tresf** [comment]
> When attempting to install on linux, you get the error message "Preinstall Task failed, run with DEBUG=TRUE for more information"

This usually means Java (e.g. openjdk@11) is not installed.

> I couldn't figure out how to actually run with `DEBUG=true`

```bash
sudo DEBUG=true bash ~/Downloads/qz-tray-2.1.4.run
```

Note, this does pass ALL environment variables from you to the installer, so the results may be slightly different.  You may also `sudo su`, `export DEBUG=true && bash /home/<user>/Downloads/qz-tray-2.1.4.run` if the former erroneously succeeds.

**Comment by tresf** [comment]
Also, the supported Linux is currently Ubuntu.  We make a best-effort to support others, but you will need to provide the steps to reproduce (Linux flavor, version, Java version, exact QZ Tray version).

**Comment by sage-132** [comment]
Hey,

I used the steps you gave me and here's the error it threw.

![Screenshot_20210916_111929](https://user-images.githubusercontent.com/68917246/133639446-352e28b5-9b85-481f-985a-e838dbc8bf7f.png)
System Used
Kubuntu 20.04 LTS
OpenJDK 11.0.12
qz-tray 2.1.4

Steps.
`cd Downloads`
`sudo DEBUG=true bash ~/Downloads/qz-tray-2.1.4.run`

**Comment by tresf** [comment]
Thanks, assuming our installer is at fault, we'll fix this soon.  We support Eclipse Adoptium Temurin with 2.1.4, but we the switchover from AdoptOpenJDK was so close we missed Linux testing.

For now, another JDK will probably solve the issue, but we should be able to get a patch out publicly in a few days, or sooner.

**Comment by sage-132** [comment]
Happy to be of help, I just wanted to reach out since we were looking to migrate our windows machines to linux soon.

**Comment by tresf** [comment]
@sage-132 can you please share how you installed Adoptium?  I can't find a good, working procedure on their website (`export PATH=...` isn't a viable technique).

**Comment by tresf** [comment]
> @sage-132 can you please share how you installed Adoptium? I can't find a good, working procedure on their website (`export PATH=...` isn't a viable technique). I've reached out to Adoptium as well to see what's going on with their `.deb`/`.rpm`/PPA steps missing.

Found them: https://github.com/adoptium/website-v2/commits/main/src/asciidoc-pages/installation/linux.adoc
Source: https://adoptium.net/installation.html#installers

Unfortunately, I'm not able to reproduce the original issue.  Can you see if the new documentation fixes it?  If not and you can provide steps that differ from our own that reproduce this, I'll happily reopen.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/6345473/159774673-30e65b96-6b97-4f32-a6c2-5ebb7e1263a1.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/6345473/159774812-227b8799-8f2f-4ea0-9b8c-c3ae316ada12.png">
