### ISSUE TITLE
No option to know the active printers using qz APIs. Its shows printers not currently connected.

### ISSUE THREAD

**Issue by gunjan001** [qzind/tray#865]
I have below printers added in my devices : 
![Screenshot from 2021-09-17 00-10-38](https://user-images.githubusercontent.com/78813293/133667391-4b931136-567e-4f53-a814-c5c43bffd46a.png)

But none of is connected or is active.

qz.printers.find().then((printersArray) ..... gives me all the three printers . 

What I need is only the physical printers in active state.

**Comment by tresf** [comment]
This should be available via #736 #42, documented here: https://qz.io/wiki/printer-status.

This will be available as a cradle-to-grave feature (such as when searching for printers, printing, etc) at some future point, but please note, this is still a relatively new feature, so we prefer to have bug reports that identify a specific issue.

If there's a particular status that's not available, we will need exact steps to reproduce.  A screenshot is helpful in understanding the problem, but not when reproducing it.

**Comment by gunjan001** [comment]
Hi, 

First thanks for the the documentation. It is what I was looking for .

I was using qz 2.0. .. version where this API dont work. 
It just lists all the printers installed on the system but not shows the status of those printers. 

Upgrading to 2.1 will help me solve the issue on my application. 

Thanks.
