### ISSUE TITLE
Cannot read property 'toUpperCase' of undefined(…)

### ISSUE THREAD

**Issue by tresf** [qzind/tray#87]
If a object inside an object is supplied as print data, a rather obscure message will display:

```
TypeError: Cannot read property 'toUpperCase' of undefined(…)
```

This can be reproduced by supplying:

```javascript
var data = ["command1\n", "command2\n"];

qz.print(config, [data]);  // <--- Accidentally double-wrapped object
```

I believe the exception is being thrown in [`qz-tray.js:840`](https://github.com/qzind/tray/blob/2.0/js/qz-tray.js#L840) when some assumptions are made about the data type.

**Comment by tresf** [comment]
@bberenz, opinions on this fix?

```diff
             for(var i = 0; i < data.length; i++) {
-                if (typeof data[i] === 'object') {
+                if (data[i].constructor === Object) {
                     console.log(data[i]);
                     if ((!data[i].format && data[i].type.toUpperCase() !== 'RAW') //unspecified format and not raw -> assume file
                         || (data[i].format && (data[i].format.toUpperCase() === 'FILE'
                         || data[i].format.toUpperCase() === 'IMAGE'
                         || data[i].format.toUpperCase() === 'XML'))) {
                         data[i].data = _qz.tools.absolute(data[i].data);
                     }
                 }
             }
```

**Comment by bberenz** [comment]
Well the error comes up because type is not specified, so it would probably be better to use
```diff
-if ((!data[i].format && data[i].type.toUpperCase() !== 'RAW')
+if ((!data[i].format && data[i].type && data[i].type.toUpperCase() !== 'RAW')
```

However, the other problem is the java side isn't equipped to handle incorrectly formatted data. Such that if it fails to pull the `data` attribute, it treats it as a string (valid syntax). Since the array is doubled up, the inner array won't have that attribute, and instead pull the entire inner array as a string value.

**Comment by tresf** [comment]
> instead pull the entire inner array as a string value.

That's fine.  That's what happens with the aforementioned logic as well, I had tested both.

> probably be better to use `if ((... data[i].type)`  the error comes up because type is not specified

Since `typeof({}) == 'object'` and `typeof([]) == 'object'`, we're looking for an object without a proper type check.  Checking to see if it is an ACTUAL object seems cleaner, no?

**Comment by bberenz** [comment]
Yes, but we also run the risk of getting a real object without the type property.
If you feel better about it, there's no problem applying both solutions.
