### ISSUE TITLE
QZ Tray uninstall does not work on Mac

### ISSUE THREAD

**Issue by tresf** [qzind/tray#874]
Since QZ Tray 2.2.0, the `uninstall` script no longer seem to remove QZ Tray from the Applicaitons folder.

```bash
sudo /Applications/QZ\ Tray.app/Contents/Resources/uninstall
```

**Comment by tresf** [comment]
@Vzor- can you please patch in a fix before the 2.2.2 version?

**Comment by hellokittychaos** [comment]
Having same issue on PC Win 10 @tresf  Did you find a fix?  Tried to run it in cmd as a service then uninstall in cmd but it isn't working either. cd C:\nssm\win64

**Comment by tresf** [comment]
> Having same issue on PC Win 10 @tresf Did you find a fix? Tried to run it in cmd as a service then uninstall in cmd but it isn't working either. cd C:\nssm\win64

@hellokittychaos I think your issue is unrelated.  The above issue is for the MacOS operating system only.

If you're having issues uninstalling QZ Tray on a Windows 10 PC, please check that your antivirus software isn't interfering.  Some AVs (such as Comodo) cause a lot of problems with QZ Tray: https://qz.io/wiki/faq#conflicting-applications
