### ISSUE TITLE
Print to Host (Ip:port) raises NullPointerException on Printing PDF File and PDF Base64

### ISSUE THREAD

**Issue by HanpoomGeorge** [qzind/tray#883]
Hi, as mentioned on the title, when I connect my qz tray to host(ip:port(wifi printer)), it raises error below and fail printing.

Unlike [#672](https://github.com/qzind/tray/issues/672), it happens when tried priting pdf and base64(pdf).

Here is the reference picture that I am experiencing.

This error commonly occurs on the versions below I have tested.
- 2.2.0
- 2.1.4
- 2.0.10

Connect To Host -> printPDF() fails printing.
![image](https://user-images.githubusercontent.com/71762153/141472274-f053ab56-59c3-4759-9ab3-de59856c3209.png)

It is printable when try to connect to the Printer Driver from the searched name of the printer.
![image](https://user-images.githubusercontent.com/71762153/141472562-58457b71-1700-4617-bec7-1a0530636a4a.png)

Same goes when trying to print the base64 type of PDF, and upon analyzing the base64 data given as an example, it is likely an octet-stream type of data.

Appreciate in advance.

**Comment by tresf** [comment]
The demo doesn't support this unless you edit some code, but you can use the RAW tab.  Pixel features all require a printer driver currently.  Bypassing this is and will continue to be a RAW only feature.

**Comment by HanpoomGeorge** [comment]
I thought It was a similar bug raised by #672 since this only happens on the 'Set to Host' status.
Thank you for your guidance.
