### ISSUE TITLE
Company Branded: Add post-install scripting capabilities

### ISSUE THREAD

**Issue by tresf** [qzind/tray#885]
Company Branded versions may need to add scripting capabilities, e.g. special firewall rules, file copy, etc.  The installer should support a post-installation script for custom deployments.

**Comment by Vzor-** [comment]
Probably good to have the script be a .in. Props to pass probably

- user qz space
- shared qz space
- qz version
- os/arch
- install location

**Comment by tresf** [comment]
Implemented and ready for testing here: #1190 

> We should pass on some env vars to the script. Some useful props to pass:
> * user qz space
> * shared qz space
> * qz version
> * os/arch
> * install location

I'm going to skip these for now, but they shouldn't be too bad to implement if needed.

**Comment by tresf** [comment]
> I'm going to skip these for now, but they shouldn't be too bad to implement if needed.

I changed my mind and decided to add these in.  Documented here: https://qz.io/docs/provisioning#script-variables
