### ISSUE TITLE
Skip Spool for Fast Throughput

### ISSUE THREAD

**Issue by austinkahly** [qzind/tray#888]
I'm using a Zebra ZD620 with raw printing with QZ Tray 2.2.0 and when printing, the print job remains in the print queue after the print has completed leading to a lower throughput from the printer. I see there is an option for skipping the spooler and sending to the printer directly for network printers, but I was wondering if there was a solution for this for a printer connected via USB.

**Comment by tresf** [comment]
> the print job remains in the print queue after the print has completed leading to a lower throughput from the printer

The Windows OS has several settings in regards to spooling, some which allow retaining or removing spooled documents, skipping the spooling process entirely, and how the OS handles spooling priority.

![image](https://user-images.githubusercontent.com/6345473/144366174-665a32e3-e20e-45c8-840a-b3efaf8384d0.png)

In regards to printing directly to a USB port, QZ does allow raw USB or HID communication, but this is generally a bit too low-level for most printing purposes.   Feel free to test and document your success with these interfaces.  At time of writing this, we did have marginal success with printing directly to BOCA printers after reconfiguring them as HID devices, but we haven't yet attempted to send raw bytes to any other USB printers.
