### ISSUE TITLE
HTTPS issue on Firefox Developer Edition on macOS

### ISSUE THREAD

**Issue by sheck** [qzind/tray#889]
I think this might be a possible regression, similar to #200 

When using:
- macOS 11.6.1
- Firefox Developer Edition 95.0b12 (64-bit)
- QZ tray 2.1.4 (official and branded builds)

I experience consistent HTTPS errors when visiting `https://localhost:8181` and inconsistent failures using qz tray (via websockets).

I have confirmed that on my machine Firefox 94.0.2 and Chrome 96 do not have these issues (see screenshots below). Several co-workers are able to reproduce this behavior as well.

<img width="1536" alt="CleanShot 2021-12-03 at 12 23 19@2x" src="https://user-images.githubusercontent.com/3035506/144669880-ae2e4b61-1eb4-4d63-b0f8-bdc1a4952ac6.png">

<img width="1536" alt="CleanShot 2021-12-03 at 12 22 40@2x" src="https://user-images.githubusercontent.com/3035506/144669910-36c069b6-c058-407f-8842-dea0a157b51c.png">

**Comment by tresf** [comment]
On Mac, the Firefox property `security.enterprise_roots.enabled` is not toggled on for Firefox Developer Edition.

This is something we can fix by expliciting searching for `Firefox Developer Edition` at install time and shimming this policy.

As a temporary workaround, please visit `about:config` and toggle this policy on manually.

**Comment by tresf** [comment]
Closed via #891.  This patch will be available in QZ Tray 2.2.1 (and if released before EOL, QZ Tray 2.1.5).
