### ISSUE TITLE
demo.qz.io uses "Force Raw" instead of "altPrinting", which doesn't work with 2.1.5 and lower

### ISSUE THREAD

**Issue by lite1979** [qzind/tray#898]
I noticed this on a client's machine a few days ago and confirmed today. 

The newer "Force Raw" flag is available on our test page https://demo.qz.io , but if the client machine is not using 2.2.0+, the printer will print the commands instead of parsing them.

**Comment by tresf** [comment]
Hmm... weird, the demo code has the upgrade routine... 

https://github.com/qzind/tray/blob/8368d99388638920808dd7c9cfb4777280e428b2/js/qz-tray.js#L791-L796

**Comment by klabarge** [comment]
@lite1979 is this issue after toggling `forceRaw` on and off again?

When I enable it for the first time, the `config` looks correct. However after I disable it, both `altPrinting` and `forceRaw` are in the `config`

Using QZ Tray version 2.1 against demo.qz.io. These are the configs grabbed from the QZ Tray logs. I truncated the `options` for readability.

**Print 1 - default configuration (forceRaw disabled)**
```json
            "options": {
                "units": "in",
                "forceRaw": false,
                "encoding": null
            }
```

**Print 2 - forceRaw enabled**
```diff
            "options": {
                "units": "in",
                "encoding": null,
+               "altPrinting": true
            }
```

**Print 3 - forceRaw disabled**
```diff
            "options": {
                "units": "in",
                "encoding": null,
                "altPrinting": true,
+               "forceRaw": false
            }
```

**Comment by lite1979** [comment]
"altPrinting" does not appear at all in my logs.

**Comment by lite1979** [comment]
Actually, I wonder if it's because I was testing against 2.1.5....

**Comment by klabarge** [comment]
@lite1979 I had originally tested this on Windows. I re-tested on macOS and was able to reproduce your issue. I'll have to double-check the version I tested on earlier tomorrow. It was on a machine I do not have access to at the moment.

### The short 

I think we need to flip the version operator and remove the `config.forceRaw` check.

   ```diff
   -  if(_qz.tools.versionCompare(2, 1, 4) < 0) {
   + if(_qz.tools.versionCompare(2, 1, 4) > 0) { 
   -     if(config.forceRaw) { 
            config.altPrinting = config.forceRaw; 
            delete config.forceRaw; 
   -     } 
    } 
   ```

### The long

1. It looks like routine was never being trigger. I think the operator should be flipped

   ```diff
   -  if(_qz.tools.versionCompare(2, 1, 4) < 0) {
   + if(_qz.tools.versionCompare(2, 1, 4) > 0) { 
        if(config.forceRaw) { 
            config.altPrinting = config.forceRaw; 
            delete config.forceRaw; 
        } 
    } 
   ```

   It looks like the value being returned from `_qz.tools.versionCompare(2, 1, 4)` is `1`: `semver[1]` = `2` and `minor` = `1`

   https://github.com/qzind/tray/blob/7a1f634b0d93aa90643f13313f2def8937381fdd/js/qz-tray.js#L719-L721

2. There's still the issue of `altPrinting` and `forceRaw` being sent at the same time after toggling on, then toggling off `forceRaw`. `altPrinting` is always enabled as `if(config.forceRaw)` isn't triggered when it is unchecked.

   Can we simply remove the `config.forceRaw` check? Then it will get updated each time.

   ```diff
      if(_qz.tools.versionCompare(2, 1, 4) < 0) {
   -    if(config.forceRaw) {
           config.altPrinting = config.forceRaw;
           delete config.forceRaw;
   -    }
      }
   ```

**Comment by tresf** [comment]
> Can we simply remove the config.forceRaw check? Then it will get updated each time.

The idea is to leave values alone if not specified, so that's why we guard it.  You're right though, we aren't handling `.reconfigure()` properly because if set from `true` to `false`, it's never toggled off due to falsey.  Instead, we should check if it's undefined.

> It looks like the value being returned from _qz.tools.versionCompare(2, 1, 4) is 1: semver[1] = 2 and minor = 1

I have no idea why I hard-coded 2.1.4, perhaps I thought this feature was going to land on a late 2.1 version?  I don't know but at a glance, this means that the logic will not be applied for 2.1.4 or 2.1.5, that's a mistake.  It should probably read:

```js
if(_qz.tools.versionCompare(2, 2) < 0) ...
```

Which should be true for all versions less than 2.2.0.

@klabarge I have a feeling your other computer was on 2.1.3 and the logic was working.

**Comment by tresf** [comment]
PR opened, ready for testing: https://github.com/qzind/tray/pull/901

**Comment by klabarge** [comment]
> @klabarge I have a feeling your other computer was on 2.1.3 and that's why the initial logic was working.

Yep, confirmed that my version was lower than 2.1.4 and therefore it worked.

> PR opened, ready for testing: #901

Tested and looks good to me

**Comment by tresf** [comment]
> > @klabarge I have a feeling your other computer was on 2.1.3 and that's why the initial logic was working.
> 
> Yep, confirmed that my version was lower than 2.1.4 and therefore it worked.
> 
> > PR opened, ready for testing: #901
> 
> Tested and looks good to me

Thanks for confirming!  I added some additional unit tests I'd like to see in the PR.
