### ISSUE TITLE
Use Default Printer still searches for all printers when printing

### ISSUE THREAD

**Issue by tresf** [qzind/tray#931]
You can skip searching for all printers by simply clicking "Use Default Printer", however when printing, it still searches all printers.

**Comment by tresf** [comment]
Closed via https://github.com/qzind/tray/pull/935.  Will be ported to master when #936  is merged.

**Comment by Vzor-** [comment]
For future reference, this item is more than a search optimization. There are scenarios where searching beyond the default printer will cause a failure.
