### ISSUE TITLE
2.1.6 will not find the default printer on Mac

### ISSUE THREAD

**Issue by SkyportDEV** [qzind/tray#944]
Hello,
after installation from v2.1.6, qz.printers.getDefault() will not return the default printer anymore. After reinstall 2.1.5, everything works fine again.

![Bildschirmfoto 2022-03-24 um 20 54 31](https://user-images.githubusercontent.com/20161851/159999675-62c761e9-94d6-450d-96a4-73c9009bbb0f.png)

**Comment by tresf** [comment]
Thanks.  I believe this regression was introduced in https://github.com/qzind/tray/pull/935.  I think the matching was written wrong.  I'll make a patch if it works for you, I'll bump to 2.1.6+1.

**Comment by tresf** [comment]
@SkyportDEV can you see if this build fixes it in your environment?   Note, this build isn't notarized, so you might need to right click, run.

https://github.com/tresf/tray/releases/download/TEMP/qz-tray-2.1.6+1.pkg

Oddly, the default printer is found just fine on my machine, but the logic was broken so I'm hoping the above patch fixes it.

**Comment by tresf** [comment]
Ok, I can reproduce.  It's a timing issue with the background task.  Investigating...

**Comment by tresf** [comment]
@SkyportDEV ok, second attempt, can you test this one?

https://github.com/tresf/tray/releases/download/TEMP/qz-tray-2.1.6+2.pkg

**Comment by tresf** [comment]
Closed via 914f6c0.  We'll update the downloads right away.

**Comment by SkyportDEV** [comment]
@tresf 
Yes! Now it works perfectly ;)
Thanks for the quick fix!

**Comment by tresf** [comment]
Thank you for reporting so quickly!  This one slipped through the cracks. 😅
