### ISSUE TITLE
Append multiple PDFs

### ISSUE THREAD

**Issue by tresf** [qzind/tray#95]
Appending multiple PDFs in a row seems to be broken.

The expected behavior is 3 PDFs are printed, but the actual behavior is only one is printed.

```javascript
var config = qz.configs.create("Microsoft XPS Document Writer");

var data= [
   { type: 'pdf', data: 'assets/pdf_sample.pdf' },
   { type: 'pdf', data: 'assets/pdf_sample.pdf' },
   { type: 'pdf', data: 'assets/pdf_sample.pdf' }
];

qz.print(config, data).catch(displayError);
```

**Comment by tresf** [comment]
Patched via https://github.com/qzind/tray/commit/a4171b07353ada2291fa74a0e8db7a3b1f383c2d.  Awaiting test results.

**Comment by tresf** [comment]
a4171b0 passes partly, but the resulting document is always in A4 size regardless of the source document size.   @bberenz any ideas?

**Comment by tresf** [comment]
**Edit:** on Mac the resulting document is always in A4

**Comment by bberenz** [comment]
Is this seen only on mac? It might be the way we merge, but I'd think that could be indicative of a pdfbox bug if the others are fine.

**Comment by tresf** [comment]
> Is this seen only on mac? It might be the way we merge, but I'd think that could be indicative of a pdfbox bug if the others are fine.

I don't know, but `PDPage()` default constructor [seems to be US Letter](https://pdfbox.apache.org/docs/2.0.2/javadocs/org/apache/pdfbox/pdmodel/PDPage.html#PDPage()), which contradicts the A4 size I'm observing if it's a PDFBOX problem.

If this is another Mac-only bug, we may have to send each page as a separate job.  This will require more testing.

**Comment by tresf** [comment]
My mistake.  PDF's don't select matching paper yet.  Once I specified 4x6, they all printed to the specified size.  Linux testing exposed this as everything was 8.5x11 until I manually specified 4x6.  I think we're just fine here.  Closing as resolved.
