### ISSUE TITLE
Serial encoding isn't null if not set in properties

### ISSUE THREAD

**Issue by klabarge** [qzind/tray#953]
On the master branch, if serial `encoding` is left out of the properties, it does not get set to `null`.

**Works**
```diff
  var properties = {
      baudRate: 9600,
      dataBits: 7,     // <--- Changed from 8
      stopBits: 1,
      parity: 'EVEN',  // <--- Changed from NONE
      flowControl: 'NONE',
+     encoding: null
  };
```

**Does not work**
```diff
  var properties = {
      baudRate: 9600,
      dataBits: 7,     // <--- Changed from 8
      stopBits: 1,
      parity: 'EVEN',  // <--- Changed from NONE
      flowControl: 'NONE',
-     encoding: null
  };
```
* `encoding` is empty rather than `null` and throws an error

   ```
   "encoding":""
   ```

   ```
   java.nio.charset.IllegalCharsetNameException: 
	at java.nio.charset.Charset.checkName(Unknown Source) ~[?:?]
	at java.nio.charset.Charset.lookup2(Unknown Source) ~[?:?]
	at java.nio.charset.Charset.lookup(Unknown Source) ~[?:?]
	at java.nio.charset.Charset.forName(Unknown Source) ~[?:?]
	at qz.communication.SerialOptions.<init>(Unknown Source) ~[qz-tray.jar:?]
	at qz.ws.PrintSocketClient.processMessage(Unknown Source) ~[qz-tray.jar:?]
	at qz.ws.PrintSocketClient.onMessage(Unknown Source) ~[qz-tray.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor5.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:70) ~[qz-tray.jar:?]
	at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:68) ~[qz-tray.jar:?]
	at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.lambda$onTextFrame$1(JettyAnnotatedEventDriver.java:270) ~[qz-tray.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) ~[qz-tray.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) ~[qz-tray.jar:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
   ```

**Comment by klabarge** [comment]
🤔 I was confused somehow. This doesn't appear to be an issues with the API, rather the sample.html doesn't `null` the `encoding` fields.

https://github.com/qzind/tray/blob/fbcd9ef93a37bfd934885bd111ba3b3758a9c00f/sample.html#L3100

**Comment by tresf** [comment]
> 🤔 I was confused somehow. This doesn't appear to be an issues with the API, rather the sample.html doesn't `null` the `encoding` fields.
> 
> https://github.com/qzind/tray/blob/fbcd9ef93a37bfd934885bd111ba3b3758a9c00f/sample.html#L3091

Thanks.

@bberenz how do we handle this elsewhere?  Guard inside Java?  I think the sample guard is sane, but not sure if it should be guarded elsewhere as well, or if we should expect an exception during normal usage when it's an empty string.

**Comment by bberenz** [comment]
It would probably make sense to add a guard in java since we can assume an empty string is the same as a null value.

**Comment by tresf** [comment]
> It would probably make sense to add a guard in java since we can assume an empty string is the same as a null value.

Although I agree, I took a quick look and we don't do that anywhere else either, so it would be more consistent with our API behavior historically to guard it from the sample and raise an exception when it's blank.

After some thinking, this is probably best, it forces the programmer to not be lazy about empty strings.

So assuming we keep this guard in sample.html, I'd like to know if this is sufficient or if there are other areas we're missing.  For example, we guard `rx.end`, but not `rx.start`.

https://github.com/qzind/tray/blob/25f7576454b53108209c89044b528fdadfdc141d/sample.html#L3099

**Comment by tresf** [comment]
... another option, which may be preferred is to pre-fill an encoding value there so a blank value is a user-choice, however I fear that this may change the behavior of the demo a bit too aggressively at a time when we're trying to get people to switch to 2.2.

**Comment by tresf** [comment]
Finally, I've noticed that some of these fields actually get pre-filled with `null`, others do not.  I think this may have masked the bug for a while for places where we weren't guarding.

e.g. 

https://github.com/qzind/tray/blob/25f7576454b53108209c89044b528fdadfdc141d/sample.html#L2456-L2457

**Comment by klabarge** [comment]
>... another option, which may be preferred is to pre-fill an encoding value there so a blank value is a user-choice, however I fear that this may change the behavior of the demo a bit too aggressively at a time when we're trying to get people to switch to 2.2.

`UTF-8` is pre-filled in for the open connecting options, however it is blank for the response options. The [API](https://qz.io/api/qz.serial#.openPort) says that `UTF-8` is the default encoding

![image](https://user-images.githubusercontent.com/12505463/161111249-b3ba345b-0583-4c87-af43-252529dcb7ce.png)

**Comment by bberenz** [comment]
It looks like we are providing empty string checks java-side on printing options that can be null and even half of the serial options have similar such checks, so I think it still makes sense to add these in for the remaining.
I think the only reason the serial options rx.end and rx.width get nulled out in the sample was to avoid a needless warning log if they were empty along with rx.start (as such logging didn't check if end/width were non-empty).

As for prefilling, it looks like only the serial response encoding is the only one not being prefilled with the api's default value, so that should be a small change to include.

And for the null setting on reset, there were only 4, and all were on the print config options, all of which have null/empty checks to handle either case already. But should not be an issue to change to match the rest of the resets.
