### ISSUE TITLE
HTML zoom problems

### ISSUE THREAD

**Issue by tresf** [qzind/tray#96]
> 2.1, when using jquery barcode with `width = 1px`, just make sure that don't use `setZoom(...)` < 1.0. this will create the barcode accuracy's problem.
instead, can use this function `webView.getTransforms().add(new Scale(0.75, 0.75));` to scale the webview.

@bberenz if @vinhlh's advice is correct, should we patch the [72/96 logic](https://github.com/qzind/tray/blob/2.1/src/qz/printer/action/WebApp.java#L84) to use a transform instead?

**Comment by bberenz** [comment]
I can't replicate the issue with barcodes as he's describing. But using scale seems to keep the page layout better than zoom does, so it would make sense to change it over:
dd1451f4cbfc0d1ae4e037a80ff806a8cdc9baee
