### ISSUE TITLE
"this only supports TripleDES" Error on the console when connect through js client

### ISSUE THREAD

**Issue by mhadiahmed** [qzind/tray#963]

**Comment by tresf** [comment]
This was already asked and answered on our YouTube tutorial, please don't double-post questions.

![Screenshot_20220416-103329](https://user-images.githubusercontent.com/6345473/163679080-459376fa-dfdf-48b3-91b6-31a1e18d3ad2.png)

https://github.com/kjur/jsrsasign/issues/433
