### ISSUE TITLE
Java is required

### ISSUE THREAD

**Issue by alu0100990539** [qzind/tray#972]
Hello, I compile my own qz tray and installed in the same pc and works all good, but now I try to install it in a Windows 7 and always stop in the "Java is required" message, I install Java and reboot the pc and continious fail to detect that Java is installed...

Any ideas why it fails?

**Comment by tresf** [comment]
Sorry about this.  Can you see if the beta works?  That comes with it's own beta version.

<img width="1164" alt="image" src="https://user-images.githubusercontent.com/6345473/168834530-1ac25313-c5ee-4854-b826-6bc7b68824c7.png">

**Comment by tresf** [comment]
Closing due to lack of response.
