### ISSUE TITLE
QZ-TRAY How to check the printer has connected with serial port?

### ISSUE THREAD

**Issue by hotantai137** [qzind/tray#984]
Dear team,

I have a Thermal Printer - FEC-80 (FEC-80T), manufactured by FIRICH ENTERPRISES CO., LTD
connect to POS(windows 7, Java 11, qz version 2.1.6) with serial port.
I want to check status printer is connected or not with serial port.
Please introduce it to me.

**Comment by tresf** [comment]
Hi,

Bidirectional serial printer status isn't currently available.  Sorry for the inconvenience.

Note, QZ Tray does implement a full serial interface, so you may write the feature yourself by writing the serial communications manually.

**Comment by hotantai137** [comment]
Hi @tresf ,
Thank you for support, can you give me some document for implement feature check serial communication with java.

**Comment by tresf** [comment]
@hotantai137 here: https://qz.io/wiki/serial

**Comment by hotantai137** [comment]
@tresf thanks you, I will try it.

**Comment by tresf** [comment]
Closing as this feature isn't available currently and we have no immediate plans to add it.
