### ISSUE TITLE
Problem mslinks.ShellLink when compiling

### ISSUE THREAD

**Issue by wiseguysby** [qzind/tray#986]
I have a problem when ant nsis getting error like this
![image](https://user-images.githubusercontent.com/33086336/180132793-f8ce16cb-ac39-461b-b51c-61cc9319e446.png)

Howto resolve the problem?

**Comment by wiseguysby** [comment]
I change to jdk11 its working now. case closed

**Comment by tresf** [comment]
Yeah, sorry, upstream changed the required version rather silently.  Thanks for sorting and documenting it!
