### ISSUE TITLE
Problem when not using direct link pdf file

### ISSUE THREAD

**Issue by wiseguysby** [qzind/tray#987]
I have a problem.
If I'm using direct link to file, for example `https://xxx.com/yyy.pdf`, qz.io is working fine
then I'm using symbol link, for example `https://xxxx.com/nquR7JEPpC_1658633591`, qz.io is not working, but with pdfjs for preview pdf file is working fine.

In my backend ( Im using cogeigniter 3), like this

```php
header('Cache-Control: public, must-revalidate, max-age=0'); // HTTP/1.1
header('Pragma: public');
header('Expires: Sat, 26 Jul 1997 05:00:00 GMT'); // Date in the past
header('Last-Modified: '.gmdate('D, d M Y H:i:s').' GMT');

 // force download
header('Content-Type: application/force-download');
header('Content-Type: application/octet-stream', false);
header('Content-Type: application/download', false);

header('Content-Disposition: attachment; filename="'.$file.'";');
header('Content-Transfer-Encoding: binary');
header('Content-Length: '.$file));
header('Content-Type: application/pdf', false);

echo file_get_contents($file);
```

code above is working with pdfjs but not qz.io. 
Could you tell me how to possible in qz.io ?

**Comment by tresf** [comment]
QZ Tray is pretty lenient about how the file is served up, this should work file.  What's probably best to share is the error logs from QZ Tray itself.

Also, I edited the `xxx<dot com>` example hyperlinks, you probably don't want people actually clicking on those.  😉

**Comment by wiseguysby** [comment]
Hhahahah, sorry, I just give for example not actually domain/website...I don't know if the domain name already exists...

btw this is error log
![image](https://user-images.githubusercontent.com/33086336/180695786-7e049450-f2dc-413c-bd26-2b1da742e5b4.png)

and this is print options
![image](https://user-images.githubusercontent.com/33086336/180696122-72701741-70e9-408f-9f6b-4a17bacac152.png)

**Comment by tresf** [comment]
@wiseguysby that URL is behind a login and QZ Tray does not have that login information, so instead it's trying to parse an HTML login page as a PDF.

**Comment by wiseguysby** [comment]
Yes, you correct. user should be login, that's way I'm confuse, why pdfjs is working but qz.io is not working, because access same url link. FYI, if I'm change to base64 is working.

**Comment by tresf** [comment]
QZ Tray runs in Java as a separate process.  It does not have access to your login sessions and cannot access files this way.  If you need to get the file from behind the login session, you will need to send it to QZ Tray using base64.

**Comment by wiseguysby** [comment]
ok, great, clear. thanks your reponse.
