### ISSUE TITLE
key is too short for SigAlg: keylen=99,sha1

### ISSUE THREAD

**Issue by ztlyde** [qzind/tray#99]
My private key generated by the JDK tools keytool, when using this jsrsasign.js signature appear this error 'Uncaught key is too short for SigAlg: keylen=99,sha1'

But I don't have any problems in Java.

**Comment by tresf** [comment]
As a followup, per https://github.com/qzind/tray/blob/2.0/assets/signing/sign-message.js#L29:L40

> Convert private key to jsrsasign compatible format:
>  *        `openssl rsa -in private-key.key -out private-key-updated.key`

Duplicate of https://github.com/qzind/tray/issues/1.
