### ISSUE TITLE
Permanently denying a website makes qz-tray.js crash

### ISSUE THREAD

**Issue by InjustFr** [qzind/tray#991]
Hi,

When you permanently deny the access, the tray closes the connection as it should and that makes the qz-tray.js script crash with the following error:
```js
Uncaught TypeError: Cannot read properties of null (reading 'promise') at _qz.websocket.connection.onclose (qz-tray.js:244:54)
```

Would it be possible to add an info message in the tray logs or in the browser (even better, both 😄 ) to indicate that the website has been denied access?

For context, a user, when prompted by QZTray if the website should be allowed, wrongly permanently denied the access and we've just spent one hour to fix it, startled by a bug happening only on one specific machine 😆 . Having an info message in the logs would have been very handy!

**Comment by tresf** [comment]
Hi,

The API already handles this rather gracefully, as the `qz.websocket.connect()` will raise an exception "Connection blocked by client", which can be caught.

https://github.com/qzind/tray/blob/0297d5b78e11924af891cfaaa4f0fe9952472ab9/src/qz/ws/PrintSocketClient.java#L139

If you would like to explicitly catch this event, you may do so using the following code:

```js
qz.websocket.setClosedCallbacks(evt => {
        switch(evt.code) {
            case 1006:
                alert("Block was clicked!");
                break;
        }
});
```

**Comment by tresf** [comment]
Closing due to lack of response.  Please request a re-open if you believe this was closed in error.
